import { useEffect, useState } from 'react'
import { Icon, type IconName } from '../../components/ui/Icon'
import { supabase } from '../../lib/supabase'
import { AttentionPanel } from './AttentionPanel'
import { getAttentionCounts, type AttentionCounts } from './attentionCounts'
import { DashboardProcessingGrid } from './DashboardProcessingGrid'
type Category='individual'|'company'|'mixed'
type Summary={category:Category;clients:number;movements:number;minutes:number;total:number|null;invoiced:number|null}&AttentionCounts
const labels:Record<Category,{title:string;description:string;icon:IconName}>={individual:{title:'Particulares',description:'Clientes com vertente particular',icon:'clients'},company:{title:'Empresas',description:'Clientes com vertente empresarial',icon:'building'},mixed:{title:'Mistos',description:'Contagem adicional: estes clientes continuam incluídos nas outras duas categorias',icon:'people'}}
const money=new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}),number=new Intl.NumberFormat('pt-PT')
export function ClientLandingPage({onSelect}:{onSelect:(category:Category)=>void}){
 const [data,setData]=useState<Summary[]|null>(null),[error,setError]=useState('')
 useEffect(()=>{let active=true;void(async()=>{const db=supabase;if(!db){setError('Ligação ao Supabase indisponível.');return}const response=await db.rpc('get_client_category_summaries');if(!active)return;if(response.error)setError(response.error.message);else{const rows=(Array.isArray(response.data)?response.data:[]) as Omit<Summary,keyof AttentionCounts>[],counts=await Promise.all(rows.map(row=>getAttentionCounts({clientType:row.category})));if(active)setData(rows.map((row,index)=>({...row,...counts[index]})).filter(row=>row.category!=='mixed'||row.clients>0))}})();return()=>{active=false}},[])
 if(error)return <DashboardProcessingGrid error={error} label="Erro ao calcular o dashboard de clientes" cards={(Object.entries(labels) as [Category,(typeof labels)[Category]][]).map(([key,item])=>({key,title:item.title,subtitle:item.description,icon:item.icon,metrics:['Clientes','Movimentos','Horas','Valor total','Facturado','Por facturar']}))}/>
 if(!data)return <DashboardProcessingGrid cards={(Object.entries(labels) as [Category,(typeof labels)[Category]][]).map(([key,item])=>({key,title:item.title,subtitle:item.description,icon:item.icon,metrics:['Clientes','Movimentos','Horas','Valor total','Facturado','Por facturar']}))}/>
 const hasMixed=data.some(item=>item.category==='mixed'&&item.clients>0)
 return <div className="space-y-5"><header><p className="text-sm text-text-secondary">Resumo operacional, alertas e acesso aos dashboards.</p>{hasMixed&&<p className="mt-1 text-xs font-medium text-secondary">As categorias são inclusivas: os clientes mistos também contam em Particulares e em Empresas.</p>}</header><div className={`grid gap-4 ${hasMixed?'lg:grid-cols-3':'lg:grid-cols-2'}`}>{data.map(item=>{const meta=labels[item.category],base=`?view=work&clientType=${item.category}`;return <article key={item.category} className="card flex flex-col overflow-hidden"><div className="h-1 bg-gradient-to-r from-secondary via-accent to-secondary"/><div className="flex flex-1 flex-col p-6"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-secondary-soft text-secondary"><Icon name={meta.icon} className="size-6"/></span><div><h3 className="font-display text-xl font-semibold">{meta.title}</h3><p className="mt-1 text-xs text-text-secondary">{meta.description}</p></div></div><dl className="mt-6 grid grid-cols-2 gap-3"><Metric label="Clientes" value={number.format(item.clients)}/><Metric label="Movimentos" value={number.format(item.movements)}/><Metric label="Horas" value={`${number.format(Math.round(item.minutes/60))} h`}/><Metric label="Valor total" value={item.total==null?'Sem acesso':money.format(item.total)} financial/><Metric label="Facturado" value={item.invoiced==null?'Sem acesso':money.format(item.invoiced)} financial/><Metric label="Por facturar" value={item.total==null||item.invoiced==null?'Sem acesso':money.format(item.total-item.invoiced)} financial/></dl><AttentionPanel counts={item} links={{uninvoiced:`${base}&collectionState=uninvoiced`,unpaid:`${base}&collectionState=unpaid`,missingPrice:`${base}&missingPrice=true`}}/><button type="button" onClick={()=>onSelect(item.category)} className="mt-5 flex min-h-11 items-center justify-center gap-2 rounded-lg bg-secondary px-4 text-sm font-semibold text-surface">Entrar em {meta.title}<Icon name="chevron" className="size-4"/></button></div></article>})}</div></div>
}
function Metric({label,value,financial=false}:{label:string;value:string;financial?:boolean}){return <div className="rounded-lg bg-surface-subtle p-3"><dt className="text-xs text-text-secondary">{label}</dt><dd className={`${financial?'financial-value ':''}mt-1 text-lg font-semibold tabular-nums`}>{value}</dd></div>}
