import { useEffect, useState } from 'react'
import { Icon, type IconName } from '../../components/ui/Icon'
import { supabase } from '../../lib/supabase'
import { AttentionPanel } from './AttentionPanel'
import { getAttentionCounts, type AttentionCounts } from './attentionCounts'
import { DashboardProcessingGrid } from './DashboardProcessingGrid'
import {formatDate} from '../../utils/date'
import type { CreditAccount } from '../clients/credit'
type Category='individual'|'company'|'mixed'
type Summary={category:Category;clients:number;movements:number;minutes:number;total:number|null;invoiced:number|null}&AttentionCounts
type RetainerRow={client_id:string;covered_minutes:number;pending_amount:number;unpaid_amount:number;current_monthly_amount:number|null}
const labels:Record<Category,{title:string;description:string;icon:IconName}>={individual:{title:'Particulares',description:'Clientes com vertente particular',icon:'clients'},company:{title:'Empresas',description:'Clientes com vertente empresarial',icon:'building'},mixed:{title:'Mistos',description:'Contagem adicional: estes clientes continuam incluídos nas outras duas categorias',icon:'people'}}
const pendingCards=[...(['individual','company'] as const).map(key=>({key,title:labels[key].title,subtitle:labels[key].description,icon:labels[key].icon,metrics:['Clientes','Movimentos','Horas','Valor total','Facturado','Por facturar']})),{key:'retainers',title:'Avenças',subtitle:'Condições e utilização',icon:'clock' as const,metrics:['Clientes','Horas','Mensalidade','Por facturar']},{key:'provisions',title:'Provisões',subtitle:'Saldos e utilização',icon:'payment' as const,metrics:['Clientes','Contas','Recebido','Saldo']}]
const money=new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}),number=new Intl.NumberFormat('pt-PT')
export function ClientLandingPage({onSelect,onRetainers,onProvisions}:{onSelect:(category:Category)=>void;onRetainers:()=>void;onProvisions:()=>void}){
 const [data,setData]=useState<Summary[]|null>(null),[retainerRows,setRetainerRows]=useState<RetainerRow[]>([]),[provisionAccounts,setProvisionAccounts]=useState<CreditAccount[]|null>(null),[coveredPeriod,setCoveredPeriod]=useState('Sem horas registadas'),[error,setError]=useState('')
 useEffect(()=>{let active=true;void(async()=>{const db=supabase;if(!db){setError('Ligação ao Supabase indisponível.');return}const [response,retainers,coveredDates,credits]=await Promise.all([db.rpc('get_client_category_summaries'),db.rpc('get_retainer_management'),db.from('work_entries').select('work_date').eq('billing_scope','retainer').order('work_date'),db.rpc('get_client_credit_accounts')]);if(!active)return;if(response.error){setError(response.error.message);return}setProvisionAccounts(credits.error?null:(Array.isArray(credits.data)?credits.data:[]) as CreditAccount[]);if(!coveredDates.error&&coveredDates.data?.length){setCoveredPeriod(`${formatDate(coveredDates.data[0].work_date)} a ${formatDate(coveredDates.data.at(-1)!.work_date)}`)}const rows=(Array.isArray(response.data)?response.data:[]) as Omit<Summary,keyof AttentionCounts>[],counts=await Promise.all(rows.map(row=>getAttentionCounts({clientType:row.category})));if(!active)return;setData(rows.map((row,index)=>({...row,...counts[index]})).filter(row=>row.category!=='mixed'||row.clients>0));if(!retainers.error&&Array.isArray(retainers.data)){setRetainerRows(retainers.data as RetainerRow[]);return}const [terms,work,charges]=await Promise.all([db.from('client_retainers').select('client_id,monthly_amount').eq('active',true),db.from('work_entries').select('client_id,duration_minutes').eq('billing_scope','retainer'),db.from('retainer_charges').select('client_id,amount,status')]);if(!active||terms.error||work.error||charges.error)return;const clients=new Map<string,RetainerRow>();for(const term of Array.isArray(terms.data)?terms.data:[])clients.set(term.client_id,{client_id:term.client_id,covered_minutes:0,pending_amount:0,unpaid_amount:0,current_monthly_amount:Number(term.monthly_amount)});for(const entry of Array.isArray(work.data)?work.data:[]){const item=clients.get(entry.client_id);if(item)item.covered_minutes+=Number(entry.duration_minutes)}for(const charge of Array.isArray(charges.data)?charges.data:[]){const item=clients.get(charge.client_id);if(item&&charge.status==='pending')item.pending_amount+=Number(charge.amount);if(item&&charge.status==='invoiced')item.unpaid_amount+=Number(charge.amount)}setRetainerRows([...clients.values()])}) ();return()=>{active=false}},[])
 useEffect(()=>{if(!coveredPeriod.startsWith('histórico global'))setCoveredPeriod(`histórico global · ${coveredPeriod}`)},[coveredPeriod])
 if(error)return <DashboardProcessingGrid error={error} label="Erro ao calcular o dashboard de clientes" cards={pendingCards}/>
 if(!data)return <DashboardProcessingGrid cards={pendingCards} label="A processar o dashboard de clientes"/>
 const retainerTotals=retainerRows.reduce((total,row)=>({minutes:total.minutes+Number(row.covered_minutes),pending:total.pending+Number(row.pending_amount),unpaid:total.unpaid+Number(row.unpaid_amount),monthly:total.monthly+Number(row.current_monthly_amount??0)}),{minutes:0,pending:0,unpaid:0,monthly:0})
 const provisionClients=provisionAccounts?new Set(provisionAccounts.map(row=>row.client_id)).size:null
 const provisionMoney=(field:'received'|'balance')=>{
  if(!provisionAccounts)return 'Sem acesso'
  const byCurrency=new Map<string,number>()
  for(const row of provisionAccounts)byCurrency.set(row.currency,(byCurrency.get(row.currency)??0)+Number(row[field]))
  if(!byCurrency.size)return money.format(0)
  return [...byCurrency].map(([currency,value])=>new Intl.NumberFormat('pt-PT',{style:'currency',currency}).format(value)).join(' · ')
 }
 return <div className="dashboard-landing space-y-5">
  <header><p className="text-sm text-text-secondary">Resumo operacional, alertas e acesso às áreas de clientes.</p><p className="mt-1 text-xs font-medium text-secondary">Avenças e Provisões são visualizações adicionais; os respectivos clientes continuam a contar em Particulares e Empresas.</p></header>
  <div className="client-summary-grid grid gap-4 md:grid-cols-2">
   {data.filter(item=>item.category!=='mixed').map(item=>{const meta=labels[item.category],base=`?view=work&clientType=${item.category}`;return <article key={item.category} className="card flex flex-col overflow-hidden"><div className="h-1 bg-gradient-to-r from-secondary via-accent to-secondary"/><div className="flex flex-1 flex-col p-6"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-secondary-soft text-secondary"><Icon name={meta.icon} className="size-6"/></span><div><h3 className="font-display text-xl font-semibold">{meta.title}</h3><p className="mt-1 text-xs text-text-secondary">{meta.description}</p></div></div><dl className="mt-6 grid grid-cols-2 gap-3"><Metric label="Clientes" value={number.format(item.clients)}/><Metric label="Movimentos" value={number.format(item.movements)}/><Metric label="Horas" value={`${number.format(Math.round(item.minutes/60))} h`}/><Metric label="Valor total" value={item.total==null?'Sem acesso':money.format(item.total)} financial/><Metric label="Facturado" value={item.invoiced==null?'Sem acesso':money.format(item.invoiced)} financial/><Metric label="Por facturar" value={item.total==null||item.invoiced==null?'Sem acesso':money.format(item.total-item.invoiced)} financial/></dl><AttentionPanel counts={item} links={{uninvoiced:`${base}&collectionState=uninvoiced`,unpaid:`${base}&collectionState=unpaid`,missingPrice:`${base}&missingPrice=true`}}/><button type="button" onClick={()=>onSelect(item.category)} className="mt-5 flex min-h-11 items-center justify-center gap-2 rounded-lg bg-secondary px-4 text-sm font-semibold text-surface">Abrir lista de {meta.title}<Icon name="chevron" className="size-4"/></button></div></article>})}
   <article className="card flex flex-col overflow-hidden"><div className="h-1 bg-gradient-to-r from-danger via-accent to-danger"/><div className="flex flex-1 flex-col p-6"><div className="flex items-start gap-4"><span className="grid size-12 place-items-center rounded-xl bg-danger-soft text-danger"><Icon name="clock" className="size-6"/></span><div><h3 className="font-display text-xl font-semibold">Avenças</h3><p className="mt-1 text-xs text-text-secondary">Condições, utilização e facturação.</p></div></div><dl className="mt-6 grid grid-cols-2 gap-3"><Metric label="Clientes com avença" value={number.format(retainerRows.length)}/><Metric label={`Horas cobertas · ${coveredPeriod}`} value={`${number.format(Math.round(retainerTotals.minutes/60))} h`}/><Metric label="Mensalidade vigente" value={money.format(retainerTotals.monthly)} financial/><Metric label="Avenças por facturar" value={money.format(retainerTotals.pending)} financial/><Metric label="Facturado por liquidar" value={money.format(retainerTotals.unpaid)} financial/></dl><p className="mt-4 rounded-lg bg-secondary-soft p-3 text-xs text-text-secondary">Os movimentos de avença guardam tempo, mas não preço ou valor individual.</p><button type="button" onClick={onRetainers} className="mt-auto flex min-h-11 items-center justify-center gap-2 rounded-lg bg-secondary px-4 text-sm font-semibold text-surface">Tratar avenças<Icon name="chevron" className="size-4"/></button></div></article>
   <article className="card flex flex-col overflow-hidden"><div className="h-1 bg-gradient-to-r from-secondary via-accent to-secondary"/><div className="flex flex-1 flex-col p-6"><div className="flex items-start gap-4"><span className="grid size-12 place-items-center rounded-xl bg-secondary-soft text-secondary"><Icon name="payment" className="size-6"/></span><div><h3 className="font-display text-xl font-semibold">Provisões</h3><p className="mt-1 text-xs text-text-secondary">Saldos recebidos, utilizados e disponíveis.</p></div></div><dl className="mt-6 grid grid-cols-2 gap-3"><Metric label="Clientes com provisões" value={provisionClients==null?'Sem acesso':number.format(provisionClients)}/><Metric label="Contas de provisão" value={provisionAccounts==null?'Sem acesso':number.format(provisionAccounts.length)}/><Metric label="Contas com saldo" value={provisionAccounts==null?'Sem acesso':number.format(provisionAccounts.filter(row=>Number(row.balance)>0).length)}/><Metric label="Contas esgotadas" value={provisionAccounts==null?'Sem acesso':number.format(provisionAccounts.filter(row=>Number(row.balance)<=0).length)}/><Metric label="Provisões recebidas" value={provisionMoney('received')} financial/><Metric label="Saldo contabilístico" value={provisionMoney('balance')} financial/></dl><p className="mt-4 rounded-lg bg-secondary-soft p-3 text-xs text-text-secondary">Os saldos incluem as notas e os estornos. A página de Provisões mostra também o trabalho ainda sem nota.</p><button type="button" onClick={onProvisions} className="mt-auto flex min-h-11 items-center justify-center gap-2 rounded-lg bg-secondary px-4 text-sm font-semibold text-surface">Abrir provisões<Icon name="chevron" className="size-4"/></button></div></article>
  </div>
 </div>
}function Metric({label,value,financial=false}:{label:string;value:string;financial?:boolean}){const preciseLabel=label.replace(/^Horas cobertas · /,'Horas utilizadas — histórico total · ');return <div className="rounded-lg bg-surface-subtle p-3"><dt className="text-xs text-text-secondary">{preciseLabel}</dt><dd className={`${financial?'financial-value ':''}mt-1 text-lg font-semibold tabular-nums`}>{value}</dd></div>}
