import { Icon, type IconName } from '../../components/ui/Icon'

type ProcessingCard={key:string;title:string;subtitle:string;icon:IconName;metrics:string[]}

export function DashboardProcessingGrid({cards,label='A processar os valores do dashboard',error}:{cards:ProcessingCard[];label?:string;error?:string}){
 return <div className="space-y-5" role="status" aria-label={label} aria-live="polite">
  <div className={`flex items-center gap-2 rounded-lg border px-4 py-3 text-sm ${error?'border-danger/40 bg-danger-soft text-danger':'border-secondary/35 bg-secondary-soft text-secondary'}`}>{!error&&<span className="size-4 shrink-0 animate-spin rounded-full border-2 border-secondary border-t-transparent" aria-hidden="true"/>}<span>{error?`Não foi possível concluir o cálculo: ${error}`:'A estrutura já está disponível. Os valores estão a ser processados…'}</span></div>
  <div className="grid gap-4 lg:grid-cols-3">{cards.map(card=><article key={card.key} className="card flex min-h-80 flex-col overflow-hidden"><div className="h-1 bg-gradient-to-r from-secondary via-accent to-secondary"/><div className="flex flex-1 flex-col p-6"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-secondary-soft text-secondary"><Icon name={card.icon} className="size-6"/></span><div><h3 className="font-display text-xl font-semibold">{card.title}</h3><p className="mt-1 text-xs text-text-secondary">{card.subtitle}</p></div></div><dl className="mt-6 grid grid-cols-2 gap-3">{card.metrics.map(metric=><div key={metric} className="rounded-lg bg-surface-subtle p-3"><dt className="text-xs text-text-secondary">{metric}</dt><dd className={`mt-1 flex min-h-7 items-center gap-2 text-xs font-semibold ${error?'text-danger':'text-secondary'}`}>{!error&&<span className="size-3 animate-spin rounded-full border-2 border-secondary border-t-transparent" aria-hidden="true"/>}{error?'Indisponível':'A processar…'}</dd></div>)}</dl><div className="mt-4 grid grid-cols-3 gap-2">{['Por facturar','Facturados não pagos','Movimentos sem preço'].map(item=><div key={item} className="rounded-lg border border-danger/35 bg-danger-soft p-2 text-center"><p className="flex min-h-8 items-center justify-center text-[0.65rem] leading-4 text-danger">{item}</p><p className="mt-1 text-xs font-semibold text-danger">{error?'Indisponível':'A processar…'}</p></div>)}</div><div className="mt-5 flex min-h-11 items-center justify-center rounded-lg border border-border bg-surface-subtle text-sm font-semibold text-text-secondary">{error?'Actualizar para tentar novamente':'Disponível após o cálculo'}</div></div></article>)}</div>
 </div>
}
