import { useEffect, useState } from 'react'
import { AppLink } from '../../components/ui/AppLink'
import { supabase } from '../../lib/supabase'
type Row={id:string;work_date:string;client_name:string;activity_description:string;professional_name:string;billing_name:string|null;is_invoiced:boolean;is_paid:boolean}
export function DashboardList({kind,id,clientType}:{kind:'client'|'billing'|'professional';id?:string;clientType?:'individual'|'company'|'mixed'|null}){
 const [rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(''),[activeRow,setActiveRow]=useState<string|null>(null)
 const params=kind==='billing'&&id?`billingEntityId=${id}`:kind==='professional'&&id?`professionalId=${id}`:clientType?`clientType=${clientType}`:id?`clientId=${id}`:''
 useEffect(()=>{let active=true;void(async()=>{const db=supabase;if(!db)return;const result=await db.rpc('search_work_entries',{p_page:1,p_page_size:100,p_search:null,p_year:null,p_professional_id:kind==='professional'?id??null:null,p_billing_entity_id:kind==='billing'?id??null:null,p_invoiced:null,p_paid:null,p_archive:null,p_review_only:false,p_missing_price:false,p_client_type:kind==='client'?clientType??null:null,p_client_id:kind==='client'&&!clientType?id??null:null,p_missing_society:false,p_sort:'work_date',p_direction:'desc'});if(!active)return;if(result.error)setError(result.error.message);else{const payload=result.data as {items?:Row[];total?:number};setRows(payload.items??[]);setTotal(payload.total??0)}})();return()=>{active=false}},[kind,id,clientType])
 if(error)return <section className="card border-danger/30 bg-danger-soft p-5 text-danger"><h3 className="font-semibold">Lista</h3><p className="mt-2 text-sm">Não foi possível carregar: {error}</p></section>
 return <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-5"><div><h3 className="font-semibold">Lista</h3><p className="mt-1 text-xs text-text-secondary">Primeiros {Math.min(rows.length,100).toLocaleString('pt-PT')} de {total.toLocaleString('pt-PT')} registos</p></div><AppLink href={`?view=work&${params}`} className="rounded-lg bg-secondary px-4 py-2 text-sm font-semibold text-surface">Abrir lista completa e editar</AppLink></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-surface-subtle"><tr><th className="px-4 py-2 text-center">Data</th><th className="px-4 py-2 text-left">Cliente</th><th className="px-4 py-2 text-left">Descrição</th><th className="px-4 py-2 text-center">Responsável</th><th className="px-4 py-2 text-center">Facturado</th><th className="px-4 py-2 text-center">Pago</th></tr></thead><tbody className="divide-y divide-border">{rows.map(row=><tr key={row.id} tabIndex={0} aria-selected={activeRow===row.id} onClick={()=>setActiveRow(row.id)} onFocus={()=>setActiveRow(row.id)} className={`h-[2.125rem] odd:bg-surface-subtle even:bg-surface hover:bg-secondary-soft ${activeRow===row.id?'table-row-active outline outline-1 outline-secondary':''}`}><td className="px-4 py-1 text-center">{new Date(`${row.work_date}T00:00:00`).toLocaleDateString('pt-PT')}</td><td className="px-4 py-1 font-medium">{row.client_name}</td><td className="max-w-md truncate px-4 py-1" title={row.activity_description}>{row.activity_description}</td><td className="px-4 py-1 text-center">{row.professional_name}</td><td className="px-4 py-1 text-center">{row.is_invoiced?'Sim':'Não'}</td><td className="px-4 py-1 text-center">{row.is_paid?'Sim':'Não'}</td></tr>)}</tbody></table></div></section>
}
