import { useEffect, useState } from 'react'
import { AnnualValueChart, HorizontalChart, MonthlyValueChart, type ChartPoint } from '../../components/dashboard/Charts'
import { Icon } from '../../components/ui/Icon'
import { supabase } from '../../lib/supabase'

type EntityKind='client'|'billing'|'professional'
type EntityData={selectedId:string;options:{id:string;label:string}[];identity:{title:string;subtitle:string;code:string};metrics:{minutes:number;total:number|null;invoiced:number|null;paid:number|null;pending:number|null;averageRate:number|null;movements:number;clients:number;professionals:number;billingEntities:number;uninvoicedCount?:number;unpaidCount?:number;missingPrice?:number};annual:ChartPoint[];monthly:ChartPoint[];recent:{work_date:string;activity_description:string;duration_minutes:number;effective_amount:number|null}[]}
const money=new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}); const number=new Intl.NumberFormat('pt-PT')
const icons={client:'clients',billing:'building',professional:'people'} as const
const labels={client:'Cliente',billing:'Sociedade',professional:'Responsável'}

export function EntityDashboard({kind,initialSelectionLabel=null,aggregateClients=false,clientCategory=null}:{kind:EntityKind;initialSelectionLabel?:string|null;aggregateClients?:boolean;clientCategory?:'individual'|'company'|'mixed'|null}){
 const [selected,setSelected]=useState<string|null>(null); const [data,setData]=useState<EntityData|null>(null); const [error,setError]=useState('')
 useEffect(()=>{let active=true;setData(null);setError('');void(async()=>{if(!supabase){setError('Ligação ao Supabase indisponível.');return}const response=aggregateClients&&kind==='client'?await supabase.rpc('get_client_category_dashboard',{p_client_type:clientCategory}):await supabase.rpc('get_entity_dashboard_rolling',{p_kind:kind,p_entity_id:selected});if(!active)return;const {data:result,error:failure}=response;if(failure)setError(failure.message);else {const next=result as EntityData;next.identity={...next.identity,subtitle:kind==='billing'?'Sociedade':kind==='professional'?'Responsável':next.identity.subtitle==='Sociedade'?'Empresa':next.identity.subtitle};if(!aggregateClients&&!selected&&initialSelectionLabel){const option=next.options.find(item=>item.label.localeCompare(initialSelectionLabel,undefined,{sensitivity:'base'})===0);if(option&&option.id!==next.selectedId){setSelected(option.id);return}}setData(next)}})();return()=>{active=false}},[kind,selected,initialSelectionLabel,aggregateClients,clientCategory])
 if(error)return <div role="alert" className="card border-danger/30 bg-danger-soft p-6 text-danger">Não foi possível carregar o dashboard: {error}</div>
 if(!data)return <div role="status" className="card flex min-h-40 items-center gap-3 p-6"><span className="size-5 animate-spin rounded-full border-2 border-secondary border-t-transparent" aria-hidden="true"/><div><p className="font-semibold">A carregar dashboard</p><p className="mt-1 text-sm text-text-secondary">A preparar indicadores, gráficos e movimentos acessíveis.</p></div></div>
 const m=data.metrics
 const financial=(value:number|null)=>value==null?'Sem acesso':money.format(value)
 const metrics=kind==='client'?[['Total de horas',`${number.format(Math.round(m.minutes/60))} h`],['Valor total',financial(m.total)],['Valor facturado',financial(m.invoiced)],['Valor pago',financial(m.paid)],['Preço médio',m.averageRate==null?'Sem acesso':`${money.format(m.averageRate)}/h`]]:kind==='billing'?[['Valor total',financial(m.total)],['Valor facturado',financial(m.invoiced)],['Valor recebido',financial(m.paid)],['Valor pendente',financial(m.pending)],['Clientes',number.format(m.clients)],['Movimentos',number.format(m.movements)]]:[['Horas',`${number.format(Math.round(m.minutes/60))} h`],['Valor',financial(m.total)],['Preço médio',m.averageRate==null?'Sem acesso':`${money.format(m.averageRate)}/h`],['Clientes',number.format(m.clients)],['Facturado',financial(m.invoiced)],['Não facturado',m.total==null||m.invoiced==null?'Sem acesso':money.format(m.total-m.invoiced)]]
 const clientQuery=kind==='client'&&!aggregateClients?`&clientId=${encodeURIComponent(data.selectedId)}`:kind==='client'&&clientCategory?`&clientType=${clientCategory}`:''
 const followUp=kind==='client'?[['Por receber',financial(m.pending),`?view=work&invoiced=true&paid=false${clientQuery}`],['Não facturados',number.format(m.uninvoicedCount??0),`?view=work&invoiced=false${clientQuery}`],['Facturados não pagos',number.format(m.unpaidCount??0),`?view=work&invoiced=true&paid=false${clientQuery}`],['Movimentos sem preço',number.format(m.missingPrice??0),`?view=work&missingPrice=true${clientQuery}`]]:[]
 return <div className="space-y-6"><section className="card overflow-hidden"><div className="h-1 bg-gradient-to-r from-secondary via-accent to-secondary"/><div className="flex flex-wrap items-center gap-4 p-6"><div className="grid size-14 place-items-center rounded-xl bg-secondary-soft text-secondary"><Icon name={icons[kind]} className="size-7"/></div><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-secondary">{labels[kind]}{data.identity.code?` · ${data.identity.code}`:''}</p><h2 className="mt-1 font-display text-2xl font-semibold">{data.identity.title}</h2><p className="mt-1 text-sm text-text-secondary">{data.identity.subtitle}</p></div>{data.options.length>0&&<label className="ml-auto text-xs font-semibold text-text-secondary">Seleccionar {labels[kind].toLowerCase()}<select value={data.selectedId} onChange={e=>setSelected(e.target.value)} className="control mt-1 block min-w-56 px-3 text-sm">{data.options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label>}</div></section>
 <section aria-label="Indicadores" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{metrics.map(([label,value])=><article key={label} className="card p-4"><p className="text-xs text-text-secondary">{label}</p><p className={`${/valor|preço|facturado|recebido|pendente/i.test(label)?'financial-value ':''}mt-2 text-xl font-semibold tabular-nums`}>{value}</p></article>)}</section>
 {followUp.length>0&&<section aria-labelledby="client-follow-up"><div className="mb-3"><h3 id="client-follow-up" className="font-semibold">Acompanhamento</h3><p className="mt-1 text-xs text-text-secondary">Abrir os movimentos contabilizados deste cliente</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{followUp.map(([label,value,href])=><article key={label} className="card p-4"><p className="text-xs text-text-secondary">{label}</p><p className={`${label==='Por receber'?'financial-value ':''}mt-2 text-xl font-semibold tabular-nums`}>{value}</p><a href={href} aria-label={`Abrir movimentos de ${label}`} className="mt-3 flex min-h-9 items-center justify-center gap-2 rounded-lg bg-secondary px-3 text-xs font-semibold text-surface shadow-sm hover:brightness-110"><Icon name="eye" className="size-4"/>Ver movimentos</a></article>)}</div></section>}
 {m.total!=null&&<div className="grid gap-4 lg:grid-cols-2"><AnnualValueChart data={data.annual}/><MonthlyValueChart data={data.monthly}/></div>}
 <div className="grid gap-4 lg:grid-cols-2">{m.total!=null?<HorizontalChart title={kind==='client'?'Actividade por ano':kind==='billing'?'Evolução anual':'Comparação anual'} subtitle="Valores efectivos" labels={data.annual.map(p=>String(p.label))} values={data.annual.map(p=>p.value)} valueFormatter={money.format}/>:<p className="card p-5 text-sm text-text-secondary">Sem permissão para consultar os gráficos financeiros desta selecção.</p>}<section className="card overflow-hidden"><div className="border-b border-border p-5"><h2 className="font-semibold">Movimentos recentes</h2><p className="mt-1 text-xs text-text-secondary">Últimos movimentos acessíveis</p></div><ul className="divide-y divide-border">{data.recent.map((entry,index)=><li key={`${entry.work_date}-${index}`} className="flex items-center gap-3 px-5 py-3"><span className="grid size-8 place-items-center rounded-lg bg-surface-subtle text-xs font-semibold text-secondary">{index+1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{entry.activity_description}</p><p className="text-xs text-text-secondary">{new Date(`${entry.work_date}T00:00:00`).toLocaleDateString('pt-PT')} · {entry.duration_minutes} min</p></div><span className="financial-value text-sm font-semibold">{financial(entry.effective_amount)}</span></li>)}</ul></section></div></div>
}
