import { useEffect, useState } from 'react'
import { AnnualValueChart, HorizontalChart, MonthlyValueChart, type ChartPoint } from '../../components/dashboard/Charts'
import { Icon } from '../../components/ui/Icon'
import { AppLink } from '../../components/ui/AppLink'
import { supabase } from '../../lib/supabase'
import { DashboardList } from './DashboardList'
import { DashboardProcessingGrid } from './DashboardProcessingGrid'
import { MetricCard } from '../../components/dashboard/MetricCard'

type EntityKind='client'|'billing'|'professional'
type EntityData={selectedId:string;options:{id:string;label:string}[];identity:{title:string;subtitle:string;code:string};metrics:{minutes:number;total:number|null;invoiced:number|null;paid:number|null;pending:number|null;averageRate:number|null;movements:number;clients:number;professionals:number;billingEntities:number;uninvoicedCount?:number;unpaidCount?:number;missingPrice?:number};annual:ChartPoint[];monthly:ChartPoint[];recent:{work_date:string;activity_description:string;duration_minutes:number;effective_amount:number|null}[]}
const money=new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}); const number=new Intl.NumberFormat('pt-PT')
const icons={client:'clients',billing:'building',professional:'people'} as const
const labels={client:'Cliente',billing:'Sociedade',professional:'Responsável'}

export function EntityDashboard({kind,initialSelectionLabel=null,aggregateClients=false,clientCategory=null}:{kind:EntityKind;initialSelectionLabel?:string|null;aggregateClients?:boolean;clientCategory?:'individual'|'company'|'mixed'|null}){
 const [selected,setSelected]=useState<string|null>(null); const [data,setData]=useState<EntityData|null>(null); const [error,setError]=useState('')
 useEffect(()=>{let active=true;setData(null);setError('');void(async()=>{if(!supabase){setError('Ligação ao Supabase indisponível.');return}if(!aggregateClients&&!selected&&initialSelectionLabel&&(kind==='billing'||kind==='professional')){const table=kind==='billing'?'billing_entities':'professionals',column=kind==='billing'?'name':'display_name';const lookup=await supabase.from(table).select('id').eq(column,initialSelectionLabel).maybeSingle();if(!active)return;if(lookup.error){setError(lookup.error.message);return}if(lookup.data?.id){setSelected(lookup.data.id);return}}const response=aggregateClients&&kind==='client'?await supabase.rpc('get_client_category_dashboard',{p_client_type:clientCategory}):await supabase.rpc('get_entity_dashboard_rolling',{p_kind:kind,p_entity_id:selected});if(!active)return;const {data:result,error:failure}=response;if(failure)setError(failure.message);else {const next=result as EntityData;next.identity={...next.identity,subtitle:kind==='billing'?'Sociedade':kind==='professional'?'Responsável':next.identity.subtitle==='Sociedade'?'Empresa':next.identity.subtitle};setData(next)}})();return()=>{active=false}},[kind,selected,initialSelectionLabel,aggregateClients,clientCategory])
 const processingTitle=kind==='client'&&clientCategory?({individual:'Particulares',company:'Empresas',mixed:'Mistos'} as const)[clientCategory]:initialSelectionLabel??labels[kind]
 const processingMetrics=kind==='client'?['Total de horas','Valor total','Valor facturado','Valor pago','Preço médio']:kind==='billing'?['Valor total','Valor facturado','Valor recebido','Valor pendente','Clientes','Movimentos']:['Horas','Valor','Preço médio','Clientes','Facturado','Não facturado']
 const processingCard={key:`${kind}-${processingTitle}`,title:processingTitle,subtitle:`Dashboard de ${labels[kind].toLowerCase()}`,icon:icons[kind],metrics:processingMetrics}
 if(error)return <DashboardProcessingGrid error={error} label={`Erro ao calcular o dashboard de ${labels[kind].toLowerCase()}`} cards={[processingCard]}/>
 if(!data)return <DashboardProcessingGrid cards={[processingCard]} label={`A processar o dashboard de ${labels[kind].toLowerCase()}`}/>
 const m=data.metrics
 const financial=(value:number|null)=>value==null?'Sem acesso':money.format(value)
 const metrics=kind==='client'?[['Total de horas',`${number.format(Math.round(m.minutes/60))} h`],['Valor total',financial(m.total)],['Valor facturado',financial(m.invoiced)],['Valor pago',financial(m.paid)],['Preço médio',m.averageRate==null?'Sem acesso':`${money.format(m.averageRate)}/h`]]:[]
 const clientQuery=kind==='client'&&!aggregateClients?`&clientId=${encodeURIComponent(data.selectedId)}`:kind==='client'&&clientCategory?`&clientType=${clientCategory}`:''
 const followUp=kind==='client'?[['Por receber',financial(m.pending),`?view=work&invoiced=true&paid=false${clientQuery}`],['Não facturados',number.format(m.uninvoicedCount??0),`?view=work&invoiced=false${clientQuery}`],['Facturados não pagos',number.format(m.unpaidCount??0),`?view=work&invoiced=true&paid=false${clientQuery}`],['Movimentos sem preço',number.format(m.missingPrice??0),`?view=work&missingPrice=true${clientQuery}`]]:[]
 const scopeQuery=kind==='billing'?`billingEntityId=${data.selectedId}`:`professionalId=${data.selectedId}`
 return <div className="space-y-6"><section className="card overflow-hidden"><div className="h-1 bg-gradient-to-r from-secondary via-accent to-secondary"/><div className="flex flex-wrap items-center gap-4 p-6"><div className="grid size-14 place-items-center rounded-xl bg-secondary-soft text-secondary"><Icon name={icons[kind]} className="size-7"/></div><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-secondary">{labels[kind]}{data.identity.code?` · ${data.identity.code}`:''}</p><h2 className="mt-1 font-display text-2xl font-semibold">{data.identity.title}</h2><p className="mt-1 text-sm text-text-secondary">{data.identity.subtitle}</p></div>{data.options.length>0&&<label className="ml-auto text-xs font-semibold text-text-secondary">Seleccionar {labels[kind].toLowerCase()}<select value={data.selectedId} onChange={e=>setSelected(e.target.value)} className="control mt-1 block min-w-56 px-3 text-sm">{data.options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label>}</div></section>
 <div className="grid items-start gap-4 lg:grid-cols-2">{kind==='client'?<><section aria-labelledby="entity-summary" className="card p-4"><div><h3 id="entity-summary" className="font-semibold">Resumo do Cliente</h3><p className="mt-1 text-xs text-text-secondary">Indicadores do universo seleccionado</p></div><div aria-label="Indicadores" className="mt-4 grid grid-cols-2 gap-3">{metrics.map(([label,value])=><article key={label} className="rounded-lg bg-surface-subtle p-3"><p className="text-xs text-text-secondary">{label}</p><p className={`${/valor|preço|facturado|recebido|pendente/i.test(label)?'financial-value ':''}mt-2 text-xl font-semibold tabular-nums`}>{value}</p></article>)}</div></section><section aria-labelledby="entity-attention" className="card p-4"><div><h3 id="entity-attention" className="font-semibold">Acompanhamento</h3><p className="mt-1 text-xs text-text-secondary">Abrir os movimentos contabilizados deste cliente</p></div><div className="mt-4 grid grid-cols-2 gap-3">{followUp.map(([label,value,href])=><article key={label} className="rounded-lg bg-surface-subtle p-3"><p className="text-xs text-text-secondary">{label}</p><p className={`${label==='Por receber'?'financial-value ':''}mt-2 text-xl font-semibold tabular-nums`}>{value}</p><AppLink href={href} aria-label={`Abrir movimentos de ${label}`} className="mt-3 flex min-h-9 items-center justify-center gap-2 rounded-lg bg-secondary px-3 text-xs font-semibold text-surface shadow-sm hover:brightness-110"><Icon name="eye" className="size-4"/>Ver movimentos</AppLink></article>)}</div></section></>:<><section aria-labelledby="entity-summary"><div className="mb-4"><h3 id="entity-summary" className="font-semibold">Resumo Operacional</h3><p className="mt-1 text-xs text-text-secondary">Indicadores {kind==='billing'?'desta Sociedade':'deste Responsável'}</p></div><div className="grid grid-cols-2 gap-3">{[
  ['Total de Horas',`${number.format(Math.round(m.minutes/60))} h`,'Duração convertida','clock',false],
  ['Valor Trabalhado',financial(m.total),'Valor efectivo','trend',true],
  ['Valor Facturado',financial(m.invoiced),'Movimentos facturados','invoice',true],
  ['Valor Recebido',financial(m.paid),'Movimentos pagos','payment',true],
  ['Preço Médio/Hora',m.averageRate==null?'Sem acesso':`${money.format(m.averageRate)}/h`,'Média ponderada','rules',true],
  ['Clientes Activos',number.format(m.clients),'Com movimentos','clients',false],
 ].map(([label,value,detail,icon,isFinancial])=><MetricCard key={String(label)} label={String(label)} value={String(value)} detail={String(detail)} icon={icon as 'clock'} financial={Boolean(isFinancial)}/>)}</div></section><section aria-labelledby="entity-attention"><div className="mb-4"><h3 id="entity-attention" className="font-semibold text-danger">Acompanhamento</h3><p className="mt-1 text-xs text-text-secondary">Pendências {kind==='billing'?'desta Sociedade':'deste Responsável'}</p></div><div className="grid grid-cols-2 gap-3">{[
  ['Por Receber',financial(m.pending),'Facturado e ainda não pago','warning',`?view=work&${scopeQuery}&invoiced=true&paid=false`,true],
  ['Não Facturados',number.format(m.uninvoicedCount??0),'Movimentos','invoice',`?view=work&${scopeQuery}&invoiced=false`,false],
  ['Facturados Não Pagos',number.format(m.unpaidCount??0),'Requer acompanhamento','payment',`?view=work&${scopeQuery}&invoiced=true&paid=false`,false],
  ['Movimentos Sem Preço',number.format(m.missingPrice??0),'Necessitam de revisão','warning',`?view=work&${scopeQuery}&missingPrice=true`,false],
 ].map(([label,value,detail,icon,href,isFinancial])=><MetricCard key={String(label)} label={String(label)} value={String(value)} detail={String(detail)} icon={icon as 'warning'} financial={Boolean(isFinancial)} tone="danger" detailHref={String(href)}/>)}</div></section></>}</div>
 {m.total!=null&&<div className="grid gap-4 md:grid-cols-2 [&>*]:min-w-0"><AnnualValueChart data={data.annual} allowSocietyComparison={kind!=='client'} comparisonLabel={kind==='billing'?'responsável':'sociedade'} comparisonPlural={kind==='billing'?'responsáveis':'sociedades'}/><MonthlyValueChart data={data.monthly} allowSocietyComparison={kind!=='client'} comparisonLabel={kind==='billing'?'responsável':'sociedade'}/></div>}
 {kind!=='client'&&<DashboardList kind={kind} id={data.selectedId}/>}
 <div className={`grid gap-4 ${kind==='billing'?'':'lg:grid-cols-2'}`}>{kind!=='billing'&&(m.total!=null?<HorizontalChart title={kind==='client'?'Actividade por ano':'Comparação anual'} subtitle="Valores efectivos" labels={data.annual.map(p=>String(p.label))} values={data.annual.map(p=>p.value)} valueFormatter={money.format}/>:<p className="card p-5 text-sm text-text-secondary">Sem permissão para consultar os gráficos financeiros desta selecção.</p>)}<section className="card overflow-hidden"><div className="border-b border-border p-5"><h2 className="font-semibold">Movimentos recentes</h2><p className="mt-1 text-xs text-text-secondary">Últimos movimentos acessíveis</p></div><ul className="divide-y divide-border">{data.recent.map((entry,index)=><li key={`${entry.work_date}-${index}`} className="flex items-center gap-3 px-5 py-3"><span className="grid size-8 place-items-center rounded-lg bg-surface-subtle text-xs font-semibold text-secondary">{index+1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{entry.activity_description}</p><p className="text-xs text-text-secondary">{new Date(`${entry.work_date}T00:00:00`).toLocaleDateString('pt-PT')} · {entry.duration_minutes} min</p></div><span className="financial-value text-sm font-semibold">{financial(entry.effective_amount)}</span></li>)}</ul></section></div></div>
}
