import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'
type Profile={client_id:string;client_type:'individual'|'company';client_code:string;clients:{display_name:string}|{display_name:string}[]|null}
type Mixed={id:string;name:string;individual:string;company:string}
export function MixedClientsTable(){
 const [rows,setRows]=useState<Mixed[]>([]),[error,setError]=useState('')
 const [activeRow,setActiveRow]=useState<string|null>(null)
 useEffect(()=>{let active=true;void(async()=>{const db=supabase;if(!db)return;const result=await db.from('client_profiles').select('client_id,client_type,client_code,clients(display_name)').eq('active',true);if(!active)return;if(result.error){setError(result.error.message);return}const grouped=new Map<string,Profile[]>();for(const profile of (result.data??[]) as Profile[])grouped.set(profile.client_id,[...(grouped.get(profile.client_id)??[]),profile]);setRows([...grouped.entries()].filter(([,profiles])=>new Set(profiles.map(p=>p.client_type)).size>1).map(([id,profiles])=>{const relation=profiles[0].clients,name=Array.isArray(relation)?relation[0]?.display_name:relation?.display_name;return{id,name:name??'Cliente sem nome',individual:profiles.find(p=>p.client_type==='individual')?.client_code??'—',company:profiles.find(p=>p.client_type==='company')?.client_code??'—'}}).sort((a,b)=>a.name.localeCompare(b.name,'pt-PT')))})();return()=>{active=false}},[])
 if(error)return <p role="alert" className="card border-danger/30 bg-danger-soft p-4 text-sm text-danger">Não foi possível carregar a lista de clientes mistos: {error}</p>
 return <section className="card overflow-hidden"><div className="border-b border-border p-5"><h3 className="font-semibold">Lista</h3><p className="mt-1 text-xs text-text-secondary">{rows.length.toLocaleString('pt-PT')} clientes mistos — vertentes e códigos para verificação</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-surface-subtle"><tr><th className="px-4 py-2 text-left">Cliente</th><th className="px-4 py-2 text-center">Código particular</th><th className="px-4 py-2 text-center">Código empresa</th></tr></thead><tbody className="divide-y divide-border">{rows.map(row=><tr key={row.id} tabIndex={0} aria-selected={activeRow===row.id} onClick={()=>setActiveRow(row.id)} onFocus={()=>setActiveRow(row.id)} className={`h-[2.125rem] odd:bg-surface-subtle even:bg-surface hover:bg-secondary-soft ${activeRow===row.id?'table-row-active outline outline-1 outline-secondary':''}`}><td className="px-4 py-1 font-medium">{row.name}</td><td className="px-4 py-1 text-center">{row.individual}</td><td className="px-4 py-1 text-center">{row.company}</td></tr>)}</tbody></table></div></section>
}
