import { useEffect, useState } from 'react'
import { Icon } from '../../components/ui/Icon'
import { supabase } from '../../lib/supabase'
import { AttentionPanel } from './AttentionPanel'
import type { AttentionCounts } from './attentionCounts'
import { DashboardProcessingGrid } from './DashboardProcessingGrid'
type Summary={id:string;name:string;minutes:number;total:number|null;invoiced:number|null;clients:number}&AttentionCounts
const money=new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR',maximumFractionDigits:0}),number=new Intl.NumberFormat('pt-PT'),financial=(v:number|null)=>v==null?'Sem acesso':money.format(v)
export function ProfessionalLandingPage({onSelect}:{onSelect:(name:string)=>void}){
 const [data,setData]=useState<Summary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const [processingNames,setProcessingNames]=useState<string[]>([])
 useEffect(()=>{let active=true;void(async()=>{const db=supabase;if(!db){setError('Ligação ao Supabase indisponível.');setLoading(false);return}const names=await db.from('professionals').select('display_name').eq('active',true).order('display_name');if(!active)return;if(!names.error)setProcessingNames((names.data??[]).map(item=>item.display_name));const response=await db.rpc('get_professional_landing_summaries');if(!active)return;if(response.error)setError(response.error.message);else setData((response.data??[]) as Summary[]);setLoading(false)})();return()=>{active=false}},[])
 if(loading)return <DashboardProcessingGrid cards={(processingNames.length?processingNames:['Responsável 1','Responsável 2','Responsável 3']).map((name,index)=>({key:`${name}-${index}`,title:name,subtitle:'Resumo do responsável',icon:'people',metrics:['Clientes','Horas','Valor','Facturado','Por facturar']}))}/>
 if(error)return <DashboardProcessingGrid error={error} label="Erro ao calcular o dashboard de responsáveis" cards={(processingNames.length?processingNames:['Responsável 1','Responsável 2','Responsável 3']).map((name,index)=>({key:`${name}-${index}`,title:name,subtitle:'Resumo do responsável',icon:'people',metrics:['Clientes','Horas','Valor','Facturado','Por facturar']}))}/>
 return <div className="space-y-5"><header><p className="text-sm text-text-secondary">Resumo operacional, alertas e acesso aos dashboards.</p></header><div className="grid gap-4 lg:grid-cols-3">{data.map(item=><article key={item.id} className="card flex flex-col overflow-hidden"><div className="h-1 bg-gradient-to-r from-secondary via-accent to-secondary"/><div className="flex flex-1 flex-col p-6"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-secondary-soft text-secondary"><Icon name="people" className="size-6"/></span><div><h3 className="font-display text-xl font-semibold">{item.name}</h3><p className="mt-1 text-xs text-text-secondary">Resumo do responsável</p></div></div><dl className="mt-6 grid grid-cols-2 gap-3"><Metric label="Clientes" value={number.format(item.clients)}/><Metric label="Horas" value={`${number.format(Math.round(item.minutes/60))} h`}/><Metric label="Valor" value={financial(item.total)} financial/><Metric label="Facturado" value={financial(item.invoiced)} financial/><Metric label="Por facturar" value={item.total==null||item.invoiced==null?'Sem acesso':money.format(item.total-item.invoiced)} financial/></dl><AttentionPanel counts={item} links={{uninvoiced:`?view=work&professionalId=${item.id}&invoiced=false`,unpaid:`?view=work&professionalId=${item.id}&invoiced=true&paid=false`,missingPrice:`?view=work&professionalId=${item.id}&missingPrice=true`}}/><button type="button" onClick={()=>onSelect(item.name)} className="mt-5 flex min-h-11 items-center justify-center gap-2 rounded-lg bg-secondary px-4 text-sm font-semibold text-surface">Abrir dashboard <Icon name="chevron" className="size-4"/></button></div></article>)}</div></div>
}
function Metric({label,value,financial=false}:{label:string;value:string;financial?:boolean}){return <div className="rounded-lg bg-surface-subtle p-3"><dt className="text-xs text-text-secondary">{label}</dt><dd className={`${financial?'financial-value ':''}mt-1 text-lg font-semibold tabular-nums`}>{value}</dd></div>}
