begin;
create extension if not exists pgtap with schema extensions;
select plan(60);

select has_table('public','billing_entity_financial_permissions','financial permissions exist per Society');
select row_security_active('public','billing_entity_financial_permissions','financial permissions have RLS enabled');
select has_function('public','search_work_entries',array['integer','integer','text','integer','uuid','uuid','boolean','boolean','text','boolean','text','text'],'controlled work-entry read model exists');
select has_function('public','get_dashboard_overview',array[]::text[],'controlled overview read model exists');
select has_function('public','get_entity_dashboard',array['text','uuid'],'controlled entity read model exists');
select has_function('public','get_client_category_dashboard',array['text'],'controlled client dashboard exists');
select has_function('public','apply_work_entry_override',array['uuid','text','jsonb','text'],'public override endpoint exists');
select has_function('public','preview_work_entry_recalculation',array['uuid[]','boolean','boolean'],'recalculation preview exists');
select has_function('public','recalculate_work_entries',array['uuid[]','boolean','boolean'],'controlled recalculation endpoint exists');
select has_function('public','replace_user_billing_permissions',array['uuid','uuid','jsonb','uuid'],'atomic permission replacement exists');
select has_function('public','update_user_membership',array['uuid','uuid','text','boolean','uuid'],'atomic membership update exists');
select has_function('public','get_my_access_status',array[]::text[],'authoritative session-status endpoint exists');
select has_function('public','get_work_entry_form_options',array[]::text[],'scoped movement form options exist');
select has_function('public','create_work_entry',array['date','uuid','uuid','uuid','uuid','text','integer','text'],'controlled movement creation exists');
select has_function('public','update_work_entry_details',array['uuid','date','uuid','uuid','uuid','text','text'],'controlled non-financial movement editing exists');
select has_function('public','get_work_entry_for_edit',array['uuid'],'scoped movement edit model exists');
select has_function('public','bulk_update_work_entries',array['uuid[]','text','jsonb','text'],'controlled bulk movement updates exist');
select has_function('public','finalize_pin_user_creation',array['uuid','uuid','uuid','text','text','text','text','uuid'],'atomic PIN-user finalisation exists');
select has_function('public','list_visible_invoices',array[]::text[],'masked invoice read model exists');
select has_function('public','list_visible_payments',array[]::text[],'masked payment read model exists');
select has_function('public','list_visible_rate_rules',array[]::text[],'masked pricing read model exists');
select has_function('public','export_visible_work_entries',array['text','integer','uuid','uuid','boolean','boolean','text','boolean','text','text'],'scoped complete work-entry export exists');
select ok(not has_function_privilege('anon','public.export_visible_work_entries(text,integer,uuid,uuid,boolean,boolean,text,boolean,text,text)','EXECUTE'),'anonymous users cannot export movements');
select ok(has_function_privilege('service_role','public.replace_user_billing_permissions(uuid,uuid,jsonb,uuid)','EXECUTE'),'service role can replace permissions atomically');
select ok(has_function_privilege('service_role','public.update_user_membership(uuid,uuid,text,boolean,uuid)','EXECUTE'),'service role can update membership atomically');
select ok(has_function_privilege('service_role','public.finalize_pin_user_creation(uuid,uuid,uuid,text,text,text,text,uuid)','EXECUTE'),'service role can finalise a PIN user atomically');
select ok(has_function_privilege('service_role','public.register_pin_login_failure(uuid,text,text)','EXECUTE'),'service role can atomically register PIN failures');
select ok(not has_function_privilege('authenticated','public.register_pin_login_failure(uuid,text,text)','EXECUTE'),'authenticated cannot bypass the PIN failure endpoint');
select ok(not has_function_privilege('authenticated','public.replace_user_billing_permissions(uuid,uuid,jsonb,uuid)','EXECUTE'),'frontend users cannot call privileged permission replacement');
select ok(not has_function_privilege('authenticated','public.update_user_membership(uuid,uuid,text,boolean,uuid)','EXECUTE'),'frontend users cannot call privileged membership update');
select ok(not has_function_privilege('authenticated','public.finalize_pin_user_creation(uuid,uuid,uuid,text,text,text,text,uuid)','EXECUTE'),'frontend users cannot finalise PIN users');
select ok(has_function_privilege('authenticated','public.get_my_access_status()','EXECUTE'),'authenticated users can validate their own effective access');
select ok(has_function_privilege('authenticated','public.get_work_entry_form_options()','EXECUTE'),'authenticated users can request scoped form options');
select ok(has_function_privilege('authenticated','public.create_work_entry(date,uuid,uuid,uuid,uuid,text,integer,text)','EXECUTE'),'authenticated users can use controlled movement creation');
select ok(has_function_privilege('authenticated','public.update_work_entry_details(uuid,date,uuid,uuid,uuid,text,text)','EXECUTE'),'authenticated users can use controlled non-financial editing');
select ok(has_function_privilege('authenticated','public.get_work_entry_for_edit(uuid)','EXECUTE'),'authenticated users can load an authorised movement for editing');
select ok(has_function_privilege('authenticated','public.bulk_update_work_entries(uuid[],text,jsonb,text)','EXECUTE'),'authenticated users can invoke controlled bulk updates');
select ok(not has_function_privilege('anon','public.create_work_entry(date,uuid,uuid,uuid,uuid,text,integer,text)','EXECUTE'),'anonymous users cannot create movements');
select ok(not has_function_privilege('anon','public.update_work_entry_details(uuid,date,uuid,uuid,uuid,text,text)','EXECUTE'),'anonymous users cannot edit movements');
select ok(not has_function_privilege('anon','public.get_work_entry_for_edit(uuid)','EXECUTE'),'anonymous users cannot load movement edit data');
select ok(not has_function_privilege('anon','public.bulk_update_work_entries(uuid[],text,jsonb,text)','EXECUTE'),'anonymous users cannot invoke bulk updates');
select ok(not has_table_privilege('authenticated','public.security_events','INSERT'),'frontend cannot forge security events');
select ok(not has_table_privilege('anon','public.security_events','INSERT'),'anonymous users cannot forge security events');
select ok(has_function_privilege('authenticated','public.apply_work_entry_override(uuid,text,jsonb,text)','EXECUTE'),'authenticated can execute the controlled override endpoint');
select ok(not has_function_privilege('anon','public.apply_work_entry_override(uuid,text,jsonb,text)','EXECUTE'),'anonymous users cannot execute overrides');
select ok(not exists(select 1 from information_schema.routine_privileges where routine_schema='public' and routine_name='apply_work_entry_override' and grantee='PUBLIC' and privilege_type='EXECUTE'),'PUBLIC cannot execute overrides');
select ok(not has_table_privilege('authenticated','public.work_entries','SELECT'),'authenticated users cannot bypass the read model');
select ok(not has_table_privilege('authenticated','public.work_entries','INSERT'),'frontend cannot bypass controlled movement creation');
select ok(not has_table_privilege('authenticated','public.work_entries','UPDATE'),'frontend cannot bypass controlled movement editing');
select ok(not has_table_privilege('authenticated','public.work_entries','DELETE'),'frontend cannot delete movements directly');
select ok(not has_table_privilege('authenticated','public.work_entries','TRUNCATE'),'frontend cannot truncate movements');
select ok(not has_table_privilege('authenticated','public.invoices','SELECT'),'authenticated users cannot bypass invoice masking');
select ok(not has_table_privilege('authenticated','public.payments','SELECT'),'authenticated users cannot bypass payment masking');
select ok(not has_table_privilege('authenticated','public.rate_rules','SELECT'),'authenticated users cannot bypass pricing masking');
select ok(not has_table_privilege('authenticated','public.invoice_lines','SELECT'),'authenticated users cannot read invoice line values directly');
select ok(not has_table_privilege('authenticated','public.manual_overrides','INSERT'),'frontend cannot bypass the controlled override endpoint');
select ok(not has_table_privilege('authenticated','public.manual_overrides','UPDATE'),'manual overrides are immutable to frontend users');
select ok(not has_table_privilege('authenticated','public.manual_overrides','DELETE'),'manual overrides cannot be deleted by frontend users');
select ok(not has_function_privilege('authenticated','private.apply_work_entry_override(uuid,text,jsonb,text)','EXECUTE'),'private override engine is not exposed');
select policies_are('public','audit_log',array['audit_log_select_privileged'],'audit log has one explicit read-only privileged policy');

select * from finish();
rollback;
