import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

const clientName = 'Cliente Alfa — DEMO'
let external: string[]
let pageErrors: string[]
async function menu(page: Page, label: string) {
  if (await page.getByRole('button', { name: 'Abrir navegação', exact: true }).isVisible()) await page.getByRole('button', { name: 'Abrir navegação', exact: true }).click()
  await page.getByRole('complementary', { name: 'Navegação principal' }).getByRole('button', { name: label, exact: false }).click()
}
async function client(page: Page) {
  await menu(page, 'Clientes')
  await page.getByRole('article').filter({ has: page.getByRole('heading', { name: clientName, exact: true }) }).getByRole('button', { name: 'Abrir ficha', exact: true }).click()
}
async function view(page: Page, fila: string) { await menu(page, 'Financeiro'); await page.getByRole('navigation', { name: 'Áreas do Financeiro' }).getByRole('button', { name: fila, exact: true }).click() }
async function modal(page: Page, name: string) { const dialog = page.getByRole('dialog', { name, exact: true }); await expect(dialog).toBeVisible(); return dialog }

test.beforeEach(async ({ page }) => {
  external = []; pageErrors = []
  page.on('pageerror', error => pageErrors.push(error.message))
  await page.route('**/*', async route => {
    const url = route.request().url()
    if (url.startsWith('http://127.0.0.1:5175/') || url.startsWith('blob:') || url.startsWith('data:')) await route.continue()
    else { external.push(url); await route.abort() }
  })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Resumo', exact: true })).toBeVisible()
})
test.afterEach(async () => { expect(external, 'O protótipo não pode tentar contactar serviços externos').toEqual([]); expect(pageErrors, 'Sem erros JavaScript no percurso').toEqual([]) })

test('cinco menus, cinco áreas da ficha, temas e largura da página', async ({ page }, info) => {
  await mkdir('output/workflow-qa/screenshots', { recursive: true })
  for (const dark of [false, true]) {
    if (dark) await page.getByRole('button', { name: 'Activar modo escuro' }).click()
    for (const name of ['Resumo', 'Clientes', 'Trabalho', 'Financeiro', 'Notas']) {
      await menu(page, name)
      await expect(page.getByRole('heading', { level: 1 })).toHaveText(name)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
      await page.screenshot({ path: `output/workflow-qa/screenshots/${info.project.name}-${name}-${dark ? 'dark' : 'light'}.png`, fullPage: true })
    }
    await client(page)
    const tabs = page.getByRole('navigation', { name: 'Áreas da ficha do cliente' })
    await expect(tabs.getByRole('button')).toHaveCount(5)
    for (const name of ['Resumo', 'Dados', 'Trabalho', 'Contratos', 'Financeiro e documentos']) {
      await tabs.getByRole('button', { name, exact: true }).click()
      await expect(tabs.getByRole('button', { name, exact: true })).toHaveAttribute('aria-current', 'page')
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
      await page.screenshot({ path: `output/workflow-qa/screenshots/${info.project.name}-cliente-${name.replaceAll(' ', '-')}-${dark ? 'dark' : 'light'}.png`, fullPage: true })
    }
  }
})

test('registo usa o mesmo formulário, guarda contexto, filtros e voltar', async ({ page }) => {
  await menu(page, 'Clientes')
  await page.getByLabel('Pesquisar clientes', { exact: true }).fill('Alfa')
  await page.getByRole('button', { name: 'Abrir ficha', exact: true }).click()
  await page.getByRole('button', { name: 'Novo registo', exact: true }).click()
  let dialog = await modal(page, 'Novo registo')
  await expect(dialog.getByRole('combobox', { name: 'Cliente', exact: true })).toHaveValue('demo-alfa')
  await dialog.getByLabel('Actividade / assunto', { exact: true }).fill('Registo fictício criado no ensaio')
  await dialog.getByLabel('Montante (€)', { exact: true }).fill('100')
  await dialog.getByRole('button', { name: 'Guardar demonstração' }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('navigation', { name: 'Áreas da ficha do cliente' }).getByRole('button', { name: 'Trabalho', exact: true }).click()
  await expect(page.getByText('Registo fictício criado no ensaio', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Voltar à lista', exact: false }).click()
  await expect(page.getByLabel('Pesquisar clientes', { exact: true })).toHaveValue('Alfa')
  await menu(page, 'Trabalho')
  await page.getByRole('button', { name: 'Novo registo', exact: true }).click()
  dialog = await modal(page, 'Novo registo')
  await expect(dialog.getByLabel('Actividade / assunto', { exact: true })).toBeVisible()
  await expect(dialog.getByLabel('Minutos', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'Cancelar' }).click()
})

test('tradução falhada bloqueia emissão; PDF/Word e reimpressão da versão', async ({ page }, info) => {
  await client(page)
  await page.getByRole('button', { name: 'Preparar nota', exact: true }).click()
  const dialog = await modal(page, 'Preparar nota de honorários')
  await dialog.getByRole('combobox', { name: 'Idioma do documento', exact: true }).selectOption('fr')
  await dialog.getByText('Ensaiar falha de tradução', { exact: true }).click()
  await dialog.getByRole('checkbox', { name: 'Simular indisponibilidade da tradução EN/FR' }).check()
  await dialog.getByRole('button', { name: 'Emitir exemplo PDF' }).click()
  await expect(dialog.getByRole('alert')).toContainText('emissão foi bloqueada')
  await dialog.getByRole('checkbox', { name: 'Simular indisponibilidade da tradução EN/FR' }).uncheck()
  await dialog.getByRole('button', { name: 'Pré-visualizar sem guardar' }).click()
  await expect(dialog.getByRole('region', { name: 'Pré-visualização do documento' })).toContainText('Réunion de suivi')
  await page.screenshot({ path: `output/workflow-qa/screenshots/${info.project.name}-traducao-fr.png`, fullPage: true })
  const pdfPromise = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Emitir exemplo PDF' }).click()
  const pdf = await pdfPromise; expect(pdf.suggestedFilename()).toMatch(/fr\.pdf$/)
  await pdf.saveAs(`output/workflow-qa/${info.project.name}-nota-fr.pdf`)
  await expect(dialog).not.toBeVisible()
  await page.getByRole('navigation', { name: 'Áreas da ficha do cliente' }).getByRole('button', { name: 'Financeiro e documentos', exact: true }).click()
  await expect(page.getByText('Réunion de suivi et analyse de documents.', { exact: true })).toBeVisible()
  const wordPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Guardar Word', exact: true }).click()
  const word = await wordPromise; expect(word.suggestedFilename()).toMatch(/fr\.docx$/)
  await word.saveAs(`output/workflow-qa/${info.project.name}-nota-fr.docx`)
  const reprint = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Guardar PDF', exact: true }).click()
  expect((await reprint).suggestedFilename()).toBe(pdf.suggestedFilename())
})

test('facturação distinta do recebimento e parcial sem utilizar provisão', async ({ page }) => {
  await view(page, 'Por facturar')
  const row = page.getByRole('article').filter({ hasText: 'Reunião de acompanhamento' })
  await row.getByRole('button', { name: 'Registar factura', exact: true }).click()
  let dialog = await modal(page, 'Registar factura')
  await dialog.getByLabel('Número da factura').fill('DEMO-FT-ENSAIO')
  await dialog.getByRole('button', { name: 'Guardar demonstração' }).click()
  await view(page, 'Pagamentos')
  const note = page.getByRole('article').filter({ hasText: 'DEMO-NH-001' })
  await note.getByRole('button', { name: 'Registar pagamento', exact: true }).click()
  dialog = await modal(page, 'Registar pagamento')
  await dialog.getByLabel('Valor recebido (€)', { exact: true }).fill('500')
  await dialog.getByLabel('Referência do recebimento').fill('DEMO-PARCIAL')
  await dialog.getByRole('checkbox', { name: 'Confirmo que o valor de demonstração foi recebido.' }).check()
  await dialog.getByRole('button', { name: 'Registar pagamento', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('não pode exceder')
  await dialog.getByLabel('Valor recebido (€)', { exact: true }).fill('25')
  await dialog.getByRole('button', { name: 'Registar pagamento', exact: true }).click()
  await expect(note).toContainText('125,00')
  await expect(page.getByText('DEMO-PARCIAL', { exact: false })).toBeVisible()
  await view(page, 'Provisões')
  await expect(page.getByText('Saldo disponível 100,00', { exact: false })).toBeVisible()
})

test('contratos, registos associados e notas partilhadas', async ({ page }) => {
  await client(page)
  await page.getByRole('navigation', { name: 'Áreas da ficha do cliente' }).getByRole('button', { name: 'Contratos', exact: true }).click()
  await page.getByText('Gerir registos associados', { exact: true }).click()
  await page.getByRole('checkbox', { name: 'Reunião de acompanhamento e análise de documentação.' }).check()
  await expect(page.getByText('Em curso', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Marcar como terminado' }).click()
  await expect(page.getByText(/^Terminado ·/)).toBeVisible()
  await menu(page, 'Notas')
  await page.getByRole('button', { name: 'Nova nota', exact: true }).click()
  const dialog = await modal(page, 'Nota de trabalho')
  await dialog.getByLabel('Título da nota').fill('Tarefa DEMO do operador')
  await dialog.getByRole('combobox', { name: 'Partilha', exact: true }).selectOption('Edição')
  await dialog.getByLabel('Conteúdo e tarefas').fill('Conferir documentos fictícios')
  await dialog.getByRole('button', { name: 'Guardar demonstração' }).click()
  await expect(page.getByRole('article').filter({ hasText: 'Tarefa DEMO do operador' })).toContainText('Partilha: Edição')
})

test('administração restrita, importação de exemplo e cobertura do tradutor', async ({ page }) => {
  await menu(page, 'Definições')
  await expect(page.getByRole('button', { name: 'Utilizadores', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Registos de acesso', exact: true })).toBeDisabled()
  await page.getByRole('combobox', { name: 'Perfil de ensaio', exact: true }).selectOption('admin')
  await expect(page.getByRole('button', { name: 'Utilizadores', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Registos de acesso', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Importações', exact: true }).click()
  await page.getByRole('button', { name: 'Analisar exemplo CSV fictício' }).click()
  await expect(page.getByText('3 linhas fictícias', { exact: false })).toBeVisible()
  await page.getByRole('combobox', { name: 'Perfil de ensaio', exact: true }).selectOption('viewer')
  await expect(page.getByRole('button', { name: '+ Adicionar' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Ver funcionalidades preservadas' }).click()
  const dialog = await modal(page, 'Funcionalidades e integrações preservadas')
  await dialog.getByLabel('Procurar função ou integração').fill('Azure')
  await expect(dialog).toContainText('Azure Translator')
  await dialog.getByRole('button', { name: 'Fechar formulário' }).click()
  await expect(dialog).not.toBeVisible()
})

test('caixas abrem exactamente os itens contados e distinguem horas de despesas', async ({ page }) => {
  const counts = page.getByLabel('Contagens e atalhos do Resumo', { exact: true })
  await expect(counts.getByRole('button', { name: 'Abrir Horas registadas', exact: true })).toContainText('3 itens')
  await page.getByRole('button', { name: 'Abrir Horas registadas', exact: true }).click()
  await expect(page.locator('tbody tr')).toHaveCount(3)
  await expect(page.getByText('Deslocação de demonstração', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Voltar ao resumo', exact: false }).click()
  await page.getByRole('button', { name: 'Abrir Registos não facturados', exact: true }).click()
  await expect(page.locator('tbody tr')).toHaveCount(2)
  await expect(page.getByText('Consulta jurídica de demonstração', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Remover pré-filtro', exact: true }).click()
  await expect(page.locator('tbody tr')).toHaveCount(4)
})

test('gráfico abre só o cliente escolhido e voltar conserva sociedade e responsável', async ({ page }) => {
  await page.getByRole('combobox', { name: 'Sociedade', exact: true }).selectOption('LEGALTEAM — DEMO')
  await page.getByRole('combobox', { name: 'Responsável', exact: true }).selectOption('Responsável A — DEMO')
  await expect(page.getByRole('button', { name: 'Abrir Horas registadas', exact: true })).toContainText('2.0 h')
  const bar = page.getByRole('button', { name: 'Filtrar horas de Cliente Gama — DEMO', exact: true })
  await bar.focus(); await page.keyboard.press('Enter')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.getByLabel('Filtros activos', { exact: true })).toContainText('Cliente Gama — DEMO')
  await expect(page.getByText('Acompanhamento de avença', { exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Resumo')
  await expect(page.getByRole('combobox', { name: 'Sociedade', exact: true })).toHaveValue('LEGALTEAM — DEMO')
  await expect(page.getByRole('combobox', { name: 'Responsável', exact: true })).toHaveValue('Responsável A — DEMO')
  await page.getByRole('button', { name: 'Filtrar Registos não facturados', exact: true }).click()
  await expect(page.locator('tbody tr')).toHaveCount(0)
  await expect(page.getByText('Nenhum movimento corresponde à selecção.', { exact: true })).toBeVisible()
})

test('pré-filtros financeiros respeitam a selecção e não confundem recebimentos com provisões', async ({ page }) => {
  await page.getByRole('button', { name: 'Abrir Notas por receber', exact: true }).click()
  await expect(page.getByRole('article').filter({ hasText: 'DEMO-NH-001 · v1' })).toHaveCount(1)
  await page.getByRole('button', { name: 'Voltar ao resumo', exact: false }).click()
  await page.getByRole('combobox', { name: 'Sociedade', exact: true }).selectOption('Sociedade Norte — DEMO')
  await expect(page.getByRole('button', { name: 'Abrir Recebimentos registados', exact: true })).toContainText('0 itens')
  await page.getByRole('button', { name: 'Abrir Recebimentos registados', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Registar recebimentos', exact: true })).toHaveCount(0)
  await expect(page.getByRole('article')).toHaveCount(0)
  await page.getByRole('button', { name: 'Voltar ao resumo', exact: false }).click()
  await page.getByRole('button', { name: 'Abrir Provisão disponível', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(1)
  await expect(page.getByText('Saldo disponível', { exact: false })).toContainText('100')
  await page.getByRole('button', { name: 'Voltar ao resumo', exact: false }).click()
  await page.getByRole('button', { name: 'Abrir Notas por receber', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(0)
})

test('segmentos de tipo e contratos conservam as contagens e o contexto', async ({ page }) => {
  await page.getByRole('button', { name: 'Filtrar clientes Particular', exact: true }).click()
  await expect(page.locator('.client-card')).toHaveCount(2)
  await expect(page.getByLabel('Filtros activos', { exact: true })).toContainText('Segmento: Particular')
  await page.getByRole('button', { name: 'Voltar ao resumo', exact: false }).click()
  await expect(page.getByRole('combobox', { name: 'Tipo de cliente', exact: true })).toHaveValue('Todos')
  await page.getByRole('button', { name: 'Abrir Trabalhos a preço fixo', exact: true }).click()
  await expect(page.locator('.contract')).toHaveCount(1)
  await expect(page.getByText('Anual · utilizadas', { exact: false })).toHaveCount(0)
  await page.getByRole('button', { name: 'Voltar ao resumo', exact: false }).click()
  await page.getByRole('button', { name: 'Filtrar Avenças', exact: true }).click()
  await expect(page.locator('.contract')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Editar condição', exact: true })).toHaveCount(1)
})
