import { lazy,Suspense,useEffect,useMemo,useRef,useState,type CSSProperties } from 'react'
import { Icon } from '../../components/ui/Icon'
import { openClientRecord } from '../master-data/openClientRecord'
import { formatDate } from '../../utils/date'
import { loadDebtors,type Debtor } from './debtorSummary'

const WorkEntriesPage=lazy(()=>import('../work-entries/WorkEntriesPage').then(module=>({default:module.WorkEntriesPage})))
const DebtorRetainerCharges=lazy(()=>import('./DebtorRetainerCharges').then(module=>({default:module.DebtorRetainerCharges})))
const money=new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'})
const count=new Intl.NumberFormat('pt-PT')
const hours=(minutes:number)=>`${Math.floor(minutes/60)} h${minutes%60?` ${minutes%60} min`:''}`
const daysSince=(date:string)=>Math.max(0,Math.floor((Date.now()-new Date(`${date}T00:00:00Z`).valueOf())/86_400_000))
const value=(amount:number|null,partial=false)=>amount==null?'Sem valor acessível':`${money.format(amount)}${partial?' · parcial':''}`

export function DebtorsPage(){
 const [rows,setRows]=useState<Debtor[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0),[search,setSearch]=useState(''),[detail,setDetail]=useState<{client:Debtor;kind:'unpaid'|'uninvoiced'|'retainerInvoiced'|'retainerPending'}|null>(null)
 const returnPoint=useRef<{x:number;y:number;source:HTMLElement|null}|null>(null)
 const openDetail=(client:Debtor,kind:NonNullable<typeof detail>['kind'],source:HTMLElement)=>{returnPoint.current={x:window.scrollX,y:window.scrollY,source};setDetail({client,kind})}
 const closeDetail=()=>{setDetail(null);setRevision(current=>current+1);const point=returnPoint.current;requestAnimationFrame(()=>{if(point){window.scrollTo(point.x,point.y);point.source?.focus({preventScroll:true})}})}
 useEffect(()=>{let active=true;setLoading(true);setError('');void loadDebtors(revision>0).then(result=>{if(active)setRows(result)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Não foi possível preparar a lista de recebimentos.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[revision])
 useEffect(()=>{const refresh=()=>setRevision(current=>current+1);window.addEventListener('entity-record-saved',refresh);return()=>window.removeEventListener('entity-record-saved',refresh)},[])
 const visible=useMemo(()=>rows.filter(row=>`${row.name} ${row.code}`.toLocaleLowerCase('pt-PT').includes(search.trim().toLocaleLowerCase('pt-PT'))),[rows,search])
 const knownTotal=rows.reduce((sum,row)=>sum+(row.unpaidAmount??0)+row.retainerAmount,0)
 const pendingTotal=rows.reduce((sum,row)=>sum+(row.uninvoicedAmount??0)+row.retainerPendingAmount,0)
 const unpaidPartial=rows.some(row=>row.unpaidPartial)
 const uninvoicedPartial=rows.some(row=>row.uninvoicedPartial)
 return <section className="space-y-5" aria-labelledby="debtors-title">
  <header className="rounded-2xl border border-danger/35 bg-gradient-to-br from-danger-soft via-surface to-surface p-5 shadow-sm sm:p-7">
   <div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-danger">Acompanhamento de recebimentos</p><h2 id="debtors-title" className="mt-1 font-display text-3xl font-semibold">Clientes por receber</h2><p className="mt-2 text-sm text-text-secondary">Inclui clientes com facturação por receber, trabalho por facturar ou prestações de avença pendentes. Ordenação pelo total em aberto, com cada fase apresentada separadamente.</p></div><button type="button" className="control min-h-11 px-4 font-semibold" onClick={()=>setRevision(current=>current+1)}><Icon name="refresh" className="mr-2 inline size-4"/>Actualizar</button></div>
   <div className="mt-5 flex flex-wrap items-end gap-x-8 gap-y-3 border-t border-danger/20 pt-4"><div><p className="text-xs text-text-secondary">Facturado por receber</p><strong className="financial-value mt-1 block text-3xl font-semibold tabular-nums text-danger">{value(knownTotal,unpaidPartial)}</strong></div><div><p className="text-xs text-text-secondary">Por facturar</p><strong className="financial-value mt-1 block text-2xl font-semibold tabular-nums">{value(pendingTotal,uninvoicedPartial)}</strong></div><div><p className="text-xs text-text-secondary">Clientes em acompanhamento</p><strong className="mt-1 block text-2xl font-semibold tabular-nums">{count.format(rows.length)}</strong></div></div>
   <p className="mt-3 text-xs text-text-secondary">Por receber: registos e avenças facturados ainda sem pagamento. Por facturar: trabalho e prestações de avença pendentes. Os incobráveis ficam fora destes totais. Valores dos registos sem IVA.</p>
   {(unpaidPartial||uninvoicedPartial)&&<p className="mt-2 text-xs font-semibold text-warning">“Parcial” indica registos sem montante disponível ou definido. Os totais e a ordenação desses clientes consideram apenas os valores conhecidos.</p>}
  </header>
  <label className="block max-w-lg text-sm font-semibold">Procurar cliente<input className="control mt-2 w-full px-4" type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Nome ou código do cliente"/></label>
  {loading&&<div role="status" className="card flex items-center gap-3 p-5"><span className="size-5 shrink-0 animate-spin rounded-full border-2 border-danger border-t-transparent" aria-hidden="true"/><div><p className="font-semibold">A calcular os valores em aberto…</p><p className="text-xs text-text-secondary">A lista aparece assim que o resumo da base de dados estiver disponível.</p></div></div>}
  {error&&<div role="alert" className="card border-danger p-5"><p>{error}</p><button type="button" className="control mt-3 px-4" onClick={()=>setRevision(current=>current+1)}>Tentar novamente</button></div>}
  {!error&&(!loading||rows.length>0)&&<div className="space-y-3" role="list" aria-label="Clientes ordenados pelo total em aberto">{visible.map(row=>{
   const rank=rows.indexOf(row),intensity=rows.length>1?rank/(rows.length-1):0
   const style={borderLeftColor:`hsl(0 70% ${Math.round(28+intensity*43)}%)`,background:`linear-gradient(105deg,color-mix(in srgb,var(--color-danger) ${Math.round(21-intensity*17)}%,var(--color-surface)),var(--color-surface) 70%)`} as CSSProperties
   const total=(row.unpaidAmount??0)+(row.uninvoicedAmount??0)+row.retainerAmount+row.retainerPendingAmount
   return <article role="listitem" key={row.id} className="rounded-xl border border-border border-l-[6px] p-3 shadow-sm sm:p-3" style={style}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full border border-danger/30 bg-surface font-bold tabular-nums text-danger">{rank+1}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-3 gap-y-1 sm:grid sm:grid-cols-[minmax(0,18rem)_auto]"><strong className="font-display text-xl font-bold leading-tight text-text-primary">{row.name}</strong><button type="button" className="control min-h-7 justify-self-start px-2 text-xs font-semibold" onClick={()=>openClientRecord(row.id)}>Abrir ficha</button></div><p className="mt-0.5 text-xs text-text-secondary">{row.code} · {count.format(row.unpaidCount+row.retainerCount)} por receber · {count.format(row.uninvoicedCount+row.retainerPendingCount)} por facturar</p></div></div><div className="min-w-0 text-left sm:text-right"><p className="text-xs font-semibold uppercase tracking-wide text-danger">Total em aberto</p><strong className="financial-value mt-1 block break-words text-2xl font-bold tabular-nums text-danger">{value(total,row.unpaidPartial||row.uninvoicedPartial)}</strong></div></div>
    <div className="mt-2 grid gap-1.5 sm:grid-cols-2 xl:grid-cols-5">{([
      ['unpaid','Registos por receber',row.unpaidCount,row.unpaidAmount,row.unpaidPartial,`${row.unpaidCount} registos · ${hours(row.unpaidMinutes)}`],
      ['retainerInvoiced','Avenças por receber',row.retainerCount,row.retainerAmount,false,`${row.retainerCount} prestações`],
      ['uninvoiced','Trabalho por facturar',row.uninvoicedCount,row.uninvoicedAmount,row.uninvoicedPartial,`${row.uninvoicedCount} registos · ${hours(row.uninvoicedMinutes)}`],
      ['retainerPending','Avenças por facturar',row.retainerPendingCount,row.retainerPendingAmount,false,`${row.retainerPendingCount} prestações`],
    ] as const).map(([kind,label,quantity,amount,partial,meta])=><button key={kind} type="button" disabled={!quantity} aria-label={`${label}: ${quantity?value(amount,partial):'sem movimentos'}; abrir movimentos`} className={`rounded-md border px-2 py-1.5 text-left ${quantity?'cursor-pointer border-[#24558d] bg-[#dceafb] hover:ring-2 hover:ring-[#24558d] focus-visible:ring-2 focus-visible:ring-[#24558d] dark:bg-[#143454]':'cursor-default border-border/40 bg-surface/60'}`} onClick={event=>openDetail(row,kind,event.currentTarget)}><span className="block text-[11px] text-text-secondary">{label}</span><strong className="financial-value block font-semibold tabular-nums">{quantity?value(amount,partial):'—'}</strong>{quantity>0&&<small className="block text-[11px] text-text-secondary">{meta}</small>}</button>)}<div className="rounded-md border border-border/50 bg-surface/80 px-2 py-1.5"><span className="block text-[11px] text-text-secondary">Mais antigo em aberto</span><strong className="block font-semibold tabular-nums">{formatDate(row.oldestDate)}</strong><small className="block text-[11px] text-text-secondary">{row.oldestKind==='avença'?'Avença por receber':row.oldestKind==='avença pendente'?'Avença por facturar':row.oldestKind==='trabalho'?'Trabalho por facturar':'Registo por receber'} · há {daysSince(row.oldestDate)} dias</small></div></div>
   </article>
  })}{!visible.length&&<p className="card p-6 text-center text-text-secondary">{rows.length?'Nenhum cliente corresponde à pesquisa.':'Não há clientes com valores por receber ou por facturar.'}</p>}</div>}
  {detail&&<div role="dialog" aria-modal="true" aria-label={`${detail.kind==='unpaid'?'Registos por receber':detail.kind==='uninvoiced'?'Trabalho por facturar':detail.kind==='retainerInvoiced'?'Avenças por receber':'Avenças por facturar'} · ${detail.client.name}`} className="app-safe-fixed fixed z-[75] flex flex-col bg-navigation/65 p-0 sm:p-4"><section className="card mx-auto flex w-full max-w-7xl flex-1 flex-col overflow-hidden"><header className="flex shrink-0 flex-wrap items-center justify-between gap-3 border-b border-border p-4"><h3 className="font-display text-xl font-semibold">{detail.client.name} · {detail.kind==='unpaid'?'Registos por receber':detail.kind==='uninvoiced'?'Trabalho por facturar':detail.kind==='retainerInvoiced'?'Avenças por receber':'Avenças por facturar'}</h3><button type="button" className="control min-h-10 px-4" onClick={closeDetail}>Fechar registos</button></header><div className="min-h-0 flex-1 overflow-auto p-4"><Suspense fallback={<p role="status">A abrir movimentos…</p>}>{detail.kind==='unpaid'||detail.kind==='uninvoiced'?<WorkEntriesPage key={`${detail.client.id}-${detail.kind}`} embeddedQuery={`?view=work&clientId=${encodeURIComponent(detail.client.id)}&collectionState=${detail.kind}`} canDelete={false} onEntrySaved={()=>setRevision(current=>current+1)}/>:<DebtorRetainerCharges key={`${detail.client.id}-${detail.kind}`} clientId={detail.client.id} status={detail.kind==='retainerInvoiced'?'invoiced':'pending'} onSaved={()=>setRevision(current=>current+1)}/>}</Suspense></div></section></div>}
 </section>
}
