import { useEffect, useMemo, useState } from 'react'
import { openClientRecord } from './openClientRecord'
import { supabase } from '../../lib/supabase'
import {formatDate} from '../../utils/date'
import { AppLink } from '../../components/ui/AppLink'

type Row={client_id:string;client_name:string;client_code:string;terms_count:number;current_monthly_amount:number|null;currency:string|null;included_hours:number|null;billing_interval_months:number|null;hours_interval_months:number|null;consumption_period_start:string|null;consumption_period_end:string|null;period_used_minutes:number;period_included_minutes:number|null;current_starts_on:string|null;current_ends_on:string|null;billing_entity_name:string|null;covered_minutes:number;effective_hourly_rate:number|null;pending_amount:number;unpaid_amount:number}
const money=(value:number,currency='EUR')=>new Intl.NumberFormat('pt-PT',{style:'currency',currency}).format(value)
const duration=(minutes:number)=>`${Math.floor(minutes/60)} h ${String(minutes%60).padStart(2,'0')} min`
const billingPeriod=(months:number|null)=>({1:'Mensal',2:'Bimestral',3:'Trimestral',6:'Semestral',12:'Anual'}[months??0]??'Periodicidade por identificar')

export function RetainersPage(){
 const [rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const demoMode=(import.meta.env.DEV||import.meta.env.VITE_APP_ENV==='test')&&new URLSearchParams(window.location.search).get('qa-demo')==='1'
 useEffect(()=>{let active=true;void(async()=>{if(demoMode){setRows([{client_id:'demo-ebo',client_name:'EBO — EXEMPLO TESTE',client_code:'02.0001',terms_count:3,current_monthly_amount:1600,currency:'EUR',included_hours:120,billing_interval_months:1,hours_interval_months:12,consumption_period_start:'2026-01-01',consumption_period_end:'2026-12-31',period_used_minutes:2160,period_included_minutes:7200,current_starts_on:'2021-01-01',current_ends_on:null,billing_entity_name:'CARINA SANTOS',covered_minutes:2160,effective_hourly_rate:528.89,pending_amount:1600,unpaid_amount:0},{client_id:'demo-infantario',client_name:'INFANTÁRIO DO POVO — EXEMPLO TESTE',client_code:'02.0002',terms_count:2,current_monthly_amount:1306.67,currency:'EUR',included_hours:100,billing_interval_months:1,hours_interval_months:12,consumption_period_start:'2026-01-01',consumption_period_end:'2026-12-31',period_used_minutes:5160,period_included_minutes:6000,current_starts_on:'2024-01-01',current_ends_on:null,billing_entity_name:'CARINA SANTOS',covered_minutes:5160,effective_hourly_rate:182.33,pending_amount:0,unpaid_amount:1306.67},{client_id:'demo-cocktail',client_name:'COCKTAIL TEAM — EXEMPLO TESTE',client_code:'02.0003',terms_count:4,current_monthly_amount:1586.67,currency:'EUR',included_hours:120,billing_interval_months:1,hours_interval_months:12,consumption_period_start:'2026-01-01',consumption_period_end:'2026-12-31',period_used_minutes:4740,period_included_minutes:7200,current_starts_on:'2023-01-01',current_ends_on:null,billing_entity_name:'LEGAL TEAM',covered_minutes:5160,effective_hourly_rate:221.4,pending_amount:0,unpaid_amount:1586.67}]);setError('');setLoading(false);return}if(!supabase)return;setLoading(true);const result=await supabase.rpc('get_retainer_management');if(!active)return;if(result.error)setError(result.error.message);else setRows((result.data??[]) as Row[]);setLoading(false)})();return()=>{active=false}},[demoMode])
 const visible=useMemo(()=>{const needle=query.trim().toLocaleLowerCase('pt-PT');return needle?rows.filter(row=>`${row.client_name} ${row.client_code} ${row.billing_entity_name??''}`.toLocaleLowerCase('pt-PT').includes(needle)):rows},[rows,query])
 if(loading)return <p role="status" className="card p-6">A carregar o estado das avenças…</p>
 return <section aria-labelledby="retainers-page-title" className="space-y-4">
  <div className="card p-5"><h2 id="retainers-page-title" className="sr-only">Tratamento das avenças</h2>{demoMode&&<p role="status" className="rounded-lg border-2 border-warning bg-warning-soft p-3 font-semibold text-warning">MODO DE DEMONSTRAÇÃO · Clientes e valores sintéticos. Não representam contratos reais.</p>}<p className="mt-1 text-sm text-text-secondary">Condições vigentes, horas contratadas e utilizadas, e estado da facturação periódica.</p><input aria-label="Pesquisar avenças" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar cliente, código ou sociedade…" className="control mt-4 w-full px-3"/></div>
  {error&&<p role="alert" className="rounded-lg bg-danger-soft p-3 text-danger">{error}</p>}
  <div role="list" aria-label="Clientes cobertos por avença" className="grid gap-4 lg:grid-cols-2">{visible.map(row=>{const currency=row.currency??'EUR',used=Number(row.period_used_minutes??0),included=row.period_included_minutes==null?null:Number(row.period_included_minutes),ratio=included&&included>0?used/included:null;return <article role="listitem" key={row.client_id} className="card flex min-w-0 flex-col overflow-hidden p-5">
   <header className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><h3 className="break-words font-display text-xl font-semibold">{row.client_name}</h3><p className="text-xs text-text-secondary">{row.client_code} · {row.billing_entity_name??'Sociedade por identificar'}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${row.current_starts_on?'bg-success-soft text-success':'bg-warning-soft text-warning'}`}>{row.current_starts_on?'Activa':'Sem condição vigente'}</span></header>
   <dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className="col-span-2 rounded-lg bg-surface-subtle p-3"><dt className="text-xs text-text-secondary">Condição vigente</dt><dd className="mt-1 font-semibold">{row.current_starts_on?`${formatDate(row.current_starts_on)} — ${row.current_ends_on?formatDate(row.current_ends_on):'sem fim'}`:'Sem condição vigente'} · {row.terms_count} {row.terms_count===1?'linha':'linhas'}</dd></div><div className="min-w-0 rounded-lg bg-secondary-soft p-3"><dt className="text-xs text-text-secondary">Valor por período de facturação</dt><dd className="financial-value mt-1 break-words font-semibold">{row.current_monthly_amount==null?'—':money(row.current_monthly_amount,currency)}</dd><small className="block text-text-secondary">{billingPeriod(row.billing_interval_months)}</small></div><div className="min-w-0 rounded-lg bg-secondary-soft p-3"><dt className="text-xs text-text-secondary">Valor anual equivalente</dt><dd className="financial-value mt-1 break-words font-semibold">{row.current_monthly_amount==null||!row.billing_interval_months?'—':money(Number(row.current_monthly_amount)*12/row.billing_interval_months,currency)}</dd><small className="block text-text-secondary">{row.billing_interval_months?`${12/row.billing_interval_months} prestações por ano`:'Sem periodicidade'}</small></div><div className="min-w-0 rounded-lg bg-surface-subtle p-3"><dt className="text-xs text-text-secondary">Valor/hora efectivo</dt><dd className="financial-value mt-1 break-words font-semibold">{row.effective_hourly_rate==null?'—':money(row.effective_hourly_rate,currency)}</dd></div><div className={`min-w-0 rounded-lg p-3 ${Number(row.pending_amount)>0?'bg-danger-soft':'bg-success-soft'}`}><dt className="text-xs text-text-secondary">Por facturar · acumulado</dt><dd className={`financial-value mt-1 break-words font-semibold ${Number(row.pending_amount)>0?'text-danger':'text-success'}`}>{money(Number(row.pending_amount),currency)}</dd></div><div className={`min-w-0 rounded-lg p-3 ${Number(row.unpaid_amount)>0?'bg-danger-soft':'bg-success-soft'}`}><dt className="text-xs text-text-secondary">Por liquidar · acumulado</dt><dd className={`financial-value mt-1 break-words font-semibold ${Number(row.unpaid_amount)>0?'text-danger':'text-success'}`}>{money(Number(row.unpaid_amount),currency)}</dd></div></dl>
   <div className="mt-3 rounded-lg border border-border p-3 text-sm"><p className="text-xs text-text-secondary">Horas utilizadas no período actual</p><strong className={ratio!=null&&ratio>=1?'text-danger':ratio!=null&&ratio>=.8?'text-warning':'text-success'}>{duration(used)}{included==null?' · sem limite':` utilizadas de ${duration(included)} contratadas`}</strong><div role="progressbar" aria-label={`Horas utilizadas de ${row.client_name}`} aria-valuenow={ratio==null?undefined:Math.round(ratio*100)} aria-valuemin={0} aria-valuemax={ratio==null?undefined:100} className="mt-2 h-2 overflow-hidden rounded-full bg-surface-subtle">{ratio!=null&&<div className={`h-full ${ratio>=1?'bg-danger':ratio>=.8?'bg-warning':'bg-success'}`} style={{width:`${Math.min(100,ratio*100)}%`}}/>}</div><p className="mt-1 text-xs text-text-secondary">{formatDate(row.consumption_period_start)} — {formatDate(row.consumption_period_end)}{ratio!=null&&` · ${Math.round(ratio*100)}% utilizado`}</p><p className="mt-2 text-xs text-text-secondary">Horas utilizadas — histórico total: <strong className="text-text-primary">{duration(Number(row.covered_minutes))}</strong></p></div>
   <div className={`mt-3 rounded-lg border-2 p-3 text-sm ${Number(row.pending_amount)+Number(row.unpaid_amount)>0?'border-danger bg-danger-soft text-danger':'border-success bg-success-soft text-success'}`}><p className="font-semibold">Prestações geradas ainda sem pagamento</p><strong className="financial-value mt-1 block text-xl">{money(Number(row.pending_amount)+Number(row.unpaid_amount),currency)}</strong><p className="mt-1 text-xs">Inclui pendentes e facturadas; só o estado Pago retira uma prestação deste total.</p></div>
   <footer className="mt-auto grid gap-2 pt-4 sm:grid-cols-2"><button type="button" className="control min-h-11 px-3 text-sm font-semibold" onClick={()=>openClientRecord(row.client_id)}>Ficha do cliente</button><AppLink href={`?view=work&clientId=${encodeURIComponent(row.client_id)}`} className="flex min-h-11 items-center justify-center rounded-lg bg-secondary px-3 text-center text-sm font-semibold text-surface">Registos do cliente</AppLink></footer>
  </article>})}</div>{!visible.length&&<p className="card p-6 text-center text-text-secondary">Nenhuma avença corresponde à pesquisa.</p>}
 </section>
}
