import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase'

type Row={client_id:string;client_name:string;client_code:string;terms_count:number;current_monthly_amount:number|null;currency:string|null;included_hours:number|null;billing_interval_months:number|null;hours_interval_months:number|null;consumption_period_start:string|null;consumption_period_end:string|null;period_used_minutes:number;period_included_minutes:number|null;current_starts_on:string|null;current_ends_on:string|null;billing_entity_name:string|null;covered_minutes:number;effective_hourly_rate:number|null;pending_amount:number;unpaid_amount:number}
const money=(value:number,currency='EUR')=>new Intl.NumberFormat('pt-PT',{style:'currency',currency}).format(value)
const duration=(minutes:number)=>`${Math.floor(minutes/60)} h ${String(minutes%60).padStart(2,'0')} min`

export function RetainersPage(){
 const [rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let active=true;void(async()=>{if(!supabase)return;setLoading(true);const result=await supabase.rpc('get_retainer_management');if(!active)return;if(result.error)setError(result.error.message);else setRows((result.data??[]) as Row[]);setLoading(false)})();return()=>{active=false}},[])
 const visible=useMemo(()=>{const needle=query.trim().toLocaleLowerCase('pt-PT');return needle?rows.filter(row=>`${row.client_name} ${row.client_code} ${row.billing_entity_name??''}`.toLocaleLowerCase('pt-PT').includes(needle)):rows},[rows,query])
 const openClient=(id:string)=>{const url=new URL(window.location.href);url.search='';url.searchParams.set('view','master-data');url.searchParams.set('entity','clients');url.searchParams.set('record',id);window.history.pushState({},'',url);window.dispatchEvent(new PopStateEvent('popstate'))}
 if(loading)return <p role="status" className="card p-6">A carregar o estado das avenças…</p>
 return <section aria-labelledby="retainers-page-title" className="space-y-4">
  <div className="card p-5"><h2 id="retainers-page-title" className="font-display text-2xl font-semibold">Tratamento das avenças</h2><p className="mt-1 text-sm text-text-secondary">Condições vigentes, horas contratadas e utilizadas, e estado da facturação mensal.</p><input aria-label="Pesquisar avenças" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar cliente, código ou sociedade…" className="control mt-4 w-full px-3"/></div>
  {error&&<p role="alert" className="rounded-lg bg-danger-soft p-3 text-danger">{error}</p>}
  <div className="overflow-x-auto rounded-xl border border-border bg-surface"><table className="w-full min-w-[86rem] text-sm"><thead className="bg-surface-subtle"><tr><th className="p-3 text-left">Cliente</th><th className="p-3 text-left">Condição vigente</th><th className="p-3 text-right">Valor / periodicidade</th><th className="p-3 text-left">Horas utilizadas no período actual</th><th className="p-3 text-right">Horas utilizadas — histórico total</th><th className="p-3 text-right">Valor/hora efectivo</th><th className="p-3 text-right">Por facturar</th><th className="p-3 text-right">Por liquidar</th><th className="p-3 text-center">Condições</th></tr></thead>
   <tbody>{visible.map(row=>{const currency=row.currency??'EUR',used=Number(row.period_used_minutes??0),included=row.period_included_minutes==null?null:Number(row.period_included_minutes),ratio=included&&included>0?used/included:null;return <tr key={row.client_id} className="hover:bg-surface-subtle">
    <td className="border-t border-border p-3"><button className="font-semibold text-primary underline-offset-2 hover:underline" onClick={()=>openClient(row.client_id)}>{row.client_name}</button><span className="ml-2 text-xs text-text-secondary">{row.client_code}</span></td>
    <td className="border-t border-border p-3">{row.current_starts_on?<><span className="font-semibold text-success">Activa</span><div className="text-xs text-text-secondary">{row.current_starts_on} — {row.current_ends_on??'sem fim'} · {row.billing_entity_name}</div></>:<span className="font-semibold text-warning">Sem condição vigente</span>}</td>
    <td className="border-t border-border p-3 text-right font-semibold">{row.current_monthly_amount==null?'—':<>{money(row.current_monthly_amount,currency)}<div className="text-xs font-normal text-text-secondary">{row.billing_interval_months===1?'mensal':`cada ${row.billing_interval_months} meses`}</div></>}</td>
    <td className="border-t border-border p-3"><div className={`font-semibold ${ratio!=null&&ratio>=1?'text-danger':ratio!=null&&ratio>=.8?'text-warning':'text-success'}`}>{duration(used)}{included==null?' · sem limite':` utilizadas de ${duration(included)} contratadas`}</div><div className="mt-1 h-2 overflow-hidden rounded-full bg-surface-subtle">{ratio!=null&&<div className={`h-full ${ratio>=1?'bg-danger':ratio>=.8?'bg-warning':'bg-success'}`} style={{width:`${Math.min(100,ratio*100)}%`}}/>}</div><div className="mt-1 text-xs text-text-secondary">{row.consumption_period_start??'—'} — {row.consumption_period_end??'—'}{ratio!=null&&` · ${Math.round(ratio*100)}% utilizado`}</div></td>
    <td className="border-t border-border p-3 text-right"><strong>{duration(Number(row.covered_minutes))}</strong><div className="text-xs text-text-secondary">Tempo registado em avença desde o início</div></td>
    <td className="border-t border-border p-3 text-right">{row.effective_hourly_rate==null?'—':money(row.effective_hourly_rate,currency)}</td><td className="border-t border-border p-3 text-right text-warning">{money(Number(row.pending_amount),currency)}</td><td className="border-t border-border p-3 text-right text-danger">{money(Number(row.unpaid_amount),currency)}</td><td className="border-t border-border p-3 text-center">{row.terms_count} {row.terms_count===1?'linha':'linhas'}</td>
   </tr>})}</tbody>
  </table>{!visible.length&&<p className="p-6 text-center text-text-secondary">Nenhuma avença corresponde à pesquisa.</p>}</div>
 </section>
}
