import { useEffect, useState, type FormEvent } from 'react'
import { supabase } from '../../lib/supabase'
import { useModalLifecycle } from '../../hooks/useModalLifecycle'
import { CalendarDateInput } from '../../components/CalendarDateInput'
import { useAuth } from '../auth/AuthContext'

type Options={societies:Array<{id:string;name:string}>;responsibles:Array<{id:string;display_name:string}>}
const actions=[['responsible','Atribuir Responsável'],['society','Alterar Sociedade'],['hourly_rate','Aplicar preço/hora'],['discount','Aplicar desconto fixo'],['invoiced','Marcar como facturado'],['paid','Marcar como pago'],['archive','Alterar arquivo']] as const

export function BulkWorkEntryModal({ids,currentTotal,onClose,onApplied}:{ids:string[];currentTotal:number;onClose:()=>void;onApplied:(count:number)=>void}){
 const {role}=useAuth(),reasonRequired=role!=='owner'&&role!=='admin'
 const [options,setOptions]=useState<Options|null>(null),[action,setAction]=useState('responsible'),[value,setValue]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useModalLifecycle(onClose,busy)
 useEffect(()=>{let active=true;void(async()=>{if(!supabase){setError('Ligação ao Supabase indisponível.');return}const result=await supabase.rpc('get_work_entry_form_options');if(!active)return;if(result.error)setError(result.error.message);else setOptions(result.data as Options)})();return()=>{active=false}},[])
 useEffect(()=>{setValue('');setConfirmed(false)},[action])
 async function submit(event:FormEvent){event.preventDefault();if(!supabase||!confirmed||!value)return;setBusy(true);setError('');const payload=action==='invoiced'?{date:value}:value;const result=await supabase.rpc('bulk_update_work_entries',{p_work_entry_ids:ids,p_action:action,p_value:payload,p_reason:reason});if(result.error){setError(result.error.message);setBusy(false);return}onApplied(Number(result.data??ids.length))}
 const input=action==='responsible'?<select required value={value} onChange={e=>setValue(e.target.value)} className="control w-full px-3"><option value="">Escolher Responsável</option>{options?.responsibles.map(item=><option key={item.id} value={item.id}>{item.display_name}</option>)}</select>:action==='society'?<select required value={value} onChange={e=>setValue(e.target.value)} className="control w-full px-3"><option value="">Escolher Sociedade</option>{options?.societies.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:action==='archive'?<select required value={value} onChange={e=>setValue(e.target.value)} className="control w-full px-3"><option value="">Escolher arquivo</option><option value="none">Nenhum</option><option value="gaveta">Gaveta</option><option value="dossier">Dossier</option><option value="findos">Findos</option><option value="digital">Digital</option><option value="other">Outro</option></select>:action==='invoiced'?<CalendarDateInput required value={value} onChange={setValue} className="w-full px-3"/>:action==='paid'?<select required value={value} onChange={e=>setValue(e.target.value)} className="control w-full px-3"><option value="">Confirmar estado</option><option value="true">Marcar como pago</option></select>:<input required type="number" min="0" step="0.01" value={value} onChange={e=>setValue(e.target.value)} className="control w-full px-3" placeholder="Valor em EUR"/>
 return <div className="app-safe-fixed fixed z-[85] grid place-items-center overflow-y-auto bg-navigation/60 p-4" role="dialog" aria-modal="true" aria-labelledby="bulk-title" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose()}}><form onSubmit={submit} className="card w-full max-w-xl p-6"><div className="flex justify-between gap-4"><div><h2 id="bulk-title" className="font-display text-2xl font-semibold">Editar em massa</h2><p className="mt-1 text-sm text-text-secondary">{ids.length} movimentos · valor actual <span className="financial-value">{new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(currentTotal)}</span></p></div><button type="button" onClick={onClose} className="min-h-11 min-w-11 text-xl" aria-label="Fechar">×</button></div>{error&&<p role="alert" className="mt-4 rounded-lg bg-danger-soft p-3 text-sm text-danger">{error}</p>}<div className="mt-5 space-y-4"><label className="block text-sm">Acção<select value={action} onChange={e=>setAction(e.target.value)} className="control mt-1 w-full px-3">{actions.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="block text-sm">Novo valor<div className="mt-1">{input}</div></label>{reasonRequired&&<label className="block text-sm">Motivo obrigatório<textarea required value={reason} onChange={e=>setReason(e.target.value)} className="control mt-1 min-h-20 w-full p-3"/></label>}<label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1"/>Confirmo a quantidade de movimentos, o valor actual apresentado e a aplicação atómica desta alteração.</label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="control px-4 py-2 font-semibold">Cancelar</button><button disabled={!confirmed||!value||(reasonRequired&&!reason.trim())||busy} className="rounded-lg bg-primary px-4 py-2 font-semibold text-surface disabled:opacity-50">{busy?'A aplicar…':'Aplicar alteração'}</button></div></form></div>
}
