import { TaskReferrerFields } from './TaskReferrerFields'
import { isLegalteam, professionalName } from '../../lib/professionalNames'
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { supabase } from '../../lib/supabase'
import { useModalLifecycle } from '../../hooks/useModalLifecycle'
import { DurationSelect } from './DurationSelect'
import { getWorkEntryOptions } from './workEntryCompatibility'
import { CalendarDateInput } from '../../components/CalendarDateInput'
import { calculateHourlyAmount } from '../pricing/engine'
import { WorkEntryExpensesEditor } from './WorkEntryExpensesEditor'
import { uploadCreatedExpenseFiles, type CreatedWorkEntryExpenses, type ExpenseDraft } from './workEntryExpenses'

type OptionData={
  societies:Array<{id:string;name:string}>
  clientProfiles:Array<{id:string;client_id:string;client_type:'individual'|'company';client_code:string;display_name:string}>
  responsibles:Array<{id:string;display_name:string}>
}

export function CreateWorkEntryModal({onClose,onCreated}:{onClose:()=>void;onCreated:()=>void}){
  const [options,setOptions]=useState<OptionData>({societies:[],clientProfiles:[],responsibles:[]})
  const [date,setDate]=useState(()=>new Date().toISOString().slice(0,10)),[profile,setProfile]=useState(''),[responsible,setResponsible]=useState(''),[society,setSociety]=useState('')
  const [activity,setActivity]=useState(''),[duration,setDuration]=useState(0),[observations,setObservations]=useState('')
  const [enteredHourlyRate,setEnteredHourlyRate]=useState<number|null>(null)
  const [billingScope,setBillingScope]=useState<'standard'|'retainer'>('standard'),[retainerAvailable,setRetainerAvailable]=useState(false)
  const [billingState,setBillingState]=useState<'billable'|'invoiced'|'paid'>('billable'),[invoiceDate,setInvoiceDate]=useState('')
  const [clientQuery,setClientQuery]=useState(''),[clientOptionsOpen,setClientOptionsOpen]=useState(false)
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const [expenses,setExpenses]=useState<ExpenseDraft[]>([])
  useModalLifecycle(onClose,saving)
  useEffect(()=>{let active=true;void(async()=>{const result=await getWorkEntryOptions();if(!active)return;if(result.error)setError(result.error.message);else if(result.data)setOptions(result.data);setLoading(false)})();return()=>{active=false}},[])
  const clientLabel=useCallback((item:OptionData['clientProfiles'][number])=>`${item.display_name} · ${item.client_code} · ${item.client_type==='individual'?'Particular':'Empresa'}`,[])
  const sortedClientProfiles=useMemo(()=>[...options.clientProfiles].sort((left,right)=>left.display_name.localeCompare(right.display_name,'pt-PT',{sensitivity:'base'})||left.client_type.localeCompare(right.client_type)||left.client_code.localeCompare(right.client_code,'pt-PT',{numeric:true})),[options.clientProfiles])
  const matchingClientProfiles=useMemo(()=>{const words=clientQuery.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-PT').split(/\s+/).filter(Boolean);return sortedClientProfiles.filter(item=>{const candidate=clientLabel(item).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-PT');return words.every(word=>candidate.includes(word))}).slice(0,15)},[clientLabel,clientQuery,sortedClientProfiles])
  useEffect(()=>{let active=true;const selected=options.clientProfiles.find(item=>item.id===profile);if(!supabase||!selected){setRetainerAvailable(false);setBillingScope('standard');return}void supabase.from('client_retainers').select('id,starts_on,ends_on').eq('client_id',selected.client_id).eq('active',true).maybeSingle().then(result=>{if(!active)return;const contract=result.data as {starts_on:string;ends_on:string|null}|null,available=Boolean(contract&&!result.error&&contract.starts_on<=date&&(!contract.ends_on||contract.ends_on>=date));setRetainerAvailable(available);setBillingScope(available?'retainer':'standard')});return()=>{active=false}},[profile,date,options.clientProfiles])
  const [taskReferrer,setTaskReferrer]=useState(''),[taskOther,setTaskOther]=useState('')
  const legalteam=isLegalteam(options.societies.find(item=>item.id===society)?.name??'')
  const hourlyRate=enteredHourlyRate
  const calculatedAmount=billingScope==='retainer'?null:hourlyRate!=null?calculateHourlyAmount(hourlyRate,duration):null
  async function submit(event:FormEvent){event.preventDefault();if(!supabase||duration<1)return;if(legalteam&&(!taskReferrer||(taskReferrer==='other'&&!taskOther.trim()))){setError('Indique o angariador da tarefa.');return;}if(billingScope==='standard'&&billingState!=='billable'&&!invoiceDate){setError('Indique a data da factura para criar um registo facturado ou pago.');return}setSaving(true);setError('');const invalid=expenses.some(item=>!Number.isFinite(Number(item.amount.replace(',','.')))||Number(item.amount.replace(',','.'))<=0);if(invalid){setError('Existe uma despesa com montante inválido.');setSaving(false);return}const result=await supabase.rpc('create_work_entry_with_allocation',{p_task_referrer:legalteam?taskReferrer:null,p_task_referrer_other:legalteam&&taskReferrer==='other'?taskOther.trim():null,p_work_date:date,p_client_profile_id:profile,p_matter_id:null,p_professional_id:responsible,p_billing_entity_id:society||null,p_activity_description:activity,p_duration_minutes:duration,p_observations:observations||null,p_hourly_rate:billingScope==='retainer'?null:hourlyRate,p_billing_scope:billingScope,p_billing_state:billingScope==='retainer'?'retainer':billingState,p_invoice_date:billingScope==='retainer'?null:invoiceDate||null,p_expenses:expenses.map(item=>({key:item.key,amount:Number(item.amount.replace(',','.')),observations:item.observations.trim()||null}))});if(result.error){setError(result.error.message);setSaving(false);return}if(expenses.length){const created=result.data as CreatedWorkEntryExpenses;const failures=await uploadCreatedExpenseFiles(created,expenses);if(failures.length)window.alert(`O movimento e as despesas ficaram guardados. Alguns anexos não foram carregados e podem ser repetidos na edição: ${failures.join(' ')}`)}onCreated()}
  return <div className="app-safe-fixed fixed z-[90] grid place-items-center overflow-y-auto bg-navigation/65 p-4" role="dialog" aria-modal="true" aria-labelledby="create-work-title" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose()}}><form onSubmit={submit} className="card my-auto max-h-[calc(100dvh-2rem)] w-full max-w-3xl overflow-y-auto p-5 pb-0 sm:p-6 sm:pb-0">
    <div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.15em] text-secondary">Registo de trabalho</p><h2 id="create-work-title" className="mt-1 font-display text-2xl font-semibold">Criar movimento</h2><p className="mt-2 text-sm text-text-secondary">O preço e o valor são resolvidos no backend segundo as regras vigentes.</p></div><button type="button" onClick={onClose} disabled={saving} className="control min-h-11 shrink-0 whitespace-nowrap px-3 font-semibold sm:px-4">Fechar</button></div>
    {error&&<p role="alert" className="mt-4 rounded-lg bg-danger-soft p-3 text-sm text-danger">Não foi possível criar o movimento: {error}</p>}
    {loading?<div role="status" className="mt-5 h-52 animate-pulse rounded-xl bg-surface-subtle"/>:<div className="mt-5 grid gap-4 sm:grid-cols-2">
      <label className="text-sm font-semibold">Data<CalendarDateInput required value={date} onChange={setDate} className="mt-1 w-full px-3"/></label>
      <label className="relative text-sm font-semibold">Cliente e vertente<input required role="combobox" aria-autocomplete="list" aria-expanded={clientOptionsOpen} aria-controls="create-client-options" value={clientQuery} onFocus={()=>setClientOptionsOpen(true)} onChange={event=>{setClientQuery(event.target.value);setProfile('');setClientOptionsOpen(true)}} placeholder="Comece a escrever o nome ou código…" autoComplete="off" className="control mt-1 w-full px-3"/>{clientOptionsOpen&&<div id="create-client-options" role="listbox" className="scrollbar-thin absolute z-40 mt-1 max-h-[26.25rem] w-full overflow-y-auto rounded-lg border border-border bg-surface p-1 shadow-raised">{matchingClientProfiles.map(item=><button key={item.id} type="button" role="option" aria-selected={profile===item.id} onClick={()=>{setProfile(item.id);setClientQuery(clientLabel(item));setClientOptionsOpen(false)}} className="block h-8 w-full truncate rounded px-2 text-left text-xs font-normal text-text-primary hover:bg-secondary-soft focus:bg-secondary-soft" title={clientLabel(item)}>{clientLabel(item)}</button>)}{!matchingClientProfiles.length&&<p className="p-2 text-xs font-normal text-text-secondary">Nenhum cliente encontrado.</p>}</div>}</label>
      <label className="text-sm font-semibold">Responsável<select required value={responsible} onChange={event=>setResponsible(event.target.value)} className="control mt-1 w-full px-3"><option value="">Seleccionar…</option>{[...options.responsibles].sort((a,b)=>a.display_name.localeCompare(b.display_name,'pt-PT',{sensitivity:'base'})).map(item=><option key={item.id} value={item.id}>{professionalName(item.display_name)}</option>)}</select></label>
      <label className="text-sm font-semibold">Sociedade<select value={society} onChange={event=>setSociety(event.target.value)} className="control mt-1 w-full px-3"><option value="">Por atribuir</option>{[...options.societies].sort((a,b)=>a.name.localeCompare(b.name,'pt-PT',{sensitivity:'base'})).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      {legalteam&&<TaskReferrerFields value={taskReferrer} other={taskOther} onChange={(value,other)=>{setTaskReferrer(value);setTaskOther(other)}}/>}
      <fieldset className="rounded-lg border border-secondary/40 bg-secondary-soft p-3 sm:col-span-2"><legend className="px-1 text-sm font-semibold">Tratamento para facturação</legend><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><label className="flex min-h-11 items-center gap-2 rounded-lg border border-border bg-surface px-3 text-sm font-semibold"><input type="checkbox" checked={billingScope==='standard'} onChange={event=>{if(event.target.checked){setBillingScope('standard');setBillingState('billable')}else if(retainerAvailable)setBillingScope('retainer')}}/>Facturável</label><label className="flex min-h-11 items-center gap-2 rounded-lg border border-border bg-surface px-3 text-sm font-semibold"><input type="checkbox" disabled={billingScope==='retainer'} checked={billingScope==='standard'&&billingState!=='billable'} onChange={event=>setBillingState(event.target.checked?'invoiced':'billable')}/>Facturado</label><label className="flex min-h-11 items-center gap-2 rounded-lg border border-border bg-surface px-3 text-sm font-semibold"><input type="checkbox" disabled={billingScope==='retainer'} checked={billingScope==='standard'&&billingState==='paid'} onChange={event=>setBillingState(event.target.checked?'paid':'invoiced')}/>Pago</label><label className={`flex min-h-11 items-center gap-2 rounded-lg border border-border bg-surface px-3 text-sm font-semibold ${retainerAvailable?'':'opacity-50'}`}><input type="checkbox" disabled={!retainerAvailable} checked={billingScope==='retainer'} onChange={event=>{setBillingScope(event.target.checked?'retainer':'standard');if(!event.target.checked)setBillingState('billable')}}/>Avença</label></div><p className="mt-2 text-xs text-text-secondary">Facturado mantém Facturável seleccionado; Pago mantém Facturável e Facturado seleccionados. Avença é exclusiva e contabiliza automaticamente a duração nos mapas e no consumo do período, sem preço nem valor individual.{!retainerAvailable?' Esta opção fica disponível quando o cliente tem uma avença activa na data escolhida.':''}</p></fieldset>
      {billingScope==='standard'&&billingState!=='billable'&&<label className="text-sm font-semibold sm:col-span-2">Data da factura<CalendarDateInput required ariaLabel="Data da factura" value={invoiceDate} onChange={setInvoiceDate} className="mt-1 w-full px-3"/></label>}
      <fieldset><legend className="text-sm font-semibold">Duração</legend><DurationSelect value={duration} onChange={setDuration}/></fieldset>
      <label className="text-sm font-semibold">Valor/hora (€)<input disabled={billingScope==='retainer'} type="number" min="0" step="0.01" inputMode="decimal" value={billingScope==='retainer'?'':hourlyRate??''} onChange={event=>setEnteredHourlyRate(event.target.value===''?null:Number(event.target.value))} className="control mt-1 w-full px-3"/><span className="mt-1 block text-xs font-normal text-text-secondary">{billingScope==='retainer'?'Não aplicável a horas cobertas pela avença.':'Se ficar vazio, será usada a regra de preço aplicável.'}</span></label>
      <label className="text-sm font-semibold">Valor total (€)<input type="number" readOnly value={calculatedAmount??''} className="control mt-1 w-full px-3 opacity-80"/><span className="mt-1 block text-xs font-normal text-text-secondary">{billingScope==='retainer'?'O valor financeiro está na mensalidade da avença.':'Actualiza automaticamente quando altera a duração ou o valor/hora.'}</span></label>
      <div className="rounded-lg border border-border bg-surface-subtle p-3 sm:col-span-2" aria-live="polite"><p className="text-xs font-semibold uppercase tracking-wide text-text-secondary">Conta</p><p className="mt-1 text-lg font-semibold tabular-nums">{billingScope==='retainer'?'Tempo coberto pela avença · sem valor individual':calculatedAmount==null?'Calculada pela regra de preço':`${duration} min ÷ 60 × ${hourlyRate?.toLocaleString('pt-PT',{minimumFractionDigits:2,maximumFractionDigits:2})} € = ${calculatedAmount.toLocaleString('pt-PT',{minimumFractionDigits:2,maximumFractionDigits:2})} €`}</p></div>
      <label className="text-sm font-semibold sm:col-span-2">Actividade<textarea required maxLength={2000} value={activity} onChange={event=>setActivity(event.target.value)} className="control mt-1 min-h-24 w-full p-3"/></label>
      <label className="text-sm font-semibold sm:col-span-2">Observações<textarea maxLength={4000} value={observations} onChange={event=>setObservations(event.target.value)} className="control mt-1 min-h-20 w-full p-3"/></label>
      <WorkEntryExpensesEditor drafts={expenses} onDraftsChange={setExpenses}/>
    </div>}
    <div className="sticky bottom-0 z-50 -mx-5 mt-6 flex flex-wrap justify-end gap-3 border-t border-border bg-surface px-5 py-3 pb-[max(.75rem,var(--safe-bottom))] shadow-[0_-8px_18px_-14px_rgba(0,0,0,.45)] sm:-mx-6 sm:px-6"><button type="button" onClick={onClose} disabled={saving} className="control min-h-11 px-4 font-semibold">Cancelar</button><button disabled={loading||saving||!profile||!responsible||!activity.trim()||duration<1} className="min-h-11 rounded-lg bg-primary px-5 font-semibold text-surface disabled:opacity-50">{saving?'A guardar…':'Guardar movimento'}</button></div>
  </form></div>
}
