import {useEffect,useMemo,useRef,useState,type FormEvent} from 'react'
import {supabase} from '../../lib/supabase'
import {useModalLifecycle} from '../../hooks/useModalLifecycle'
import {getWorkEntryOptions,type WorkEntryOptions} from './workEntryCompatibility'
import {uploadExpenseFiles,type CreatedWorkEntryExpenses} from './workEntryExpenses'
import {isLegalteam} from '../../lib/professionalNames'
import {TaskReferrerFields} from './TaskReferrerFields'
import {ExpenseCamera} from './ExpenseCamera'

type EntryOption={id:string;work_date:string;activity_description:string}
const today=()=>{const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}

export function QuickExpenseModal({onClose,onCreated}:{onClose:()=>void;onCreated:()=>void}){
 const demoMode=(import.meta.env.DEV||import.meta.env.VITE_APP_ENV==='test')&&new URLSearchParams(window.location.search).get('qa-demo')==='1'
 const [options,setOptions]=useState<WorkEntryOptions|null>(null),[loading,setLoading]=useState(true)
 const [query,setQuery]=useState(''),[profileId,setProfileId]=useState('')
 const [entries,setEntries]=useState<EntryOption[]>([]),[entriesLoading,setEntriesLoading]=useState(false)
 const [mode,setMode]=useState<'existing'|'new'>('existing'),[entryId,setEntryId]=useState('')
 const [date,setDate]=useState(today),[professionalId,setProfessionalId]=useState(''),[activity,setActivity]=useState(''),[duration,setDuration]=useState('')
 const [societyId,setSocietyId]=useState(''),[defaultLoading,setDefaultLoading]=useState(false),[taskReferrer,setTaskReferrer]=useState(''),[taskOther,setTaskOther]=useState('')
 const manualSociety=useRef(false)
 const [retainerStatus,setRetainerStatus]=useState<'idle'|'loading'|'ready'|'error'>('idle'),[billingScope,setBillingScope]=useState<'standard'|'retainer'>('standard')
 const [amount,setAmount]=useState(''),[observations,setObservations]=useState(''),[files,setFiles]=useState<File[]>([])
 const [saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 useModalLifecycle(onClose,saving)
 useEffect(()=>{let active=true;void getWorkEntryOptions().then(result=>{if(!active)return;if(result.error)setError(result.error.message);else setOptions(result.data);setLoading(false)});return()=>{active=false}},[])
 useEffect(()=>{let active=true;setEntries([]);setEntryId('');if(!profileId||!supabase)return;setEntriesLoading(true);void supabase.from('work_entries').select('id,work_date,activity_description').eq('client_profile_id',profileId).order('work_date',{ascending:false}).limit(100).then(result=>{if(!active)return;if(result.error)setError(`Não foi possível consultar os registos: ${result.error.message}`);else setEntries((result.data??[]) as EntryOption[]);setEntriesLoading(false)});return()=>{active=false}},[profileId])
 useEffect(()=>{let active=true;setSocietyId('');setTaskReferrer('');setTaskOther('');const clientId=options?.clientProfiles.find(item=>item.id===profileId)?.client_id;if(!clientId||!supabase)return;setDefaultLoading(true);void supabase.from('clients').select('primary_billing_entity_id').eq('id',clientId).maybeSingle().then(result=>{if(!active)return;if(result.error)setError('Não foi possível consultar a sociedade predefinida do cliente. Confirme-a no novo registo.');else if(!manualSociety.current)setSocietyId(result.data?.primary_billing_entity_id??'');setDefaultLoading(false)});return()=>{active=false}},[profileId,options])
 useEffect(()=>{let active=true;const clientId=options?.clientProfiles.find(item=>item.id===profileId)?.client_id;setBillingScope('standard');if(!clientId||!supabase||!date){setRetainerStatus('idle');return}setRetainerStatus('loading');void supabase.from('client_retainers').select('id').eq('client_id',clientId).eq('active',true).lte('starts_on',date).or(`ends_on.is.null,ends_on.gte.${date}`).order('starts_on',{ascending:false}).limit(1).maybeSingle().then(result=>{if(!active)return;if(result.error){setRetainerStatus('error');setError('Não foi possível consultar a avença activa. Tente seleccionar novamente o cliente.')}else{setBillingScope(result.data?'retainer':'standard');setRetainerStatus('ready')}});return()=>{active=false}},[profileId,date,options])
 const clients=useMemo(()=>{const words=query.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-PT').split(/\s+/).filter(Boolean);return [...(options?.clientProfiles??[])].filter(item=>words.every(word=>`${item.display_name} ${item.client_code} ${item.client_type}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-PT').includes(word))).sort((a,b)=>a.display_name.localeCompare(b.display_name,'pt-PT',{sensitivity:'base'}))},[options,query])
 const selected=options?.clientProfiles.find(item=>item.id===profileId)
 const legalteam=isLegalteam(options?.societies.find(item=>item.id===societyId)?.name??'')
 const validAmount=Number(amount.replace(',','.'))
 async function submit(event:FormEvent){
  event.preventDefault();if(demoMode||!supabase||saving||saved||!profileId||!Number.isFinite(validAmount)||validAmount<=0)return
  if(mode==='existing'&&!entryId){setError('Escolha um registo.');return}
  if(mode==='new'&&(!professionalId||!activity.trim()||!Number.isInteger(Number(duration))||Number(duration)<1)){setError('Preencha o responsável, a actividade e a duração do novo registo.');return}
  if(mode==='new'&&retainerStatus!=='ready'){setError('Aguarde a consulta da avença activa antes de criar o registo.');return}
  if(mode==='new'&&legalteam&&(!taskReferrer||(taskReferrer==='other'&&!taskOther.trim()))){setError('Indique o angariador da tarefa.');return}
  setSaving(true);setError('');setNotice('')
  try{
   let expenseId:string|undefined
   if(mode==='existing'){
    const result=await supabase.rpc('create_work_entry_expense',{p_work_entry_id:entryId,p_amount:validAmount,p_observations:observations.trim()||null})
    if(result.error||!result.data)throw new Error(result.error?.message??'Não foi possível guardar a despesa.')
    expenseId=String(result.data)
   }else{
    const key=crypto.randomUUID()
    const result=await supabase.rpc('create_work_entry_with_allocation',{p_task_referrer:legalteam?taskReferrer:null,p_task_referrer_other:legalteam&&taskReferrer==='other'?taskOther.trim():null,p_work_date:date,p_client_profile_id:profileId,p_matter_id:null,p_professional_id:professionalId,p_billing_entity_id:societyId||null,p_activity_description:activity.trim(),p_duration_minutes:Number(duration),p_observations:null,p_hourly_rate:null,p_billing_scope:billingScope,p_billing_state:billingScope==='retainer'?'retainer':'billable',p_invoice_date:null,p_expenses:[{key,amount:validAmount,observations:observations.trim()||null}]})
    if(result.error)throw new Error(result.error.message)
    expenseId=(result.data as CreatedWorkEntryExpenses|null)?.expenses?.find(item=>item.key===key)?.id
   }
   setSaved(true);onCreated()
   if(files.length){
    if(!expenseId)setNotice('A despesa ficou guardada, mas não foi possível identificar o anexo. Acrescente-o na edição do registo.')
    else {const failures=await uploadExpenseFiles(expenseId,files);if(failures.length)setNotice(`A despesa ficou guardada. Alguns anexos falharam: ${failures.join(' ')}`)}
   }
  }catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível guardar a despesa.')}finally{setSaving(false)}
 }
 return <div className="app-safe-fixed fixed z-[90] grid place-items-center overflow-y-auto bg-navigation/65 p-3 sm:p-4" role="dialog" aria-modal="true" aria-labelledby="quick-expense-title" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose()}}><form onSubmit={event=>void submit(event)} className="card my-auto max-h-[calc(100dvh-1.5rem)] w-full max-w-xl overflow-y-auto p-4 pb-0 sm:p-6 sm:pb-0">
  <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-secondary">Atalho</p><h2 id="quick-expense-title" className="font-display text-2xl font-semibold">Nova despesa</h2></div><button type="button" onClick={onClose} disabled={saving} className="control min-h-11 px-3 font-semibold">Fechar</button></div>
  {demoMode&&<p className="mt-3 rounded-lg bg-secondary-soft p-3 text-xs">Pré-visualização com dados fictícios. A gravação está desactivada.</p>}{error&&<p role="alert" className="mt-3 rounded-lg bg-danger-soft p-3 text-sm text-danger">{error}</p>}{notice&&<p role="status" className="mt-3 rounded-lg bg-secondary-soft p-3 text-sm">{notice}</p>}{saved&&<p role="status" className="mt-3 rounded-lg bg-secondary-soft p-3 text-sm font-semibold">Despesa guardada.</p>}
  {loading?<p role="status" className="mt-4">A carregar clientes…</p>:<div className="mt-4 grid gap-4">
   <div><label htmlFor="quick-client-search" className="text-sm font-semibold">1. Cliente</label><input id="quick-client-search" type="search" value={query} onChange={event=>{manualSociety.current=false;setQuery(event.target.value);setProfileId('')}} placeholder="Pesquisar por nome ou código" className="control mt-1 w-full px-3"/><select aria-label="Cliente e vertente" required value={profileId} onChange={event=>{manualSociety.current=false;setProfileId(event.target.value)}} className="control mt-2 w-full px-3"><option value="">Seleccionar cliente…</option>{clients.map(item=><option key={item.id} value={item.id}>{item.display_name} · {item.client_code} · {item.client_type==='individual'?'Particular':'Empresa'}</option>)}</select>{selected&&<p className="mt-1 text-xs text-text-secondary">{selected.display_name} · {selected.client_code}</p>}</div>
   {profileId&&<fieldset className="rounded-lg border border-border p-3"><legend className="px-1 text-sm font-semibold">2. Registo</legend><div className="grid grid-cols-2 gap-2"><label className="flex min-h-11 items-center gap-2 rounded-lg border border-border px-3 text-sm"><input type="radio" name="quick-expense-mode" checked={mode==='existing'} onChange={()=>setMode('existing')}/>Existente</label><label className="flex min-h-11 items-center gap-2 rounded-lg border border-border px-3 text-sm"><input type="radio" name="quick-expense-mode" checked={mode==='new'} onChange={()=>setMode('new')}/>Criar novo</label></div>
    {mode==='existing'?<div className="mt-3"><label htmlFor="quick-entry" className="text-sm font-semibold">Registo deste cliente</label><select id="quick-entry" required value={entryId} onChange={event=>setEntryId(event.target.value)} disabled={entriesLoading} className="control mt-1 w-full px-3"><option value="">{entriesLoading?'A carregar…':'Seleccionar registo…'}</option>{entries.map(item=><option key={item.id} value={item.id}>{item.work_date} · {item.activity_description}</option>)}</select>{!entriesLoading&&!entries.length&&<p className="mt-2 text-xs text-text-secondary">Sem registos. Escolha «Criar novo».</p>}</div>:<div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Data<input type="date" required value={date} onChange={event=>setDate(event.target.value)} className="control mt-1 w-full px-3"/></label><label className="text-sm font-semibold">Responsável<select required value={professionalId} onChange={event=>setProfessionalId(event.target.value)} className="control mt-1 w-full px-3"><option value="">Seleccionar…</option>{options?.responsibles.map(item=><option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label><label className="text-sm font-semibold sm:col-span-2">Actividade<input required maxLength={2000} value={activity} onChange={event=>setActivity(event.target.value)} placeholder="Descrição breve do registo" className="control mt-1 w-full px-3"/></label><label className="text-sm font-semibold">Duração (minutos)<input required type="number" min="1" step="1" inputMode="numeric" value={duration} onChange={event=>setDuration(event.target.value)} className="control mt-1 w-full px-3"/></label></div>}
    {mode==='new'&&<div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Sociedade<select value={societyId} onChange={event=>{manualSociety.current=true;setSocietyId(event.target.value)}} className="control mt-1 w-full px-3"><option value="">Por atribuir</option>{options?.societies.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{legalteam&&<TaskReferrerFields value={taskReferrer} other={taskOther} onChange={(value,other)=>{setTaskReferrer(value);setTaskOther(other)}}/>}<p className="text-xs text-text-secondary sm:col-span-2" role="status">{retainerStatus==='loading'?'A consultar avença activa…':retainerStatus==='error'?'A consulta da avença falhou. Seleccione novamente o cliente.':billingScope==='retainer'?'A duração ficará coberta pela avença activa.':'O novo registo contabiliza a duração indicada e segue as regras de preço do cliente.'}</p></div>}
   </fieldset>}
   {profileId&&<fieldset className="grid gap-3 rounded-lg border border-border p-3"><legend className="px-1 text-sm font-semibold">3. Despesa e comprovativo</legend><label className="text-sm font-semibold">Montante (€)<input required type="number" min="0.01" step="0.01" inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} className="control mt-1 w-full px-3"/></label><label className="text-sm font-semibold">Observações / notas<textarea maxLength={4000} value={observations} onChange={event=>setObservations(event.target.value)} className="control mt-1 min-h-16 w-full p-3"/></label><ExpenseCamera onCapture={file=>setFiles(current=>[...current,file])}/><label className="text-sm font-semibold">Escolher a partir de ficheiro<input type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.docx,.xlsx,image/jpeg,image/png" onChange={event=>{const selected=Array.from(event.target.files??[]);setFiles(current=>[...current,...selected]);event.target.value=''}} className="control mt-1 w-full p-2"/><span className="mt-1 block text-xs font-normal text-text-secondary">Ficheiros, incluindo fotografias da Fototeca · máximo 20 MB por ficheiro.</span></label>{files.length>0&&<div className="text-xs" aria-live="polite"><p className="font-semibold">{files.length} {files.length===1?'ficheiro seleccionado':'ficheiros seleccionados'}</p>{files.map((file,index)=><div key={`${file.name}-${index}`} className="flex items-center justify-between gap-2 py-1"><span className="min-w-0 truncate">{file.name}</span><button type="button" onClick={()=>setFiles(current=>current.filter((_,position)=>position!==index))} className="min-h-8 px-2 text-danger">Remover</button></div>)}</div>}</fieldset>}
  </div>}
  <div className="sticky bottom-0 -mx-4 mt-5 flex justify-end gap-2 border-t border-border bg-surface px-4 py-3 pb-[max(.75rem,var(--safe-bottom))] sm:-mx-6 sm:px-6"><button type="button" onClick={onClose} disabled={saving} className="control min-h-11 px-4">{saved?'Concluir':'Cancelar'}</button><button type="submit" disabled={demoMode||loading||saving||saved||defaultLoading||!profileId||(mode==='existing'?!entryId:retainerStatus!=='ready'||!professionalId||!activity.trim()||!duration||legalteam&&(!taskReferrer||(taskReferrer==='other'&&!taskOther.trim())))||!Number.isFinite(validAmount)||validAmount<=0} className="record-save min-h-11 rounded-lg border px-5 font-semibold">{saving?'A guardar…':'Guardar despesa'}</button></div>
 </form></div>
}
