import {useCallback,useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'
import {emptyExpense,saveExpenseDrafts,uploadExpenseFiles,type ExpenseDraft} from './workEntryExpenses'

type WorkExpense={id:string;amount:number;currency:string;observations:string|null;created_at:string;documents?:ExpenseDocument[]}
type ExpenseDocument={id:string;original_filename:string;storage_path:string;mime_type:string;size_bytes:number}

export function WorkEntryExpensesEditor({entryId,drafts,onDraftsChange,requiresReason=false}:{entryId?:string;drafts?:ExpenseDraft[];onDraftsChange?:(value:ExpenseDraft[])=>void;requiresReason?:boolean}){
 const [items,setItems]=useState<WorkExpense[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const local=drafts??[]
 const load=useCallback(async()=>{if(!supabase||!entryId)return;const expenses=await supabase.from('work_entry_expenses').select('id,amount,currency,observations,created_at').eq('work_entry_id',entryId).eq('status','active').order('created_at');if(expenses.error){setError(expenses.error.message);return}const rows=(Array.isArray(expenses.data)?expenses.data:[]) as WorkExpense[];if(rows.length){const docs=await supabase.from('work_entry_expense_documents').select('id,expense_id,original_filename,storage_path,mime_type,size_bytes').in('expense_id',rows.map(row=>row.id)).eq('status','active');const documents=Array.isArray(docs.data)?docs.data:[];if(!docs.error)for(const row of rows)row.documents=documents.filter(doc=>doc.expense_id===row.id) as ExpenseDocument[]}setItems(rows)},[entryId])
 useEffect(()=>{void load()},[load])
 const add=()=>onDraftsChange?.([...local,emptyExpense()])
 const change=(key:string,patch:Partial<ExpenseDraft>)=>onDraftsChange?.(local.map(item=>item.key===key?{...item,...patch}:item))
 async function persist(draft:ExpenseDraft){if(!entryId)return;setBusy(true);setError('');const failures=await saveExpenseDrafts(entryId,[draft]);if(failures.length)setError(failures.join(' '));else{onDraftsChange?.(local.filter(item=>item.key!==draft.key));await load()}setBusy(false)}
 async function remove(item:WorkExpense){if(!supabase)return;const reason=requiresReason?window.prompt('Indique o motivo da remoção para a auditoria:')?.trim():'';if(requiresReason&&!reason){setError('A despesa não foi removida. O Operador tem de indicar um motivo.');return}setBusy(true);const result=await supabase.rpc('remove_work_entry_expense',{p_expense_id:item.id,p_reason:reason||null});if(result.error)setError(result.error.message);else await load();setBusy(false)}
 async function edit(item:WorkExpense){if(!supabase)return;const amountText=window.prompt('Montante da despesa:',String(item.amount));if(amountText===null)return;const amount=Number(amountText.replace(',','.'));if(!Number.isFinite(amount)||amount<=0){setError('Indique um montante válido.');return}const observations=window.prompt('Observações / notas:',item.observations??'');if(observations===null)return;const reason=requiresReason?window.prompt('Indique o motivo da alteração para a auditoria:')?.trim():'';if(requiresReason&&!reason){setError('A despesa não foi alterada. O Operador tem de indicar um motivo.');return}setBusy(true);const result=await supabase.rpc('update_work_entry_expense',{p_expense_id:item.id,p_amount:amount,p_observations:observations.trim()||null,p_reason:reason||null});if(result.error)setError(result.error.message);else await load();setBusy(false)}
 async function attach(item:WorkExpense,files:File[]){if(!files.length)return;setBusy(true);const failures=await uploadExpenseFiles(item.id,files);if(failures.length)setError(failures.join(' '));await load();setBusy(false)}
 async function open(document:ExpenseDocument){if(!supabase)return;const result=await supabase.storage.from('client-documents').createSignedUrl(document.storage_path,60);if(result.error)setError(result.error.message);else window.open(result.data.signedUrl,'_blank','noopener,noreferrer')}
 return <section className="mt-2 rounded-xl border border-border bg-surface-subtle p-4 sm:col-span-2 lg:col-span-3" aria-labelledby="work-expenses-title"><div className="flex flex-col items-start justify-between gap-3 min-[360px]:flex-row"><div className="min-w-0"><h3 id="work-expenses-title" className="font-display text-lg font-semibold">Despesas associadas</h3><p className="mt-1 text-xs text-text-secondary">Informativas: nunca entram na facturação, IVA ou totais financeiros.</p></div><button type="button" onClick={add} className="control min-h-10 w-full shrink-0 px-3 font-semibold min-[360px]:w-auto">+ Adicionar despesa</button></div>
 {error&&<p role="alert" className="mt-3 rounded-lg bg-danger-soft p-3 text-sm text-danger">{error}</p>}
 {items.map(item=><div key={item.id} className="mt-3 rounded-lg border border-border bg-surface p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong className="tabular-nums">{item.amount.toLocaleString('pt-PT',{style:'currency',currency:item.currency})}</strong>{item.observations&&<p className="mt-1 whitespace-pre-wrap text-sm">{item.observations}</p>}<p className="mt-1 text-xs font-semibold text-text-secondary">{item.documents?.length?`${item.documents.length} ${item.documents.length===1?'anexo':'anexos'}`:'Sem anexos'}</p></div><div className="flex gap-2"><button type="button" disabled={busy} onClick={()=>void edit(item)} className="rounded border border-border px-3 py-2 text-sm font-semibold text-primary">Editar</button><button type="button" disabled={busy} onClick={()=>void remove(item)} className="rounded border border-danger/40 px-3 py-2 text-sm font-semibold text-danger">Remover</button></div></div>{item.documents?.length?<div className="mt-2 flex flex-wrap gap-2">{item.documents.map(document=><button key={document.id} type="button" onClick={()=>void open(document)} className="rounded border border-border px-3 py-2 text-xs font-semibold text-primary">{document.original_filename}</button>)}</div>:null}<label className="mt-3 block text-xs font-semibold">Adicionar anexos<input multiple type="file" accept=".pdf,.jpg,.jpeg,.png,.docx,.xlsx" onChange={event=>void attach(item,Array.from(event.target.files??[]))} className="control mt-1 w-full p-2"/></label></div>)}
 {local.map(draft=><div key={draft.key} className="mt-3 grid gap-3 rounded-lg border border-border bg-surface p-3 sm:grid-cols-[10rem_1fr]"><label className="text-sm font-semibold">Montante (€)<input aria-label="Montante da despesa" required type="number" min="0.01" step="0.01" inputMode="decimal" value={draft.amount} onChange={event=>change(draft.key,{amount:event.target.value})} className="control mt-1 w-full px-3 text-right"/></label><label className="text-sm font-semibold">Observações / notas<textarea maxLength={4000} value={draft.observations} onChange={event=>change(draft.key,{observations:event.target.value})} className="control mt-1 min-h-20 w-full p-3"/></label><label className="text-sm font-semibold sm:col-span-2">Documentos<input multiple type="file" accept=".pdf,.jpg,.jpeg,.png,.docx,.xlsx" onChange={event=>change(draft.key,{files:Array.from(event.target.files??[])})} className="control mt-1 w-full p-2"/><span className="mt-1 block text-xs font-normal text-text-secondary">Selector normal do dispositivo · PDF, fotografia, Word ou Excel · máximo 20 MB.</span></label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={()=>onDraftsChange?.(local.filter(item=>item.key!==draft.key))} className="control min-h-10 px-3">Cancelar</button>{entryId&&<button type="button" disabled={busy||draft.amount===''} onClick={()=>void persist(draft)} className="min-h-10 rounded bg-primary px-3 font-semibold text-surface disabled:opacity-50">Guardar despesa</button>}</div></div>)}
 {!items.length&&!local.length&&<p className="mt-3 text-sm text-text-secondary">Sem despesas associadas.</p>}</section>
}
