import { useMemo, useState } from 'react'
import { Icon } from '../../components/ui/Icon'

const rows = [
  { id:'LC-1048', date:'07/04/2026', client:'Cliente Atlas', code:'C-0142', matter:'PROC-26-018', activity:'Reunião de acompanhamento processual', owner:'Carina', duration:'01:30', rate:'€ 120,00', value:180, billing:'Carina Santos', invoiced:false, invoiceDate:'—', paid:false, archive:'Dossier', source:'Excel', override:false },
  { id:'LC-1047', date:'07/04/2026', client:'Cliente Boreal', code:'C-0087', matter:'PROC-25-103', activity:'Análise de documentação e parecer', owner:'Paula', duration:'02:15', rate:'€ 95,00', value:213.75, billing:'Legal Team', invoiced:true, invoiceDate:'15/04/2026', paid:true, archive:'Digital', source:'Excel', override:false },
  { id:'LC-1046', date:'06/04/2026', client:'Cliente Cobalto', code:'C-0191', matter:'—', activity:'Consulta jurídica', owner:'Hugo', duration:'00:45', rate:'Sem preço', value:0, billing:'Massive Search', invoiced:false, invoiceDate:'—', paid:false, archive:'Gaveta', source:'Manual', override:false },
  { id:'LC-1045', date:'06/04/2026', client:'Cliente Duna', code:'C-0054', matter:'PROC-24-077', activity:'Preparação de audiência', owner:'Carina', duration:'03:00', rate:'€ 135,00', value:405, billing:'Carina Santos', invoiced:true, invoiceDate:'12/04/2026', paid:false, archive:'Dossier', source:'Excel', override:true },
  { id:'LC-1044', date:'05/04/2026', client:'Cliente Estrela', code:'C-0128', matter:'PROC-26-011', activity:'Correspondência com contraparte', owner:'Paula', duration:'00:30', rate:'€ 90,00', value:45, billing:'Legal Team', invoiced:false, invoiceDate:'—', paid:false, archive:'Digital', source:'CSV', override:false },
  { id:'LC-1043', date:'04/04/2026', client:'Cliente Farol', code:'C-0031', matter:'PROC-23-201', activity:'Revisão contratual', owner:'Hugo', duration:'01:45', rate:'€ 110,00', value:192.5, billing:'Massive Search', invoiced:true, invoiceDate:'10/04/2026', paid:true, archive:'Findos', source:'Excel', override:false },
] as const

const filterOptions = ['Data', 'Ano: 2026', 'Responsável: Todos', 'Sociedade faturante', 'Estado de faturação', 'Pagamento', 'Arquivo', 'Mais filtros']
const bulkActions = ['Alterar sociedade faturante', 'Atribuir responsável', 'Atribuir processo', 'Aplicar preço', 'Aplicar desconto', 'Marcar como faturado', 'Marcar como pago', 'Alterar arquivo', 'Recalcular']

function Badge({ children, tone='neutral' }: { children: React.ReactNode; tone?: 'neutral'|'success'|'warning'|'danger'|'info' }) {
  const style = { neutral:'bg-surface-subtle text-text-secondary', success:'bg-success-soft text-success', warning:'bg-warning-soft text-warning', danger:'bg-danger-soft text-danger', info:'bg-secondary-soft text-secondary' }[tone]
  return <span className={`inline-flex items-center gap-1 whitespace-nowrap rounded-full px-2 py-1 text-[0.68rem] font-semibold ${style}`}>{children}</span>
}

export function WorkEntriesPage() {
  const [selected, setSelected] = useState<string[]>([])
  const [chips, setChips] = useState(['Ano: 2026'])
  const [density, setDensity] = useState<'comfortable'|'compact'>('comfortable')
  const [showColumns, setShowColumns] = useState(false)
  const [bulkAction, setBulkAction] = useState('')
  const [showConfirm, setShowConfirm] = useState(false)
  const selectedValue = useMemo(() => rows.filter((row) => selected.includes(row.id)).reduce((sum,row) => sum + row.value, 0), [selected])
  const allSelected = selected.length === rows.length
  const toggleAll = () => setSelected(allSelected ? [] : rows.map((row) => row.id))
  const toggle = (id: string) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items,id])
  const money = new Intl.NumberFormat('pt-PT', { style:'currency', currency:'EUR' })

  return <div className="space-y-4">
    <section aria-label="Filtros dos registos" className="card p-4"><div className="grid gap-3 md:grid-cols-[1fr_auto]"><div className="relative"><Icon name="search" className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-text-secondary"/><input aria-label="Pesquisar registos" className="control w-full py-2 pl-10 pr-3 text-sm" placeholder="Pesquisar cliente, código, processo ou atividade…"/></div><div className="flex flex-wrap gap-2"><button className="control flex items-center gap-2 px-3 text-sm"><Icon name="filter" className="size-4"/>Filtros avançados</button><button className="control flex items-center gap-2 px-3 text-sm"><Icon name="download" className="size-4"/>Exportar</button></div></div>
      <div className="mt-3 flex flex-wrap gap-2">{filterOptions.map((filter) => <button key={filter} onClick={() => !chips.includes(filter) && setChips([...chips,filter])} className="rounded-lg border border-border bg-surface px-3 py-1.5 text-xs text-text-secondary hover:border-secondary hover:text-secondary">{filter}</button>)}</div>
      <div className="mt-3 flex flex-wrap items-center gap-2 border-t border-border pt-3"><span className="text-xs font-medium text-text-secondary">Filtros ativos:</span>{chips.map((chip) => <span key={chip} className="inline-flex items-center gap-1.5 rounded-full bg-secondary-soft px-2.5 py-1 text-xs font-medium text-secondary">{chip}<button aria-label={`Remover filtro ${chip}`} onClick={() => setChips(chips.filter((item) => item !== chip))}><Icon name="close" className="size-3"/></button></span>)}<button onClick={() => setChips([])} className="ml-1 text-xs font-semibold text-secondary hover:underline">Limpar filtros</button><button className="ml-auto text-xs font-semibold text-secondary hover:underline">Guardar vista</button></div>
    </section>

    <section aria-labelledby="table-title" className="card overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b border-border p-4"><div><h2 id="table-title" className="font-semibold">Movimentos</h2><p className="text-xs text-text-secondary">6 de 6 794 registos demonstrados</p></div>{selected.length > 0 && <div className="ml-2 flex flex-wrap items-center gap-2 rounded-lg bg-secondary-soft px-3 py-2"><strong className="text-xs text-secondary">{selected.length} selecionados</strong><select aria-label="Ação em massa" value={bulkAction} onChange={(event) => setBulkAction(event.target.value)} className="control h-8 min-h-0 px-2 text-xs"><option value="">Escolher ação…</option>{bulkActions.map((action) => <option key={action}>{action}</option>)}</select><button disabled={!bulkAction} onClick={() => setShowConfirm(true)} className="rounded-md bg-primary px-3 py-1.5 text-xs font-semibold text-surface disabled:opacity-40">Aplicar</button></div>}
      <div className="relative ml-auto flex gap-2"><label className="sr-only" htmlFor="density">Densidade</label><select id="density" value={density} onChange={(event) => setDensity(event.target.value as typeof density)} className="control px-2 text-xs"><option value="comfortable">Confortável</option><option value="compact">Compacta</option></select><button onClick={() => setShowColumns((value) => !value)} aria-expanded={showColumns} className="control grid w-10 place-items-center" aria-label="Selecionar colunas"><Icon name="columns" className="size-4"/></button>{showColumns && <div className="absolute right-0 top-12 z-20 w-56 rounded-xl border border-border bg-surface p-3 shadow-raised"><p className="mb-2 text-xs font-semibold">Colunas visíveis</p>{['Cliente','Processo','Responsável','Valor','Sociedade','Faturação','Pagamento','Arquivo','Origem','Override'].map((column) => <label key={column} className="flex items-center gap-2 py-1.5 text-xs"><input type="checkbox" defaultChecked />{column}</label>)}</div>}</div></div>
      <div className="scrollbar-thin max-h-[38rem] overflow-auto"><table className="min-w-[1650px] border-separate border-spacing-0 text-left text-xs"><caption className="sr-only">Registos de trabalho com faturação e arquivo</caption><thead className="sticky top-0 z-10 bg-surface-subtle text-text-secondary"><tr>
        <th className="border-b border-border px-3 py-3"><input type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="Selecionar todos os registos"/></th>{['Data','Cliente','Código','Processo','Atividade','Responsável','Duração','Valor/hora','Valor','Sociedade faturante','Faturado','Data fatura','Pago','Arquivo','Origem','Override',''].map((heading) => <th key={heading} scope="col" className="whitespace-nowrap border-b border-border px-3 py-3 font-semibold"><button className="inline-flex items-center gap-1 hover:text-primary">{heading}{heading && <span aria-hidden="true" className="text-border-strong">↕</span>}</button></th>)}</tr></thead>
        <tbody>{rows.map((row) => <tr key={row.id} className={`transition-colors hover:bg-secondary-soft/35 ${selected.includes(row.id) ? 'bg-secondary-soft/50' : ''}`}>
          <td className={`border-b border-border px-3 ${density === 'compact' ? 'py-2' : 'py-3.5'}`}><input type="checkbox" checked={selected.includes(row.id)} onChange={() => toggle(row.id)} aria-label={`Selecionar ${row.id}`}/></td>
          <td className="whitespace-nowrap border-b border-border px-3 tabular-nums">{row.date}</td><td className="max-w-44 truncate border-b border-border px-3 font-semibold">{row.client}</td><td className="border-b border-border px-3 text-text-secondary">{row.code}</td><td className="border-b border-border px-3 text-secondary">{row.matter}</td><td className="max-w-64 truncate border-b border-border px-3" title={row.activity}>{row.activity}</td><td className="border-b border-border px-3">{row.owner}</td><td className="border-b border-border px-3 tabular-nums">{row.duration}</td><td className={`border-b border-border px-3 ${row.rate === 'Sem preço' ? 'font-semibold text-danger' : ''}`}>{row.rate}</td><td className="border-b border-border px-3 font-semibold tabular-nums">{money.format(row.value)}</td><td className="border-b border-border px-3">{row.billing}</td><td className="border-b border-border px-3"><Badge tone={row.invoiced ? 'info':'warning'}>{row.invoiced ? <><Icon name="check" className="size-3"/>Sim</>:'Não'}</Badge></td><td className="border-b border-border px-3 tabular-nums">{row.invoiceDate}</td><td className="border-b border-border px-3"><Badge tone={row.paid ? 'success':'neutral'}>{row.paid ? <><Icon name="check" className="size-3"/>Pago</>:'Pendente'}</Badge></td><td className="border-b border-border px-3"><Badge>{row.archive}</Badge></td><td className="border-b border-border px-3"><Badge tone="info">{row.source}</Badge></td><td className="border-b border-border px-3">{row.override ? <Badge tone="warning"><Icon name="warning" className="size-3"/>Manual</Badge>:'—'}</td><td className="border-b border-border px-3"><button aria-label={`Ações de ${row.id}`} className="grid size-8 place-items-center rounded-md hover:bg-surface-subtle"><Icon name="more" className="size-4"/></button></td>
        </tr>)}</tbody></table></div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border p-4 text-xs text-text-secondary"><span>Página 1 de 1 133</span><div className="flex items-center gap-2"><label htmlFor="page-size">Linhas por página</label><select id="page-size" className="control min-h-8 px-2"><option>25</option><option>50</option><option>100</option></select><button className="control min-h-8 px-3" disabled>Anterior</button><button className="control min-h-8 px-3">Seguinte</button></div></div>
    </section>

    {showConfirm && <div className="fixed inset-0 z-50 grid place-items-center bg-primary/45 p-4" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="bulk-title" className="card w-full max-w-lg p-6 shadow-raised"><p className="text-xs font-semibold uppercase tracking-widest text-secondary">Ação protegida</p><h2 id="bulk-title" className="mt-2 font-display text-2xl font-semibold">Confirmar edição em massa</h2><p className="mt-2 text-sm text-text-secondary">A ação <strong className="text-text-primary">{bulkAction}</strong> será aplicada apenas depois da confirmação.</p><dl className="mt-5 grid grid-cols-2 gap-3 rounded-xl bg-surface-subtle p-4"><div><dt className="text-xs text-text-secondary">Linhas afetadas</dt><dd className="mt-1 text-xl font-semibold">{selected.length}</dd></div><div><dt className="text-xs text-text-secondary">Valor atual</dt><dd className="mt-1 text-xl font-semibold">{money.format(selectedValue)}</dd></div><div><dt className="text-xs text-text-secondary">Valor proposto</dt><dd className="mt-1 text-xl font-semibold">A calcular</dd></div><div><dt className="text-xs text-text-secondary">Impacto financeiro</dt><dd className="mt-1 text-xl font-semibold">A validar</dd></div></dl><p className="mt-4 rounded-lg bg-warning-soft p-3 text-xs text-warning">A gravação está desativada neste protótipo até existir autorização e ligação ao Supabase.</p><div className="mt-6 flex justify-end gap-2"><button onClick={() => setShowConfirm(false)} className="control px-4">Cancelar</button><button disabled className="rounded-lg bg-primary px-4 py-2 font-semibold text-surface opacity-45">Confirmar aplicação</button></div></section></div>}
  </div>
}
