import { useEffect,useMemo,useState } from 'react'
import { Icon } from '../../components/ui/Icon'
import { StandardDataTable,type TableColumn } from '../../components/table/StandardDataTable'
import { supabase } from '../../lib/supabase'
import { RecalculationPanel } from '../pricing/RecalculationPanel'
import type { RecalculationPreview } from '../pricing/types'
import { CreateWorkEntryModal } from './CreateWorkEntryModal'
import { EditWorkEntryModal } from './EditWorkEntryModal'
import { BulkWorkEntryModal } from './BulkWorkEntryModal'

type Entry={id:string;work_date:string;client_name:string;client_code:string;matter_code:string|null;matter_title:string|null;activity_description:string;professional_name:string;duration_minutes:number;effective_hourly_rate:number|null;effective_amount:number|null;billing_entity_name:string|null;is_invoiced:boolean;invoice_date:string|null;is_paid:boolean;archive_status:string|null;observations:string|null;source_type:string;has_manual_override:boolean;has_historical_state_exception:boolean;validation_warnings:string[]}
type Option={id:string;label:string}
type SearchMeta={items:Entry[];total:number;professionals:Option[];billingEntities:Option[]}
const money=new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}),number=new Intl.NumberFormat('pt-PT')
const archives=[['gaveta','Gaveta'],['dossier','Dossier'],['findos','Findos'],['digital','Digital'],['other','Outro']]

export function WorkEntriesPage(){
 const [rows,setRows]=useState<Entry[]>([]),[meta,setMeta]=useState<SearchMeta>({items:[],total:0,professionals:[],billingEntities:[]}),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[year,setYear]=useState(''),[professional,setProfessional]=useState(''),[billing,setBilling]=useState(''),[invoiced,setInvoiced]=useState(''),[paid,setPaid]=useState(''),[archive,setArchive]=useState(''),[review,setReview]=useState(false)
 const [selected,setSelected]=useState<string[]>([]),[refreshToken,setRefreshToken]=useState(0),[recalculation,setRecalculation]=useState<RecalculationPreview|null>(null),[actionBusy,setActionBusy]=useState(false),[notice,setNotice]=useState('')
 const [creating,setCreating]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[bulkEditing,setBulkEditing]=useState(false)
 useEffect(()=>{const timer=setTimeout(()=>setQuery(search.trim()),300);return()=>clearTimeout(timer)},[search])
 useEffect(()=>{let active=true;setLoading(true);setError('');setSelected([]);void(async()=>{if(!supabase){setError('Ligação ao Supabase indisponível.');setLoading(false);return}const args={p_search:query||null,p_year:year?Number(year):null,p_professional_id:professional||null,p_billing_entity_id:billing||null,p_invoiced:invoiced===''?null:invoiced==='true',p_paid:paid===''?null:paid==='true',p_archive:archive||null,p_review_only:review,p_sort:'work_date',p_direction:'desc'};const metadata=await supabase.rpc('search_work_entries',{p_page:1,p_page_size:100,...args});if(!active)return;if(metadata.error)setError(metadata.error.message??'Não foi possível carregar os movimentos.');else{const next=metadata.data as SearchMeta;setMeta(next);setRows(next.items??[])}setLoading(false)})();return()=>{active=false}},[query,year,professional,billing,invoiced,paid,archive,review,refreshToken])
 const selectedValue=useMemo(()=>rows.filter(row=>selected.includes(row.id)).reduce((sum,row)=>sum+(row.effective_amount??0),0),[rows,selected])
 const clear=()=>{setSearch('');setQuery('');setYear('');setProfessional('');setBilling('');setInvoiced('');setPaid('');setArchive('');setReview(false)}
 const activeFilters=[year&&`Ano: ${year}`,professional&&`Responsável: ${meta.professionals.find(o=>o.id===professional)?.label}`,billing&&`Sociedade: ${meta.billingEntities.find(o=>o.id===billing)?.label}`,invoiced&&`Facturado: ${invoiced==='true'?'Sim':'Não'}`,paid&&`Pago: ${paid==='true'?'Sim':'Não'}`,archive&&`Arquivo: ${archive}`,review&&'Requer revisão'].filter(Boolean) as string[]
 const loadExportRows=async()=>{if(!supabase)throw new Error('Ligação ao Supabase indisponível.');const result=await supabase.rpc('export_visible_work_entries',{p_search:query||null,p_year:year?Number(year):null,p_professional_id:professional||null,p_billing_entity_id:billing||null,p_invoiced:invoiced===''?null:invoiced==='true',p_paid:paid===''?null:paid==='true',p_archive:archive||null,p_review_only:review,p_sort:'work_date',p_direction:'desc'});if(result.error)throw new Error(result.error.message??'Não foi possível exportar os movimentos.');return(Array.isArray(result.data)?result.data:[])as Entry[]}
 const previewRecalculation=async()=>{if(!supabase||!selected.length)return;setActionBusy(true);setError('');const result=await supabase.rpc('preview_work_entry_recalculation',{p_target_ids:selected,p_skip_overrides:true,p_uninvoiced_only:true});setActionBusy(false);if(result.error){setError(result.error.message);return}const row=(Array.isArray(result.data)?result.data[0]:result.data) as Record<string,number>|null;if(!row){setError('O backend não devolveu a pré-visualização.');return}const chosen=rows.filter(item=>selected.includes(item.id));setRecalculation({entries:[],selectedCount:selected.length,recalculableCount:Number(row.selected_count??0),skippedOverrideCount:chosen.filter(item=>item.has_manual_override).length,skippedInvoicedCount:chosen.filter(item=>item.is_invoiced).length,missingPriceCount:Number(row.records_without_price??0),currentTotal:Number(row.current_total??0),proposedTotal:Number(row.proposed_total??0),difference:Number(row.difference??0)})}
 const confirmRecalculation=async()=>{if(!supabase||!selected.length)return;setActionBusy(true);const result=await supabase.rpc('recalculate_work_entries',{p_target_ids:selected,p_skip_overrides:true,p_uninvoiced_only:true});setActionBusy(false);if(result.error){setError(result.error.message);return}setRecalculation(null);setSelected([]);setNotice('Recálculo concluído e registado para os movimentos elegíveis.');setRefreshToken(value=>value+1)}
 const columns:TableColumn<Entry>[]=[
  {id:'date',label:'Data',kind:'date',essential:true,sticky:true,value:row=>row.work_date,render:row=>new Date(`${row.work_date}T00:00:00`).toLocaleDateString('pt-PT')},{id:'client',label:'Cliente',value:row=>row.client_name},{id:'code',label:'Código',value:row=>row.client_code},{id:'matter',label:'Processo',value:row=>[row.matter_code,row.matter_title].filter(Boolean).join(' · ')},{id:'activity',label:'Actividade',value:row=>row.activity_description},{id:'responsible',label:'Responsável',value:row=>row.professional_name},{id:'duration',label:'Duração (min)',kind:'number',align:'right',value:row=>row.duration_minutes},
  {id:'rate',label:'Valor/hora (EUR)',kind:'money',align:'right',value:row=>row.effective_hourly_rate,render:row=><span className="financial-value">{row.effective_hourly_rate==null?'Sem acesso ou sem preço':money.format(row.effective_hourly_rate)}</span>},{id:'amount',label:'Valor (EUR)',kind:'money',align:'right',value:row=>row.effective_amount,render:row=><span className="financial-value">{row.effective_amount==null?'Sem acesso':money.format(row.effective_amount)}</span>},{id:'society',label:'Sociedade',value:row=>row.billing_entity_name},{id:'invoiced',label:'Facturado',kind:'boolean',value:row=>row.is_invoiced,render:row=>row.is_invoiced?'Sim':'Não'},{id:'invoiceDate',label:'Data factura',kind:'date',value:row=>row.invoice_date},{id:'paid',label:'Pago',kind:'boolean',value:row=>row.is_paid,render:row=>row.is_paid?'Sim':'Não'},{id:'archive',label:'Arquivo',value:row=>row.archive_status},{id:'notes',label:'Observações',value:row=>row.observations},{id:'origin',label:'Origem',value:row=>row.source_type},{id:'override',label:'Override',kind:'boolean',value:row=>row.has_manual_override,render:row=>row.has_manual_override?'Alterado manualmente':'Não'},
 ]
 return <div className="space-y-4">
  {notice&&<p role="status" className="rounded-lg bg-success-soft p-3 text-sm text-success">{notice}</p>}
  <section aria-label="Filtros dos registos" className="card p-4"><div className="grid gap-3 lg:grid-cols-[minmax(15rem,2fr)_repeat(3,minmax(9rem,1fr))]"><div className="relative"><Icon name="search" className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-text-secondary"/><input value={search} onChange={e=>setSearch(e.target.value)} aria-label="Pesquisar registos" className="control w-full py-2 pl-10 pr-3 text-sm" placeholder="Cliente, código, actividade ou observação…"/></div><select aria-label="Ano" value={year} onChange={e=>setYear(e.target.value)} className="control px-3 text-sm"><option value="">Todos os anos</option>{Array.from({length:9},(_,i)=>2026-i).map(value=><option key={value}>{value}</option>)}</select><select aria-label="Responsável" value={professional} onChange={e=>setProfessional(e.target.value)} className="control px-3 text-sm"><option value="">Todos os responsáveis</option>{meta.professionals.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select><select aria-label="Sociedade" value={billing} onChange={e=>setBilling(e.target.value)} className="control px-3 text-sm"><option value="">Todas as sociedades</option>{meta.billingEntities.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><select aria-label="Estado de facturação" value={invoiced} onChange={e=>setInvoiced(e.target.value)} className="control px-3 text-sm"><option value="">Facturados e não facturados</option><option value="true">Facturados</option><option value="false">Não facturados</option></select><select aria-label="Pagamento" value={paid} onChange={e=>setPaid(e.target.value)} className="control px-3 text-sm"><option value="">Pagos e pendentes</option><option value="true">Pagos</option><option value="false">Pendentes</option></select><select aria-label="Arquivo" value={archive} onChange={e=>setArchive(e.target.value)} className="control px-3 text-sm"><option value="">Todos os arquivos</option>{archives.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><label className="control flex items-center gap-2 px-3 text-sm"><input type="checkbox" checked={review} onChange={e=>setReview(e.target.checked)}/>Requer revisão</label><button onClick={clear} className="control px-3 text-sm font-semibold">Limpar filtros</button></div>{activeFilters.length>0&&<div className="mt-3 flex flex-wrap gap-2 border-t border-border pt-3">{activeFilters.map(filter=><span key={filter} className="rounded-full bg-secondary-soft px-2.5 py-1 text-xs font-medium text-secondary">{filter}</span>)}</div>}</section>
  <div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-text-secondary">{loading?'A actualizar…':`${number.format(meta.total)} movimentos acessíveis`}</p><button type="button" onClick={()=>setCreating(true)} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-surface">Criar movimento</button></div>
  {!loading&&meta.total>rows.length&&<p role="alert" className="rounded-lg bg-warning-soft p-3 text-sm text-warning">A vista apresenta os primeiros {number.format(rows.length)} de {number.format(meta.total)} movimentos. Restrinja os filtros antes de exportar ou editar em massa.</p>}
  {selected.length>0&&<div className="card flex flex-wrap items-center gap-2 p-3 text-sm"><strong>{selected.length} seleccionados</strong><span>·</span><span className="financial-value">{money.format(selectedValue)}</span>{selected.length===1&&<button type="button" onClick={()=>setEditingId(selected[0])} className="control min-h-9 px-3 font-semibold">Editar</button>}<button type="button" onClick={()=>setBulkEditing(true)} className="control min-h-9 px-3 font-semibold">Editar em massa</button><button type="button" disabled={actionBusy} onClick={()=>void previewRecalculation()} className="rounded-lg bg-primary px-3 py-2 font-semibold text-surface disabled:opacity-50">{actionBusy?'A analisar…':'Recalcular'}</button></div>}
  <StandardDataTable id="work-entries" label="Registos de trabalho" rows={rows} columns={columns} rowKey={row=>row.id} loading={loading} updating={loading&&rows.length>0} error={error||undefined} onRetry={()=>setRefreshToken(value=>value+1)} defaultPageSize={50} selected={selected} onSelectionChange={setSelected} emptyMessage="Ainda não existem movimentos acessíveis." loadExportRows={loadExportRows} onRowDoubleClick={row=>setEditingId(row.id)}/>
  {recalculation&&<div className="app-safe-fixed fixed z-[80] grid place-items-center overflow-y-auto bg-navigation/60 p-4" role="dialog" aria-modal="true" aria-label="Confirmar recálculo" onMouseDown={event=>{if(event.target===event.currentTarget)setRecalculation(null)}}><div className="w-full max-w-4xl"><RecalculationPanel preview={recalculation} onCancel={()=>setRecalculation(null)} onConfirm={()=>void confirmRecalculation()}/></div></div>}
  {creating&&<CreateWorkEntryModal onClose={()=>setCreating(false)} onCreated={()=>{setCreating(false);setNotice('Movimento criado e registado na auditoria.');setRefreshToken(value=>value+1)}}/>}
  {editingId&&<EditWorkEntryModal entryId={editingId} onClose={()=>setEditingId(null)} onSaved={()=>{setEditingId(null);setSelected([]);setNotice('Movimento actualizado e registado na auditoria.');setRefreshToken(value=>value+1)}}/>}
  {bulkEditing&&<BulkWorkEntryModal ids={selected} currentTotal={selectedValue} onClose={()=>setBulkEditing(false)} onApplied={count=>{setBulkEditing(false);setSelected([]);setNotice(`${count} movimentos actualizados em massa e registados na auditoria.`);setRefreshToken(value=>value+1)}}/>}
 </div>
}
