import { fireEvent,render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach,describe,expect,test,vi } from 'vitest'
import { CreateWorkEntryModal } from './CreateWorkEntryModal'
import { EditWorkEntryModal } from './EditWorkEntryModal'
import { BulkWorkEntryModal } from './BulkWorkEntryModal'
import { AuthContext } from '../auth/AuthContext'

const rpc=vi.fn()
let retainerContract:{starts_on:string;ends_on:string|null}|null=null
const emptyQuery=()=>{const result={data:[],error:null};const chain:any={select:()=>chain,eq:()=>chain,in:()=>chain,order:()=>chain,maybeSingle:async()=>({data:null,error:null}),then:(resolve:(value:typeof result)=>void)=>Promise.resolve(result).then(resolve)};return chain}
const retainerQuery=()=>{const chain:any={select:()=>chain,eq:()=>chain,maybeSingle:async()=>({data:retainerContract,error:null})};return chain}
vi.mock('../../lib/supabase',()=>({supabase:{rpc:(name:string,...args:unknown[])=>rpc(name==='create_work_entry_with_treatment'?'create_classified_work_entry':name,...args),from:(name:string)=>name==='client_retainers'?retainerQuery():emptyQuery(),functions:{invoke:vi.fn()},storage:{from:()=>({createSignedUrl:vi.fn()})}}}))

const options={societies:[{id:'soc-1',name:'Carina Santos'}],clientProfiles:[{id:'profile-1',client_id:'client-1',client_type:'company',client_code:'C-1',display_name:'Cliente Teste'}],responsibles:[{id:'resp-1',display_name:'Carina'}],processes:[{id:'matter-1',client_id:'client-1',matter_code:'P-1',title:'Processo Teste'}]}

beforeEach(()=>{retainerContract=null;rpc.mockReset();rpc.mockImplementation(async(name:string,args?:Record<string,unknown>)=>name==='get_work_entry_form_options'?{data:options,error:null}:name==='get_work_entry_for_edit'?{data:{id:'entry-1',work_date:'2026-08-16',client_profile_id:'profile-1',matter_id:'matter-1',professional_id:'resp-1',billing_entity_id:'soc-1',activity_description:'Actividade original',observations:null,duration_minutes:30,effective_hourly_rate:150,effective_amount:75,currency:'EUR',status:'draft',is_billable:true,is_invoiced:false,invoice_date:null,is_paid:false,archive_status:null,charge_type:'hourly',effective_discount_amount:0,discount_percentage:0,discount_reason:null,has_manual_override:false,source_type:'manual',billing_scope:'standard'},error:null}:name==='create_classified_work_entry'?{data:{workEntryId:'entry-new',expenses:((args?.p_expenses as {key:string}[])??[]).map((item,index)=>({key:item.key,id:`expense-${index+1}`}))},error:null}:{data:1,error:null})})

describe('movimentos controlados',()=>{
 test('abre a ficha editável e só activa Guardar alterações depois de uma mudança',async()=>{const user=userEvent.setup();render(<EditWorkEntryModal entryId="entry-1" requiresReason={false} onClose={vi.fn()} onSaved={vi.fn()}/>);const activity=await screen.findByDisplayValue('Actividade original'),save=screen.getByRole('button',{name:'Guardar alterações'});expect(activity).toBeEnabled();expect(save).toBeDisabled();await user.type(activity,' revista');expect(save).toBeEnabled()})
 test('calcula o total num só sentido e envia o valor/hora ao criar um movimento',async()=>{const user=userEvent.setup(),onCreated=vi.fn();render(<CreateWorkEntryModal onClose={vi.fn()} onCreated={onCreated}/>);const client=await screen.findByRole('combobox',{name:'Cliente e vertente'});await user.click(client);await user.click(await screen.findByRole('option',{name:/Cliente Teste/}));await user.selectOptions(screen.getByLabelText('Responsável'),'resp-1');await user.selectOptions(screen.getByLabelText('Sociedade'),'soc-1');await user.selectOptions(screen.getByLabelText('Minutos'),'30');const rate=screen.getByRole('spinbutton',{name:/^Valor\/hora/}),amount=screen.getByRole('spinbutton',{name:/^Valor total/});expect(amount).toHaveAttribute('readonly');await user.type(rate,'150');expect(amount).toHaveValue(75);expect(screen.getByText(/30 min ÷ 60 × 150,00 € = 75,00 €/)).toBeInTheDocument();await user.type(screen.getByLabelText('Actividade'),'Reunião');await user.click(screen.getByRole('button',{name:'Guardar movimento'}));await waitFor(()=>expect(onCreated).toHaveBeenCalled());expect(rpc).toHaveBeenCalledWith('create_classified_work_entry',expect.objectContaining({p_duration_minutes:30,p_hourly_rate:150,p_billing_scope:'standard',p_client_profile_id:'profile-1',p_activity_description:'Reunião'}))},10000)
 test('cria um registo de avença sem preço e envia a duração para contabilização',async()=>{retainerContract={starts_on:'2020-01-01',ends_on:null};const user=userEvent.setup(),onCreated=vi.fn();render(<CreateWorkEntryModal onClose={vi.fn()} onCreated={onCreated}/>);const client=await screen.findByRole('combobox',{name:'Cliente e vertente'});await user.click(client);await user.click(await screen.findByRole('option',{name:/Cliente Teste/}));await waitFor(()=>expect(screen.getByLabelText('Avença')).toBeChecked());await user.selectOptions(screen.getByLabelText('Responsável'),'resp-1');await user.selectOptions(screen.getByLabelText('Minutos'),'45');await user.type(screen.getByLabelText('Actividade'),'Trabalho incluído');expect(screen.getByRole('spinbutton',{name:/^Valor\/hora/})).toBeDisabled();await user.click(screen.getByRole('button',{name:'Guardar movimento'}));await waitFor(()=>expect(onCreated).toHaveBeenCalled());expect(rpc).toHaveBeenCalledWith('create_classified_work_entry',expect.objectContaining({p_duration_minutes:45,p_hourly_rate:null,p_billing_scope:'retainer',p_billing_state:'retainer'}))},10000)
 test('permite associar várias despesas com observações durante a criação',async()=>{const user=userEvent.setup(),onCreated=vi.fn();render(<CreateWorkEntryModal onClose={vi.fn()} onCreated={onCreated}/>);const client=await screen.findByRole('combobox',{name:'Cliente e vertente'});await user.click(client);await user.click(await screen.findByRole('option',{name:/Cliente Teste/}));await user.selectOptions(screen.getByLabelText('Responsável'),'resp-1');await user.selectOptions(screen.getByLabelText('Minutos'),'30');await user.type(screen.getByLabelText('Actividade'),'tcodexadministrador despesas');await user.click(screen.getByRole('button',{name:'+ Adicionar despesa'}));await user.click(screen.getByRole('button',{name:'+ Adicionar despesa'}));const amounts=screen.getAllByLabelText('Montante da despesa');await user.type(amounts[0],'12.50');await user.type(amounts[1],'7.25');const notes=screen.getAllByLabelText('Observações / notas');await user.type(notes[0],'Certidão');await user.type(notes[1],'Portes');await user.click(screen.getByRole('button',{name:'Guardar movimento'}));await waitFor(()=>expect(onCreated).toHaveBeenCalled());expect(rpc).toHaveBeenCalledWith('create_classified_work_entry',expect.objectContaining({p_expenses:[expect.objectContaining({amount:12.5,observations:'Certidão'}),expect.objectContaining({amount:7.25,observations:'Portes'})]}))},15000)
 test('edita a ficha completa sem voltar a carregar o formulário ao guardar',async()=>{const user=userEvent.setup(),onSaved=vi.fn();render(<EditWorkEntryModal entryId="entry-1" onClose={vi.fn()} onSaved={onSaved}/>);const activity=await screen.findByDisplayValue('Actividade original');await user.clear(activity);await user.type(activity,'Actividade revista');await user.selectOptions(screen.getByLabelText('Minutos'),'45');await user.click(screen.getByRole('button',{name:'Guardar alterações'}));await waitFor(()=>expect(onSaved).toHaveBeenCalled());expect(rpc.mock.calls.filter(([name])=>name==='get_work_entry_form_options')).toHaveLength(1);expect(rpc).toHaveBeenCalledWith('update_work_entry_full',expect.objectContaining({p_work_entry_id:'entry-1',p_values:expect.objectContaining({activity_description:'Actividade revista',duration_minutes:45})}))})
 test('recalcula imediatamente o total ao alterar duração e valor hora',async()=>{const user=userEvent.setup();render(<EditWorkEntryModal entryId="entry-1" requiresReason={false} onClose={vi.fn()} onSaved={vi.fn()}/>);await screen.findByDisplayValue('Actividade original');await user.selectOptions(screen.getByLabelText('Minutos'),'45');expect(screen.getByLabelText('Valor final')).toHaveValue(112.5);await user.clear(screen.getByLabelText('Preço/hora efectivo'));await user.type(screen.getByLabelText('Preço/hora efectivo'),'200');expect(screen.getByLabelText('Valor final')).toHaveValue(150)})
 test('uma alteração manual do total não altera valor hora nem duração',async()=>{const user=userEvent.setup(),onSaved=vi.fn();render(<EditWorkEntryModal entryId="entry-1" requiresReason={false} onClose={vi.fn()} onSaved={onSaved}/>);await screen.findByDisplayValue('Actividade original');const amount=screen.getByLabelText('Valor final');await user.clear(amount);await user.type(amount,'90');expect(screen.getByLabelText('Preço/hora efectivo')).toHaveValue(150);expect(screen.getByLabelText('Minutos')).toHaveValue('30');await user.click(screen.getByRole('button',{name:'Guardar alterações'}));await waitFor(()=>expect(onSaved).toHaveBeenCalled());expect(rpc).toHaveBeenCalledWith('update_work_entry_full',expect.objectContaining({p_values:expect.objectContaining({effective_amount:90,effective_hourly_rate:150,duration_minutes:30})}))})
 test('permite ao administrador eliminar sem justificação',async()=>{const user=userEvent.setup(),onSaved=vi.fn();render(<EditWorkEntryModal entryId="entry-1" requiresReason={false} onClose={vi.fn()} onSaved={onSaved}/>);await screen.findByDisplayValue('Actividade original');await user.click(screen.getByRole('button',{name:'Apagar movimento'}));await user.click(screen.getByRole('button',{name:'Sim, apagar movimento'}));await waitFor(()=>expect(onSaved).toHaveBeenCalledWith('deleted'));expect(rpc).toHaveBeenCalledWith('delete_work_entry',{p_work_entry_id:'entry-1',p_reason:''})})
 test('a Data da factura activa automaticamente Facturado e é guardada em conjunto',async()=>{const user=userEvent.setup(),onSaved=vi.fn();render(<EditWorkEntryModal entryId="entry-1" onClose={vi.fn()} onSaved={onSaved}/>);const invoiceDate=await screen.findByLabelText('Data da factura');fireEvent.change(invoiceDate,{target:{value:'2026-08-18'}});expect(screen.getByLabelText('Facturado')).toBeChecked();expect(screen.getByLabelText('Pago')).toBeEnabled();await user.click(screen.getByRole('button',{name:'Guardar alterações'}));await waitFor(()=>expect(onSaved).toHaveBeenCalled());expect(rpc).toHaveBeenCalledWith('update_work_entry_full',expect.objectContaining({p_values:expect.objectContaining({invoice_date:'2026-08-18',is_invoiced:true,is_paid:false,status:'invoiced'})}))})
 test('mantém Estado, Facturado e Pago coerentes, incluindo os dois tipos de incobrável',async()=>{const user=userEvent.setup(),onSaved=vi.fn();render(<EditWorkEntryModal entryId="entry-1" onClose={vi.fn()} onSaved={onSaved}/>);const status=await screen.findByLabelText('Estado');expect(screen.getByRole('option',{name:'Incobrável — não facturado'})).toBeInTheDocument();expect(screen.getByRole('option',{name:'Incobrável — facturado e não pago'})).toBeInTheDocument();await user.selectOptions(status,'uncollectible_uninvoiced');expect(screen.getByLabelText('Facturado')).not.toBeChecked();expect(screen.getByLabelText('Pago')).not.toBeChecked();fireEvent.change(screen.getByLabelText('Data da factura'),{target:{value:'2026-08-18'}});await user.click(screen.getByLabelText('Pago'));expect(status).toHaveValue('paid');await user.click(screen.getByRole('button',{name:'Guardar alterações'}));await waitFor(()=>expect(onSaved).toHaveBeenCalled());expect(rpc).toHaveBeenCalledWith('update_work_entry_full',expect.objectContaining({p_values:expect.objectContaining({is_invoiced:true,is_paid:true,status:'paid'})}))})
 test('exige confirmação e motivo auditável antes de eliminar',async()=>{const user=userEvent.setup(),onSaved=vi.fn();render(<EditWorkEntryModal entryId="entry-1" onClose={vi.fn()} onSaved={onSaved}/>);await screen.findByDisplayValue('Actividade original');await user.click(screen.getByRole('button',{name:'Apagar movimento'}));await user.click(screen.getByRole('button',{name:'Sim, apagar movimento'}));expect(await screen.findByText('Indique o motivo da eliminação para o registo de auditoria.')).toBeInTheDocument();expect(onSaved).not.toHaveBeenCalled();await user.type(screen.getByLabelText('Motivo da alteração manual'),'Correcção de registo duplicado');await user.click(screen.getByRole('button',{name:'Sim, apagar movimento'}));await waitFor(()=>expect(onSaved).toHaveBeenCalled());expect(rpc).toHaveBeenCalledWith('delete_work_entry',{p_work_entry_id:'entry-1',p_reason:'Correcção de registo duplicado'})})
 test('oculta a eliminação quando o perfil não tem essa permissão',async()=>{render(<EditWorkEntryModal entryId="entry-1" canDelete={false} onClose={vi.fn()} onSaved={vi.fn()}/>);await screen.findByDisplayValue('Actividade original');expect(screen.queryByRole('button',{name:'Apagar movimento'})).not.toBeInTheDocument()})
 test('exige confirmação mas não justificação numa alteração em massa',async()=>{const user=userEvent.setup(),onApplied=vi.fn();render(<BulkWorkEntryModal ids={['entry-1','entry-2']} currentTotal={200} onClose={vi.fn()} onApplied={onApplied}/>);await screen.findByRole('option',{name:'Carina'});expect(screen.queryByLabelText('Motivo obrigatório')).not.toBeInTheDocument();await user.selectOptions(screen.getByLabelText('Novo valor'),'resp-1');await user.click(screen.getByText(/Confirmo a quantidade/));await user.click(screen.getByRole('button',{name:'Aplicar alteração'}));await waitFor(()=>expect(onApplied).toHaveBeenCalledWith(1));expect(rpc).toHaveBeenCalledWith('bulk_update_work_entries',{p_work_entry_ids:['entry-1','entry-2'],p_action:'responsible',p_value:'resp-1',p_reason:''})})
 test('não exige justificação ao administrador numa alteração em massa',async()=>{const user=userEvent.setup(),onApplied=vi.fn();render(<AuthContext.Provider value={{user:null,role:'admin',signOut:async()=>undefined,updatePassword:async()=>false,enrollPasskey:async()=>''}}><BulkWorkEntryModal ids={['entry-1']} currentTotal={100} onClose={vi.fn()} onApplied={onApplied}/></AuthContext.Provider>);await screen.findByRole('option',{name:'Carina'});expect(screen.queryByLabelText('Motivo obrigatório')).not.toBeInTheDocument();await user.selectOptions(screen.getByLabelText('Novo valor'),'resp-1');await user.click(screen.getByText(/Confirmo a quantidade/));await user.click(screen.getByRole('button',{name:'Aplicar alteração'}));await waitFor(()=>expect(onApplied).toHaveBeenCalledWith(1));expect(rpc).toHaveBeenCalledWith('bulk_update_work_entries',{p_work_entry_ids:['entry-1'],p_action:'responsible',p_value:'resp-1',p_reason:''})})
})
