import { test,expect } from '@playwright/test'
const demo='/?qa-iphone=1&qa-demo=1&qa-allocation=1'
test('repartição por período, pagos, campos e responsáveis completos',async({page})=>{
 await page.goto(`${demo}&view=billing&society=LEGALTEAM`)
 const map=page.getByRole('region',{name:'Repartição LEGALTEAM',exact:true})
 await page.getByLabel('Data final da repartição').fill('2026-09-30')
 await expect(map.getByRole('button',{name:/Total do período/})).toContainText('2000,00')
 await expect(map).toContainText('40,00 € ainda por atribuir')
 await map.getByLabel('Registos considerados').selectOption('paid')
 await expect(map.getByRole('button',{name:/Total do período/})).toContainText('1300,00')
 await map.getByLabel('Registos considerados').selectOption('all')
 await map.getByRole('button',{name:/Angariações por identificar/}).click()
 await expect(map.getByRole('table')).toContainText('Cliente Demonstração Beta')
 await map.getByRole('cell',{name:'Reunião de acompanhamento',exact:true}).dblclick()
 const dialog=page.getByRole('dialog',{name:'Editar movimento'})
 await expect(dialog.getByLabel('Angariador da tarefa',{exact:true})).toHaveAttribute('required','')
 await dialog.getByLabel('Angariador da tarefa',{exact:true}).selectOption('other')
 await expect(dialog.getByLabel('Nome do angariador da tarefa',{exact:true})).toHaveAttribute('required','')
 await dialog.getByLabel('Nome do angariador da tarefa',{exact:true}).fill('Parceiro de Demonstração')
 await dialog.getByRole('button',{name:'Guardar alterações',exact:true}).click()
 await expect(dialog).toHaveCount(0)
 await page.goto(`${demo}&view=professionals`)
 for(const name of ['Carina Santos','Hugo Mendonça','Paula Chaves'])await expect(page.getByRole('heading',{name,exact:true})).toBeVisible()
})
test('angariador existe na ficha de todos os clientes e permite preencher retroactivamente',async({page})=>{
 await page.goto(`${demo}&view=clients&clientType=company&clientMode=list`)
 await page.getByRole('cell',{name:'Cliente Demonstração Beta',exact:true}).dblclick()
 const select=page.getByLabel('Angariador do cliente',{exact:true})
 await expect(select).toHaveValue('')
 await select.selectOption('hugo')
 await page.getByRole('button',{name:'Guardar alterações',exact:true}).click()
 await expect(page.getByText('Cliente Demonstração Beta actualizado.',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Fechar',exact:true}).first().click()
 await page.getByRole('cell',{name:'Cliente Demonstração Beta',exact:true}).dblclick()
 await expect(page.getByLabel('Angariador do cliente',{exact:true})).toHaveValue('hugo')
})
for(const width of [320,390,768,1440])test(`repartição responsiva claro/escuro ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.goto(`${demo}&view=billing&society=LEGALTEAM`)
 const map=page.getByRole('region',{name:'Repartição LEGALTEAM',exact:true});await expect(map.getByRole('button',{name:/Total do período/})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
 await page.getByRole('button',{name:'Activar modo escuro',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
})
