import{expect,test,type Page}from'@playwright/test'

async function mockNotes(page:Page){await page.route('**/rest/v1/**',route=>{const url=new URL(route.request().url()),table=url.pathname.split('/').at(-1);if(table==='firm_members')return route.fulfill({contentType:'application/json',body:JSON.stringify({firm_id:'11111111-1111-4111-8111-111111111111'})});if(table==='workspace_notes')return route.fulfill({contentType:'application/json',body:JSON.stringify([{id:'22222222-2222-4222-8222-222222222222',firm_id:'11111111-1111-4111-8111-111111111111',title:'Nota curta',body:'Um lembrete.',urgency:'normal',created_by:'33333333-3333-4333-8333-333333333333',created_at:'2026-08-30T00:00:00Z',updated_at:'2026-08-30T00:00:00Z'},{id:'44444444-4444-4444-8444-444444444444',firm_id:'11111111-1111-4111-8111-111111111111',title:'Nota crítica com lista',body:'Conteúdo mais longo para confirmar que os cartões crescem de acordo com a informação apresentada sem forçar as restantes caixas à mesma altura.',urgency:'critical',created_by:'55555555-5555-4555-8555-555555555555',created_at:'2026-08-30T00:00:00Z',updated_at:'2026-08-30T00:00:00Z'}])});if(table==='workspace_note_items')return route.fulfill({contentType:'application/json',body:JSON.stringify([{id:'i1',note_id:'44444444-4444-4444-8444-444444444444',content:'Primeira tarefa',completed:true,position:0},{id:'i2',note_id:'44444444-4444-4444-8444-444444444444',content:'Segunda tarefa',completed:false,position:1}])});if(table==='workspace_note_assets'||table==='workspace_note_shares')return route.fulfill({contentType:'application/json',body:'[]'});if(table==='get_workspace_note_users')return route.fulfill({contentType:'application/json',body:JSON.stringify([{user_id:'33333333-3333-4333-8333-333333333333',display_name:'CARINA'},{user_id:'55555555-5555-4555-8555-555555555555',display_name:'PAULA'}])});return route.fulfill({contentType:'application/json',body:'[]'})})}

test('Notas usa cartões de altura variável, urgência, listas e partilha',async({page})=>{await mockNotes(page);await page.goto('/?qa-iphone=1&qa-role=admin&view=notes');await expect(page.getByRole('heading',{name:'Notas'})).toHaveCount(0);const createButton=page.getByRole('button',{name:'+ Nova nota'});await expect(createButton).toBeVisible();const cards=page.locator('article');await expect(cards).toHaveCount(2);const boxes=await Promise.all([cards.nth(0).boundingBox(),cards.nth(1).boundingBox()]);expect(boxes[0]!.height).not.toBe(boxes[1]!.height);await expect(page.getByText('1 de 2 concluídos')).toBeVisible();await expect(page.getByText('Crítico',{exact:true}).first()).toBeVisible();await createButton.click();const dialog=page.getByRole('dialog',{name:'Criar nota'});await dialog.getByRole('button',{name:'+ Adicionar item'}).click();await expect(dialog.getByLabel('Item 1',{exact:true})).toBeVisible();await expect(dialog.getByLabel('Permissão de CARINA')).toContainText('Consulta');await expect(dialog.getByLabel('Permissão de CARINA')).toContainText('Edição')})

test('Notas no iPhone usa apenas scroll vertical e mantém as acções acessíveis',async({page})=>{await page.setViewportSize({width:320,height:568});await mockNotes(page);await page.goto('/?qa-iphone=1&qa-role=admin&view=notes');const createButton=page.getByRole('button',{name:'+ Nova nota'});await expect(createButton).toBeInViewport();expect((await createButton.boundingBox())!.width).toBeGreaterThan(250);await createButton.click();const dialog=page.getByRole('dialog',{name:'Criar nota'});const fit=await dialog.evaluate(element=>({pageClient:document.documentElement.clientWidth,pageScroll:document.documentElement.scrollWidth,dialogClient:element.clientWidth,dialogScroll:element.scrollWidth}));expect(fit.pageScroll).toBeLessThanOrEqual(fit.pageClient);expect(fit.dialogScroll).toBeLessThanOrEqual(fit.dialogClient);await dialog.evaluate(element=>{element.scrollTop=element.scrollHeight});await expect(dialog.getByRole('button',{name:'Cancelar'})).toBeInViewport();await expect(dialog.getByRole('button',{name:'Guardar nota'})).toBeInViewport()})

test('Protótipo local de Notas não consulta dados reais nem apresenta erros de permissões',async({page})=>{await page.goto('/?qa-iphone=1&qa-role=admin&qa-demo=1&view=notes');await expect(page.getByRole('alert')).toHaveCount(0);const cards=page.locator('article');await expect(cards).toHaveCount(4);await expect(cards.getByText('De CARINA SANTOS')).toHaveCount(4);for(const title of ['Lembrete TESTE','Preparar reunião TESTE','Documento recebido TESTE','Mensagem de voz TESTE'])await expect(page.getByRole('heading',{name:title})).toBeVisible();await expect(cards.locator('img')).toHaveCount(1);await expect(cards.locator('audio')).toHaveCount(1);await expect(page.getByRole('button',{name:'+ Nova nota'})).toBeVisible()})
