import { expect,test } from '@playwright/test'

const clients=Array.from({length:5000},(_,index)=>({id:`qa-client-${index}`,firm_id:'qa-firm',display_name:`Cliente desempenho ${String(index).padStart(5,'0')}`,client_code:`01.${String(index).padStart(5,'0')}`,client_type:'company',active:true}))
const workRows=Array.from({length:1000},(_,index)=>({id:`qa-work-perf-${index}`,work_date:`2026-08-${String(index%21+1).padStart(2,'0')}`,created_at:`2026-08-21T${String(index%24).padStart(2,'0')}:${String(index%60).padStart(2,'0')}:00Z`,client_name:`Cliente desempenho ${String(index).padStart(5,'0')}`,client_code:`01.${String(index).padStart(5,'0')}`,matter_code:null,matter_title:null,activity_description:`tcodexoperador desempenho ${index}`,professional_name:'tcodexoperador',duration_minutes:15+(index%8)*15,effective_hourly_rate:150,effective_amount:37.5+(index%8)*37.5,billing_entity_name:index%2?'SOCIEDADE A':'SOCIEDADE B',status:'draft',is_invoiced:false,invoice_number:null,invoice_date:null,is_paid:false,archive_status:null,observations:null,source_type:'manual',has_manual_override:false,has_historical_state_exception:false,validation_warnings:[]}))

test('Administrador abre e filtra 5000 clientes sem soluços prolongados',async({page})=>{
 await page.route('**/rest/v1/**',async route=>{const url=new URL(route.request().url()),path=url.pathname;if(path.endsWith('/firm_members'))return route.fulfill({contentType:'application/json',body:JSON.stringify({firm_id:'qa-firm'})});if(path.endsWith('/clients'))return route.fulfill({contentType:'application/json',body:JSON.stringify(clients)});if(path.endsWith('/client_profiles'))return route.fulfill({contentType:'application/json',body:JSON.stringify(clients.map(item=>({client_id:item.id,client_type:'company'})))});if(path.endsWith('/rpc/get_client_document_action_flags'))return route.fulfill({contentType:'application/json',body:'[]'});if(path.endsWith('/billing_entities'))return route.fulfill({contentType:'application/json',body:'[]'});return route.fulfill({contentType:'application/json',body:'[]'})})
 await page.addInitScript(()=>{(window as typeof window&{qaLongTasks:number[]}).qaLongTasks=[];new PerformanceObserver(list=>{for(const entry of list.getEntries())(window as typeof window&{qaLongTasks:number[]}).qaLongTasks.push(entry.duration)}).observe({type:'longtask',buffered:true})})
 const started=Date.now();await page.goto('/?qa-iphone=1&qa-role=admin&view=master-data&entity=clients');await expect(page.getByText('5000 resultados de 5000')).toBeVisible();const initialMs=Date.now()-started
 const search=page.getByRole('textbox',{name:'Pesquisar em Lista de Clientes'}),filterStart=Date.now();await search.fill('Cliente desempenho 04999');await expect(page.getByText('1 resultados de 5000')).toBeVisible();const filterMs=Date.now()-filterStart
 await search.fill('');await expect(page.getByText('5000 resultados de 5000')).toBeVisible()
 const longTasks=await page.evaluate(()=>(window as typeof window&{qaLongTasks:number[]}).qaLongTasks)
 console.info(`QA_PERF_ADMIN ${JSON.stringify({rows:clients.length,initialMs,filterMs,maxLongTaskMs:Math.round(Math.max(0,...longTasks)),longTasks:longTasks.map(value=>Math.round(value))})}`)
 expect(initialMs,'abertura da lista de 5000 clientes').toBeLessThan(5000)
 expect(filterMs,'filtragem de 5000 clientes').toBeLessThan(1200)
 expect(Math.max(0,...longTasks),'maior tarefa longa').toBeLessThan(1000)
})

test('Operador mantém filtros e cabeçalho estáveis sob scroll prolongado',async({page},testInfo)=>{
 await page.route('**/rest/v1/**',async route=>{const url=new URL(route.request().url());if(url.pathname.endsWith('/rpc/search_work_entries')){const query=String((route.request().postDataJSON() as {p_search?:string|null})?.p_search??'').toLocaleLowerCase('pt-PT'),matching=query?workRows.filter(row=>`${row.client_name} ${row.activity_description}`.toLocaleLowerCase('pt-PT').includes(query)):workRows;return route.fulfill({contentType:'application/json',body:JSON.stringify({items:matching.slice(0,100),total:matching.length,pageSize:100,professionals:[{id:'qa-operator',label:'tcodexoperador'}],billingEntities:[{id:'qa-society',label:'SOCIEDADE A'}]})})}return route.fulfill({contentType:'application/json',body:'[]'})})
 await page.setViewportSize({width:1440,height:800});await page.goto('/?qa-iphone=1&qa-role=operator&view=work');const table=page.getByRole('region',{name:'Registos de trabalho'});await expect(table.getByText('1000 movimentos de 1000')).toBeVisible()
 const header=table.locator('thead'),tools=table.locator('.table-tools');await page.evaluate(()=>window.scrollTo(0,900));const initialHeader=(await header.boundingBox())!,initialTools=(await tools.boundingBox())!
 const {positions,elapsed}=await page.evaluate(async()=>{const headerElement=document.querySelector('[aria-label="Registos de trabalho"] thead')!,positions:number[]=[];const started=performance.now();for(let cycle=0;cycle<12;cycle++)for(const top of [900,940,980,1020,980,940]){window.scrollTo(0,top);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));positions.push(headerElement.getBoundingClientRect().y)}return{positions,elapsed:performance.now()-started}})
 expect(Math.max(...positions)-Math.min(...positions),'deslocação vertical do cabeçalho').toBeLessThanOrEqual(1)
 expect(initialHeader.y).toBeGreaterThanOrEqual(initialTools.y+initialTools.height-1)
 expect(elapsed,'72 movimentos de scroll sincronizados').toBeLessThan(5000)
 const filterStarted=Date.now();await page.getByRole('textbox',{name:'Pesquisar registos'}).fill('tcodexoperador desempenho 999');await expect(table.getByText('1 movimentos de 1')).toBeVisible();const filterMs=Date.now()-filterStarted,filterBudgetMs=testInfo.config.workers>1?3000:1500;expect(filterMs,'pesquisa remota com debounce').toBeLessThan(filterBudgetMs);console.info(`QA_PERF_OPERATOR ${JSON.stringify({accessibleRows:workRows.length,scrollSamples:positions.length,scrollMs:elapsed,headerDeviationPx:Math.max(...positions)-Math.min(...positions),filterMs,filterBudgetMs,workers:testInfo.config.workers})}`)
})
