import {readFile} from 'node:fs/promises'
import {test,expect} from '@playwright/test'

test('Provisões calcula o saldo na linha e abre os registos sem emitir notas',async({page})=>{
 let notesIssued=0
 page.on('request',request=>{if(request.url().includes('/rpc/issue_provision_honorarium_note'))notesIssued++})
 await page.goto('/?qa-iphone=1&qa-demo=1&qa-provisions=1&view=provisions')
 const table=page.getByRole('table',{name:'Clientes com provisões'})
 await expect(table).toContainText('Cliente Sintético');await expect(table).toContainText('Cliente Sem Saldo')
 await expect(table).toContainText('877,00');await expect(table).toContainText('Saldo esgotado')
 await page.getByRole('button',{name:/Histórico de Cliente Sintético/}).click()
 const usage=page.getByRole('region',{name:'Consumo da provisão nos registos'})
 await expect(usage).toContainText('01/08/2026');await expect(usage).toContainText('631,00')
 await usage.getByText('Ver os registos considerados no saldo',{exact:true}).click()
 await expect(usage).toContainText('Preparação de requerimento')
 await expect(page.getByRole('button',{name:'Emitir Nota de Honorários com provisão'})).toHaveCount(0)
 const download=page.waitForEvent('download');await usage.getByRole('button',{name:'Guardar mapa de consumo PDF'}).click();await page.getByRole('dialog',{name:'Apresentação do histórico'}).getByRole('button',{name:'Guardar PDF',exact:true}).click();await (await download).saveAs('.tmp/provision-usage.pdf')
 const exported=page.getByRole('dialog',{name:'Apresentação do histórico'})
 await expect(exported.getByRole('status')).toContainText('PDF preparado')
 await expect(exported.getByRole('link',{name:'Abrir PDF',exact:true})).toHaveAttribute('href',/^blob:/)
 await exported.getByRole('button',{name:'Alterar modalidade'}).click()
 await exported.getByRole('radio',{name:/Apenas tempos/}).check()
 const timeDownload=page.waitForEvent('download');await exported.getByRole('button',{name:'Guardar PDF',exact:true}).click()
 const timeFile=await timeDownload;await timeFile.saveAs('.tmp/provision-usage-time.pdf')
 const contents=(await readFile('.tmp/provision-usage-time.pdf')).toString('latin1');expect(contents).toContain('631,00');expect(contents).not.toContain('Honorários:')
 expect(notesIssued).toBe(0)
})

test('estornar a nota repõe o saldo efectivo na ficha e na linha do cliente',async({page})=>{
 await page.goto('/?qa-iphone=1&qa-demo=1&qa-provisions=1&view=provisions')
 await page.getByRole('button',{name:/Histórico de Cliente Sintético/}).click()
 const balance=page.getByRole('region',{name:'Saldo disponível da provisão',exact:true})
 await expect(balance).toContainText('877,00')
 const note=page.getByRole('article').filter({has:page.getByText(/01\/09\/2026 · Nota de Honorários/)})
 await note.getByRole('button',{name:'Estornar',exact:true}).click()
 await note.getByLabel('Motivo do estorno').fill('Correcção sintética para nova emissão')
 await note.getByRole('button',{name:'Confirmar estorno'}).click()
 await expect(balance).toContainText('1000,00')
 await expect(page.getByText('Estorno concluído. O saldo foi actualizado.')).toBeVisible()
 await page.getByRole('button',{name:'Fechar provisões'}).click()
 await expect(page.getByRole('table',{name:'Clientes com provisões'})).toContainText('1000,00')
})

for(const viewport of [{width:320,height:568},{width:390,height:844},{width:768,height:1024},{width:1440,height:900}]){
 test(`Provisões sem overflow e formulário acessível ${viewport.width}px`,async({page})=>{
  await page.setViewportSize(viewport)
  await page.goto('/?qa-iphone=1&qa-demo=1&qa-provisions=1&view=provisions')
  await page.getByRole('cell',{name:'Cliente Sintético',exact:true}).dblclick()
  const dialog=page.getByRole('dialog',{name:'Provisões · Cliente Sintético'})
  await dialog.getByRole('button',{name:'Registar provisão'}).click()
  await dialog.getByRole('combobox',{name:'Sociedade',exact:true}).selectOption('00000000-0000-4000-8000-000000000030')
  await dialog.getByLabel('Montante').fill('100,50');await dialog.getByLabel('Origem / referência').fill('Reforço sintético')
  await dialog.getByRole('button',{name:'Confirmar provisão'}).click()
  await expect(dialog).toContainText('731,50')
  expect(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true)
  await dialog.getByRole('button',{name:'Fechar provisões'}).click()
  await page.getByRole('button',{name:'Activar modo escuro'}).click()
  await page.getByRole('cell',{name:'Cliente Sintético',exact:true}).dblclick()
  await expect(dialog).toContainText('Provisões para honorários')
  expect(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true)
 })
}

for(const mode of ['values','time'])test('exportação XLSX de provisões: '+mode,async({page})=>{
 await page.goto('/?qa-iphone=1&qa-demo=1&qa-provisions=1&view=provisions')
 await page.getByRole('button',{name:/Histórico de Cliente Sintético/}).click()
 await page.getByRole('button',{name:'Guardar histórico XLSX',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Apresentação do histórico'})
 await dialog.getByRole('radio',{name:mode==='time'?/Apenas tempos/:/Tempos e valores/}).check()
 const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Guardar XLSX',exact:true}).click()
 const file=await pending,path='.tmp/provision-history-'+mode+'.xlsx';await file.saveAs(path)
 const XLSX=await import('xlsx');const book=XLSX.read(await readFile(path),{type:'buffer'}),rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1}) as unknown[][]
 expect(rows.flat()).toContain('Resumo final');expect(rows.flat()).toContain('Saldo disponível')
 expect(rows[4]).toHaveLength(mode==='time'?3:8)
 expect(rows.find(r=>r[0]==='Saldo disponível')?.[1]).toBe(877)
 expect(rows.find(r=>r[0]==='Saldo estimado após registos')?.[1]).toBe(631)
 await expect(dialog.getByRole('status')).toContainText('XLSX preparado')
 const repeat=page.waitForEvent('download');await dialog.getByRole('link',{name:'Descarregar XLSX novamente'}).click();expect((await repeat).suggestedFilename()).toBe(file.suggestedFilename())
 await dialog.getByRole('button',{name:'Fechar',exact:true}).click();await expect(dialog).toHaveCount(0)
})
