import {expect,test,type Page} from '@playwright/test'

const row={id:'qa-role-entry',work_date:'2026-08-21',created_at:'2026-08-21T12:00:00Z',client_name:'Cliente QA Perfis',client_code:'01.9998',matter_code:null,matter_title:null,activity_description:'tcodexadministrador linha de permissões',professional_name:'Responsável A',duration_minutes:30,effective_hourly_rate:150,effective_amount:75,billing_entity_name:'Sociedade A',status:'draft',is_invoiced:false,invoice_number:null,invoice_date:null,is_paid:false,archive_status:null,observations:null,source_type:'manual',has_manual_override:false,has_historical_state_exception:false,validation_warnings:[]}
const options={societies:[{id:'soc-a',name:'Sociedade A'},{id:'soc-b',name:'Sociedade B'}],clientProfiles:[{id:'profile-a',client_id:'client-a',client_type:'company',client_code:'01.9998',display_name:'Cliente QA Perfis'}],responsibles:[{id:'prof-a',display_name:'Responsável A'}],processes:[]}
const editable={id:row.id,work_date:row.work_date,client_profile_id:'profile-a',matter_id:null,professional_id:'prof-a',billing_entity_id:'soc-a',activity_description:row.activity_description,observations:null,duration_minutes:30,effective_hourly_rate:150,effective_amount:75,currency:'EUR',status:'draft',is_billable:true,is_invoiced:false,invoice_date:null,is_paid:false,archive_status:null,charge_type:'hourly',effective_discount_amount:0,discount_percentage:0,discount_reason:null,has_manual_override:false,source_type:'manual'}

async function mockWork(page:Page,calls:Array<{name:string;body:Record<string,unknown>}>) {
 await page.route('**/rest/v1/**',async route=>{const url=new URL(route.request().url()),name=url.pathname.split('/').at(-1)??'',body=(route.request().postDataJSON()??{}) as Record<string,unknown>;if(url.pathname.includes('/rpc/'))calls.push({name,body});if(name==='search_work_entries')return route.fulfill({contentType:'application/json',body:JSON.stringify({items:[row],total:1,pageSize:100,professionals:[{id:'prof-a',label:'Responsável A'}],billingEntities:[{id:'soc-a',label:'Sociedade A'},{id:'soc-b',label:'Sociedade B'}]})});if(name==='get_work_entry_form_options')return route.fulfill({contentType:'application/json',body:JSON.stringify(options)});if(name==='get_work_entry_for_edit')return route.fulfill({contentType:'application/json',body:JSON.stringify(editable)});return route.fulfill({contentType:'application/json',body:'1'})})
}
async function openEntry(page:Page){const entry=page.getByRole('row',{name:/Abrir qa-role-entry/});await entry.click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(entry.locator('input,select,textarea')).toHaveCount(0);await entry.click();await expect(entry.locator('input,select,textarea')).toHaveCount(0);await entry.dblclick();await expect(page.getByRole('dialog',{name:/Editar movimento/})).toBeVisible()}

test('Administrador altera e elimina sem justificação obrigatória',async({page})=>{
 const calls:Array<{name:string;body:Record<string,unknown>}>=[];await mockWork(page,calls);await page.goto('/?qa-iphone=1&qa-role=admin&view=work');await openEntry(page)
 const dialog=page.getByRole('dialog',{name:/Editar movimento/});await expect(dialog.getByLabel(/Motivo da alteração manual/)).not.toHaveAttribute('required');await dialog.locator('select').filter({has:page.locator('option[value="soc-b"]')}).selectOption('soc-b');await dialog.locator('select[aria-label="Minutos"]').selectOption('45');await expect(dialog.getByLabel('Valor final')).toHaveValue('112.5');await dialog.getByRole('button',{name:'Guardar alterações'}).click();await expect(page.getByText('Movimento actualizado e registado na auditoria.')).toBeVisible()
 const update=calls.find(call=>call.name==='update_work_entry_with_allocation');expect(update?.body.p_reason).toBe('');expect(update?.body.p_values).toMatchObject({billing_entity_id:'soc-b',duration_minutes:45,effective_amount:112.5})
 await openEntry(page);await page.getByRole('button',{name:'Apagar movimento'}).click();await page.getByRole('button',{name:'Sim, apagar movimento'}).click();await expect(page.getByText('Movimento apagado e preservado no histórico de auditoria.')).toBeVisible();expect(calls.find(call=>call.name==='delete_work_entry')?.body.p_reason).toBe('')
})

test('Operador altera e elimina sem justificação obrigatória',async({page})=>{
 const calls:Array<{name:string;body:Record<string,unknown>}>=[];await mockWork(page,calls);await page.goto('/?qa-iphone=1&qa-role=operator&view=work');await openEntry(page)
 const dialog=page.getByRole('dialog',{name:/Editar movimento/}),reason=dialog.getByLabel('Motivo da alteração manual');await expect(reason).not.toHaveAttribute('required');await dialog.locator('select').filter({has:page.locator('option[value="soc-b"]')}).selectOption('soc-b');await dialog.locator('select[aria-label="Minutos"]').selectOption('45');await dialog.getByRole('button',{name:'Guardar alterações'}).click();await expect(page.getByText('Movimento actualizado e registado na auditoria.')).toBeVisible();expect(calls.find(call=>call.name==='update_work_entry_with_allocation')?.body.p_reason).toBe('')
 await openEntry(page);await page.getByRole('button',{name:'Apagar movimento'}).click();await page.getByRole('button',{name:'Sim, apagar movimento'}).click();await expect(page.getByText('Movimento apagado e preservado no histórico de auditoria.')).toBeVisible();expect(calls.find(call=>call.name==='delete_work_entry')?.body.p_reason).toBe('')
})
