import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Icon } from '../../components/ui/Icon'
import { supabase } from '../../lib/supabase'

type Role='admin'|'billing'|'professional'|'viewer'|'auditor'
type AdminUser={userId:string;email:string;role:Role|'owner';active:boolean;invitedAt:string;lastSignInAt:string|null}
const roleLabels:Record<AdminUser['role'],string>={owner:'Proprietário',admin:'Administrador',billing:'Financeiro',professional:'Advogado',viewer:'Consulta',auditor:'Auditor'}

export function AdminPage(){
 const [firmId,setFirmId]=useState('');const [users,setUsers]=useState<AdminUser[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('')
 const [email,setEmail]=useState('');const [role,setRole]=useState<Role>('professional');const [sending,setSending]=useState(false)
 const load=useCallback(async()=>{if(!supabase){setError('Ligação ao Supabase indisponível.');setLoading(false);return}setLoading(true);setError('');const {data:membership,error:membershipError}=await supabase.from('firm_members').select('firm_id,role').eq('active',true).in('role',['owner','admin']).limit(1).maybeSingle();if(membershipError||!membership){setError('Permissão administrativa necessária.');setLoading(false);return}setFirmId(membership.firm_id);const {data,error:failure}=await supabase.functions.invoke('admin-users',{body:{action:'list_users',firmId:membership.firm_id}});if(failure||data?.error)setError(data?.error??failure?.message??'Não foi possível listar os utilizadores.');else setUsers(data.users??[]);setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 const invite=async(event:FormEvent)=>{event.preventDefault();if(!supabase||!firmId)return;setSending(true);setError('');setNotice('');const {data,error:failure}=await supabase.functions.invoke('admin-users',{body:{action:'invite_user',firmId,email:email.trim(),role,redirectTo:`${window.location.origin}/`}});if(failure||data?.error)setError(data?.error??failure?.message??'Não foi possível enviar o convite.');else{setNotice(`Convite enviado para ${email.trim()}.`);setEmail('');await load()}setSending(false)}
 return <div className="space-y-5"><nav aria-label="Secções de administração" className="card flex gap-2 p-2"><button aria-current="page" className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-surface">Utilizadores</button><button disabled className="rounded-lg px-4 py-2 text-sm text-text-secondary opacity-60">Equipas</button><button disabled className="rounded-lg px-4 py-2 text-sm text-text-secondary opacity-60">Permissões</button></nav>
  <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_24rem]"><div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-semibold">Utilizadores da aplicação</h2><p className="mt-1 text-sm text-text-secondary">Perfis aplicados no backend e protegidos por RLS.</p></div><button onClick={()=>void load()} className="control grid size-10 place-items-center" aria-label="Atualizar utilizadores"><Icon name="trend" className="size-4"/></button></div>{error&&<div role="alert" className="m-4 rounded-lg bg-danger-soft p-3 text-sm text-danger">{error}</div>}{loading?<div role="status" className="space-y-2 p-5">{Array.from({length:3},(_,i)=><div key={i} className="h-12 animate-pulse rounded bg-surface-subtle"/>)}</div>:<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-surface-subtle text-text-secondary"><tr><th className="px-5 py-3">Email</th><th className="px-5 py-3">Perfil</th><th className="px-5 py-3">Estado</th><th className="px-5 py-3">Último acesso</th></tr></thead><tbody>{users.map(user=><tr key={user.userId} className="border-t border-border"><td className="px-5 py-3 font-medium">{user.email||'Convite pendente'}</td><td className="px-5 py-3">{roleLabels[user.role]}</td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${user.active?'bg-success-soft text-success':'bg-surface-subtle text-text-secondary'}`}>{user.active?'Ativo':'Inativo'}</span></td><td className="px-5 py-3 text-text-secondary">{user.lastSignInAt?new Date(user.lastSignInAt).toLocaleString('pt-PT'):'Ainda não entrou'}</td></tr>)}</tbody></table></div>}</div>
   <form onSubmit={invite} className="card h-fit p-5"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-secondary">Administração</p><h2 className="mt-2 font-display text-xl font-semibold">Criar acesso</h2><p className="mt-2 text-sm text-text-secondary">O utilizador recebe um convite seguro. Não existe registo público nem é criada uma password conhecida pelo administrador.</p><label className="mt-5 block text-sm font-semibold">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="control mt-1 w-full px-3" autoComplete="email"/></label><label className="mt-4 block text-sm font-semibold">Perfil<select value={role} onChange={e=>setRole(e.target.value as Role)} className="control mt-1 w-full px-3"><option value="admin">Administrador</option><option value="billing">Financeiro</option><option value="professional">Advogado</option><option value="viewer">Consulta</option><option value="auditor">Auditor</option></select></label><button disabled={sending||!firmId} className="mt-5 w-full rounded-lg bg-primary px-4 py-2.5 font-semibold text-surface disabled:opacity-50">{sending?'A enviar…':'Enviar convite'}</button>{notice&&<p role="status" className="mt-3 rounded-lg bg-success-soft p-3 text-sm text-success">{notice}</p>}</form></section>
 </div>
}
