import { useEffect, useState } from 'react'
import { MetricCard } from '../components/dashboard/MetricCard'
import { AnnualValueChart, DonutChart, HorizontalChart, MonthlyValueChart, StackedSocietyChart, type ChartPoint } from '../components/dashboard/Charts'
import { supabase } from '../lib/supabase'

type AnnualPoint = ChartPoint & { minutes:number }
type OverviewData = { metrics:{ minutes:number; worked:number; invoiced:number; paid:number; receivable:number; uninvoicedCount:number; unpaidCount:number; averageRate:number; activeClients:number; missingPrice:number; overrides:number; importErrors:number }; annual:AnnualPoint[]; monthly:ChartPoint[]; latestYear:number; byClient:ChartPoint[]; byBilling:ChartPoint[]; byProfessional:ChartPoint[]; byArchive:ChartPoint[]; clientTypes:ChartPoint[] }
const money = new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR',maximumFractionDigits:0})
const number = new Intl.NumberFormat('pt-PT')
const percent=(part:number,total:number)=>total>0?Math.round(part/total*100):0

export function OverviewPage(){
 const [data,setData]=useState<OverviewData|null>(null); const [error,setError]=useState('')
 useEffect(()=>{let active=true; void(async()=>{if(!supabase){setError('Ligação ao Supabase indisponível.');return} const {data:result,error:failure}=await supabase.rpc('get_dashboard_overview'); if(!active)return; if(failure)setError(failure.message);else setData(result as OverviewData)})();return()=>{active=false}},[])
 if(error)return <div role="alert" className="card border-danger/30 bg-danger-soft p-6 text-danger">Não foi possível carregar o dashboard: {error}</div>
 if(!data)return <div role="status" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="card h-32 animate-pulse bg-surface-subtle"/>)}</div>
 const m=data.metrics
 const metrics=[
  ['Total de horas',`${number.format(Math.round(m.minutes/60))} h`,'Duração importada convertida','clock','default'],['Total de minutos',number.format(m.minutes),'Movimentos acessíveis','clock','default'],['Valor trabalhado',money.format(m.worked),'Valor efectivo preservado','trend','default'],['Valor facturado',money.format(m.invoiced),`${percent(m.invoiced,m.worked)}% do trabalhado`,'invoice','default'],['Valor recebido',money.format(m.paid),`${percent(m.paid,m.invoiced)}% do facturado`,'payment','success'],['Por receber',money.format(m.receivable),'Facturado e ainda não pago','warning','warning'],['Não facturados',number.format(m.uninvoicedCount),'Movimentos','invoice','warning'],['Facturados não pagos',number.format(m.unpaidCount),'Requer acompanhamento','payment','warning'],['Preço médio/hora',money.format(m.averageRate),'Média ponderada','rules','default'],['Clientes activos',number.format(m.activeClients),'Com movimentos','clients','default'],['Movimentos sem preço',number.format(m.missingPrice),'Necessitam de revisão','warning',m.missingPrice?'danger':'default'],['Com override',number.format(m.overrides),'Alterações justificadas','audit','default'],['Importações com erros',number.format(m.importErrors),'Com linhas rejeitadas','import',m.importErrors?'danger':'default'],
 ] as const
 const individual=data.clientTypes.find(p=>p.label==='individual')?.value??0; const company=data.clientTypes.find(p=>p.label==='company')?.value??0
 return <div className="space-y-6"><section aria-labelledby="summary-title"><div className="mb-4"><h2 id="summary-title" className="font-semibold">Resumo operacional</h2><p className="mt-1 text-sm text-text-secondary">Dados reais acessíveis através das políticas RLS</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-5">{metrics.map(([label,value,detail,icon,tone])=><MetricCard key={label} label={label} value={value} detail={detail} icon={icon} tone={tone}/>)}</div></section>
 <section aria-labelledby="analysis-title"><div className="mb-4"><h2 id="analysis-title" className="font-semibold">Análise e tendências</h2><p className="mt-1 text-sm text-text-secondary">Histórico importado de 2018 a {data.latestYear}</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><AnnualValueChart data={data.annual}/><MonthlyValueChart data={data.monthly}/><HorizontalChart title="Horas por ano" subtitle="Volume anual" labels={data.annual.map(p=>String(p.label))} values={data.annual.map(p=>p.minutes)} valueFormatter={v=>`${number.format(Math.round(v/60))} h`}/><HorizontalChart title="Valor por cliente" subtitle="Cinco maiores" labels={data.byClient.map(p=>String(p.label))} values={data.byClient.map(p=>p.value)} valueFormatter={money.format}/><HorizontalChart title="Valor por sociedade" subtitle="Sociedades" labels={data.byBilling.map(p=>String(p.label))} values={data.byBilling.map(p=>p.value)} valueFormatter={money.format}/><HorizontalChart title="Valor por responsável" subtitle="Distribuição do trabalho" labels={data.byProfessional.map(p=>String(p.label))} values={data.byProfessional.map(p=>p.value)} valueFormatter={money.format}/><DonutChart title="Facturação" subtitle="Valor facturado versus restante" firstLabel="Facturado" secondLabel="Não facturado" first={percent(m.invoiced,m.worked)}/><DonutChart title="Recebimentos" subtitle="Valor pago versus por receber" firstLabel="Pago" secondLabel="Por receber" first={percent(m.paid,m.invoiced)} tone="success"/><HorizontalChart title="Preço médio/hora" subtitle="Média global actual" labels={['Média ponderada']} values={[m.averageRate]} valueFormatter={v=>`${money.format(v)}/h`}/><DonutChart title="Tipo de cliente" subtitle="Empresas versus particulares" firstLabel="Empresas" secondLabel="Particulares" first={percent(company,company+individual)}/><HorizontalChart title="Arquivo" subtitle="Movimentos por localização" labels={data.byArchive.map(p=>String(p.label))} values={data.byArchive.map(p=>p.value)}/><StackedSocietyChart data={data.byBilling}/></div></section></div>
}
