import { useEffect, useState } from 'react'
import { MetricCard } from '../components/dashboard/MetricCard'
import { AnnualValueChart, DonutChart, HorizontalChart, MonthlyValueChart, SocietyEvolutionChart, StackedSocietyChart, type ChartPoint, type MonthlyYearPoint, type SocietyMonthPoint, type SocietyYearPoint } from '../components/dashboard/Charts'
import { supabase } from '../lib/supabase'

type AnnualPoint = ChartPoint & { minutes:number }
type MoneyValue=number|null
type OverviewData = { metrics:{ minutes:number; worked:MoneyValue; invoiced:MoneyValue; paid:MoneyValue; receivable:MoneyValue; uninvoicedCount:number; unpaidCount:number; averageRate:MoneyValue; activeClients:number; missingPrice:number; overrides:number; importErrors:number }; annual:AnnualPoint[]; monthly:ChartPoint[]; monthlyByYear:MonthlyYearPoint[]; billingAnnual:SocietyYearPoint[]; billingMonthly:SocietyMonthPoint[]; latestYear:number; byClient:ChartPoint[]; byBilling:ChartPoint[]; byProfessional:ChartPoint[]; byArchive:ChartPoint[]; clientTypes:ChartPoint[] }
const money = new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR',maximumFractionDigits:0})
const number = new Intl.NumberFormat('pt-PT')
const financial=(value:MoneyValue)=>value==null?'Sem acesso':money.format(value)
const percent=(part:MoneyValue,total:MoneyValue)=>part!=null&&total!=null&&total>0?Math.round(part/total*100):0

async function loadSocietySeries(){
 type VisibleRow={work_date:string;effective_amount:number|null;billing:{name:string}|null}
 const end=new Date();end.setUTCDate(1);end.setUTCHours(0,0,0,0)
 const periods=Array.from({length:12},(_,offset)=>{const date=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()-11+offset,1));return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}`})
 const rows:VisibleRow[]=[]
 for(let from=0;;from+=1000){const response=await supabase!.from('work_entries').select('work_date,effective_amount,billing:billing_entities(name)').gte('work_date',`${periods[0]}-01`).order('work_date',{ascending:false}).range(from,from+999);if(response.error)throw response.error;const batch=(response.data??[]) as unknown as VisibleRow[];rows.push(...batch);if(batch.length<1000)break}
 const monthly=periods.map(label=>{const matching=rows.filter(row=>row.work_date.startsWith(label)),societies:Record<string,number>={};for(const row of matching){const society=row.billing?.name??'Sem sociedade';societies[society]=(societies[society]??0)+(row.effective_amount??0)}return {label,value:matching.reduce((sum,row)=>sum+(row.effective_amount??0),0),societies}})
 const annual:SocietyYearPoint[]=[]
 for(const row of rows){const society=row.billing?.name??'Sem sociedade',year=Number(row.work_date.slice(0,4)),existing=annual.find(point=>point.year===year&&point.society===society);if(existing)existing.value+=row.effective_amount??0;else annual.push({society,year,value:row.effective_amount??0})}
 return {monthly,annual}
}

export function OverviewPage(){
 const [data,setData]=useState<OverviewData|null>(null); const [error,setError]=useState('')
 useEffect(()=>{let active=true; void(async()=>{if(!supabase){setError('Ligação ao Supabase indisponível.');return}const {data:result,error:failure}=await supabase.rpc('get_dashboard_overview');if(!active)return;if(failure){setError(failure.message);return}const next=result as OverviewData;const serverAnnual=next.billingAnnual??[];next.annual=next.annual.map(point=>({...point,societies:Object.fromEntries(serverAnnual.filter(item=>item.year===Number(point.label)).map(item=>[item.society,item.value]))}));setData(next);if(serverAnnual.length&&next.billingMonthly?.length)return;try{const fallback=await loadSocietySeries();if(!active)return;const annual=serverAnnual.length?serverAnnual:fallback.annual;setData(current=>current?{...current,billingAnnual:annual,monthly:fallback.monthly,annual:current.annual.map(point=>({...point,societies:Object.fromEntries(annual.filter(item=>item.year===Number(point.label)).map(item=>[item.society,item.value]))}))}:current)}catch{if(active)setData(current=>current)}})();return()=>{active=false}},[])
 if(error)return <div role="alert" className="card border-danger/30 bg-danger-soft p-6 text-danger">Não foi possível carregar o dashboard: {error}</div>
 if(!data)return <div role="status" className="space-y-4"><div className="card flex min-h-24 items-center gap-3 p-5"><span className="size-5 animate-spin rounded-full border-2 border-secondary border-t-transparent" aria-hidden="true"/><div><p className="font-semibold">A carregar a Visão geral</p><p className="mt-1 text-sm text-text-secondary">Os dados estão a ser preparados.</p></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="card h-32 animate-pulse bg-surface-subtle"/>)}</div></div>
 const m=data.metrics
 const metrics=[
  ['Total de horas',`${number.format(Math.round(m.minutes/60))} h`,'Duração importada convertida','clock','default'],['Total de minutos',number.format(m.minutes),'Movimentos acessíveis','clock','default'],['Valor trabalhado',financial(m.worked),'Valor efectivo preservado','trend','default'],['Valor facturado',financial(m.invoiced),m.invoiced==null?'Sem permissão financeira':`${percent(m.invoiced,m.worked)}% do trabalhado`,'invoice','default'],['Valor recebido',financial(m.paid),m.paid==null?'Sem permissão financeira':`${percent(m.paid,m.invoiced)}% do facturado`,'payment','success'],['Por receber',financial(m.receivable),'Facturado e ainda não pago','warning','warning'],['Não facturados',number.format(m.uninvoicedCount),'Movimentos','invoice','warning'],['Facturados não pagos',number.format(m.unpaidCount),'Requer acompanhamento','payment','warning'],['Preço médio/hora',financial(m.averageRate),'Média ponderada','rules','default'],['Clientes activos',number.format(m.activeClients),'Com movimentos','clients','default'],['Movimentos sem preço',number.format(m.missingPrice),'Necessitam de revisão','warning',m.missingPrice?'danger':'default'],['Com override',number.format(m.overrides),'Alterações justificadas','audit','default'],['Importações com erros',number.format(m.importErrors),'Com linhas rejeitadas','import',m.importErrors?'danger':'default'],
 ] as const
 const individual=data.clientTypes.find(p=>p.label==='individual')?.value??0; const company=data.clientTypes.find(p=>p.label==='company')?.value??0
 return <div className="space-y-6"><section aria-labelledby="summary-title"><div className="mb-4"><h2 id="summary-title" className="font-semibold">Resumo operacional</h2><p className="mt-1 text-sm text-text-secondary">Dados reais acessíveis através das políticas RLS</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-5">{metrics.map(([label,value,detail,icon,tone])=><MetricCard key={label} label={label} value={value} detail={detail} icon={icon} tone={tone} financial={/valor|preço|receb/i.test(label)}/>)}</div></section>
 <section aria-labelledby="analysis-title"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h2 id="analysis-title" className="font-semibold">Análise e tendências</h2><p className="mt-1 text-sm text-text-secondary">Histórico importado de 2018 a {data.latestYear}</p></div></div>{m.worked==null?<p className="card p-5 text-sm text-text-secondary">Os gráficos financeiros não são apresentados porque este utilizador não tem permissão para consultar valores.</p>:<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><AnnualValueChart data={data.annual} allowSocietyComparison/><MonthlyValueChart data={data.monthly} allowSocietyComparison/><HorizontalChart title="Horas por ano" subtitle="Volume anual" labels={data.annual.map(p=>String(p.label))} values={data.annual.map(p=>p.minutes)} valueFormatter={v=>`${number.format(Math.round(v/60))} h`}/><HorizontalChart title="Valor por cliente" subtitle="Cinco maiores" labels={data.byClient.map(p=>String(p.label))} values={data.byClient.map(p=>p.value)} valueFormatter={money.format}/><HorizontalChart title="Valor por sociedade" subtitle="Sociedades" labels={data.byBilling.map(p=>String(p.label))} values={data.byBilling.map(p=>p.value)} valueFormatter={money.format}/><HorizontalChart title="Valor por responsável" subtitle="Distribuição do trabalho" labels={data.byProfessional.map(p=>String(p.label))} values={data.byProfessional.map(p=>p.value)} valueFormatter={money.format}/><DonutChart title="Facturação" subtitle="Valor facturado versus restante" firstLabel="Facturado" secondLabel="Não facturado" first={percent(m.invoiced,m.worked)}/><DonutChart title="Recebimentos" subtitle="Valor pago versus por receber" firstLabel="Pago" secondLabel="Por receber" first={percent(m.paid,m.invoiced)} tone="success"/><HorizontalChart title="Preço médio/hora" subtitle="Média global actual" labels={['Média ponderada']} values={[m.averageRate??0]} valueFormatter={v=>`${money.format(v)}/h`}/><DonutChart title="Tipo de cliente" subtitle="Empresas versus particulares" firstLabel="Empresas" secondLabel="Particulares" first={percent(company,company+individual)}/><HorizontalChart title="Arquivo" subtitle="Movimentos por localização" labels={data.byArchive.map(p=>String(p.label))} values={data.byArchive.map(p=>p.value)}/><StackedSocietyChart data={data.byBilling}/><SocietyEvolutionChart data={data.billingAnnual??[]}/></div>}</section></div>
}
