import {createClient} from 'npm:@supabase/supabase-js@2.112.1'
import {corsHeaders,isAllowedOrigin,json} from '../_shared/http.ts'
const maximumSize=20*1024*1024,uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const mimeByExtension:Record<string,string>={pdf:'application/pdf',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}
function safeName(value:string){return value.normalize('NFKC').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(-120)||'documento'}
function valid(extension:string,bytes:Uint8Array){if(extension==='pdf')return bytes[0]===0x25&&bytes[1]===0x50&&bytes[2]===0x44&&bytes[3]===0x46;if(extension==='jpg'||extension==='jpeg')return bytes[0]===0xff&&bytes[1]===0xd8&&bytes.at(-2)===0xff&&bytes.at(-1)===0xd9;if(extension==='png')return[0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a].every((v,i)=>bytes[i]===v);if(extension==='docx'||extension==='xlsx'){if(bytes[0]!==0x50||bytes[1]!==0x4b)return false;const d=new TextDecoder('latin1').decode(bytes);return d.includes('[Content_Types].xml')&&(extension==='docx'?d.includes('word/'):d.includes('xl/'))&&!/(vbaProject|externalLinks|embeddings)/i.test(d)}return false}
async function hash(bytes:Uint8Array){const result=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(result),b=>b.toString(16).padStart(2,'0')).join('')}
Deno.serve(async request=>{
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(request)});if(request.method!=='POST')return json(request,{error:'Método não permitido.'},405);if(!isAllowedOrigin(request))return json(request,{error:'Origem não autorizada.'},403)
 const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),authorization=request.headers.get('authorization');if(!url||!key)return json(request,{error:'Arquivo documental não configurado.'},503);if(!authorization?.startsWith('Bearer '))return json(request,{error:'Autenticação necessária.'},401)
 const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),token=authorization.slice(7),auth=await admin.auth.getUser(token);if(auth.error||!auth.data.user)return json(request,{error:'Sessão inválida.'},401)
 const user=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')??key,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}})
 try{const form=await request.formData(),file=form.get('file'),expenseId=String(form.get('expenseId')??'');if(!(file instanceof File)||!uuid.test(expenseId)||file.size<=0||file.size>maximumSize)return json(request,{error:'Dados do documento inválidos.'},400)
  const allowed=await user.rpc('can_manage_work_entry_expense_document',{target_expense_id:expenseId});if(!allowed.data)return json(request,{error:'Sem permissão para arquivar este documento.'},403)
  const expense=await admin.from('work_entry_expenses').select('id,firm_id,work_entry_id,work_entries!inner(client_id)').eq('id',expenseId).eq('status','active').single();if(expense.error||!expense.data)return json(request,{error:'Despesa não encontrada.'},404)
  const extension=file.name.split('.').at(-1)?.toLowerCase()??'',mime=mimeByExtension[extension],bytes=new Uint8Array(await file.arrayBuffer());if(!mime||!valid(extension,bytes))return json(request,{error:'Formato inválido ou conteúdo activo.'},400)
  const digest=await hash(bytes),duplicate=await admin.from('work_entry_expense_documents').select('id').eq('expense_id',expenseId).eq('sha256',digest).eq('status','active').maybeSingle();if(duplicate.data)return json(request,{error:'Este documento já está associado à despesa.'},409)
  const clientId=(expense.data.work_entries as unknown as {client_id:string}).client_id,documentId=crypto.randomUUID(),path=`${expense.data.firm_id}/${clientId}/expenses/${expenseId}/${documentId}/${safeName(file.name)}`
  const uploaded=await admin.storage.from('client-documents').upload(path,bytes,{contentType:mime,upsert:false});if(uploaded.error)throw uploaded.error
  const inserted=await admin.from('work_entry_expense_documents').insert({id:documentId,firm_id:expense.data.firm_id,expense_id:expenseId,original_filename:file.name.normalize('NFKC').slice(0,255),storage_path:path,mime_type:mime,size_bytes:file.size,sha256:digest,uploaded_by:auth.data.user.id,created_by:auth.data.user.id});if(inserted.error){await admin.storage.from('client-documents').remove([path]);throw inserted.error}return json(request,{documentId},201)
 }catch{return json(request,{error:'Não foi possível concluir o carregamento.'},400)}
})
