import { useState, type ChangeEvent, type FormEvent } from 'react'

export function InitialPinChangePage({ busy, error, onSubmit, onLogout }: { busy:boolean; error:string; onSubmit:(currentPin:string,newPin:string)=>Promise<void>; onLogout:()=>Promise<void> }) {
  const [currentPin,setCurrentPin] = useState(''), [newPin,setNewPin] = useState(''), [confirmation,setConfirmation] = useState('')
  const mismatch = confirmation.length === 4 && newPin !== confirmation
  const valid = /^\d{4}$/.test(currentPin) && /^\d{4}$/.test(newPin) && newPin === confirmation && newPin !== currentPin
  const update = (setter:(value:string)=>void) => (event:ChangeEvent<HTMLInputElement>) => setter(event.target.value.replace(/\D/g,'').slice(0,4))
  function submit(event:FormEvent) { event.preventDefault(); if (valid) void onSubmit(currentPin,newPin) }
  return <main className="app-safe-min-h grid min-h-screen place-items-center bg-background p-5"><section className="card w-full max-w-md p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-secondary">Primeiro acesso</p><h1 className="mt-2 font-display text-2xl font-semibold">Escolha o seu PIN</h1><p className="mt-3 text-sm leading-6 text-text-secondary">O PIN atribuído pela administração é temporário. Antes de continuar, confirme-o e escolha um PIN pessoal diferente.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-semibold">PIN inicial<input aria-label="PIN inicial" type="password" inputMode="numeric" autoComplete="current-password" pattern="[0-9]{4}" maxLength={4} value={currentPin} onChange={update(setCurrentPin)} className="control mt-1 w-full px-3 text-center text-xl tracking-[0.35em]"/></label><label className="block text-sm font-semibold">Novo PIN<input aria-label="Novo PIN" type="password" inputMode="numeric" autoComplete="new-password" pattern="[0-9]{4}" maxLength={4} value={newPin} onChange={update(setNewPin)} className="control mt-1 w-full px-3 text-center text-xl tracking-[0.35em]"/></label><label className="block text-sm font-semibold">Confirmar novo PIN<input aria-label="Confirmar novo PIN" type="password" inputMode="numeric" autoComplete="new-password" pattern="[0-9]{4}" maxLength={4} value={confirmation} onChange={update(setConfirmation)} className="control mt-1 w-full px-3 text-center text-xl tracking-[0.35em]"/></label>{mismatch&&<p role="alert" className="text-sm text-danger">Os novos PIN não coincidem.</p>}{newPin.length===4&&newPin===currentPin&&<p role="alert" className="text-sm text-danger">O novo PIN tem de ser diferente do PIN inicial.</p>}{error&&<p role="alert" className="rounded-lg bg-danger-soft p-3 text-sm text-danger">{error}</p>}<button disabled={busy||!valid} className="min-h-11 w-full rounded-lg bg-primary px-4 font-semibold text-surface disabled:opacity-50">{busy?'A guardar…':'Guardar novo PIN'}</button><button type="button" onClick={()=>void onLogout()} className="min-h-11 w-full rounded-lg border border-border px-4 font-semibold text-primary">Terminar sessão</button></form></section></main>
}
