import { useState } from 'react'
import type { LegalDocumentRow } from '../../types/database.types'

const labels: Record<LegalDocumentRow['document_type'], string> = { terms_of_service:'Termos de Serviço', privacy_policy:'Política de Privacidade', gdpr_terms:'Termos de RGPD' }

export function TermsModal({ documents, busy, error, onAccept }: { documents:LegalDocumentRow[]; busy:boolean; error:string; onAccept:()=>Promise<void> }) {
  const [service,setService]=useState(false); const [privacy,setPrivacy]=useState(false); const complete=service&&privacy
  return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-primary/55 p-4" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="terms-title" className="card my-4 max-h-[calc(100vh-2rem)] w-full max-w-3xl overflow-y-auto p-6 shadow-raised sm:p-8"><p className="text-xs font-semibold uppercase tracking-widest text-secondary">Primeiro acesso</p><h1 id="terms-title" className="mt-2 font-display text-3xl font-semibold">Aceitação obrigatória</h1><p className="mt-3 text-sm leading-6 text-text-secondary">Leia integralmente os documentos vigentes. O acesso permanece bloqueado até aceitar ambos os grupos.</p><div className="mt-6 space-y-4">{documents.map((document)=><article key={document.id} className="rounded-xl border border-border p-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{labels[document.document_type]}</h2><span className="text-xs text-text-secondary">Versão {document.version} · em vigor desde {new Intl.DateTimeFormat('pt-PT',{dateStyle:'long'}).format(new Date(document.effective_at))}</span></div><div className="mt-3 max-h-40 overflow-y-auto whitespace-pre-wrap rounded-lg bg-surface-subtle p-4 text-sm leading-6 text-text-secondary">{document.body_markdown}</div></article>)}</div><div className="mt-6 space-y-3 border-t border-border pt-5"><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={service} onChange={(e)=>setService(e.target.checked)} className="mt-1"/><span>Li e aceito os Termos de Serviço.</span></label><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={privacy} onChange={(e)=>setPrivacy(e.target.checked)} className="mt-1"/><span>Li e aceito os Termos de RGPD e a Política de Privacidade.</span></label>{error&&<p role="alert" className="rounded-lg bg-danger-soft p-3 text-sm text-danger">{error}</p>}<button disabled={!complete||busy} onClick={()=>void onAccept()} className="w-full rounded-lg bg-primary px-4 py-3 font-semibold text-surface disabled:cursor-not-allowed disabled:opacity-40">{busy?'A registar aceitação…':'Aceitar e continuar'}</button></div></section></div>
}
