import { useState } from 'react'

export type ChartPoint = { label: string | number; value: number; societies?:Record<string,number> }
export type MonthlyYearPoint = { year:number; month:number; value:number }
export type SocietyYearPoint = { society:string; year:number; value:number }
export type SocietyMonthPoint = { society:string; period:string; value:number }

const compactMoney = new Intl.NumberFormat('pt-PT', { style:'currency', currency:'EUR', notation:'compact', maximumFractionDigits:1 })
const smoothLine=(values:number[],max:number,scale=90)=>values.map((value,index)=>({x:index/Math.max(values.length-1,1)*100,y:100-value/max*scale})).reduce((path,point,index,all)=>{if(index===0)return `M ${point.x} ${point.y}`;const previous=all[index-1],midX=(previous.x+point.x)/2;return `${path} C ${midX} ${previous.y}, ${midX} ${point.y}, ${point.x} ${point.y}`},'')

function ChartCard({ title, subtitle, children, className = '' }: { title: string; subtitle: string; children: React.ReactNode; className?: string }) {
  return <figure data-chart-title={title} className={`card relative min-w-0 p-5 ${className}`}><figcaption className="pr-36"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-xs text-text-secondary">{subtitle}</p></figcaption><div className="mt-5">{children}</div></figure>
}
function SeriesToggle({individual,onChange,label}:{individual:boolean;onChange:(value:boolean)=>void;label:string}) {
  return <div className="absolute right-3 top-3 flex gap-0.5" role="group" aria-label={`Representação de ${label}`}><button type="button" aria-pressed={!individual} onClick={()=>onChange(false)} className={`min-h-7 rounded-l-md border px-2 text-[0.65rem] font-semibold ${!individual?'border-secondary bg-secondary text-surface':'border-border bg-surface text-text-secondary'}`}>Agregado</button><button type="button" aria-pressed={individual} onClick={()=>onChange(true)} className={`min-h-7 rounded-r-md border px-2 text-[0.65rem] font-semibold ${individual?'border-secondary bg-secondary text-surface':'border-border bg-surface text-text-secondary'}`}>Por sociedade</button></div>
}

export function AnnualValueChart({ data,societyData=[],allowSocietyComparison=false }: { data: ChartPoint[]; societyData?:SocietyYearPoint[]; allowSocietyComparison?:boolean }) {
  const [individual,setIndividual]=useState(false)
  const max = Math.max(...data.map((point) => point.value), 1)
  const societySeries=societyData.length?societyData:data.flatMap(point=>Object.entries(point.societies??{}).map(([society,value])=>({society,year:Number(point.label),value})))
  const societies=allowSocietyComparison?[...new Set(societySeries.map(point=>point.society))]:[],seriesMax=Math.max(...societySeries.map(point=>point.value),1)
  const canCompareSocieties=allowSocietyComparison
  return <ChartCard title="Valor por ano" subtitle={individual?'Sociedades representadas individualmente':'Todas as sociedades agregadas'} className="lg:col-span-2">{canCompareSocieties&&<SeriesToggle individual={individual} onChange={setIndividual} label="valor por ano"/>}
    {individual?<><div className="mb-3 flex flex-wrap justify-end gap-3 text-xs">{societies.map((society,index)=><span key={society} className="flex items-center gap-2"><i className="size-2.5 rounded-full" style={{background:`var(--color-chart-${index%4+1})`}}/>{society}</span>)}</div><div className="overflow-x-auto pb-1"><div className="grid h-56 min-w-[42rem] items-end gap-2 border-b border-border pb-1" style={{gridTemplateColumns:`repeat(${Math.max(data.length,1)},minmax(4rem,1fr))`}}>{data.map(point=><div key={point.label} className="relative flex h-full min-w-0 items-end justify-center gap-1 pb-5">{societies.map((society,index)=>{const value=societySeries.find(item=>item.year===Number(point.label)&&item.society===society)?.value??0;return <div key={society} className="flex h-full min-w-0 flex-1 flex-col justify-end"><span className="financial-value mb-1 -rotate-45 whitespace-nowrap text-[0.48rem] font-semibold tabular-nums">{compactMoney.format(value)}</span><i className="min-h-0.5 rounded-t" style={{height:`${value/seriesMax*84}%`,background:`var(--color-chart-${index%4+1})`}}/></div>})}<span className="absolute inset-x-0 bottom-0 text-center text-[0.62rem] text-text-secondary">{point.label}</span></div>)}</div></div></>:
    <div className="overflow-x-auto pb-1"><div className="flex h-56 min-w-[34rem] items-end gap-2 border-b border-border pb-1 sm:gap-3" role="img" aria-label="Valor anual dos movimentos acessíveis">
      {data.map((point) => <div key={point.label} className="group flex h-full min-w-0 flex-1 flex-col justify-end"><span className="financial-value mb-2 whitespace-nowrap text-center text-[0.62rem] font-semibold tabular-nums text-text-primary">{compactMoney.format(point.value)}</span><div className="min-h-1 rounded-t-md bg-chart-1 transition-[height,filter] duration-300 hover:brightness-110" style={{ height: `${point.value / max * 100}%` }} /><span className="mt-2 text-center text-[0.62rem] text-text-secondary">{String(point.label).slice(2)}</span></div>)}
    </div></div>}
  </ChartCard>
}

export function MonthlyValueChart({ data,societyData=[],allowSocietyComparison=false }: { data: ChartPoint[]; societyData?:SocietyMonthPoint[]; allowSocietyComparison?:boolean }) {
  const [individual,setIndividual]=useState(false)
  const rolling=data.some(point=>/^\d{4}-\d{2}$/.test(String(point.label)))
  const pointsData:ChartPoint[]=rolling?data.slice(-12):Array.from({length:12},(_,index)=>{const point=data.find(item=>Number(item.label)===index+1);return {label:index+1,value:point?.value??0,societies:point?.societies}})
  const values=pointsData.map(point=>point.value)
  const max = Math.max(...values, 1)
  const points = values.map((value, index) => `${(index / 11) * 100},${100 - value / max * 90}`).join(' ')
  const labels=pointsData.map(point=>{const raw=String(point.label);if(!rolling)return ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'][Number(raw)-1];const [year,month]=raw.split('-').map(Number);return new Intl.DateTimeFormat('pt-PT',{month:'short',year:'2-digit',timeZone:'UTC'}).format(new Date(Date.UTC(year,month-1,1))).replace('.','')})
  const societySeries=societyData.length?societyData:pointsData.flatMap(point=>Object.entries(point.societies??{}).map(([society,value])=>({society,period:String(point.label),value})))
  const societies=allowSocietyComparison?[...new Set(societySeries.map(point=>point.society))]:[],seriesMax=Math.max(...societySeries.map(point=>point.value),1)
  if(!allowSocietyComparison)return <ChartCard title="Valor por mês" subtitle={rolling?'Últimos 12 meses':'Distribuição mensal disponível'} className="lg:col-span-2"><div className="overflow-x-auto pb-1"><div className="h-56 min-w-[42rem]"><div className="relative h-48"><svg viewBox="0 0 100 110" preserveAspectRatio="none" className="absolute inset-0 h-full w-full overflow-visible" role="img" aria-label="Valor mensal"><defs><linearGradient id="area-single" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--color-chart-1)" stopOpacity=".25"/><stop offset="1" stopColor="var(--color-chart-1)" stopOpacity="0"/></linearGradient></defs><path d={`M0,100 L${points} L100,100 Z`} fill="url(#area-single)"/><path d={smoothLine(values,max)} fill="none" stroke="var(--color-chart-1)" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>{values.map((value,index)=><span key={index} className="financial-value absolute -translate-x-1/2 rounded bg-surface/90 px-1 text-[0.58rem] font-semibold tabular-nums text-text-primary shadow-sm" style={{left:`${index/11*100}%`,top:`${Math.max(0,88-value/max*82)}%`}}>{compactMoney.format(value)}</span>)}</div><div className="grid grid-cols-12 text-center text-[0.62rem] text-text-secondary">{labels.map((month,index)=><span key={`${month}-${index}`}>{month}</span>)}</div></div></div></ChartCard>
  const valuesFor=(society:string)=>pointsData.map(point=>societySeries.find(item=>item.period===String(point.label)&&item.society===society)?.value??0)
  return <ChartCard title="Valor por mês" subtitle={individual?'Últimos 12 meses por sociedade':rolling?'Últimos 12 meses agregados':'Distribuição mensal disponível'} className="lg:col-span-2"><SeriesToggle individual={individual} onChange={setIndividual} label="valor por mês"/>{individual?<><div className="mb-3 flex flex-wrap justify-end gap-3 text-xs">{societies.map((society,index)=><span key={society} className="flex items-center gap-2"><i className="size-2.5 rounded-full" style={{background:`var(--color-chart-${index%4+1})`}}/>{society}</span>)}</div><div className="overflow-x-auto pb-1"><div className="h-60 min-w-[56rem]"><div className="relative h-52" role="img" aria-label="Valor mensal por sociedade"><svg viewBox="0 0 100 110" preserveAspectRatio="none" className="absolute inset-0 h-full w-full overflow-visible">{societies.map((society,index)=><path key={society} d={smoothLine(valuesFor(society),seriesMax,86)} fill="none" stroke={`var(--color-chart-${index%4+1})`} strokeWidth="2" vectorEffect="non-scaling-stroke"/>)}</svg>{societies.flatMap((society,societyIndex)=>valuesFor(society).map((value,monthIndex)=><span key={`${society}-${monthIndex}`} className="financial-value absolute -translate-x-1/2 whitespace-nowrap rounded bg-surface/90 px-0.5 text-[0.46rem] font-semibold tabular-nums shadow-sm" style={{left:`${monthIndex/11*100}%`,top:`${Math.max(0,86-value/seriesMax*78+societyIndex*4)}%`,color:`var(--color-chart-${societyIndex%4+1})`}}>{compactMoney.format(value)}</span>))}</div><div className="grid grid-cols-12 text-center text-[0.62rem] text-text-secondary">{labels.map((month,index)=><span key={`${month}-${index}`}>{month}</span>)}</div></div></div></>:<div className="overflow-x-auto pb-1"><div className="h-56 min-w-[42rem]">
    <div className="relative h-48"><svg viewBox="0 0 100 110" preserveAspectRatio="none" className="absolute inset-0 h-full w-full overflow-visible" role="img" aria-label="Valor mensal">
      <defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--color-chart-1)" stopOpacity=".25"/><stop offset="1" stopColor="var(--color-chart-1)" stopOpacity="0"/></linearGradient></defs>
      <path d={`M0,100 L${points} L100,100 Z`} fill="url(#area)"/><path d={smoothLine(values,max)} fill="none" stroke="var(--color-chart-1)" strokeWidth="2" vectorEffect="non-scaling-stroke"/>
    </svg>{values.map((value,index)=><span key={index} className="financial-value absolute -translate-x-1/2 rounded bg-surface/90 px-1 text-[0.58rem] font-semibold tabular-nums text-text-primary shadow-sm" style={{left:`${(index/11)*100}%`,top:`${Math.max(0,88-value/max*82)}%`}}>{compactMoney.format(value)}</span>)}</div><div className="grid grid-cols-12 text-center text-[0.62rem] text-text-secondary">{labels.map((month,index) => <span key={`${month}-${index}`}>{month}</span>)}</div>
  </div></div>}</ChartCard>
}
export function HorizontalChart({ title, subtitle, labels, values, valueFormatter = (value) => value.toLocaleString('pt-PT') }: { title: string; subtitle: string; labels: string[]; values: number[]; valueFormatter?: (value: number) => string }) {
  const max = Math.max(...values, 1)
  const financial = /valor|preço|factura|receb/i.test(`${title} ${subtitle}`)
  return <ChartCard title={title} subtitle={subtitle}><div className="space-y-3" role="img" aria-label={title}>
    {labels.map((label, index) => <div key={label}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate text-text-secondary">{label}</span><span className={`${financial?'financial-value ':''}font-semibold tabular-nums`}>{valueFormatter(values[index])}</span></div><div className="h-2 overflow-hidden rounded-full bg-surface-subtle"><div className="h-full rounded-full bg-chart-1" style={{ width: `${values[index] / max * 100}%` }} /></div></div>)}
  </div></ChartCard>
}

export function DonutChart({ title, subtitle, firstLabel, secondLabel, first, tone = 'secondary' }: { title: string; subtitle: string; firstLabel: string; secondLabel: string; first: number; tone?: 'secondary' | 'success' }) {
  const color = tone === 'success' ? 'var(--color-success)' : 'var(--color-secondary)'
  const financial = /factura|receb/i.test(title)
  const remainderColor=financial?'var(--color-danger)':'var(--color-surface-subtle)'
  return <ChartCard title={title} subtitle={subtitle}><div className="grid justify-items-center gap-5 py-3 sm:grid-cols-[7rem_minmax(0,1fr)] sm:items-center sm:justify-items-stretch">
    <div className="grid size-28 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(${color} ${first}%, ${remainderColor} 0)` }} role="img" aria-label={`${firstLabel}: ${first}%`}><div className="grid size-20 place-items-center rounded-full bg-surface text-lg font-semibold"><span className={financial?'financial-value':''}>{first}%</span></div></div>
    <div className="grid w-full min-w-0 gap-3 text-xs"><p className="grid min-w-0 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2"><span className="inline-block size-2.5 rounded-full" style={{background:color}}/><span className="truncate">{firstLabel}</span><strong className={`${financial?'financial-value ':''}tabular-nums`}>{first}%</strong></p><p className="grid min-w-0 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2"><span className="inline-block size-2.5 rounded-full ring-1 ring-border" style={{background:remainderColor}}/><span className="truncate">{secondLabel}</span><strong className={`${financial?'financial-value ':''}tabular-nums`}>{100-first}%</strong></p></div>
  </div></ChartCard>
}

export function StackedSocietyChart({ data }: { data: ChartPoint[] }) {
  return <ChartCard title="Distribuição das sociedades" subtitle="Valor total por sociedade" className="lg:col-span-2"><div className="space-y-4" role="img" aria-label="Distribuição real das sociedades">
    {data.map((point) => <div key={point.label} className="grid grid-cols-[8rem_minmax(0,1fr)_auto] items-center gap-3"><span className="truncate text-xs text-text-secondary">{point.label}</span><div className="h-4 overflow-hidden rounded-full bg-surface-subtle"><span className="block h-full bg-chart-1" style={{ width: `${point.value / Math.max(...data.map((item) => item.value),1) * 100}%` }}/></div><strong className="financial-value text-xs tabular-nums">{compactMoney.format(point.value)}</strong></div>)}
  </div></ChartCard>
}

export function YearComparisonChart({data,years}:{data:MonthlyYearPoint[];years:number[]}){
  const months=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
  const values=years.flatMap(year=>months.map((_,index)=>data.find(point=>point.year===year&&point.month===index+1)?.value??0))
  const max=Math.max(...values,1)
  return <ChartCard title="Comparação mensal entre anos" subtitle={years.length?years.join(' versus '):'Seleccione anos'} className="lg:col-span-2"><div className="overflow-x-auto"><div className="min-w-[42rem]"><div className="mb-3 flex justify-end gap-4 text-xs">{years.map((year,index)=><span key={year} className="flex items-center gap-2"><i className="size-2.5 rounded-full" style={{background:`var(--color-chart-${index+1})`}}/>{year}</span>)}</div><div className="grid h-60 grid-cols-12 items-end gap-2 border-b border-border">{months.map((month,monthIndex)=><div key={month} className="flex h-full min-w-0 items-end justify-center gap-0.5">{years.map((year,yearIndex)=>{const value=data.find(point=>point.year===year&&point.month===monthIndex+1)?.value??0;return <div key={year} className="group flex h-full min-w-0 flex-1 flex-col justify-end"><span className="financial-value mb-1 -rotate-45 whitespace-nowrap text-[0.5rem] font-semibold tabular-nums">{compactMoney.format(value)}</span><span className="min-h-0.5 rounded-t" style={{height:`${value/max*90}%`,background:`var(--color-chart-${yearIndex+1})`}}/></div>})}</div>)}</div><div className="grid grid-cols-12 gap-2 pt-2 text-center text-[0.62rem] text-text-secondary">{months.map(month=><span key={month}>{month}</span>)}</div></div></div></ChartCard>
}

export function SocietyEvolutionChart({data}:{data:SocietyYearPoint[]}){
  const years=[...new Set(data.map(point=>point.year))].sort(),societies=[...new Set(data.map(point=>point.society))]
  const max=Math.max(...data.map(point=>point.value),1)
  return <ChartCard title="Evolução anual das sociedades" subtitle="Comparação por sociedade" className="lg:col-span-2"><div className="overflow-x-auto"><div className="min-w-[36rem] space-y-4">{societies.map((society,societyIndex)=><div key={society}><p className="mb-2 truncate text-xs font-semibold">{society}</p><div className="grid gap-2" style={{gridTemplateColumns:`repeat(${Math.max(years.length,1)},minmax(3rem,1fr))`}}>{years.map(year=>{const value=data.find(point=>point.society===society&&point.year===year)?.value??0;return <div key={year} className="min-w-0"><span className="financial-value block truncate text-[0.58rem] font-semibold tabular-nums">{compactMoney.format(value)}</span><span className="mt-1 block h-2 rounded-full bg-surface-subtle"><i className="block h-full rounded-full" style={{width:`${value/max*100}%`,background:`var(--color-chart-${societyIndex%4+1})`}}/></span><span className="mt-1 block text-[0.58rem] text-text-secondary">{year}</span></div>})}</div></div>)}</div></div></ChartCard>
}
