import { useEffect, useLayoutEffect, useMemo, useRef, useState, type CSSProperties, type KeyboardEvent as ReactKeyboardEvent, type ReactNode } from 'react'

type Scalar=string|number|boolean|Date|null|undefined
type FilterValue={text?:string;min?:string;max?:string;selected?:string[]}
type SortRule={id:string;direction:'asc'|'desc'}
export type TableColumn<Row>={
  id:string;label:string;value:(row:Row)=>Scalar;render?:(row:Row)=>ReactNode
  kind?:'text'|'number'|'date'|'money'|'boolean';filterOptions?:Array<{value:string;label:string}>
  essential?:boolean;sticky?:boolean;align?:'left'|'center'|'right';width?:number
  sortable?:boolean;searchable?:boolean;filterable?:boolean;exportable?:boolean
}
type Props<Row>={
  id:string;label:string;rows:Row[];columns:TableColumn<Row>[];rowKey:(row:Row)=>string
  loading?:boolean;updating?:boolean;error?:string;onRetry?:()=>void;defaultPageSize?:10|20|50|'all'
  selected?:string[];onSelectionChange?:(ids:string[])=>void;emptyMessage?:string;loadExportRows?:()=>Promise<Row[]>;onRowDoubleClick?:(row:Row)=>void
}

const fold=(value:Scalar)=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-PT')
const numeric=(value:Scalar)=>value instanceof Date?value.valueOf():Number(value)
const comparable=(value:Scalar,kind:TableColumn<unknown>['kind'])=>kind==='date'?new Date(String(value)).valueOf():kind==='number'||kind==='money'?numeric(value):kind==='boolean'?Number(Boolean(value)):fold(value)
const safeSpreadsheetValue=(value:Scalar)=>typeof value==='string'&&/^[=+\-@]/.test(value)?`'${value}`:value??''
const spreadsheetValue=(value:Scalar,kind:TableColumn<unknown>['kind'])=>{if(value==null)return'';if(kind==='date'){const parsed=value instanceof Date?value:new Date(String(value));return Number.isNaN(parsed.valueOf())?safeSpreadsheetValue(value):parsed}if(kind==='number'||kind==='money')return Number(value);if(kind==='boolean')return Boolean(value);return safeSpreadsheetValue(value)}
const hasFilterValue=(value?:FilterValue)=>Boolean(value?.text||value?.min||value?.max||value?.selected!==undefined)
const cyclePanelFocus=(event:ReactKeyboardEvent<HTMLElement>)=>{if(event.key!=='ArrowDown'&&event.key!=='ArrowUp')return;const controls=[...event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled)')];if(!controls.length)return;const current=controls.indexOf(document.activeElement as HTMLElement),step=event.key==='ArrowDown'?1:-1,next=current<0?0:(current+step+controls.length)%controls.length;event.preventDefault();controls[next].focus()}

function matchesFilter<Row>(row:Row,column:TableColumn<Row>,filter:FilterValue){
  const value=column.value(row)
  if(filter.text&&!fold(value).includes(fold(filter.text)))return false
  if(filter.selected!==undefined&&!filter.selected.includes(String(value)))return false
  if(filter.min){const candidate=column.kind==='date'?new Date(String(value)).valueOf():numeric(value);const minimum=column.kind==='date'?new Date(filter.min).valueOf():Number(filter.min);if(!Number.isFinite(candidate)||candidate<minimum)return false}
  if(filter.max){const candidate=column.kind==='date'?new Date(String(value)).valueOf():numeric(value);const maximum=column.kind==='date'?new Date(filter.max).valueOf():Number(filter.max);if(!Number.isFinite(candidate)||candidate>maximum)return false}
  return true
}

function FilterPanel<Row>({column,value,onChange,onClose}:{column:TableColumn<Row>;value:FilterValue;onChange:(next:FilterValue)=>void;onClose:()=>void}){
  const panel=useRef<HTMLDivElement>(null)
  const [optionQuery,setOptionQuery]=useState('')
  const [style,setStyle]=useState<CSSProperties>({visibility:'hidden'})
  useEffect(()=>{panel.current?.querySelector<HTMLElement>('input,button')?.focus()},[])
  useLayoutEffect(()=>{const update=()=>{const anchor=panel.current?.parentElement?.querySelector<HTMLElement>('button');if(!anchor||!panel.current)return;const rect=anchor.getBoundingClientRect(),panelRect=panel.current.getBoundingClientRect(),margin=8;const width=Math.min(256,window.innerWidth-margin*2),height=Math.min(panelRect.height||320,window.innerHeight-margin*2);const left=Math.max(margin,Math.min(rect.left,window.innerWidth-width-margin));const below=window.innerHeight-rect.bottom>=height+margin;const top=below?Math.min(rect.bottom+6,window.innerHeight-height-margin):Math.max(margin,rect.top-height-6);setStyle({left,top,width,visibility:'visible'})};update();window.addEventListener('resize',update);window.addEventListener('scroll',update,true);return()=>{window.removeEventListener('resize',update);window.removeEventListener('scroll',update,true)}},[])
  const options=column.filterOptions??(column.kind==='boolean'?[{value:'true',label:'Sim'},{value:'false',label:'Não'}]:undefined)
  const visibleOptions=options?.filter(option=>fold(option.label).includes(fold(optionQuery)))??[]
  const selected=value.selected??options?.map(item=>item.value)??[]
  const selectVisible=()=>onChange({...value,selected:[...new Set([...selected,...visibleOptions.map(item=>item.value)])]})
  const clearVisible=()=>onChange({...value,selected:selected.filter(item=>!visibleOptions.some(option=>option.value===item))})
  const invertVisible=()=>onChange({...value,selected:[...selected.filter(item=>!visibleOptions.some(option=>option.value===item)),...visibleOptions.filter(option=>!selected.includes(option.value)).map(option=>option.value)]})
  return <div ref={panel} role="dialog" aria-label={`Filtro ${column.label}`} style={style} className="fixed z-[120] max-h-[min(20rem,calc(100dvh-1rem))] overflow-auto rounded-xl border border-border bg-surface p-3 shadow-raised" onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();onClose()}else cyclePanelFocus(event)}}>
    {options?<><p className="mb-2 text-xs text-text-secondary">{selected.length} opções seleccionadas</p>{options.length>6&&<label className="block text-xs font-semibold">Pesquisar opções<input value={optionQuery} onChange={event=>setOptionQuery(event.target.value)} className="control mt-1 w-full px-2"/></label>}<div className="flex flex-wrap gap-x-3 text-xs"><button type="button" className="min-h-11 font-semibold text-primary" onClick={selectVisible}>{optionQuery?'Seleccionar encontrados':'Seleccionar todos'}</button><button type="button" className="min-h-11 font-semibold text-secondary" onClick={clearVisible}>Limpar</button><button type="button" className="min-h-11 font-semibold text-secondary" onClick={invertVisible}>Inverter</button></div><div className="mt-2 space-y-1">{visibleOptions.map(option=><label key={option.value} className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={selected.includes(option.value)} onChange={event=>onChange({...value,selected:event.target.checked?[...new Set([...selected,option.value])]:selected.filter(item=>item!==option.value)})}/><span>{option.label}</span></label>)}</div>{!visibleOptions.length&&<p className="py-3 text-xs text-text-secondary">Nenhuma opção encontrada.</p>}</>:
      column.kind==='number'||column.kind==='money'||column.kind==='date'?<div className="grid gap-3"><label className="text-xs font-semibold">Mínimo / início<input type={column.kind==='date'?'date':'number'} value={value.min??''} onChange={event=>onChange({...value,min:event.target.value})} className="control mt-1 w-full px-2"/></label><label className="text-xs font-semibold">Máximo / fim<input type={column.kind==='date'?'date':'number'} value={value.max??''} onChange={event=>onChange({...value,max:event.target.value})} className="control mt-1 w-full px-2"/></label></div>:
      <label className="text-xs font-semibold">Texto<input value={value.text??''} onChange={event=>onChange({...value,text:event.target.value})} className="control mt-1 w-full px-2" placeholder="Filtrar…"/></label>}
    <div className="mt-3 flex justify-between"><button type="button" onClick={()=>onChange({})} className="min-h-11 text-xs font-semibold text-secondary">Limpar filtro</button><button type="button" onClick={onClose} className="min-h-11 text-xs font-semibold text-primary">Concluir</button></div>
  </div>
}

export function StandardDataTable<Row>({id,label,rows,columns,rowKey,loading=false,updating=false,error,onRetry,defaultPageSize=20,selected=[],onSelectionChange,emptyMessage='Não existem dados.',loadExportRows,onRowDoubleClick}:Props<Row>){
  const storageKey=`carina.table.${id}`
  const saved=useMemo(()=>{try{return JSON.parse(localStorage.getItem(storageKey)??'{}')}catch{return {}}},[storageKey])
  const [query,setQuery]=useState<string>(saved.query??'')
  const [sorts,setSorts]=useState<SortRule[]>(saved.sorts??(saved.sort?[saved.sort]:[]))
  const [hidden,setHidden]=useState<string[]>(saved.hidden??[])
  const [filters,setFilters]=useState<Record<string,FilterValue>>(saved.filters??{})
  const [order,setOrder]=useState<string[]>(saved.order??columns.map(column=>column.id))
  const [widths,setWidths]=useState<Record<string,number>>(saved.widths??{})
  const [pageSize,setPageSize]=useState<10|20|50|'all'>(saved.pageSize??defaultPageSize)
  const [page,setPage]=useState<number>(Number(saved.page??1))
  const [columnsOpen,setColumnsOpen]=useState(false),[openFilter,setOpenFilter]=useState<string|null>(null)
  const [exporting,setExporting]=useState(false),[exportStatus,setExportStatus]=useState('')
  const [columnsStyle,setColumnsStyle]=useState<CSSProperties>({visibility:'hidden'})
  const columnsButton=useRef<HTMLButtonElement>(null),columnsPanel=useRef<HTMLDivElement>(null),filterButtons=useRef<Record<string,HTMLButtonElement|null>>({}),draggedColumn=useRef<string|null>(null)
  const ordered=[...columns].sort((a,b)=>{const ai=order.indexOf(a.id),bi=order.indexOf(b.id);return(ai<0?columns.length:ai)-(bi<0?columns.length:bi)})
  const visible=ordered.filter(column=>column.essential||!hidden.includes(column.id))
  const hasFilter=(id:string)=>hasFilterValue(filters[id])
  const stickyOffset=(index:number)=>{let left=onSelectionChange?48:0;for(let cursor=0;cursor<index;cursor+=1){const column=visible[cursor];if(column.sticky||cursor===0)left+=widths[column.id]??column.width??160}return left}
  const processed=useMemo(()=>{
    const words=fold(query).split(/\s+/).filter(Boolean)
    const result=rows.filter(row=>words.every(word=>columns.some(column=>(column.searchable??column.exportable!==false)&&fold(column.value(row)).includes(word)))&&columns.every(column=>!hasFilterValue(filters[column.id])||matchesFilter(row,column,filters[column.id])))
    if(sorts.length)result.sort((a,b)=>{for(const sort of sorts){const column=columns.find(item=>item.id===sort.id);if(!column)continue;const av=comparable(column.value(a),column.kind),bv=comparable(column.value(b),column.kind),direction=av<bv?-1:av>bv?1:0;if(direction)return sort.direction==='asc'?direction:-direction}return 0})
    return result
  },[rows,columns,query,filters,sorts])
  const pageCount=pageSize==='all'?1:Math.max(1,Math.ceil(processed.length/pageSize)),validPage=Math.min(page,pageCount)
  const shown=pageSize==='all'?processed:processed.slice((validPage-1)*pageSize,validPage*pageSize)
  useEffect(()=>{localStorage.setItem(storageKey,JSON.stringify({query,filters,sorts,hidden,pageSize,page:validPage,order,widths}))},[storageKey,query,filters,sorts,hidden,pageSize,validPage,order,widths])
  useEffect(()=>{if(page>pageCount)setPage(pageCount)},[page,pageCount])
  useEffect(()=>{if(!columnsOpen)return;const outside=(event:MouseEvent)=>{if(!columnsPanel.current?.contains(event.target as Node)&&!columnsButton.current?.contains(event.target as Node)){setColumnsOpen(false);columnsButton.current?.focus()}};const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setColumnsOpen(false);columnsButton.current?.focus()}};document.addEventListener('mousedown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',outside);document.removeEventListener('keydown',key)}},[columnsOpen])
  useLayoutEffect(()=>{if(!columnsOpen)return;const update=()=>{const anchor=columnsButton.current,panel=columnsPanel.current;if(!anchor||!panel)return;const rect=anchor.getBoundingClientRect(),panelRect=panel.getBoundingClientRect(),margin=8,width=Math.min(256,window.innerWidth-margin*2),height=Math.min(panelRect.height||320,window.innerHeight-margin*2),left=Math.max(margin,Math.min(rect.right-width,window.innerWidth-width-margin)),below=window.innerHeight-rect.bottom>=height+margin,top=below?Math.min(rect.bottom+6,window.innerHeight-height-margin):Math.max(margin,rect.top-height-6);setColumnsStyle({left,top,width,visibility:'visible'})};update();window.addEventListener('resize',update);window.addEventListener('scroll',update,true);return()=>{window.removeEventListener('resize',update);window.removeEventListener('scroll',update,true)}},[columnsOpen])
  useEffect(()=>{if(!openFilter)return;const outside=(event:MouseEvent)=>{const target=event.target as Node;if(!document.querySelector(`[data-filter-panel="${openFilter}"]`)?.contains(target)&&!filterButtons.current[openFilter]?.contains(target)){setOpenFilter(null);filterButtons.current[openFilter]?.focus()}};document.addEventListener('mousedown',outside);return()=>document.removeEventListener('mousedown',outside)},[openFilter])
  const toggleSort=(column:TableColumn<Row>,multiple:boolean)=>{if(column.sortable===false)return;setSorts(current=>{const found=current.find(item=>item.id===column.id);const next=found?found.direction==='asc'?{id:column.id,direction:'desc' as const}:null:{id:column.id,direction:'asc' as const};if(!multiple)return next?[next]:[];return[...current.filter(item=>item.id!==column.id),...(next?[next]:[])]});setPage(1)}
  const moveColumn=(target:string)=>{const source=draggedColumn.current;if(!source||source===target)return;setOrder(current=>{const next=current.filter(item=>item!==source);next.splice(Math.max(0,next.indexOf(target)),0,source);return next});draggedColumn.current=null}
  const resize=(event:React.MouseEvent,column:TableColumn<Row>)=>{event.preventDefault();event.stopPropagation();const start=event.clientX,initial=widths[column.id]??column.width??160;const move=(next:MouseEvent)=>setWidths(value=>({...value,[column.id]:Math.max(88,initial+next.clientX-start)}));const stop=()=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',stop)};document.addEventListener('mousemove',move);document.addEventListener('mouseup',stop)}
  const autoFit=(column:TableColumn<Row>)=>{const longest=Math.max(column.label.length,...processed.slice(0,250).map(row=>String(column.value(row)??'').length));setWidths(value=>({...value,[column.id]:Math.max(96,Math.min(420,longest*8+44))}))}
  const exportXlsx=async()=>{setExporting(true);setExportStatus('');try{const sourceRows=loadExportRows?await loadExportRows():processed;const{utils,writeFile}=await import('xlsx');const exportColumns=visible.filter(column=>column.exportable!==false),exportRows=sourceRows.map(row=>Object.fromEntries(exportColumns.map(column=>[column.label,spreadsheetValue(column.value(row),column.kind)])));const sheet=utils.json_to_sheet(exportRows,{cellDates:true}),book=utils.book_new();utils.book_append_sheet(book,sheet,label.slice(0,31));const context=fold(query).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,30);writeFile(book,`${id}-${new Date().toISOString().slice(0,10)}${context?`-${context}`:''}.xlsx`);setExportStatus(`${sourceRows.length} resultados exportados para XLSX.`)}catch(exportError){setExportStatus(exportError instanceof Error?exportError.message:'Não foi possível preparar a exportação XLSX.')}finally{setExporting(false)}}
  const allShownSelected=Boolean(onSelectionChange&&shown.length&&shown.every(row=>selected.includes(rowKey(row))))
  return <section className="table-standard card overflow-visible" aria-label={label}>
    <div className="print-table-heading hidden"><h2>{label}</h2><p>Gerado em {new Date().toLocaleString('pt-PT')} · {processed.length} resultados · {Object.values(filters).filter(hasFilterValue).length} filtros por coluna{query?` · Pesquisa: ${query}`:''}</p></div>
    <div className="table-tools flex flex-wrap items-center gap-2 border-b border-border p-3"><label className="relative min-w-52 flex-1"><span className="sr-only">Pesquisar em {label}</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} className="control w-full px-3 pr-10 text-sm" placeholder="Pesquisar em todas as colunas…"/>{query&&<button type="button" onClick={()=>setQuery('')} aria-label="Limpar pesquisa" className="absolute right-1 top-1 grid size-8 place-items-center rounded">×</button>}</label>
      <button type="button" onClick={()=>{setFilters({});setQuery('');setPage(1)}} className="control px-3 text-sm font-semibold">Limpar filtros</button>
      <div><button ref={columnsButton} type="button" aria-expanded={columnsOpen} onClick={()=>setColumnsOpen(value=>!value)} className="control px-3 text-sm font-semibold">Colunas · {visible.length}/{columns.length}</button>{columnsOpen&&<div ref={columnsPanel} role="dialog" aria-label={`Colunas visíveis em ${label}`} style={columnsStyle} onKeyDown={cyclePanelFocus} className="fixed z-[120] max-h-[min(20rem,calc(100dvh-1rem))] overflow-auto rounded-xl border border-border bg-surface p-3 shadow-raised"><div className="mb-2 flex gap-3"><button type="button" onClick={()=>setHidden([])} className="min-h-11 text-xs font-semibold text-primary">Mostrar todas</button><button type="button" onClick={()=>{setHidden([]);setOrder(columns.map(column=>column.id));setWidths({})}} className="min-h-11 text-xs font-semibold text-secondary">Repor predefinição</button></div>{ordered.map(column=><label key={column.id} className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={column.essential||!hidden.includes(column.id)} disabled={column.essential} onChange={event=>setHidden(current=>event.target.checked?current.filter(item=>item!==column.id):[...current,column.id])}/>{column.label}</label>)}</div>}</div>
      <button type="button" disabled={exporting} onClick={()=>void exportXlsx()} className="control px-3 text-sm font-semibold disabled:opacity-50">{exporting?'A preparar XLSX…':'XLSX'}</button><button type="button" onClick={()=>window.print()} className="control px-3 text-sm font-semibold">Imprimir / PDF</button>
    </div>
    {exportStatus&&<p role="status" className="border-b border-border px-3 py-2 text-xs text-text-secondary">{exportStatus}</p>}
    <div className="px-3 py-2 text-xs text-text-secondary" role="status">{updating?'A actualizar… · ':''}{processed.length} resultados de {rows.length}{selected.length?` · ${selected.length} seleccionados`:''}</div>
    <div className="scrollbar-thin max-h-[42rem] overflow-auto overscroll-contain"><table className="w-full min-w-max border-separate border-spacing-0 text-left text-sm"><caption className="sr-only">{label}</caption><thead className="sticky top-0 z-30 bg-surface"><tr>{onSelectionChange&&<th style={{width:48,minWidth:48}} className="sticky left-0 z-50 border-b border-border bg-surface px-3 py-3"><input type="checkbox" aria-label="Seleccionar linhas visíveis" checked={allShownSelected} onChange={event=>onSelectionChange(event.target.checked?[...new Set([...selected,...shown.map(rowKey)])]:selected.filter(key=>!shown.some(row=>rowKey(row)===key)))}/></th>}{visible.map((column,index)=>{const sticky=column.sticky||index===0,width=widths[column.id]??column.width??160,sortIndex=sorts.findIndex(item=>item.id===column.id);return <th key={column.id} draggable={!sticky} onDragStart={()=>{draggedColumn.current=column.id}} onDragOver={event=>event.preventDefault()} onDrop={()=>moveColumn(column.id)} style={{width,minWidth:width,left:sticky?stickyOffset(index):undefined}} aria-sort={sortIndex>=0?(sorts[sortIndex].direction==='asc'?'ascending':'descending'):'none'} className={`relative border-b border-border bg-surface px-3 py-2 align-bottom ${sticky?'sticky z-40 shadow-[2px_0_3px_-3px_rgba(0,0,0,.35)]':'cursor-grab'}`}><button type="button" disabled={column.sortable===false} onClick={event=>toggleSort(column,event.shiftKey)} className="flex min-h-8 w-full items-center gap-2 font-semibold disabled:cursor-default"><span>{column.label}</span>{sortIndex>=0&&<span aria-hidden="true">{sorts[sortIndex].direction==='asc'?'↑':'↓'}{sorts.length>1?sortIndex+1:''}</span>}</button>{column.filterable!==false&&column.searchable!==false&&<div className="relative" data-filter-panel={column.id}><button ref={node=>{filterButtons.current[column.id]=node}} type="button" aria-expanded={openFilter===column.id} onClick={()=>setOpenFilter(current=>current===column.id?null:column.id)} className={`mt-1 min-h-8 w-full rounded border px-2 text-left text-xs ${hasFilter(column.id)?'border-secondary bg-secondary-soft text-secondary':'border-border bg-background text-text-secondary'}`}>{hasFilter(column.id)?'Filtro activo':'Filtrar…'}</button>{openFilter===column.id&&<FilterPanel column={column} value={filters[column.id]??{}} onChange={next=>{setFilters(current=>({...current,[column.id]:next}));setPage(1)}} onClose={()=>{setOpenFilter(null);filterButtons.current[column.id]?.focus()}}/>}</div>}<span role="separator" aria-label={`Redimensionar ${column.label}`} onMouseDown={event=>resize(event,column)} onDoubleClick={()=>autoFit(column)} className="absolute inset-y-0 right-0 w-2 cursor-col-resize hover:bg-secondary/20"/></th>})}</tr></thead>
      <tbody>{!loading&&shown.map(row=>{const key=rowKey(row),isSelected=selected.includes(key);return <tr key={key} tabIndex={0} onDoubleClick={()=>onRowDoubleClick?.(row)} onKeyDown={event=>{if(event.key==='Enter'&&onRowDoubleClick){event.preventDefault();onRowDoubleClick(row);return}if(event.key!=='ArrowDown'&&event.key!=='ArrowUp')return;const sibling=event.key==='ArrowDown'?event.currentTarget.nextElementSibling:event.currentTarget.previousElementSibling;if(sibling instanceof HTMLElement){event.preventDefault();sibling.focus()}}} className={`${isSelected?'bg-secondary-soft outline outline-1 outline-secondary':'hover:bg-surface-subtle'} ${onRowDoubleClick?'cursor-pointer':''} focus-visible:outline focus-visible:outline-2 focus-visible:outline-secondary`} aria-label={onRowDoubleClick?`Abrir ${key}`:undefined}>{onSelectionChange&&<td style={{width:48,minWidth:48}} className="sticky left-0 z-20 border-b border-border bg-inherit px-3 py-3"><input type="checkbox" aria-label={`Seleccionar ${key}`} checked={isSelected} onChange={()=>onSelectionChange(isSelected?selected.filter(item=>item!==key):[...selected,key])}/></td>}{visible.map((column,index)=>{const sticky=column.sticky||index===0,width=widths[column.id]??column.width??160;return <td key={column.id} style={{width,minWidth:width,maxWidth:width,left:sticky?stickyOffset(index):undefined}} className={`border-b border-border bg-inherit px-3 py-3 ${column.align==='right'?'text-right tabular-nums':column.align==='center'?'text-center':''} ${sticky?'sticky z-10 shadow-[2px_0_3px_-3px_rgba(0,0,0,.35)]':''}`}>{column.render?column.render(row):String(column.value(row)??'—')}</td>})}</tr>})}</tbody></table>
      {loading&&<div role="status" className="space-y-2 p-4">{Array.from({length:5},(_,index)=><div key={index} className="h-10 animate-pulse rounded bg-surface-subtle"/>)}</div>}{error&&<div role="alert" className="m-4 rounded-lg bg-danger-soft p-4 text-sm text-danger">{error}{onRetry&&<button type="button" onClick={onRetry} className="ml-3 font-semibold underline">Tentar novamente</button>}</div>}{!loading&&!error&&!processed.length&&<div className="p-8 text-center text-sm text-text-secondary">{rows.length?'Os filtros não encontraram resultados.':emptyMessage}</div>}
    </div>
    <div className="table-pagination flex flex-wrap items-center justify-between gap-3 border-t border-border p-3 text-sm"><label>Linhas <select value={pageSize} onChange={event=>{setPageSize(event.target.value==='all'?'all':Number(event.target.value) as 10|20|50);setPage(1)}} className="control ml-2 min-h-9 px-2"><option value={10}>10</option><option value={20}>20</option><option value={50}>50</option>{rows.length<=500&&<option value="all">Todas</option>}</select></label><span>{processed.length?`${pageSize==='all'?1:(validPage-1)*pageSize+1}–${pageSize==='all'?processed.length:Math.min(validPage*pageSize,processed.length)} de ${processed.length}`:'0 resultados'}</span><div className="flex gap-2"><button type="button" disabled={validPage<=1} onClick={()=>setPage(value=>value-1)} className="control min-h-9 px-3 disabled:opacity-40">Anterior</button><button type="button" disabled={validPage>=pageCount} onClick={()=>setPage(value=>value+1)} className="control min-h-9 px-3 disabled:opacity-40">Seguinte</button></div></div>
  </section>
}
