-- Recalcula de forma centralizada todos os campos dependentes do preço.
create or replace function private.prepare_work_entry()
returns trigger language plpgsql set search_path='' as $$
declare is_recalculation boolean:=coalesce(current_setting('app.pricing_recalculation',true),'')='on';is_import_reconciliation boolean:=coalesce(current_setting('app.import_reconciliation',true),'')='on';society_only_operator_change boolean:=false;
begin
 if tg_op='INSERT' then
  if(new.imported_hourly_rate is not null or new.calculated_hourly_rate is not null or new.effective_hourly_rate is not null or new.calculated_amount is not null or new.effective_amount is not null or new.imported_amount is not null or new.manual_amount is not null or new.is_invoiced or new.is_paid)and not(private.has_scope_access(new.firm_id,new.billing_entity_id,new.client_id,new.matter_id,'edit')and private.can_view_billing_financials(new.firm_id,new.billing_entity_id))then raise exception 'financial values require edit and financial permission for the Society' using errcode='42501';end if;
  new.imported_duration_minutes:=coalesce(new.imported_duration_minutes,case when new.source_type in('xlsx','csv')then new.duration_minutes end);new.effective_hourly_rate:=coalesce(new.effective_hourly_rate,new.specific_hourly_rate,new.calculated_hourly_rate,new.imported_hourly_rate);new.calculated_amount:=coalesce(new.calculated_amount,round((new.duration_minutes::numeric/60)*new.calculated_hourly_rate,2));new.effective_amount:=coalesce(new.effective_amount,new.imported_amount,new.calculated_amount,round((new.duration_minutes::numeric/60)*new.effective_hourly_rate,2));return new;
 end if;
 society_only_operator_change:=new.billing_entity_id is distinct from old.billing_entity_id and private.has_firm_role(old.firm_id,array['operator']) and private.has_scope_access(old.firm_id,old.billing_entity_id,old.client_id,old.matter_id,'edit') and private.has_current_override(old.id,'billing_entity_id',to_jsonb(new.billing_entity_id)) and new.imported_hourly_rate is not distinct from old.imported_hourly_rate and new.calculated_hourly_rate is not distinct from old.calculated_hourly_rate and new.effective_hourly_rate is not distinct from old.effective_hourly_rate and new.calculated_amount is not distinct from old.calculated_amount and new.effective_amount is not distinct from old.effective_amount and new.effective_discount_amount is not distinct from old.effective_discount_amount and new.currency is not distinct from old.currency and new.is_invoiced is not distinct from old.is_invoiced and new.invoice_date is not distinct from old.invoice_date and new.is_paid is not distinct from old.is_paid;
 if(new.billing_entity_id is distinct from old.billing_entity_id or new.imported_hourly_rate is distinct from old.imported_hourly_rate or new.calculated_hourly_rate is distinct from old.calculated_hourly_rate or new.effective_hourly_rate is distinct from old.effective_hourly_rate or new.calculated_amount is distinct from old.calculated_amount or new.effective_amount is distinct from old.effective_amount or new.effective_discount_amount is distinct from old.effective_discount_amount or new.currency is distinct from old.currency or new.is_invoiced is distinct from old.is_invoiced or new.invoice_date is distinct from old.invoice_date or new.is_paid is distinct from old.is_paid)and not is_recalculation and not society_only_operator_change and not(private.has_scope_access(old.firm_id,old.billing_entity_id,old.client_id,old.matter_id,'edit')and private.can_view_billing_financials(old.firm_id,old.billing_entity_id)and(new.billing_entity_id is not distinct from old.billing_entity_id or private.can_view_billing_financials(old.firm_id,new.billing_entity_id)))then raise exception 'financial fields require edit and financial permission for the Society' using errcode='42501';end if;
 if new.duration_minutes is distinct from old.duration_minutes and not is_recalculation and not is_import_reconciliation and not private.has_current_override(old.id,'duration_minutes',to_jsonb(new.duration_minutes))then raise exception 'duration_minutes requires a matching manual override';end if;
 if new.effective_hourly_rate is distinct from old.effective_hourly_rate and not is_recalculation and not is_import_reconciliation and not private.has_current_override(old.id,'effective_hourly_rate',to_jsonb(new.effective_hourly_rate))then raise exception 'effective_hourly_rate requires a matching manual override';end if;
 if new.effective_discount_amount is distinct from old.effective_discount_amount and not is_recalculation and not is_import_reconciliation and not private.has_current_override(old.id,'effective_discount_amount',to_jsonb(new.effective_discount_amount))then raise exception 'effective_discount_amount requires a matching manual override';end if;
 if new.effective_amount is distinct from old.effective_amount and not is_recalculation and not is_import_reconciliation and not private.has_current_override(old.id,'effective_amount',to_jsonb(new.effective_amount))then raise exception 'effective_amount requires a matching manual override';end if;
 if new.billing_entity_id is distinct from old.billing_entity_id and not is_import_reconciliation and not private.has_current_override(old.id,'billing_entity_id',to_jsonb(new.billing_entity_id))then raise exception 'billing_entity_id requires a matching manual override';end if;
 if new.is_invoiced is distinct from old.is_invoiced and not is_import_reconciliation and not private.has_current_override(old.id,'is_invoiced',to_jsonb(new.is_invoiced))then raise exception 'is_invoiced requires a matching manual override';end if;
 if new.is_paid is distinct from old.is_paid and not is_import_reconciliation and not private.has_current_override(old.id,'is_paid',to_jsonb(new.is_paid))then raise exception 'is_paid requires a matching manual override';end if;return new;
end;$$;

create or replace function public.update_work_entry_full(p_work_entry_id uuid,p_values jsonb,p_reason text)
returns void language plpgsql security invoker set search_path='' as $$
declare previous public.work_entries%rowtype;current_entry public.work_entries%rowtype;operator_requires_reason boolean;rate_changed boolean;dimensions_changed boolean;discount_changed boolean;pricing record;base_amount numeric;discount_amount numeric;final_amount numeric;
begin
 select * into previous from public.work_entries where id=p_work_entry_id;
 select coalesce(bool_or(role='operator'),false) into operator_requires_reason from public.firm_members where firm_id=previous.firm_id and user_id=auth.uid() and active;
 if operator_requires_reason and btrim(coalesce(p_reason,''))=''then raise exception 'override reason required';end if;
 rate_changed:=nullif(p_values->>'effective_hourly_rate','')::numeric is distinct from previous.effective_hourly_rate;
 discount_changed:=nullif(p_values->>'effective_discount_amount','')::numeric is distinct from previous.effective_discount_amount or nullif(p_values->>'discount_percentage','')::numeric is distinct from previous.discount_percentage;
 dimensions_changed:=(p_values->>'work_date')::date is distinct from previous.work_date or nullif(p_values->>'client_profile_id','')::uuid is distinct from previous.client_profile_id or nullif(p_values->>'matter_id','')::uuid is distinct from previous.matter_id or nullif(p_values->>'professional_id','')::uuid is distinct from previous.professional_id or nullif(p_values->>'billing_entity_id','')::uuid is distinct from previous.billing_entity_id;
 if rate_changed then p_values:=jsonb_set(p_values,'{charge_type}',to_jsonb('hourly'::text),true);end if;
 perform private.update_work_entry_full(p_work_entry_id,p_values,p_reason);
 select * into current_entry from public.work_entries where id=p_work_entry_id;
 perform set_config('app.pricing_recalculation','on',true);
 if dimensions_changed and not rate_changed then
  select * into pricing from private.calculate_work_entry(p_work_entry_id);
  update public.work_entries set pricing_rule_id=pricing.pricing_rule_id,charge_type=pricing.charge_type,calculated_hourly_rate=pricing.hourly_rate,effective_hourly_rate=pricing.hourly_rate,pre_discount_amount=pricing.pre_discount_amount,calculated_discount_amount=pricing.discount_amount,effective_discount_amount=pricing.discount_amount,calculated_amount=pricing.proposed_amount,effective_amount=pricing.proposed_amount,currency=coalesce(pricing.currency,currency),calculation_version=calculation_version+1,last_calculated_at=now(),updated_by=auth.uid() where id=p_work_entry_id;
 elsif rate_changed or discount_changed or current_entry.duration_minutes is distinct from previous.duration_minutes or current_entry.charge_type is distinct from previous.charge_type then
  base_amount:=case when current_entry.charge_type in('free','non_billable')then 0 when current_entry.charge_type in('fixed','retainer','hour_package','per_act','manual_negotiated')then coalesce(current_entry.pre_discount_amount,current_entry.effective_amount+coalesce(current_entry.effective_discount_amount,0)) when current_entry.effective_hourly_rate is null then null else round(current_entry.effective_hourly_rate*current_entry.duration_minutes::numeric/60,2)end;
  discount_amount:=case when current_entry.discount_percentage is not null then round(coalesce(base_amount,0)*current_entry.discount_percentage/100,2)else coalesce(current_entry.effective_discount_amount,0)end;
  final_amount:=case when base_amount is null then null else round(greatest(0,base_amount-discount_amount),2)end;
  update public.work_entries set pre_discount_amount=base_amount,calculated_discount_amount=discount_amount,effective_discount_amount=discount_amount,calculated_amount=final_amount,effective_amount=final_amount,calculation_version=calculation_version+1,last_calculated_at=now(),updated_by=auth.uid() where id=p_work_entry_id;
 end if;
end;$$;

revoke all on function private.prepare_work_entry() from public,anon,authenticated;
revoke all on function public.update_work_entry_full(uuid,jsonb,text) from public,anon;
grant execute on function public.update_work_entry_full(uuid,jsonb,text) to authenticated;
notify pgrst,'reload schema';
