import {fireEvent,render,screen,waitFor} from '@testing-library/react'
import {beforeEach,expect,test,vi} from 'vitest'
import {PaymentDialog} from './PaymentDialog'
import {paymentAmount,paymentCounts,type PaymentItem} from './payments'
const rpc=vi.hoisted(()=>vi.fn())
vi.mock('../../lib/supabase',()=>({supabase:{rpc}}))
const item:PaymentItem={id:'note',category:'note',client_id:'client',client_name:'Cliente sintético',society_name:'Sociedade teste',title:'NH-TESTE',date:'2026-10-01',currency:'EUR',total:123,received:10,deducted:20,remaining:93,token:'v1-10',can_pay:true,can_edit:true,status:'Por receber',revision:1}
beforeEach(()=>{rpc.mockReset();rpc.mockResolvedValue({data:{item,items:[],receipts:[]},error:null})})
test('valida cêntimos, vírgula e montantes inválidos',()=>{expect(paymentAmount('12,34')).toBe(12.34);for(const value of ['','0','-1','1.001','NaN','1e3','Infinity','1,2.3'])expect(paymentAmount(value)).toBeNull();expect(paymentCounts([item,{...item,category:'work'}])).toEqual({unbilled:0,work:1,note:1,retainer:0})})
async function fill(){await screen.findByLabelText('Valor recebido');fireEvent.change(screen.getByLabelText('Valor recebido'),{target:{value:'20,00'}});fireEvent.change(screen.getByLabelText('Referência / motivo'),{target:{value:'Transferência teste'}});fireEvent.click(screen.getByRole('checkbox'))}
test('cancelar não escreve nem emite documentos',async()=>{const close=vi.fn();render(<PaymentDialog item={item} onClose={close} onSaved={vi.fn()} onEdit={vi.fn()}/>);await screen.findByLabelText('Valor recebido');fireEvent.click(screen.getByRole('button',{name:'Cancelar'}));expect(close).toHaveBeenCalledOnce();expect(rpc).toHaveBeenCalledTimes(1)})
test('clique duplo envia um recebimento parcial, separado da provisão',async()=>{let resolve:(value:unknown)=>void=()=>{};const saved=vi.fn();render(<PaymentDialog item={item} onClose={vi.fn()} onSaved={saved} onEdit={vi.fn()}/>);await fill();rpc.mockImplementation(()=>new Promise(done=>{resolve=done}));const button=screen.getByRole('button',{name:'Registar pagamento'});fireEvent.click(button);fireEvent.click(button);expect(rpc.mock.calls.filter(call=>call[0]==='record_pending_payment')).toHaveLength(1);expect(rpc).toHaveBeenLastCalledWith('record_pending_payment',expect.objectContaining({p_amount:20,p_expected_token:'v1-10',p_reference:'Transferência teste'}));resolve({data:{},error:null});await waitFor(()=>expect(saved).toHaveBeenCalledOnce())})
test('reenvio após falha conserva o pedido e o saldo esperado',async()=>{const saved=vi.fn();render(<PaymentDialog item={item} onClose={vi.fn()} onSaved={saved} onEdit={vi.fn()}/>);await fill();rpc.mockResolvedValueOnce({error:{message:'Resposta interrompida'}});fireEvent.click(screen.getByRole('button',{name:'Registar pagamento'}));expect(await screen.findByRole('alert')).toHaveTextContent('Resposta interrompida');const first=rpc.mock.calls.at(-1)![1];rpc.mockResolvedValueOnce({data:{replayed:true},error:null});fireEvent.click(screen.getByRole('button',{name:'Registar pagamento'}));await waitFor(()=>expect(saved).toHaveBeenCalledOnce());expect(rpc.mock.calls.at(-1)![1]).toEqual(first)})
test('não facturado abre a ficha e nunca oferece pagar',async()=>{rpc.mockResolvedValue({data:{item:{...item,category:'unbilled',can_pay:false,status:'Por facturar'},items:[],receipts:[]}});const edit=vi.fn();render(<PaymentDialog item={{...item,category:'unbilled'}} onClose={vi.fn()} onSaved={vi.fn()} onEdit={edit}/>);fireEvent.click(await screen.findByRole('button',{name:'Abrir ficha para facturar'}));expect(edit).toHaveBeenCalledOnce();expect(screen.queryByRole('button',{name:'Registar pagamento'})).not.toBeInTheDocument();expect(rpc).toHaveBeenCalledTimes(1)})
test('rejeita excesso e não permite enviar sem confirmação',async()=>{render(<PaymentDialog item={item} onClose={vi.fn()} onSaved={vi.fn()} onEdit={vi.fn()}/>);await screen.findByLabelText('Valor recebido');expect(screen.getByRole('button',{name:'Registar pagamento'})).toBeDisabled();await fill();fireEvent.change(screen.getByLabelText('Valor recebido'),{target:{value:'94'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Registar pagamento'}));expect(await screen.findByRole('alert')).toHaveTextContent('Confirme');expect(rpc).toHaveBeenCalledTimes(1)})
