import { useCallback,useEffect,useMemo,useState } from 'react'
import { supabase } from '../../lib/supabase'
import { EditWorkEntryModal } from '../work-entries/EditWorkEntryModal'
import { allocatedAmounts } from './fixedFeeAllocation'
import { FixedFeeNoteActions } from './FixedFeeNoteActions'

type Job={id:string;firm_id:string;client_id:string;billing_entity_id:string|null;title:string;description:string|null;agreed_amount:number;currency:string;vat_rate:number|null;provision_applied?:number;status:'not_started'|'open'|'completed'|'cancelled';is_invoiced:boolean;invoice_date:string|null;is_paid:boolean}
type Entry={id:string;work_date:string;activity_description:string;duration_minutes:number;billing_scope:string;fixed_fee_job_id:string|null;is_invoiced:boolean;is_paid:boolean;billing_entity_id:string|null}
type Society={id:string;name:string;default_vat_rate:number}
type Props={firmId:string;clientId:string;readOnly:boolean;onRequestEdit:()=>void}
const money=new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'})
const totalWithVat=(amount:number,rate:number)=>(Math.round(amount*100)+Math.round(Math.round(amount*100)*rate/100))/100
const duration=(minutes:number)=>`${Math.floor(minutes/60)} h${minutes%60?` ${minutes%60} min`:''}`
const empty={title:'',description:'',agreed_amount:'',billing_entity_id:'',status:'not_started' as Job['status'],is_invoiced:false,invoice_date:'',is_paid:false}
const unavailable=(message:string)=>/fixed_fee_jobs|schema cache|PGRST205|42P01/i.test(message)
const phaseLabel:Record<Job['status'],string>={not_started:'Por iniciar',open:'Em curso',completed:'Terminado',cancelled:'Cancelado'}
export function ClientFixedFeePanel({firmId,clientId,readOnly,onRequestEdit}:Props){
 const [jobs,setJobs]=useState<Job[]>([]),[entries,setEntries]=useState<Entry[]>([]),[societies,setSocieties]=useState<Society[]>([])
 const [selected,setSelected]=useState<string|null>(null),[draft,setDraft]=useState(empty),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[schemaPending,setSchemaPending]=useState(false),[entryToEdit,setEntryToEdit]=useState<string|null>(null),[selectedEntryIds,setSelectedEntryIds]=useState<Set<string>>(new Set())
 const [phaseFilter,setPhaseFilter]=useState<'all'|Job['status']>('all')
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);const [j,e,s]=await Promise.all([
  supabase.from('fixed_fee_jobs').select('id,firm_id,client_id,billing_entity_id,title,description,agreed_amount,currency,vat_rate,status,is_invoiced,invoice_date,is_paid').eq('client_id',clientId).order('created_at',{ascending:false}),
  supabase.from('work_entries').select('id,work_date,activity_description,duration_minutes,billing_scope,fixed_fee_job_id,is_invoiced,is_paid,billing_entity_id').eq('client_id',clientId).order('work_date',{ascending:false}),
  supabase.from('billing_entities').select('id,name,default_vat_rate').eq('firm_id',firmId).eq('active',true).order('name'),
 ]);setLoading(false);const failure=j.error??e.error??s.error;if(failure){if(unavailable(failure.message)){setSchemaPending(true);setJobs([]);setEntries([]);setSocieties((s.data??[]) as Society[]);setSelected(null);setError('O módulo de trabalhos a preço fixo não está disponível neste ambiente. Nenhum trabalho pode ser criado ou alterado até a base de dados estar actualizada.');return}setError(failure.message);return}const applied=await supabase.rpc('get_fixed_fee_provision_totals');if(applied.error){setError(applied.error.message);return}const totals=new Map(((applied.data??[]) as {job_id:string;gross_applied:number}[]).map(row=>[row.job_id,Number(row.gross_applied)]));setSchemaPending(false);setError('');setJobs(((j.data??[]) as Job[]).map(job=>({...job,provision_applied:totals.get(job.id)??0})));setEntries((e.data??[]) as Entry[]);setSocieties((s.data??[]) as Society[])},[clientId,firmId])
 useEffect(()=>{void load()},[load])
 const visibleJobs=jobs.filter(job=>phaseFilter==='all'||job.status===phaseFilter)
 const current=visibleJobs.find(job=>job.id===selected)??null
 const linked=useMemo(()=>entries.filter(entry=>entry.fixed_fee_job_id===selected),[entries,selected])
 const minutes=linked.reduce((sum,entry)=>sum+entry.duration_minutes,0)
 const allocation=useMemo(()=>allocatedAmounts(current?.agreed_amount??0,linked),[current?.agreed_amount,linked])
 const candidates=useMemo(()=>entries.filter(entry=>entry.billing_scope==='standard'&&!entry.is_invoiced&&!entry.is_paid&&(current?.billing_entity_id==null||entry.billing_entity_id===current.billing_entity_id)),[entries,current])
 function edit(job:Job){setSelected(job.id);setDraft({title:job.title,description:job.description??'',agreed_amount:String(job.agreed_amount),billing_entity_id:job.billing_entity_id??'',status:job.status,is_invoiced:job.is_invoiced,invoice_date:job.invoice_date??'',is_paid:job.is_paid});setEditing(true);setError('')}
 function create(){setSelected(null);setDraft({...empty});setEditing(true);setError('')}
 async function finish(job:Job){if(job.status!=='open'||!supabase||schemaPending)return;setBusy(true);setError('');const result=await supabase.from('fixed_fee_jobs').update({status:'completed'}).eq('id',job.id);setBusy(false);if(result.error){setError(result.error.message);return}await load();window.dispatchEvent(new Event('entity-record-saved'))}
 async function save(){if(!supabase||schemaPending)return;const amount=Number(draft.agreed_amount.replace(',','.'));if(!draft.title.trim()||!Number.isFinite(amount)||amount<0){setError('Indique o assunto e um preço válido.');return}if(draft.is_invoiced&&!draft.billing_entity_id){setError('Escolha a sociedade antes de facturar; a taxa de IVA do trabalho fica fixada nessa altura.');return}if(draft.is_invoiced&&!draft.invoice_date){setError('Indique a data da factura.');return}setBusy(true);setError('');const values={title:draft.title.trim(),description:draft.description.trim()||null,agreed_amount:amount,billing_entity_id:draft.billing_entity_id||null,is_invoiced:draft.is_invoiced,invoice_date:draft.is_invoiced?draft.invoice_date:null,is_paid:draft.is_paid};const result=selected?await supabase.from('fixed_fee_jobs').update(values).eq('id',selected):await supabase.from('fixed_fee_jobs').insert({...values,firm_id:firmId,client_id:clientId,currency:'EUR',vat_rate:null,status:'not_started',created_by:(await supabase.auth.getUser()).data.user?.id}).select('id').single();setBusy(false);if(result.error){setError(result.error.message);return}setEditing(false);setSelected(selected??(result.data as {id:string}).id);await load();window.dispatchEvent(new Event('entity-record-saved'))}
 async function assign(entryId:string,jobId:string|null){if(!supabase||schemaPending)return;setBusy(true);setError('');const result=await supabase.rpc('assign_work_entry_fixed_fee',{p_work_entry_id:entryId,p_fixed_fee_job_id:jobId,p_reason:'Associação na ficha do cliente'});setBusy(false);if(result.error){setError(result.error.message);return}await load();window.dispatchEvent(new Event('entity-record-saved'))}
 async function assignSelected(){if(!current||!selectedEntryIds.size||schemaPending||!supabase)return;setBusy(true);setError('');let done=0;for(const id of selectedEntryIds){const result=await supabase.rpc('assign_work_entry_fixed_fee',{p_work_entry_id:id,p_fixed_fee_job_id:current.id,p_reason:'Associação na ficha do cliente'});if(result.error){setError(`${done} registos associados. ${result.error.message}`);break}done++}setBusy(false);setSelectedEntryIds(new Set());await load();window.dispatchEvent(new Event('entity-record-saved'))}
 return <section className="mt-6 space-y-4 rounded-xl border border-border p-4" aria-labelledby="fixed-fee-title">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 id="fixed-fee-title" className="font-display text-xl font-semibold">Trabalhos a preço fixo</h3><p className="mt-1 text-sm text-text-secondary">Um preço por assunto. Os registos associados contam horas, sem acrescentar honorários ao valor acordado.</p></div><button type="button" disabled={schemaPending} className="min-h-10 rounded-lg bg-primary px-4 font-semibold text-surface disabled:opacity-50" onClick={()=>{if(readOnly){onRequestEdit();return}create()}}>{readOnly?'Editar ficha':'Novo trabalho'}</button></div>
  {loading&&<p role="status" className="text-sm">A carregar trabalhos…</p>}
  {error&&<p role="alert" className="rounded-lg border border-warning bg-warning-soft p-3 text-sm">{error}</p>}
  {!loading&&!error&&<><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-text-secondary">{jobs.filter(job=>job.status==='not_started').length} por iniciar · {jobs.filter(job=>job.status==='open').length} em curso · {jobs.filter(job=>job.status==='completed').length} terminados</p><label className="text-sm font-semibold">Mostrar <select className="control ml-2 min-h-9 px-2" value={phaseFilter} onChange={event=>{setPhaseFilter(event.target.value as typeof phaseFilter);setSelected(null)}}><option value="all">Todos</option><option value="not_started">Por iniciar</option><option value="open">Em curso</option><option value="completed">Terminados</option><option value="cancelled">Cancelados</option></select></label></div><div className="grid gap-2">{visibleJobs.map(job=>{const used=entries.filter(entry=>entry.fixed_fee_job_id===job.id).reduce((sum,entry)=>sum+entry.duration_minutes,0);return <button key={job.id} type="button" className={`rounded-xl border p-3 text-left ${selected===job.id?'border-primary bg-primary/10':'border-border bg-surface'}`} onClick={()=>{setSelected(job.id);setSelectedEntryIds(new Set())}}><span className="flex flex-wrap items-center justify-between gap-2"><strong>{job.title}</strong><span className={`font-semibold ${job.agreed_amount>0?'financial-value':'text-warning'}`}>{job.agreed_amount>0?money.format(job.agreed_amount):'Preço por definir'}</span></span><span className="mt-2 flex flex-wrap gap-2 text-xs font-semibold"><span className={`rounded-md px-2 py-1 ${job.status==='completed'?'bg-success-soft text-success':job.status==='cancelled'?'bg-surface-subtle text-text-secondary':'bg-primary/10 text-primary'}`}>Fase: {phaseLabel[job.status]}</span><span className={`rounded-md px-2 py-1 ${job.is_invoiced?'bg-success-soft text-success':'bg-warning-soft text-warning'}`}>Facturação: {job.is_invoiced?'Facturado':'Por facturar'}</span><span className={`rounded-md px-2 py-1 ${job.is_paid?'bg-success-soft text-success':'bg-danger-soft text-danger'}`}>Pagamento: {job.is_paid?'Pago':Number(job.provision_applied)>0?<><span>Provisão aplicada </span><span className="financial-value">{money.format(Number(job.provision_applied))}</span></>:job.is_invoiced?'Por receber':'Não pago'}</span></span><span className="mt-2 block text-xs text-text-secondary">{duration(used)} registadas · {job.agreed_amount<=0?'Defina o preço antes de associar registos':used?<><span className="financial-value">{money.format(job.agreed_amount*60/used)}</span><span>/h</span></>:'Valor médio/hora após o primeiro registo'}</span></button>})}{!jobs.length?<p className="text-sm text-text-secondary">Ainda não há trabalhos a preço fixo para este cliente.</p>:!visibleJobs.length?<p className="text-sm text-text-secondary">Não há trabalhos nesta fase.</p>:null}</div>
  {current&&<div className="rounded-xl border border-primary/30 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h4 className="font-semibold">{current.title}</h4>{current.description&&<p className="text-sm text-text-secondary">{current.description}</p>}</div>{readOnly?<button type="button" className="control min-h-9 px-3 text-sm" onClick={onRequestEdit}>Gerir registos</button>:<button type="button" className="control min-h-9 px-3 text-sm" onClick={()=>edit(current)}>Editar trabalho</button>}</div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><p>Honorários sem IVA: <strong className="financial-value">{money.format(current.agreed_amount)}</strong></p><p>Horas: <strong>{duration(minutes)}</strong></p><p>Valor médio/hora: <strong className="financial-value">{minutes?money.format(current.agreed_amount*60/minutes):'—'}</strong></p>{current.vat_rate!==null&&<p>Total com IVA ({current.vat_rate}%): <strong className="financial-value">{money.format(totalWithVat(current.agreed_amount,current.vat_rate))}</strong></p>}</div><p className="mt-2 text-xs font-semibold">Fase: {phaseLabel[current.status]} · {current.is_paid?'Pago':current.is_invoiced?'Facturado por receber':'Por facturar'}{current.invoice_date?` · factura de ${current.invoice_date}`:''}</p>
   {!readOnly&&current.status==='open'&&<button type="button" className="control mt-3 min-h-9 px-3 text-sm font-semibold" disabled={busy} onClick={()=>void finish(current)}>Marcar como terminado</button>}
   {current.status==='not_started'&&<p className="mt-2 text-xs text-text-secondary">A fase passa automaticamente a «Em curso» quando associar o primeiro registo.</p>}
   {!schemaPending&&current.billing_entity_id&&<FixedFeeNoteActions key={current.id} job={current} societyName={societies.find(society=>society.id===current.billing_entity_id)?.name??''} readOnly={readOnly}/>}
   <h5 className="mt-4 border-t border-border pt-3 text-sm font-semibold">Registos associados</h5><div className="mt-2 space-y-1">{linked.map(entry=><div key={entry.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-surface-subtle px-3 py-2 text-sm">{schemaPending?<span className="text-left font-medium">{entry.work_date} · {entry.activity_description}</span>:<button type="button" className="text-left font-medium text-primary underline" onClick={()=>setEntryToEdit(entry.id)}>{entry.work_date} · {entry.activity_description}</button>}<span>{duration(entry.duration_minutes)} · <span className="financial-value">{allocation.has(entry.id)?money.format(allocation.get(entry.id)!):'—'}</span> imputados</span>{!readOnly&&<button type="button" disabled={busy} className="text-xs text-danger underline" onClick={()=>void assign(entry.id,null)}>Retirar</button>}</div>)}{!linked.length&&<p className="text-sm text-text-secondary">Ainda sem registos associados.</p>}</div>
   {!readOnly&&<div className="mt-4"><h5 className="text-sm font-semibold">Adicionar registos deste cliente</h5><p className="mt-1 text-xs text-text-secondary">{current.agreed_amount>0?'Seleccione vários registos. Os valores que tenham deixam de contar individualmente; as horas passam a integrar este trabalho.':'Edite o trabalho e defina primeiro os honorários acordados. Só depois poderá associar registos.'}</p><div className="mt-2 max-h-52 space-y-1 overflow-auto rounded-lg border border-border p-2">{candidates.map(entry=><label key={entry.id} className={`flex items-center gap-2 rounded-md px-2 py-1 text-sm ${current.agreed_amount>0?'cursor-pointer hover:bg-surface-subtle':'cursor-not-allowed opacity-55'}`}><input type="checkbox" disabled={current.agreed_amount<=0} checked={selectedEntryIds.has(entry.id)} onChange={event=>setSelectedEntryIds(current=>{const next=new Set(current);if(event.target.checked)next.add(entry.id);else next.delete(entry.id);return next})}/><span className="min-w-0 flex-1 truncate">{entry.work_date} · {entry.activity_description}</span><span className="shrink-0 tabular-nums">{duration(entry.duration_minutes)}</span></label>)}{!candidates.length&&<p className="p-2 text-sm text-text-secondary">Não há registos por facturar disponíveis para associação.</p>}</div><button type="button" className="mt-2 min-h-10 rounded-lg bg-primary px-4 font-semibold text-surface disabled:opacity-50" disabled={busy||current.agreed_amount<=0||!selectedEntryIds.size} onClick={()=>void assignSelected()}>Associar {selectedEntryIds.size||''} registos</button></div>}
  </div>}</>}
  {editing&&<div role="dialog" aria-modal="true" aria-labelledby="fixed-fee-form-title" className="app-safe-fixed fixed z-[85] grid place-items-center overflow-y-auto bg-navigation/60 p-4"><div className="card w-full max-w-xl space-y-3 p-5"><h3 id="fixed-fee-form-title" className="font-display text-xl font-semibold">{selected?'Editar trabalho':'Novo trabalho a preço fixo'}</h3><label className="block text-sm font-semibold">Assunto<input required maxLength={200} className="control mt-1 w-full px-3" value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label className="block text-sm font-semibold">Honorários acordados antes de IVA (€)<input required type="number" min="0" step="0.01" className="control mt-1 w-full px-3" value={draft.agreed_amount} onChange={event=>setDraft({...draft,agreed_amount:event.target.value})}/></label><label className="block text-sm font-semibold">Sociedade<select className="control mt-1 w-full px-3" value={draft.billing_entity_id} onChange={event=>setDraft({...draft,billing_entity_id:event.target.value})}><option value="">Por atribuir</option>{societies.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm font-semibold">Descrição<textarea className="control mt-1 w-full px-3" value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></label><p className="text-sm text-text-secondary">Fase: {phaseLabel[draft.status]}. O primeiro registo inicia o trabalho; depois pode marcá-lo como terminado na ficha.</p><div className="grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.is_invoiced} onChange={event=>setDraft({...draft,is_invoiced:event.target.checked,is_paid:event.target.checked?draft.is_paid:false,invoice_date:event.target.checked?draft.invoice_date:''})}/>Facturado</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.is_paid} disabled={!draft.is_invoiced} onChange={event=>setDraft({...draft,is_paid:event.target.checked})}/>Pago</label></div>{draft.is_invoiced&&<label className="block text-sm font-semibold">Data da factura<input type="date" required className="control mt-1 w-full px-3" value={draft.invoice_date} onChange={event=>setDraft({...draft,invoice_date:event.target.value})}/></label>}<div className="flex justify-end gap-2 pt-2"><button type="button" className="control min-h-10 px-4" disabled={busy} onClick={()=>setEditing(false)}>Cancelar</button><button type="button" onClick={()=>void save()} className="min-h-10 rounded-lg bg-primary px-4 font-semibold text-surface" disabled={busy}>{busy?'A guardar…':'Guardar'}</button></div></div></div>}
  {entryToEdit&&<EditWorkEntryModal entryId={entryToEdit} onClose={()=>setEntryToEdit(null)} onSaved={()=>{setEntryToEdit(null);void load()}}/>}
 </section>
}
