import { useCallback, useEffect, useRef, useState } from 'react'
import { supabase } from '../../lib/supabase'
import { creditDate, creditKind, creditMoney, type CreditAccount, type CreditDetail } from './credit'
import { saveProvisionNotePdf } from './creditPdf'
import { loadCreditUsage } from './loadCreditUsage'
import { CreditUsageSummary } from './CreditUsageSummary'
import type { CreditUsage } from './creditUsage'
import {CalendarDateInput} from '../../components/CalendarDateInput'
import {todayIso} from '../../utils/date'

const today=todayIso
const button='min-h-11 rounded-lg border border-border px-3 text-sm font-semibold disabled:opacity-40'
type FixedFeeCandidate={job_id:string;title:string;honoraria:number;vat_rate:number;total_with_vat:number;already_applied:number;remaining:number}
const parseMoney=(raw:string)=>Number(raw.replace(',','.'))
export function ClientCreditPanel({clientId,initialAccountId,readOnly=false,onRequestEdit}:{clientId:string;initialAccountId?:string;readOnly?:boolean;onRequestEdit?:()=>void}){
  const [accounts,setAccounts]=useState<CreditAccount[]>([]),[societies,setSocieties]=useState<{id:string;name:string}[]>([])
  const [accountId,setAccountId]=useState(''),[detail,setDetail]=useState<CreditDetail|null>(null)
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const [paymentOpen,setPaymentOpen]=useState(false),[society,setSociety]=useState(''),[currency,setCurrency]=useState('EUR'),[amount,setAmount]=useState(''),[date,setDate]=useState(today),[reference,setReference]=useState('')
  const [candidates,setCandidates]=useState<FixedFeeCandidate[]>([]),[allocations,setAllocations]=useState<Record<string,string>>({}),[candidatesLoading,setCandidatesLoading]=useState(false),[candidateError,setCandidateError]=useState('')
  const [laterOpen,setLaterOpen]=useState(false),[laterCandidates,setLaterCandidates]=useState<FixedFeeCandidate[]>([]),[laterAllocations,setLaterAllocations]=useState<Record<string,string>>({}),[laterLoading,setLaterLoading]=useState(false),[laterError,setLaterError]=useState('')
  const [usage,setUsage]=useState<CreditUsage|null>(null),[from,setFrom]=useState(''),[to,setTo]=useState('')
  const [reverseId,setReverseId]=useState(''),[reason,setReason]=useState('')
  const paymentRequest=useRef(crypto.randomUUID()),reverseRequest=useRef(crypto.randomUUID()),laterRequest=useRef(crypto.randomUUID()),lock=useRef(false)
  const generation=useRef(0)
  const refresh=useCallback(async(preferred?:string)=>{
    if(!supabase)throw new Error('Ligação ao Supabase indisponível.')
    const result=await supabase.rpc('get_client_credit_accounts',{p_client_id:clientId})
    if(result.error)throw result.error
    const rows=(result.data??[]) as CreditAccount[];setAccounts(rows)
    const next=preferred||rows.find(row=>row.id===initialAccountId)?.id||rows[0]?.id||'';setAccountId(next)
    if(next){const response=await supabase.rpc('get_client_credit_detail',{p_account_id:next});if(response.error)throw response.error;setUsage(await loadCreditUsage(response.data as CreditDetail));setDetail(response.data as CreditDetail)}else setDetail(null)
  },[clientId,initialAccountId])
  useEffect(()=>{let active=true;setLoading(true);setError('');setDetail(null);void(async()=>{
    try{await refresh();if(supabase){const result=await supabase.from('billing_entities').select('id,name').eq('active',true).order('name');if(result.error)throw result.error;if(active)setSocieties(result.data??[])}}
    catch(cause){if(active)setError(message(cause))}finally{if(active)setLoading(false)}
  })();return()=>{active=false}},[refresh])
  useEffect(()=>{let active=true;setCandidates([]);setAllocations({});setCandidateError('');if(!paymentOpen||!society)return;setCandidatesLoading(true);void(async()=>{const result=await supabase!.rpc('get_fixed_fee_credit_candidates',{p_client_id:clientId,p_billing_entity_id:society});if(!active)return;if(result.error)setCandidateError(message(result.error));else setCandidates((result.data??[]) as FixedFeeCandidate[]);setCandidatesLoading(false)})();return()=>{active=false}},[paymentOpen,society,clientId])
  useEffect(()=>{let active=true;setLaterCandidates([]);setLaterAllocations({});setLaterError('');if(!laterOpen||!detail)return;setLaterLoading(true);void(async()=>{const result=await supabase!.rpc('get_fixed_fee_credit_candidates',{p_client_id:clientId,p_billing_entity_id:detail.account.billing_entity_id});if(!active)return;if(result.error)setLaterError(message(result.error));else setLaterCandidates((result.data??[]) as FixedFeeCandidate[]);setLaterLoading(false)})();return()=>{active=false}},[laterOpen,detail,clientId])
  async function choose(id:string){const version=++generation.current;setAccountId(id);setDetail(null);setLoading(true);setError('');try{const result=await supabase!.rpc('get_client_credit_detail',{p_account_id:id});if(result.error)throw result.error;const nextUsage=await loadCreditUsage(result.data as CreditDetail);if(version===generation.current){setDetail(result.data as CreditDetail);setUsage(nextUsage)}}catch(cause){if(version===generation.current)setError(message(cause))}finally{if(version===generation.current)setLoading(false)}}
  async function mutate(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await action()}catch(cause){setError(message(cause))}finally{lock.current=false;setBusy(false)}}
  const validMovements=(detail?.movements??[]).filter(row=>row.kind==='consumption'||(!row.reversed&&row.kind!=='reversal')).map(row=>({...row,recorded_at:row.movement_date+'T00:00:00Z'}))
  const statement={rows:validMovements.filter(row=>(!from||row.movement_date>=from)&&(!to||row.movement_date<=to))},invalidPeriod=Boolean(from&&to&&from>to)
  const selectedAllocations=Object.entries(allocations).filter(([,value])=>value.trim()).map(([job_id,value])=>({job_id,amount:parseMoney(value)}))
  const allocatedTotal=selectedAllocations.reduce((sum,row)=>sum+row.amount,0)
  const laterSelected=Object.entries(laterAllocations).filter(([,value])=>value.trim()).map(([job_id,value])=>({job_id,amount:parseMoney(value)}))
  const laterTotal=laterSelected.reduce((sum,row)=>sum+row.amount,0)
  async function payment(){await mutate(async()=>{
    const value=parseMoney(amount);if(!Number.isFinite(value)||value<=0||Math.abs(value*100-Math.round(value*100))>0.00001||!society||!reference.trim()||!date||date>today())throw new Error('Preencha sociedade, valor positivo com até duas casas decimais, data e referência.')
    if(candidatesLoading||candidateError)throw new Error('Confirme primeiro os trabalhos de preço fixo disponíveis.')
    if(selectedAllocations.some(row=>!Number.isFinite(row.amount)||row.amount<=0||Math.abs(row.amount*100-Math.round(row.amount*100))>0.00001||row.amount>Number(candidates.find(candidate=>candidate.job_id===row.job_id)?.remaining??0))||allocatedTotal>value+0.00001)throw new Error('Os abatimentos têm de ser positivos, não podem exceder o valor em falta de cada trabalho nem o total desta provisão.')
    const result=await supabase!.rpc('record_client_credit_payment_with_fixed_fees',{p_client_id:clientId,p_billing_entity_id:society,p_currency:currency,p_amount:value,p_date:date,p_reference:reference,p_request_id:paymentRequest.current,p_allocations:selectedAllocations});if(result.error)throw result.error
    paymentRequest.current=crypto.randomUUID();setAmount('');setReference('');setPaymentOpen(false);await refresh();setNotice(selectedAllocations.length?'Provisão registada e abatida aos trabalhos escolhidos. O saldo disponível foi actualizado.':'Provisão registada sem abatimento a trabalhos. O saldo disponível foi actualizado.')
  })}
  async function reverse(){await mutate(async()=>{const result=await supabase!.rpc('reverse_client_credit',{p_movement_id:reverseId,p_reason:reason,p_request_id:reverseRequest.current});if(result.error)throw result.error;reverseRequest.current=crypto.randomUUID();setReverseId('');setReason('');await refresh(accountId);setNotice('Estorno concluído. O saldo foi actualizado.')})}
  async function applyLater(){await mutate(async()=>{if(!detail||laterLoading||laterError||!laterSelected.length||laterSelected.some(row=>!Number.isFinite(row.amount)||row.amount<=0||Math.abs(row.amount*100-Math.round(row.amount*100))>0.00001||row.amount>Number(laterCandidates.find(candidate=>candidate.job_id===row.job_id)?.remaining??0))||laterTotal>Number(detail.account.balance)+0.00001)throw new Error('Escolha montantes válidos, dentro do saldo disponível e do valor em falta de cada trabalho.');const result=await supabase!.rpc('apply_client_credit_to_fixed_fees',{p_account_id:detail.account.id,p_allocations:laterSelected,p_request_id:laterRequest.current});if(result.error)throw result.error;laterRequest.current=crypto.randomUUID();setLaterOpen(false);await refresh(detail.account.id);setNotice('Provisão disponível abatida aos trabalhos escolhidos.')})}
  return <section aria-label="Provisões para honorários" className="min-w-0 space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">Provisões para honorários</h3><p className="mt-1 text-sm text-text-secondary">Saldo inicial, reforços, abates em notas e respectivos estornos.</p></div>{readOnly?<button type="button" className={button} onClick={onRequestEdit}>Gerir provisões</button>:<button type="button" className={`${button} bg-primary text-surface`} disabled={busy||loading} onClick={()=>setPaymentOpen(!paymentOpen)}>Registar provisão</button>}</div>
    {error&&<div role="alert" className="rounded-lg bg-danger-soft p-3 text-danger">{error}<button type="button" className={`${button} ml-2`} disabled={busy} onClick={()=>void mutate(()=>refresh(accountId))}>Tentar novamente</button></div>}
    {notice&&<p role="status" className="rounded-lg bg-success-soft p-3 text-success">{notice}</p>}
    {paymentOpen&&!readOnly&&<fieldset disabled={busy} className="grid gap-3 rounded-xl border border-border bg-surface-subtle p-4 sm:grid-cols-2"><legend className="px-2 font-semibold">Saldo inicial / reforço da provisão</legend>
      <label>Sociedade<select className="control mt-1 block w-full px-2" value={society} onChange={event=>setSociety(event.target.value)}><option value="">Seleccionar sociedade</option>{societies.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
      <label>Moeda<select className="control mt-1 block w-full px-2" value={currency} onChange={event=>setCurrency(event.target.value)}>{['EUR'].map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Montante<input className="control mt-1 block w-full px-2" inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="0,00"/></label>
      <label>Data de entrada<CalendarDateInput ariaLabel="Data de entrada" className="mt-1 w-full px-2" max={today()} value={date} onChange={setDate}/></label>
      <label className="sm:col-span-2">Origem / referência<input maxLength={1000} className="control mt-1 block w-full px-2" value={reference} onChange={event=>setReference(event.target.value)} placeholder="Ex.: saldo inicial, transferência, referência do recibo…"/></label>
      <div className="space-y-3 rounded-lg border border-border bg-surface p-3 sm:col-span-2"><h4 className="font-semibold">Esta provisão abate algum trabalho a preço fixo?</h4><p className="text-sm text-text-secondary">Escolha cada trabalho e indique quanto do dinheiro recebido lhe quer atribuir, já com IVA. Pode deixar todos os campos vazios: o valor ficará disponível na conta de provisões. O preço acordado, a facturação e o valor médio por hora do trabalho não mudam; apenas o montante por receber diminui.</p>{candidatesLoading?<p role="status">A verificar trabalhos deste cliente…</p>:candidateError?<p role="alert" className="text-danger">{candidateError}</p>:candidates.length?candidates.map(job=><label key={job.job_id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span className="min-w-0 font-medium">{job.title} · em falta {creditMoney(Number(job.remaining),currency)} (com IVA)</span><input aria-label={`Abater ao trabalho ${job.title}`} className="control w-36 px-2" inputMode="decimal" placeholder="0,00" value={allocations[job.job_id]??''} onChange={event=>setAllocations(previous=>({...previous,[job.job_id]:event.target.value}))}/></label>):<p className="text-sm text-text-secondary">Não há trabalhos elegíveis nesta sociedade. A provisão ficará como saldo disponível.</p>}<p className="text-sm font-semibold">Atribuído agora: {creditMoney(Number.isFinite(allocatedTotal)?allocatedTotal:0,currency)} · ficará em saldo: {creditMoney(Math.max(0,(parseMoney(amount)||0)-(Number.isFinite(allocatedTotal)?allocatedTotal:0)),currency)}</p></div>
      <div className="flex flex-wrap gap-2 sm:col-span-2"><button type="button" className={`${button} bg-primary text-surface`} disabled={candidatesLoading||Boolean(candidateError)} onClick={()=>void payment()}>Confirmar provisão</button><button type="button" className={button} onClick={()=>setPaymentOpen(false)}>Cancelar</button></div>
    </fieldset>}
    {accounts.length>0&&<label className="block text-sm font-semibold">Conta de provisões<select className="control mt-1 block w-full px-2" value={accountId} disabled={busy||loading} onChange={event=>void choose(event.target.value)}>{accounts.map(row=><option key={row.id} value={row.id}>{row.society_name} · {row.currency}</option>)}</select></label>}
    {loading?<p role="status">A carregar as provisões…</p>:!detail&&!error?<p className="rounded-lg bg-surface-subtle p-4">Ainda não existem pagamentos antecipados neste cliente.</p>:null}
    {detail&&!loading&&<>
      <section aria-label="Saldo disponível da provisão" className={`rounded-xl border p-4 ${Number(detail.account.balance)>0?'border-success/40 bg-success-soft':'border-danger/40 bg-danger-soft'}`}><h4 className="font-semibold">Saldo disponível da provisão</h4><div className="mt-2 grid gap-3 sm:grid-cols-3">{[['Provisões recebidas',detail.account.received],['Abatido em notas ou trabalhos',detail.account.consumed],['Saldo disponível',detail.account.balance]].map(([label,value])=><div key={label}><p className="text-xs">{label}</p><p className="financial-value text-xl font-semibold">{creditMoney(Number(value),detail.account.currency)}</p></div>)}</div><p className="mt-2 text-xs">Os estornos devolvem o montante abatido a este saldo. A estimativa pelos registos é apresentada em separado.</p></section>
      {!readOnly&&Number(detail.account.balance)>0&&<div className="space-y-3 rounded-xl border border-border p-4"><button type="button" className={button} disabled={busy} onClick={()=>setLaterOpen(!laterOpen)}>{laterOpen?'Fechar atribuição':'Abater saldo disponível a trabalhos a preço fixo'}</button>{laterOpen&&<div className="space-y-3"><p className="text-sm text-text-secondary">Escolha individualmente os trabalhos e os montantes com IVA. A provisão sai do saldo disponível e reduz o valor por receber de cada trabalho. O preço acordado e a média por hora não mudam.</p>{laterLoading?<p role="status">A verificar trabalhos…</p>:laterError?<p role="alert" className="text-danger">{laterError}</p>:laterCandidates.length?laterCandidates.map(job=><label key={job.job_id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span className="font-medium">{job.title} · em falta {creditMoney(Number(job.remaining),detail.account.currency)}</span><input aria-label={`Abater saldo ao trabalho ${job.title}`} className="control w-36 px-2" inputMode="decimal" placeholder="0,00" value={laterAllocations[job.job_id]??''} onChange={event=>setLaterAllocations(previous=>({...previous,[job.job_id]:event.target.value}))}/></label>):<p className="text-sm">Não há trabalhos elegíveis nesta sociedade.</p>}<p className="text-sm font-semibold">Abatimento escolhido: {creditMoney(Number.isFinite(laterTotal)?laterTotal:0,detail.account.currency)} de {creditMoney(Number(detail.account.balance),detail.account.currency)} disponíveis</p><button type="button" className={`${button} bg-primary text-surface`} disabled={busy||laterLoading||Boolean(laterError)||!laterSelected.length} onClick={()=>void applyLater()}>Confirmar abatimento</button></div>}</div>}
      {usage&&<CreditUsageSummary account={detail.account} usage={usage} movements={detail.movements} onSaved={()=>void choose(accountId)}/>}
      <div className="space-y-3"><div className="flex flex-wrap items-end gap-3"><h4 className="mr-auto font-semibold">Provisões e histórico de notas</h4><label className="text-xs">Lançamentos desde<CalendarDateInput ariaLabel="Lançamentos desde" className="mt-1 px-2" value={from} onChange={setFrom}/></label><label className="text-xs">Até<CalendarDateInput ariaLabel="Lançamentos até" className="mt-1 px-2" value={to} onChange={setTo}/></label></div>
        {invalidPeriod?<p role="alert" className="text-danger">A data final deve ser igual ou posterior à inicial.</p>:<><div className="space-y-2">{statement.rows.map(row=><article key={row.id} className="rounded-lg border border-border p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{creditDate(row.recorded_at)} · {row.kind==='consumption'&&!row.note?'Abatimento a trabalho':creditKind(row.kind)}{row.reversed?' · Estornado':''}</strong><span className="financial-value font-semibold">{creditMoney(row.amount,detail.account.currency)}</span></div><details className="mt-2 text-sm"><summary className="cursor-pointer">Referência</summary><p className="mt-1 break-words">{row.reference}</p></details>{row.note&&<><p className="mt-1 text-sm text-text-secondary">Total da nota: {creditMoney(row.note.total,detail.account.currency)} · Provisão descontada: {creditMoney(row.note.deducted,detail.account.currency)} · A pagar: {creditMoney(row.note.remaining,detail.account.currency)}</p><details className="mt-2 text-sm"><summary className="cursor-pointer font-semibold">Ver os {row.note.items.length} registos da nota</summary>{row.note.items.map(item=><p key={item.id} className="mt-2 break-words">{creditDate(item.work_date)} · {item.activity_description} · {item.duration_minutes} min · {creditMoney(item.effective_amount,detail.account.currency)}</p>)}</details><button type="button" className={`${button} mt-2`} onClick={()=>void saveProvisionNotePdf(detail.account,row.note!,row.reversed||row.kind==='reversal').catch(cause=>setError(cause instanceof Error?cause.message:'Não foi possível reimprimir a nota.'))}>Reimprimir nota</button></>}<div className="mt-2 flex flex-wrap items-center justify-between gap-2">{!readOnly&&!row.reversed&&row.kind!=='reversal'&&<button type="button" className={button} disabled={busy} onClick={()=>{setReverseId(row.id);setReason('');reverseRequest.current=crypto.randomUUID()}}>Estornar</button>}</div>{reverseId===row.id&&<div className="mt-2 space-y-2"><label className="block text-sm">Motivo do estorno<input className="control mt-1 w-full px-2" maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label><button type="button" className={`${button} text-danger`} disabled={busy||reason.trim().length<3} onClick={()=>void reverse()}>Confirmar estorno</button><button type="button" className={`${button} ml-2`} disabled={busy} onClick={()=>setReverseId('')}>Cancelar</button></div>}</article>)}</div></>}
      </div>
    </>}
  </section>
}
function message(cause:unknown){const text=cause&&typeof cause==='object'&&'message' in cause?String(cause.message):'Não foi possível concluir a operação.';return /get_client_credit|schema cache/.test(text)?'O módulo de provisões ainda não está instalado neste ambiente. A activação depende da publicação da nova versão.':text}
