import { act,render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach,describe,expect,it,vi } from 'vitest'
import { HonorariumNoteModal } from './HonorariumNoteModal'
const {translateDocument}=vi.hoisted(()=>({translateDocument:vi.fn()}))
vi.mock('./documentTranslation',async(importOriginal)=>({...await importOriginal<typeof import('./documentTranslation')>(),translateDocument}))

const {rpc,from,provisionRpc,historyRpc,documentRpc}=vi.hoisted(()=>({rpc:vi.fn(),from:vi.fn(),provisionRpc:vi.fn(),historyRpc:vi.fn(),documentRpc:vi.fn()}))
vi.mock('../../lib/supabase',()=>({supabase:{rpc:(name:string,...args:unknown[])=>name==='get_client_credit_accounts'?provisionRpc(name,...args):name==='get_client_honorarium_documents'?historyRpc(name,...args):name==='save_honorarium_document'||name==='void_honorarium_document'?documentRpc(name,...args):rpc(name,...args),from}}))
const {pdfRect,pdfText,pdfAddPage,pdfSetPage,pdfState}=vi.hoisted(()=>({pdfRect:vi.fn(),pdfText:vi.fn(),pdfAddPage:vi.fn(),pdfSetPage:vi.fn(),pdfState:{pages:1}}))
vi.mock('jspdf',()=>({jsPDF:class{constructor(){pdfState.pages=1}setFont(){}setFontSize(){}getTextWidth(value:string){return value.length*1.5}text=pdfText;setFillColor(){}rect=pdfRect;addPage(){pdfState.pages+=1;pdfAddPage()}getNumberOfPages(){return pdfState.pages}setPage=pdfSetPage;setProperties(){}splitTextToSize(value:string){return value.length>80?[value.slice(0,40),value.slice(40,80),value.slice(80)]:[value]}output(){return new Blob(['pdf'],{type:'application/pdf'})}}}))
const downloads:string[]=[]
const query=(data:unknown)=>{const result={error:null,data};const chain:any={select:()=>chain,eq:()=>chain,in:()=>chain,order:()=>chain,range:()=>chain,maybeSingle:async()=>result,then:(resolve:(value:typeof result)=>void)=>Promise.resolve(result).then(resolve)};return chain}
const testIssuer={id:'sociedade-1',name:'Sociedade',legal_name:'Sociedade Legal',tax_number:'500000000',address:'Lisboa',email:'sociedade@example.test',phone:null,bank_account_holder:'Sociedade Legal',bank_name:'Banco',bank_account_number:'1',iban:'PT50000000000000000000000',bic_swift:'BICPT',bank_accounts:null,default_vat_rate:23,default_currency:'EUR',logo_path:null}

describe('HonorariumNoteModal',()=>{
 beforeEach(()=>{translateDocument.mockReset();translateDocument.mockImplementation(async(_client,language,items)=>({language,items:items.map((item:any)=>({...item,text:({ 'Análise documental':language==='en'?'Document review':'Analyse documentaire',Reunião:language==='en'?'Meeting':'Réunion',Certidões:language==='en'?'Certificates':'Certificats'} as Record<string,string>)[item.text]??item.text}))}))})
 it.each(['en','fr'] as const)('traduz registos e despesas antes de guardar a nota em %s e conserva a tradução no histórico',async(language)=>{
  const description=language==='en'?'Document review':'Analyse documentaire',expense=language==='en'?'Registered post':'Courrier recommandé'
  translateDocument.mockImplementation(async(_client,lang,items)=>({language:lang,items:items.map((item:any)=>({...item,text:item.kind==='work'?description:expense}))}))
  from.mockImplementation((table:string)=>query(table==='work_entry_expenses'?[{id:'expense',work_entry_id:'one',amount:5,currency:'EUR',observations:'Correio registado'}]:table==='work_entry_expense_documents'?[]:table==='billing_entities'?testIssuer:null))
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client" clientName="Cliente Sintético" onClose={()=>{}}/>)
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'));await user.selectOptions(screen.getByLabelText('Idioma do documento'),language)
  await user.click(screen.getByRole('button',{name:'Emitir nota e guardar PDF'}));await waitFor(()=>expect(downloads).toHaveLength(1))
  const text=pdfText.mock.calls.flatMap(([value])=>Array.isArray(value)?value:[value]).join(' ')
  expect(text).toContain(description);expect(text).toContain(expense);expect(text).not.toContain('Análise documental');expect(text).not.toContain('Correio registado')
  expect(documentRpc).toHaveBeenCalledWith('save_honorarium_document',expect.objectContaining({p_document_options:expect.objectContaining({translation:expect.objectContaining({language}),expenses:[expect.objectContaining({observations:expense})]})}))
  expect(screen.getByText('Análise documental',{selector:'td'})).toBeInTheDocument()
  await user.click(screen.getByRole('button',{name:'Guardar novamente em PDF'}));await waitFor(()=>expect(downloads).toHaveLength(2));expect(translateDocument).toHaveBeenCalledTimes(1)
 })
 it('não emite nem desconta provisão enquanto aguarda tradução e permite tentar novamente após falha',async()=>{
  let fail!:(reason:Error)=>void;translateDocument.mockReturnValue(new Promise((_resolve,reject)=>{fail=reject}))
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client" clientName="Cliente Sintético" onClose={()=>{}}/>)
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'));await user.selectOptions(screen.getByLabelText('Idioma do documento'),'en')
  await user.click(screen.getByRole('button',{name:'Emitir nota e guardar PDF'}));expect(await screen.findByRole('button',{name:'A traduzir todos os registos…'})).toBeDisabled();expect(documentRpc).not.toHaveBeenCalled()
  await act(async()=>fail(new Error('Tradução incompleta')));expect(await screen.findByRole('alert')).toHaveTextContent('Tradução incompleta');expect(documentRpc).not.toHaveBeenCalled();expect(downloads).toHaveLength(0)
  expect(screen.getByRole('button',{name:'Emitir nota e guardar PDF'})).toBeEnabled()
 })
 beforeEach(()=>{historyRpc.mockReset();historyRpc.mockResolvedValue({data:[],error:null});documentRpc.mockReset();documentRpc.mockImplementation(async(_name:string,args:any)=>{const result=rpc.mock.results.at(-1)?.value?(await rpc.mock.results.at(-1)!.value).data.items:[];const items=result.filter((row:any)=>args.p_work_entry_ids.includes(row.id));const subtotal=items.reduce((sum:number,row:any)=>sum+Number(row.effective_amount),0),vat=Math.round(subtotal*args.p_vat_rate)/100;return {error:null,data:{id:'note',number:'NH-00000001',document_id:'doc',revision:1,items,vat_rate:args.p_vat_rate,issued_at:'2026-09-03T12:00:00Z',subtotal,vat,total:args.p_expected_total,deducted:args.p_expected_deduction,remaining:Math.max(0,args.p_expected_total-args.p_expected_deduction-Number(args.p_document_options.direct_payment?.amount??0)),balance_after:0,document_options:args.p_document_options}}});provisionRpc.mockReset();provisionRpc.mockResolvedValue({data:[],error:null});vi.restoreAllMocks();downloads.length=0;vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(function(this:HTMLAnchorElement){downloads.push(this.download)});rpc.mockReset();from.mockReset();pdfRect.mockReset();pdfText.mockReset();pdfAddPage.mockReset();pdfSetPage.mockReset();pdfState.pages=1;URL.createObjectURL=vi.fn(()=> 'blob:test');URL.revokeObjectURL=vi.fn();from.mockImplementation((table:string)=>query(table==='billing_entities'?testIssuer:null));rpc.mockResolvedValue({error:null,data:{total:2,items:[
  {id:'one',work_date:'2026-07-03',activity_description:'Análise documental',duration_minutes:75,professional_name:'Responsável',billing_entity_name:'Sociedade',effective_hourly_rate:80,effective_amount:100,is_paid:false},
  {id:'two',work_date:'2026-06-30',activity_description:'Reunião',duration_minutes:30,professional_name:'Responsável',billing_entity_name:'Sociedade',effective_hourly_rate:80,effective_amount:40,is_paid:false},
 ]}})})
 it('consulta todos os movimentos independentemente da facturação e prepara só os seleccionados',async()=>{
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client-1" clientName="Cliente Teste" onClose={()=>{}}/> )
  expect(await screen.findByText('Análise documental')).toBeInTheDocument()
  await waitFor(()=>expect(rpc).toHaveBeenCalledWith('search_work_entries',expect.objectContaining({p_client_id:'client-1',p_invoiced:null,p_page_size:10000})))
  expect(document.querySelector('.overflow-x-auto table')).not.toHaveTextContent('Responsável')
  expect(screen.queryByLabelText('Responsável')).not.toBeInTheDocument()
  expect(screen.queryByLabelText('Valor')).not.toBeInTheDocument()
  expect(screen.getByLabelText('Total de tempo')).toBeChecked()
  expect(screen.getByLabelText('Total monetário')).not.toBeChecked()
  expect(screen.getByText(/despesas dos movimentos seleccionados são somadas ao total/i)).toBeInTheDocument()
  expect(screen.getByRole('button',{name:/^(Emitir nota e guardar PDF|Guardar PDF)$/})).toBeDisabled()
  await user.click(screen.getByLabelText('Seleccionar movimento de 2026-07-03'))
  expect(screen.getByRole('button',{name:/^(Emitir nota e guardar PDF|Guardar PDF)$/})).toBeEnabled()
  const printable=document.querySelector('.honorarium-print-area')!
  expect(printable).toHaveTextContent('Cliente: Cliente Teste')
  expect(printable).toHaveTextContent('NOTA DE HONORÁRIOS')
  expect(printable).toHaveTextContent('07-2026')
  expect(printable).toHaveTextContent('Análise documental')
  expect(printable).toHaveTextContent('1:15:00')
  expect(printable).not.toHaveTextContent('Reunião')
  await user.click(screen.getByRole('button',{name:/^(Emitir nota e guardar PDF|Guardar PDF)$/}))
  await waitFor(()=>expect(URL.createObjectURL).toHaveBeenCalled())
  expect(downloads).toEqual([expect.stringMatching(/^nota-honorarios-cliente-teste-\d{2}-\d{2}-\d{4}\.pdf$/)])
  expect(pdfText.mock.calls.some(([value,,,options])=>value==='07-2026'&&options?.align==='center')).toBe(true)
  expect(pdfText.mock.calls.some(([value,,,options])=>value==='1:15:00'&&options?.align==='center')).toBe(true)
 })
 it('avisa logo sobre valor/hora em falta e emite apenas os registos não pagos com preço',async()=>{
  rpc.mockResolvedValueOnce({error:null,data:{total:3,items:[
   {id:'pago',work_date:'2026-07-01',activity_description:'Trabalho pago',duration_minutes:60,billing_entity_name:'Sociedade',effective_hourly_rate:100,effective_amount:100,is_paid:true},
   {id:'pronto',work_date:'2026-07-02',activity_description:'Trabalho por pagar',duration_minutes:60,billing_entity_name:'Sociedade',effective_hourly_rate:100,effective_amount:100,is_paid:false},
   {id:'sem-preco',work_date:'2026-07-03',activity_description:'Trabalho por valorizar',duration_minutes:30,billing_entity_name:'Sociedade',effective_hourly_rate:null,effective_amount:null,is_paid:false},
  ]}})
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client" clientName="Cliente Sintético" onClose={()=>{}}/>)
  expect(await screen.findByRole('alert',{name:'Registos sem preço'})).toHaveTextContent('1 registo sem valor/hora e sem montante')
  expect(screen.getByLabelText('Filtrar registos por nota')).toHaveValue('unpaid')
  expect(screen.queryByText('Trabalho pago')).not.toBeInTheDocument()
  expect(screen.getByLabelText('Seleccionar movimento de 2026-07-03')).toBeDisabled()
  await user.click(screen.getByLabelText('Seleccionar todos os 1 movimento com preço'))
  expect(screen.getByLabelText('Seleccionar movimento de 2026-07-02')).toBeChecked()
  await user.click(screen.getByRole('button',{name:'Emitir nota e guardar PDF'}))
  await waitFor(()=>expect(documentRpc).toHaveBeenCalledWith('save_honorarium_document',expect.objectContaining({p_work_entry_ids:['pronto']})))
  expect(downloads).toHaveLength(1)
 })
 it('mantém a lista e os filtros visíveis após uma recusa do backend',async()=>{
  documentRpc.mockResolvedValueOnce({data:null,error:{message:'Confirme o montante e o estado de cada registo.'}})
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client" clientName="Cliente Sintético" onClose={()=>{}}/>)
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'))
  await user.click(screen.getByRole('button',{name:'Emitir nota e guardar PDF'}))
  expect(await screen.findByText(/Não foi possível gerar o documento: Confirme o montante/)).toBeInTheDocument()
  expect(screen.getByLabelText('Filtrar registos por nota')).toBeInTheDocument()
  expect(screen.getByLabelText('Seleccionar movimento de 2026-07-03')).toBeChecked()
 })
 it('emite uma nota, desconta a provisão uma vez e permite repetir o download',async()=>{
  provisionRpc.mockResolvedValue({data:[{id:'account',client_id:'client',society_name:'Sociedade',currency:'EUR',balance:1000}],error:null})
  rpc.mockResolvedValue({data:{total:1,items:[{id:'one',work_date:'2026-07-03',activity_description:'Análise documental',duration_minutes:60,billing_entity_name:'Sociedade',effective_amount:100}]},error:null})
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client" clientName="Cliente Sintético" onClose={()=>{}}/>)
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'))
  await user.click(screen.getByRole('button',{name:'Emitir nota e guardar PDF'}))
  await screen.findByRole('button',{name:'Guardar novamente em PDF'})
  expect(documentRpc.mock.calls.filter(([name])=>name==='save_honorarium_document')).toHaveLength(1)
  expect(documentRpc).toHaveBeenCalledWith('save_honorarium_document',expect.objectContaining({p_client_id:'client',p_work_entry_ids:['one'],p_expected_total:123,p_expected_deduction:123}))
  await user.click(screen.getByRole('button',{name:'Guardar novamente em PDF'}))
  await waitFor(()=>expect(downloads).toHaveLength(2))
  expect(documentRpc.mock.calls.filter(([name])=>name==='save_honorarium_document')).toHaveLength(1)
  const generatedText=pdfText.mock.calls.flatMap(([text])=>Array.isArray(text)?text:[text]).join(' ')
  expect(generatedText).not.toContain('Provisão descontada: 123,00 EUR')
  expect(generatedText).not.toContain('Valor a pagar: 0,00 EUR')
  expect(generatedText).toContain('Alfragide, 3 de Setembro de 2026')
  expect(generatedText).toContain('montante de €100,00 (cem euros)')
  expect(generatedText).toContain('perfazendo a quantia total de €123,00 (cento e vinte e três euros)')
  expect(generatedText).toContain('Não existe valor adicional a pagar nesta nota.')
  expect(screen.getByLabelText('Seleccionar movimento de 2026-07-03')).toBeDisabled()
 })
 it('não apresenta qualquer referência a provisões quando o desconto é zero',async()=>{
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client" clientName="Cliente neutro" onClose={()=>{}}/>)
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'))
  expect(screen.queryByRole('region',{name:'Provisão para honorários'})).not.toBeInTheDocument()
  await user.click(screen.getByRole('button',{name:'Emitir nota e guardar PDF'}))
  await waitFor(()=>expect(downloads).toHaveLength(1))
  expect(pdfText.mock.calls.flatMap(([value])=>Array.isArray(value)?value:[value]).join(' ')).not.toMatch(/provis|advance deducted|provision déduite/i)
 })
 it('exige a escolha de uma saudação formal quando a ficha do cliente não a tem definida',async()=>{
  from.mockImplementation((table:string)=>query(table==='clients'?{legal_name:'Cliente sem tratamento',address:'Rua de Teste, 1',honorarium_language:'pt',honorarium_delivery_method:'email',honorarium_recipient_name:'Maria Teste',honorarium_salutation:null,default_billing_entity_id:null}:table==='work_entry_expenses'?[]:table==='billing_entities'?testIssuer:null))
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client" clientName="Cliente sem tratamento" onClose={()=>{}}/>)
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'))
  expect(screen.getByRole('alert',{name:'Escolher tratamento formal'})).toBeInTheDocument()
  expect(screen.getByRole('button',{name:'Emitir nota e guardar PDF'})).toBeDisabled()
  await user.selectOptions(screen.getByLabelText('Saudação do documento'),'exma_senhora')
  expect(screen.queryByRole('alert',{name:'Escolher tratamento formal'})).not.toBeInTheDocument()
  expect(screen.getByRole('button',{name:'Emitir nota e guardar PDF'})).toBeEnabled()
  await user.click(screen.getByRole('button',{name:'Emitir nota e guardar PDF'}))
  await waitFor(()=>expect(downloads).toHaveLength(1))
  expect(pdfText.mock.calls.flatMap(([value])=>Array.isArray(value)?value:[value]).join(' ')).toContain('Exma. Senhora,')
 })
 it('permite emitir a mesma nota em Word editável',async()=>{
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client" clientName="Cliente Word" onClose={()=>{}}/>)
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'))
  await user.selectOptions(screen.getByLabelText('Formato do documento'),'docx')
  await user.click(screen.getByRole('button',{name:'Emitir nota e guardar Word'}))
  await waitFor(()=>expect(downloads).toContainEqual(expect.stringMatching(/^nota-honorarios-cliente-word-\d{2}-\d{2}-\d{4}\.docx$/)),{timeout:10000})
 })
 it('permite seleccionar registos já incluídos numa nota com provisão descontada',async()=>{
  provisionRpc.mockResolvedValue({data:[{id:'account',society_name:'Sociedade',currency:'EUR',balance:877,noted_work_ids:['one']}],error:null})
  render(<HonorariumNoteModal clientId="client" clientName="Cliente Sintético" onClose={()=>{}}/>)
  await screen.findByLabelText('Seleccionar movimento de 2026-06-30')
  expect(screen.queryByLabelText('Seleccionar movimento de 2026-07-03')).toBeInTheDocument()
 })
 it('mantém todos os movimentos disponíveis mesmo com saldo esgotado e nota anterior',async()=>{
  provisionRpc.mockResolvedValue({data:[{id:'account',society_name:'Sociedade',currency:'EUR',balance:0,noted_work_ids:['one','two']}],error:null})
  render(<HonorariumNoteModal clientId="client" clientName="Cliente Sintético" onClose={()=>{}}/>)
  expect(await screen.findByLabelText('Seleccionar todos os 2 movimentos com preço')).toBeInTheDocument()
  expect(screen.getByRole('button',{name:/^(Emitir nota e guardar PDF|Guardar PDF)$/})).toBeDisabled()
 })
 it('não volta a cobrar os registos de uma nota com provisão',async()=>{
  provisionRpc.mockResolvedValue({data:[{id:'account',society_name:'Sociedade',currency:'EUR',balance:0,noted_work_ids:['one']}],error:null})
  render(<HonorariumNoteModal clientId="client" clientName="Cliente Sintético" documentKind="collection" onClose={()=>{}}/>)
  await screen.findByLabelText('Seleccionar movimento de 2026-06-30')
  expect(screen.queryByLabelText('Seleccionar movimento de 2026-07-03')).not.toBeInTheDocument()
  expect(screen.getByText(/Consulte essas notas e o respectivo valor a pagar/)).toBeInTheDocument()
 })
 it('aguarda a emissora predefinida sem fixar a primeira sociedade que carrega',async()=>{
  let finishClient!:(value:unknown)=>void
  const clientResponse=new Promise(resolve=>{finishClient=resolve})
  from.mockImplementation((table:string)=>{const request=query(table==='billing_entities'?{name:'Sociedade B',default_vat_rate:23,default_currency:'EUR'}:[]);if(table==='clients')request.maybeSingle=()=>clientResponse;return request})
  rpc.mockResolvedValue({error:null,data:{total:2,items:[
   {id:'a',work_date:'2026-07-03',activity_description:'Movimento A',duration_minutes:60,billing_entity_name:'Sociedade A'},
   {id:'b',work_date:'2026-07-04',activity_description:'Movimento B',duration_minutes:30,billing_entity_name:'Sociedade B'},
  ]}})
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client" clientName="Cliente Sintético" onClose={()=>{}}/>)
  await waitFor(()=>expect(from).toHaveBeenCalledWith('clients'))
  expect(screen.queryByLabelText('Sociedade emissora do documento')).not.toBeInTheDocument()
  await act(async()=>finishClient({error:null,data:{default_billing_entity_id:'issuer-b'}}))
  const society=await screen.findByLabelText('Sociedade emissora do documento')
  await waitFor(()=>expect(society).toHaveValue('Sociedade B'))
  expect(screen.getByText('Movimento B')).toBeInTheDocument()
  expect(screen.queryByText('Movimento A')).not.toBeInTheDocument()
  await user.selectOptions(society,'Sociedade A')
  expect(society).toHaveValue('Sociedade A')
  expect(screen.getByText('Movimento A')).toBeInTheDocument()
 })
 it('separa movimentos por sociedade emissora',async()=>{
  rpc.mockResolvedValueOnce({error:null,data:{total:2,items:[
   {id:'a',work_date:'2026-07-03',activity_description:'Movimento da Sociedade A',duration_minutes:60,professional_name:'Responsável',billing_entity_name:'Sociedade A'},
   {id:'b',work_date:'2026-07-04',activity_description:'Movimento da Sociedade B',duration_minutes:30,professional_name:'Responsável',billing_entity_name:'Sociedade B'},
  ]}})
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client-multi" clientName="Cliente Multi" onClose={()=>{}}/> )
  const issuerSelect=await screen.findByLabelText('Sociedade emissora do documento')
  await waitFor(()=>expect(issuerSelect).toHaveValue('Sociedade A'))
  expect(screen.getByText('Movimento da Sociedade A')).toBeInTheDocument()
  await waitFor(()=>expect(screen.queryByText('Movimento da Sociedade B')).not.toBeInTheDocument())
  await user.selectOptions(issuerSelect,'Sociedade B')
  expect(screen.queryByText('Movimento da Sociedade A')).not.toBeInTheDocument()
  expect(screen.getByText('Movimento da Sociedade B')).toBeInTheDocument()
 })
 it('carrega todas as páginas quando o cliente ultrapassa o limite da primeira resposta',async()=>{
  rpc.mockResolvedValueOnce({error:null,data:{total:3,pageSize:2,items:[
   {id:'p1-a',work_date:'2026-07-03',activity_description:'Primeira página A',duration_minutes:60,professional_name:'Responsável',billing_entity_name:'Sociedade',effective_amount:100},
   {id:'p1-b',work_date:'2026-07-04',activity_description:'Primeira página B',duration_minutes:30,professional_name:'Responsável',billing_entity_name:'Sociedade',effective_amount:50},
  ]}}).mockResolvedValueOnce({error:null,data:{total:3,pageSize:2,items:[
   {id:'p2',work_date:'2026-07-05',activity_description:'Segunda página',duration_minutes:15,professional_name:'Responsável',billing_entity_name:'Sociedade',effective_amount:25},
  ]}})
  render(<HonorariumNoteModal clientId="client-pages" clientName="Cliente Paginado" onClose={()=>{}}/> )
  expect(await screen.findByText('Segunda página')).toBeInTheDocument()
  expect(rpc).toHaveBeenNthCalledWith(2,'search_work_entries',expect.objectContaining({p_client_id:'client-pages',p_page:2,p_page_size:10000}))
  expect(screen.getByText('Seleccionar todos os 3 movimentos com preço')).toBeInTheDocument()
 })
 it('prepara a cobrança apenas com movimentos facturados e não pagos',async()=>{
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client-2" clientName="Cliente Cobrança" documentKind="collection" onClose={()=>{}}/> )
  expect(await screen.findByRole('heading',{name:'Cobrança · Cliente Cobrança'})).toBeInTheDocument()
  expect(screen.queryByLabelText('Despesas')).not.toBeInTheDocument()
  await waitFor(()=>expect(rpc).toHaveBeenCalledWith('search_work_entries',expect.objectContaining({p_client_id:'client-2',p_invoiced:true,p_paid:false})))
  await user.click(screen.getByLabelText('Seleccionar movimento de 2026-07-03'))
  await user.click(screen.getByRole('button',{name:/^(Emitir nota e guardar PDF|Guardar PDF)$/}))
  await waitFor(()=>expect(URL.createObjectURL).toHaveBeenCalled())
  expect(downloads).toEqual([expect.stringMatching(/^cobranca-cliente-cobranca-\d{2}-\d{2}-\d{4}\.pdf$/)])
  expect(document.querySelector('.honorarium-print-area')).toHaveTextContent('COBRANÇA')
  expect(document.querySelector('.honorarium-print-area')).toHaveTextContent('Cliente: Cliente Cobrança')
  expect(pdfText.mock.calls.some(([value])=>value==='ASSUNTO: COBRANÇA')).toBe(true)
  expect(pdfText.mock.calls.some(([value])=>Array.isArray(value)&&value.join(' ').includes('permanecem por liquidar'))).toBe(true)
 })
 it.each(['honorarium','collection'] as const)('permite substituir destinatário e idioma no próprio documento %s',async(documentKind)=>{
  from.mockImplementation((table:string)=>query(table==='clients'?{legal_name:'Cliente Legal',address:'Lisboa',honorarium_language:'pt',honorarium_delivery_method:'email',honorarium_recipient_name:'Destinatário inicial',honorarium_salutation:'exmos_senhores',default_billing_entity_id:null}:table==='billing_entities'?testIssuer:null))
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client-override" clientName="Cliente Legal" documentKind={documentKind} onClose={()=>{}}/> )
  const recipient=await screen.findByLabelText('Destinatário do documento')
  await waitFor(()=>expect(recipient).toHaveValue('Destinatário inicial'))
  await user.clear(recipient);await user.type(recipient,'Destinatário específico')
  await user.selectOptions(screen.getByLabelText('Idioma do documento'),'fr')
  await user.click(screen.getByLabelText('Seleccionar movimento de 2026-07-03'))
  await user.click(screen.getByRole('button',{name:/^(Emitir nota e guardar PDF|Guardar PDF)$/}))
  expect(pdfText.mock.calls.some(([value])=>value==='Destinatário específico')).toBe(true)
  expect(pdfText.mock.calls.some(([value])=>value===(documentKind==='collection'?'OBJET : RELANCE DE PAIEMENT':"OBJET : HONORAIRES"))).toBe(true)
 })
 it('soma as despesas ao total da Nota de Honorários e mostra apenas montante e observações',async()=>{
  rpc.mockResolvedValueOnce({error:null,data:{total:1,items:[{id:'fee',work_date:'2026-07-03',activity_description:'Serviço com despesas',duration_minutes:60,professional_name:'Responsável',billing_entity_name:'Sociedade',effective_amount:100}]}})
  from.mockImplementation((table:string)=>query(table==='clients'?{legal_name:'Cliente Legal',address:'Lisboa',honorarium_language:'pt',honorarium_delivery_method:'email',honorarium_recipient_name:'Destinatário',honorarium_salutation:'exmos_senhores',default_billing_entity_id:'sociedade-1'}:table==='billing_entities'?{name:'Sociedade',legal_name:'Sociedade Legal',tax_number:'500000000',address:'Lisboa',phone:'210000000',bank_account_holder:'Sociedade Legal',bank_name:'Banco',bank_account_number:'1',iban:'PT50000000000000000000000',bic_swift:'BICPT',default_vat_rate:23,default_currency:'EUR'}:table==='work_entry_expense_documents'?[]:[{id:'expense-1',work_entry_id:'fee',amount:25,currency:'EUR',observations:'Certidões'}]))
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client-fees" clientName="Cliente Legal" onClose={()=>{}}/> )
  await user.selectOptions(await screen.findByLabelText('Idioma do documento'),'fr')
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'))
  await user.click(screen.getByLabelText('Total monetário'))
  expect(document.querySelector('.honorarium-print-area')).toHaveTextContent('Frais engagés')
  expect(document.querySelector('.honorarium-print-area')).toHaveTextContent('MontantObservations')
  await user.click(screen.getByRole('button',{name:/^(Emitir nota e guardar PDF|Guardar PDF)$/}))
  expect(documentRpc).toHaveBeenCalledWith('save_honorarium_document',expect.objectContaining({p_expected_total:148,p_document_options:expect.objectContaining({expenses_included:true})}))
  const generatedText=pdfText.mock.calls.flatMap(([value])=>Array.isArray(value)?value:[String(value)]).join(' ')
  expect(generatedText).toContain('Certificats')
  expect(generatedText).toContain('Frais engagés')
  expect(generatedText).toContain('100,00')
  expect(generatedText).toContain('148,00')
  expect(generatedText).toContain('TVA')
 })
 it('permite seleccionar várias contas e alterar o IVA apenas no documento',async()=>{
  rpc.mockResolvedValueOnce({error:null,data:{total:1,items:[{id:'bank-fee',work_date:'2026-07-03',activity_description:'Serviço bancário',duration_minutes:60,professional_name:'Responsável',billing_entity_name:'Sociedade',effective_amount:100}]}})
  from.mockImplementation((table:string)=>query(table==='clients'?{legal_name:'Cliente Bancário',address:'Lisboa',honorarium_language:'pt',honorarium_delivery_method:'email',honorarium_recipient_name:null,honorarium_salutation:'exmos_senhores',default_billing_entity_id:'sociedade-1'}:table==='billing_entities'?{name:'Sociedade',legal_name:'Sociedade Legal',tax_number:'500000000',address:'Lisboa',phone:'210000000',bank_account_holder:'Titular A',bank_name:'Banco A',bank_account_number:'1',iban:'PT50000000000000000000001',bic_swift:'BICAPTPL',bank_accounts:[{account_holder:'Titular A',bank_name:'Banco A',account_number:'1',iban:'PT50000000000000000000001',bic_swift:'BICAPTPL',currency:'EUR'},{account_holder:'Titular B',bank_name:'Banco B',account_number:'2',iban:'PT50000000000000000000002',bic_swift:'BICBPTPL',currency:'EUR'}],default_vat_rate:23,default_currency:'EUR'}:[]))
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client-bank" clientName="Cliente Bancário" onClose={()=>{}}/> )
  expect(await screen.findByText('Banco A')).toBeInTheDocument()
  const accounts=screen.getAllByRole('checkbox',{name:/Banco [AB]/})
  await waitFor(()=>expect(accounts[0]).toBeChecked());expect(accounts[1]).not.toBeChecked()
  await user.click(accounts[1]);await user.clear(screen.getByLabelText('IVA do documento'));await user.type(screen.getByLabelText('IVA do documento'),'10')
  await user.click(screen.getByLabelText('Seleccionar movimento de 2026-07-03'));await user.click(screen.getByRole('button',{name:/^(Emitir nota e guardar PDF|Guardar PDF)$/}))
  const generatedText=pdfText.mock.calls.flatMap(([value])=>Array.isArray(value)?value:[String(value)]).join(' ')
  expect(generatedText).toContain('PT50000000000000000000001');expect(generatedText).toContain('PT50000000000000000000002');expect(generatedText).toContain('110,00')
 })
 it('avisa também na cobrança quando faltam dados da sociedade emissora',async()=>{
  from.mockImplementation((table:string)=>query(table==='clients'?{legal_name:'Cliente Cobrança',address:'Lisboa',honorarium_language:'pt',honorarium_delivery_method:'email',honorarium_recipient_name:null,honorarium_salutation:'exmos_senhores',default_billing_entity_id:'sociedade-1'}:{name:'Sociedade',legal_name:'Sociedade Legal',tax_number:'500000000',address:'Lisboa',phone:null,bank_account_holder:null,bank_name:null,bank_account_number:null,iban:null,bic_swift:null,default_vat_rate:23,default_currency:'EUR'}))
  render(<HonorariumNoteModal clientId="client-warning" clientName="Cliente Cobrança" documentKind="collection" onClose={()=>{}}/> )
  expect(await screen.findByText(/Complete na ficha da sociedade:/)).toHaveTextContent('titular da conta, banco, IBAN, BIC / SWIFT')
 })
 it('exclui incobráveis da nota e da cobrança',async()=>{
  rpc.mockResolvedValue({error:null,data:{total:3,items:[
   {id:'normal',work_date:'2026-07-03',activity_description:'Movimento elegível',duration_minutes:60,professional_name:'Responsável',billing_entity_name:'Sociedade',status:'approved'},
   {id:'before',work_date:'2026-07-02',activity_description:'Incobrável antes de facturar',duration_minutes:30,professional_name:'Responsável',billing_entity_name:'Sociedade',status:'uncollectible_uninvoiced'},
   {id:'after',work_date:'2026-07-01',activity_description:'Incobrável depois de facturar',duration_minutes:30,professional_name:'Responsável',billing_entity_name:'Sociedade',status:'uncollectible_invoiced'},
  ]}})
  const {unmount}=render(<HonorariumNoteModal clientId="client-3" clientName="Cliente Teste" onClose={()=>{}}/> )
  expect(await screen.findByText('Movimento elegível')).toBeInTheDocument()
  expect(screen.queryByText('Incobrável antes de facturar')).not.toBeInTheDocument()
  unmount()
  render(<HonorariumNoteModal clientId="client-3" clientName="Cliente Teste" documentKind="collection" onClose={()=>{}}/> )
  expect(await screen.findByText('Movimento elegível')).toBeInTheDocument()
  expect(screen.queryByText('Incobrável depois de facturar')).not.toBeInTheDocument()
 })
 it('traduz cabeçalho, colunas e totais para inglês e francês',async()=>{
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client-lang" clientName="Cliente Teste" onClose={()=>{}}/> )
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'))
  await user.click(screen.getByLabelText('Total monetário'))
  await user.selectOptions(screen.getByLabelText('Idioma do documento'),'en')
  expect(document.querySelector('.honorarium-print-area')).toHaveTextContent('FEE NOTE')
  expect(document.querySelector('.honorarium-print-area')).toHaveTextContent('Work description')
  expect(document.querySelector('.honorarium-print-area')).toHaveTextContent('Total amount')
  await user.selectOptions(screen.getByLabelText('Idioma do documento'),'fr')
  expect(document.querySelector('.honorarium-print-area')).toHaveTextContent("NOTE D'HONORAIRES")
  expect(document.querySelector('.honorarium-print-area')).toHaveTextContent('Description des prestations')
  expect(document.querySelector('.honorarium-print-area')).toHaveTextContent('Montant total')
 })
 it('aumenta a altura da linha do PDF quando a descrição ocupa várias linhas',async()=>{
  rpc.mockResolvedValueOnce({error:null,data:{total:1,items:[{id:'longa',work_date:'2026-07-03',activity_description:'Descrição muito longa destinada a ocupar várias linhas no documento PDF sem cortar, ocultar ou sobrepor o movimento seguinte.',duration_minutes:75,professional_name:'Responsável',billing_entity_name:'Sociedade',effective_amount:100}]}})
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client-long" clientName="Cliente Longo" onClose={()=>{}}/> )
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'))
  await user.click(screen.getByRole('button',{name:/^(Emitir nota e guardar PDF|Guardar PDF)$/}))
  expect(pdfRect.mock.calls.some((call)=>Number(call[3])>8&&Number(call[3])!==9)).toBe(true)
 })
 it.each([
  ['honorarium' as const,/^nota-honorarios-cliente-acores-teste-\d{2}-\d{2}-\d{4}\.pdf$/],
  ['collection' as const,/^cobranca-cliente-acores-teste-\d{2}-\d{2}-\d{4}\.pdf$/],
 ])('gera %s multipágina com todas as linhas, cabeçalhos e rodapés repetidos e nome seguro',async(documentKind,filePattern)=>{
  const manyRows=Array.from({length:90},(_,index)=>({id:`many-${index}`,work_date:`2026-${String(index%12+1).padStart(2,'0')}-15`,activity_description:`Intervenção sintética número ${index+1} com descrição suficiente para validar a paginação`,duration_minutes:15+(index%8)*15,professional_name:'Responsável',billing_entity_name:'Sociedade',effective_amount:10+index,status:'approved'}))
  rpc.mockResolvedValueOnce({error:null,data:{total:manyRows.length,items:manyRows}})
  from.mockImplementation((table:string)=>query(table==='clients'?{legal_name:'Cliente Açores Teste',address:'Ponta Delgada',honorarium_language:'pt',honorarium_delivery_method:'email',honorarium_recipient_name:null,honorarium_salutation:'exmos_senhores',default_billing_entity_id:'sociedade-1'}:table==='billing_entities'?{name:'Sociedade',legal_name:'Sociedade Legal',tax_number:'500000000',address:'Lisboa',phone:'210000000',bank_account_holder:'Sociedade Legal',bank_name:'Banco',bank_account_number:'1',iban:'PT50000000000000000000000',bic_swift:'BICPT',default_vat_rate:23,default_currency:'EUR'}:[]))
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client-many" clientName="Cliente Açores / Teste" documentKind={documentKind} onClose={()=>{}}/> )
  await user.click(await screen.findByLabelText(`Seleccionar todos os ${manyRows.length} movimentos com preço`))
  await user.click(screen.getByRole('button',{name:/^(Emitir nota e guardar PDF|Guardar PDF)$/}))
  expect(pdfAddPage).toHaveBeenCalled()
  expect(pdfState.pages).toBeGreaterThan(1)
  expect(pdfSetPage).toHaveBeenCalledTimes(pdfState.pages)
  expect(pdfText.mock.calls.filter(([value])=>value==='Mês/Ano').length).toBe(pdfState.pages)
  expect(downloads).toEqual([expect.stringMatching(filePattern)])
 })
 it('mostra a ordem final, permite reposicionar colunas e actualiza a miniatura',async()=>{
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client-order" clientName="Cliente Ordem" onClose={()=>{}}/> )
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'))
  expect(screen.queryByLabelText('Responsável')).not.toBeInTheDocument()
  expect(screen.queryByLabelText('Valor')).not.toBeInTheDocument()
  expect(screen.getByLabelText('Pré-visualização do resultado')).toHaveTextContent('Mês/AnoDescrição do movimentoTempo')
  const position=screen.getByLabelText('Posição de Tempo')
  await user.selectOptions(position,position.querySelector('option[value="1"]')!)
  const headings=[...document.querySelectorAll('.honorarium-print-area thead th')].map(node=>node.textContent)
  expect(headings).toEqual(['Mês/Ano','Tempo','Descrição do movimento'])
  await user.click(screen.getByLabelText('Total de tempo'))
  expect(screen.getByLabelText('Pré-visualização do resultado')).not.toHaveTextContent('Tempo total: 0:00:00')
  expect(document.querySelector('.honorarium-print-area tfoot')).toBeNull()
 })
 it('regista um pagamento directo na nota sem o transformar em provisão e apresenta o excedente',async()=>{
  provisionRpc.mockResolvedValue({data:[{id:'account',client_id:'client',society_name:'Sociedade',currency:'EUR',balance:50}],error:null})
  rpc.mockResolvedValue({data:{total:1,items:[{id:'one',work_date:'2026-07-03',activity_description:'Análise documental',duration_minutes:60,billing_entity_name:'Sociedade',effective_amount:100}]},error:null})
  const user=userEvent.setup();render(<HonorariumNoteModal clientId="client" clientName="Cliente Sintético" onClose={()=>{}}/>)
  await user.click(await screen.findByLabelText('Seleccionar movimento de 2026-07-03'))
  await user.type(screen.getByRole('textbox',{name:'Pagamento directo da nota'}),'100')
  expect(screen.getByText(/Excedente a regularizar fora das provisões: 27,00/)).toBeInTheDocument()
  await user.click(screen.getByRole('button',{name:'Emitir nota e guardar PDF'}))
  await screen.findByRole('button',{name:'Guardar novamente em PDF'})
  expect(documentRpc).toHaveBeenCalledWith('save_honorarium_document',expect.objectContaining({p_expected_total:123,p_expected_deduction:50,p_document_options:expect.objectContaining({direct_payment:expect.objectContaining({amount:100})})}))
  const text=pdfText.mock.calls.flatMap(([value])=>Array.isArray(value)?value:[value]).join(' ')
  expect(text).not.toContain('Pagamento directo recebido: 100,00 EUR')
  expect(text).not.toContain('Valor a pagar: 0,00 EUR')
  expect(text).not.toContain('Excedente a regularizar fora das provisões: 27,00 EUR')
 })
})
