import { useEffect, useMemo, useRef, useState } from 'react'
import { supabase } from '../../lib/supabase'
import { readIdBatches } from '../../lib/readBatches'
import { documentIsVoided, noteCreditPreview, type HonorariumDocument } from './honorariumDocuments'
import { saveProvisionNotePdf } from './creditPdf'
import { creditMoney, type CreditAccount, type ProvisionNote } from './credit'
import { honorariumSettlement } from './honorariumSettlement'
import {issuerLogoPath,issuerMatchesSociety} from './societyBranding'
import {createFormalDocumentPdf, downloadPdf, filePart, fileDate, type FormalSnapshot} from './formalDocumentPdf'
import {createFormalDocumentDocx,downloadDocx} from './formalDocumentDocx'
import { translateDocument, translationKey, validateTranslations, type DocumentTranslation, type TranslationItem } from './documentTranslation'
import {formatDate} from '../../utils/date'
import type {HonorariumSalutation} from './formalDocumentShared'
import {DocumentContentLayout} from './DocumentContentLayout'
import {documentColumnLabels as pdfColumnLabels,type DocumentColumn as PdfColumn} from './documentContent'
import pdfWorkerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url'

type Entry={id:string;work_date:string;activity_description:string;duration_minutes:number;professional_name:string;billing_entity_name:string|null;billing_entity_id?:string;effective_hourly_rate?:number|null;effective_amount:number|null;status?:string;is_invoiced?:boolean;is_paid?:boolean}
function priceIssue(row:Entry){
 if(row.effective_amount==null)return row.effective_hourly_rate==null?'Sem valor/hora e sem montante':'Sem montante calculado'
 if(!Number.isFinite(row.effective_amount)||row.effective_amount<0)return 'Montante inválido'
 return null
}
type EntryExpense={id:string;work_entry_id:string;amount:number;currency:string;observations:string|null}
type SearchResult={items:Entry[];total:number;pageSize?:number}
type DocumentLanguage='pt'|'en'|'fr'
type ClientDocumentData={legal_name:string|null;address:string|null;honorarium_language:DocumentLanguage;honorarium_delivery_method:'email'|'post'|'hand';honorarium_recipient_name:string|null;honorarium_salutation?:HonorariumSalutation|null;default_billing_entity_id:string|null}
type BankAccount={account_holder:string;bank_name:string;account_number:string;iban:string;bic_swift:string;currency:string}
type IssuerData={id?:string;name:string;legal_name:string|null;tax_number:string|null;address:string|null;email:string|null;phone:string|null;bank_account_holder:string|null;bank_name:string|null;bank_account_number:string|null;iban:string|null;bic_swift:string|null;bank_accounts:BankAccount[]|null;default_vat_rate:number;default_currency:string;logo_path:string|null}
type SaveFileHandle={createWritable:()=>Promise<{write:(data:BufferSource)=>Promise<void>;close:()=>Promise<void>}>}
type SaveFilePicker=(options:{suggestedName:string;types:{description:string;accept:Record<string,string[]>}[]})=>Promise<SaveFileHandle>
const documentCopy={
 pt:{honorarium:'Nota de Honorários',collection:'Cobrança',client:'Cliente',columns:pdfColumnLabels,timeTotal:'Tempo total',amountTotal:'Valor total',honorariumFile:'nota-honorarios',collectionFile:'cobranca'},
 en:{honorarium:'Fee Note',collection:'Collection Notice',client:'Client',columns:{period:'Month/Year',description:'Work description',duration:'Time'} as Record<PdfColumn,string>,timeTotal:'Total time',amountTotal:'Total amount',honorariumFile:'fee-note',collectionFile:'collection-notice'},
 fr:{honorarium:"Note d'honoraires",collection:'Relance de paiement',client:'Client',columns:{period:'Mois/Année',description:'Description des prestations',duration:'Temps'} as Record<PdfColumn,string>,timeTotal:'Temps total',amountTotal:'Montant total',honorariumFile:'note-honoraires',collectionFile:'relance-paiement'},
} as const
const expenseCopy:Record<DocumentLanguage,{heading:string;amount:string;notes:string}>={
 pt:{heading:'Despesas suportadas',amount:'Montante',notes:'Observações'},
 en:{heading:'Expenses incurred',amount:'Amount',notes:'Notes'},
 fr:{heading:'Frais engagés',amount:'Montant',notes:'Observations'},
}

const monthYear=(date:string)=>{const [year,month]=date.split('-');return `${month}-${year}`}
const duration=(minutes:number)=>`${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,'0')}:00`
const blobData=async(blob:Blob)=>await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})
const readLogo=async(url:string)=>{const response=await fetch(url);return response.ok?blobData(await response.blob()):null}
const logoData=async(path:string|null|undefined)=>{if(!path)return null;if(path.startsWith('/'))return readLogo(path);if(!supabase)return null;const stored=await supabase.storage.from('billing-entity-logos').download(path);return stored.error||!stored.data?null:blobData(stored.data)}
const bankAccountsFor=(entity:IssuerData|null)=>{const stored=entity?.bank_accounts??[];return stored.length?stored:entity?.iban?[{account_holder:entity.bank_account_holder??'',bank_name:entity.bank_name??'',account_number:entity.bank_account_number??'',iban:entity.iban,bic_swift:entity.bic_swift??'',currency:entity.default_currency||'EUR'}]:[]}

async function compactLogo(data:string|null){
 if(!data)return null
 const image=new Image();image.src=data;await image.decode()
 const scale=Math.min(1,1200/image.width,800/image.height),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale)
 const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Não foi possível preparar o logótipo.')
 ctx.drawImage(image,0,0,canvas.width,canvas.height)
 const pixels=ctx.getImageData(0,0,canvas.width,canvas.height).data;let minX=canvas.width,minY=canvas.height,maxX=-1,maxY=-1
 for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const offset=(y*canvas.width+x)*4,visible=pixels[offset+3]>12&&(pixels[offset]<248||pixels[offset+1]<248||pixels[offset+2]<248);if(visible){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}}
 if(maxX<0)return canvas.toDataURL('image/png')
 const padding=Math.max(2,Math.round(Math.max(maxX-minX,maxY-minY)*.025)),left=Math.max(0,minX-padding),top=Math.max(0,minY-padding),right=Math.min(canvas.width-1,maxX+padding),bottom=Math.min(canvas.height-1,maxY+padding),cropWidth=right-left+1,cropHeight=bottom-top+1,documentScale=Math.min(1,720/cropWidth,480/cropHeight),output=document.createElement('canvas');output.width=Math.max(1,Math.round(cropWidth*documentScale));output.height=Math.max(1,Math.round(cropHeight*documentScale))
 const outputContext=output.getContext('2d');if(!outputContext)throw new Error('Não foi possível preparar o logótipo.')
 outputContext.fillStyle='#ffffff';outputContext.fillRect(0,0,output.width,output.height);outputContext.drawImage(canvas,left,top,cropWidth,cropHeight,0,0,output.width,output.height)
 let quality=.94,result=output.toDataURL('image/jpeg',quality)
 while(result.length>24000&&quality>.56){quality-=.03;result=output.toDataURL('image/jpeg',quality)}
 return result
}

export function HonorariumNoteModal({clientId,clientName,onClose,documentKind='honorarium',initialProvisionAccountId}:{clientId:string;clientName:string;onClose:()=>void;documentKind?:'honorarium'|'collection';initialProvisionAccountId?:string}){
 const [provisionAccounts,setProvisionAccounts]=useState<CreditAccount[]>([]),[provisionError,setProvisionError]=useState(''),[provisionLoading,setProvisionLoading]=useState(true),[useProvision,setUseProvision]=useState(true),[issuedProvision,setIssuedProvision]=useState<ProvisionNote|null>(null)
 const provisionRequest=useRef(crypto.randomUUID()),savingLock=useRef(false)
 const [rows,setRows]=useState<Entry[]>([]),[selected,setSelected]=useState<string[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[generating,setGenerating]=useState(false)
 const [pdfColumns,setPdfColumns]=useState<PdfColumn[]>(['period','description','duration']),[showTimeTotal,setShowTimeTotal]=useState(true),[showAmountTotal,setShowAmountTotal]=useState(false)
 const [documentLanguage,setDocumentLanguage]=useState<DocumentLanguage>('pt')
 const [outputFormat,setOutputFormat]=useState<'pdf'|'docx'>('pdf')
 const [translation,setTranslation]=useState<{fingerprint:string;value:DocumentTranslation}|null>(null)
 const [translationBusy,setTranslationBusy]=useState(false)
 const [entryExpenses,setEntryExpenses]=useState<EntryExpense[]>([]),[expensesLoading,setExpensesLoading]=useState(true)
 const [expensesError,setExpensesError]=useState(false)
 const [selectedSociety,setSelectedSociety]=useState('')
 const [selectedBankAccounts,setSelectedBankAccounts]=useState<number[]>([])
 const [documentVatRate,setDocumentVatRate]=useState(23)
 const [clientDocument,setClientDocument]=useState<ClientDocumentData|null>(null),[issuer,setIssuer]=useState<IssuerData|null>(null)
 const [clientDocumentLoading,setClientDocumentLoading]=useState(true)
 const [history,setHistory]=useState<HonorariumDocument[]>([]),[historyLoading,setHistoryLoading]=useState(true)
 const [revisionBase,setRevisionBase]=useState<HonorariumDocument|null>(null),[noteFilter,setNoteFilter]=useState(documentKind==='collection'?'all':'unpaid')
 const [directPayment,setDirectPayment]=useState('')
 const [historyOpen,setHistoryOpen]=useState(false),[voidTarget,setVoidTarget]=useState<HonorariumDocument|null>(null)
 const [previewPages,setPreviewPages]=useState<string[]>([])
 const [previewPdf,setPreviewPdf]=useState<{bytes:Uint8Array<ArrayBuffer>;fileName:string}|null>(null)
 const [previewDocx,setPreviewDocx]=useState<{bytes:Uint8Array<ArrayBuffer>;fileName:string}|null>(null)
 const preparing=expensesLoading||loading||clientDocumentLoading||provisionLoading||historyLoading
 const isCollection=documentKind==='collection',copy=documentCopy[documentLanguage],expenseLabelsCopy=expenseCopy[documentLanguage],documentTitle=isCollection?copy.collection:copy.honorarium,eligibleLabel=isCollection?'facturados e não pagos':'do cliente'
 useEffect(()=>{let active=true;void(async()=>{if(!supabase){setProvisionLoading(false);return}try{const result=await supabase.rpc('get_client_credit_accounts',{p_client_id:clientId});if(!active)return;if(result.error)throw result.error;setProvisionAccounts(Array.isArray(result.data)?result.data:[])}catch(cause){if(active)setProvisionError(cause&&typeof cause==='object'&&'message' in cause?String(cause.message):'Não foi possível consultar o saldo de provisão.')}finally{if(active)setProvisionLoading(false)}})();return()=>{active=false}},[clientId,documentKind])
 useEffect(()=>{let active=true;void(async()=>{if(!supabase){setError('Ligação ao Supabase indisponível.');setLoading(false);return}const args={p_search:null,p_year:null,p_professional_id:null,p_billing_entity_id:null,p_invoiced:isCollection?true:null,p_paid:isCollection?false:null,p_archive:null,p_review_only:false,p_missing_price:false,p_client_type:null,p_client_id:clientId,p_missing_society:false,p_sort:'work_date',p_direction:'asc',p_page_size:10000};const response=await supabase.rpc('search_work_entries',{...args,p_page:1});if(!active)return;if(response.error){setError(response.error.message);setLoading(false);return}const first=(response.data as SearchResult),pageSize=Math.max(1,first.pageSize??first.items.length??10000),pages=Math.ceil((first.total??first.items.length)/pageSize);let items=[...(first.items??[])];if(pages>1){const remaining=await Promise.all(Array.from({length:pages-1},(_,index)=>supabase!.rpc('search_work_entries',{...args,p_page:index+2})));if(!active)return;const failure=remaining.find(result=>result.error)?.error;if(failure){setError(failure.message);setLoading(false);return}items=items.concat(remaining.flatMap(result=>((result.data as SearchResult)?.items??[]) as Entry[]))}if(items.length!==(first.total??items.length)){setError(`Foram recebidos ${items.length} de ${first.total} movimentos. Tente novamente.`);setLoading(false);return}setRows(items.filter(row=>!['cancelled','uncollectible_invoiced','uncollectible_uninvoiced'].includes(row.status??'')));setLoading(false)})();return()=>{active=false}},[clientId,isCollection])
 useEffect(()=>{let active=true;void(async()=>{if(!supabase||!rows.length||isCollection){setEntryExpenses([]);setExpensesLoading(false);return}setExpensesLoading(true);setExpensesError(false);try{const db=supabase;const all=await readIdBatches(rows.map(row=>row.id),(ids,from,to)=>db.from('work_entry_expenses').select('id,work_entry_id,amount,currency,observations').in('work_entry_id',ids).eq('status','active').order('created_at').order('id').range(from,to));if(active)setEntryExpenses(all as EntryExpense[])}catch(cause){if(active){setExpensesError(true);setError(cause instanceof Error?cause.message:'Não foi possível carregar as despesas.')}}finally{if(active)setExpensesLoading(false)}})();return()=>{active=false}},[rows,isCollection])
 useEffect(()=>{let active=true;void(async()=>{try{if(!supabase)return;const result=await supabase.from('clients').select('legal_name,address,honorarium_language,honorarium_delivery_method,honorarium_recipient_name,honorarium_salutation,default_billing_entity_id').eq('id',clientId).maybeSingle();if(!active||result.error||!result.data)return;const client=result.data as ClientDocumentData;setClientDocument(client);setDocumentLanguage(client.honorarium_language??'pt');if(!client.default_billing_entity_id)return;const entity=await supabase.from('billing_entities').select('id,name,legal_name,tax_number,address,email,phone,bank_account_holder,bank_name,bank_account_number,iban,bic_swift,bank_accounts,default_vat_rate,default_currency,logo_path').eq('id',client.default_billing_entity_id).maybeSingle();if(active&&!entity.error&&entity.data)setIssuer(entity.data as IssuerData)}catch(cause){if(active)setError(cause instanceof Error?cause.message:'Não foi possível consultar a sociedade emissora do cliente.')}finally{if(active)setClientDocumentLoading(false)}})();return()=>{active=false}},[clientId])
 useEffect(()=>{let active=true;void(async()=>{try{if(!supabase||isCollection)return;const result=await supabase.rpc('get_client_honorarium_documents',{p_client_id:clientId});if(result.error)throw result.error;if(active)setHistory(Array.isArray(result.data)?result.data:[])}catch(cause){if(active)setError(cause&&typeof cause==='object'&&'message' in cause?String(cause.message):'Não foi possível consultar o histórico de notas.')}finally{if(active)setHistoryLoading(false)}})();return()=>{active=false}},[clientId,isCollection])
 const societyOptions=useMemo(()=>[...new Set(rows.map(row=>row.billing_entity_name).filter((name):name is string=>Boolean(name)))].sort((a,b)=>a.localeCompare(b,'pt-PT')),[rows])
 useEffect(()=>{if(preparing)return;if(!societyOptions.length){setSelectedSociety('');return}setSelectedSociety(current=>current&&societyOptions.includes(current)?current:provisionAccounts.find(row=>row.id===initialProvisionAccountId)?.society_name??(issuer?.name&&societyOptions.includes(issuer.name)?issuer.name:societyOptions[0]))},[societyOptions,issuer?.name,initialProvisionAccountId,provisionAccounts,preparing])
 useEffect(()=>{let active=true;if(!supabase||!selectedSociety||issuer?.name===selectedSociety)return;void supabase.from('billing_entities').select('id,name,legal_name,tax_number,address,email,phone,bank_account_holder,bank_name,bank_account_number,iban,bic_swift,bank_accounts,default_vat_rate,default_currency,logo_path').eq('name',selectedSociety).maybeSingle().then(result=>{if(active&&!result.error&&result.data)setIssuer(result.data as IssuerData)});return()=>{active=false}},[selectedSociety,issuer?.name])
 const issuerBankAccounts=useMemo(()=>bankAccountsFor(issuer),[issuer])
 const issuerReady=!selectedSociety||issuerMatchesSociety(issuer,selectedSociety)
 useEffect(()=>setSelectedBankAccounts(issuerBankAccounts.length?[0]:[]),[issuer?.name,issuerBankAccounts.length])
 useEffect(()=>setDocumentVatRate(issuer?.default_vat_rate??23),[issuer?.name,issuer?.default_vat_rate])
 const alreadyNoted=useMemo(()=>new Set(provisionAccounts.flatMap(account=>account.noted_work_ids??[])),[provisionAccounts])
 const currentNotes=history.filter(note=>note.is_current&&!documentIsVoided(note))
 const notesFor=(id:string)=>currentNotes.filter(note=>note.items.some(item=>item.id===id))
 const voidedFor=(id:string)=>history.some(note=>note.is_current&&documentIsVoided(note)&&note.items.some(item=>item.id===id))
 const societyRows=rows.filter(row=>(!selectedSociety||row.billing_entity_name===selectedSociety)&&(!isCollection||!alreadyNoted.has(row.id)))
 const documentRows=societyRows.filter(row=>noteFilter==='all'||(noteFilter==='unpaid'?!row.is_paid:noteFilter==='with'?notesFor(row.id).length>0:noteFilter==='void'?voidedFor(row.id):notesFor(row.id).length===0))
 const selectableRows=documentRows.filter(row=>!priceIssue(row)),noHourlyRateCount=documentRows.filter(row=>row.effective_amount==null&&row.effective_hourly_rate==null).length,unpricedCount=documentRows.length-selectableRows.length
 const chosen=societyRows.filter(row=>selected.includes(row.id)),invalidChosen=chosen.filter(row=>priceIssue(row)),allSelected=selectableRows.length>0&&selectableRows.every(row=>selected.includes(row.id)),totalMinutes=chosen.reduce((sum,row)=>sum+row.duration_minutes,0),totalAmount=chosen.reduce((sum,row)=>sum+(row.effective_amount??0),0)
 const provisionAccount=provisionAccounts.find(row=>row.society_name===selectedSociety&&row.currency===(issuer?.default_currency||'EUR'))
 const chosenExpenses=useMemo(()=>entryExpenses.filter(expense=>selected.includes(expense.work_entry_id)),[entryExpenses,selected])
 const expenseTotal=Math.round(chosenExpenses.reduce((sum,expense)=>sum+Number(expense.amount),0)*100)/100
 const provisionPreview=noteCreditPreview(chosen,documentVatRate,provisionAccount,history,revisionBase,useProvision,expenseTotal)
 const directPaid=Number(directPayment.replace(',','.'))||0
 const settlement=honorariumSettlement(provisionPreview.total,provisionPreview.deducted,directPaid)

 const translationSource:TranslationItem[]=[...chosen.filter(row=>row.activity_description.trim()).map(row=>({id:row.id,kind:'work' as const,text:row.activity_description})),...chosenExpenses.filter(row=>row.observations?.trim()).map(row=>({id:row.id,kind:'expense' as const,text:row.observations!}))]
 const translationFingerprint=JSON.stringify([documentLanguage,translationSource])
 const preparedTranslation=translation?.fingerprint===translationFingerprint?translation.value:null
 const printableText=(kind:'work'|'expense',id:string,original:string)=>documentLanguage==='pt'?original:preparedTranslation?.items.find(item=>item.kind===kind&&item.id===id)?.text??''
 const chosenBankAccounts=issuerBankAccounts.filter((_,index)=>selectedBankAccounts.includes(index))
 const accountForValidation=chosenBankAccounts[0]
 const missingIssuerFields=issuer?[['denominação legal',issuer.legal_name],['NIF',issuer.tax_number],['morada',issuer.address],['titular da conta',accountForValidation?.account_holder],['banco',accountForValidation?.bank_name],['IBAN',accountForValidation?.iban],['BIC / SWIFT',accountForValidation?.bic_swift]].filter(([,value])=>!value).map(([label])=>label):[]
 async function refreshDocuments(){if(!supabase)return;const [notes,accounts]=await Promise.all([supabase.rpc('get_client_honorarium_documents',{p_client_id:clientId}),supabase.rpc('get_client_credit_accounts',{p_client_id:clientId})]);if(notes.error||accounts.error)throw notes.error??accounts.error;setHistory(Array.isArray(notes.data)?notes.data:[]);setProvisionAccounts(Array.isArray(accounts.data)?accounts.data:[])}
 function review(note:HonorariumDocument){setError('');setRevisionBase(note);setIssuedProvision(null);setSelectedSociety(note.society_name);setSelected(note.items.map(item=>item.id));setNoteFilter('all');provisionRequest.current=crypto.randomUUID();setDocumentVatRate(Number(note.vat_rate));const opts=note.document_options;setDirectPayment(Number((opts.direct_payment as {amount?:number}|undefined)?.amount??0)>0?String((opts.direct_payment as {amount:number}).amount):'');if(['pt','en','fr'].includes(String(opts.language)))setDocumentLanguage(opts.language as DocumentLanguage);if(opts.outputFormat==='pdf'||opts.outputFormat==='docx')setOutputFormat(opts.outputFormat);if(Array.isArray(opts.columns))setPdfColumns(opts.columns.filter(value=>['period','description','duration'].includes(String(value))) as PdfColumn[]);if(typeof opts.showTimeTotal==='boolean')setShowTimeTotal(opts.showTimeTotal);if(typeof opts.showAmountTotal==='boolean')setShowAmountTotal(opts.showAmountTotal);if(typeof opts.recipient==='string')setClientDocument(current=>current?{...current,honorarium_recipient_name:opts.recipient as string}:current);setHistoryOpen(false)}
 function newDocument(){setError('');setRevisionBase(null);setIssuedProvision(null);setSelected([]);setDirectPayment('');setNoteFilter('unpaid');provisionRequest.current=crypto.randomUUID();void refreshDocuments().catch(cause=>setError(String(cause.message??cause)))}
 async function previewStoredNote(note:HonorariumDocument){
  const account={id:'',client_id:clientId,client_name:clientName,billing_entity_id:note.billing_entity_id,society_name:note.society_name,currency:note.currency,received:0,consumed:0,balance:note.balance_after}
  if(!note.document_options.presentation){void saveProvisionNotePdf(account,note,documentIsVoided(note)).catch(cause=>setError(cause instanceof Error?cause.message:'Não foi possível reimprimir a nota.'));return}
  setGenerating(true);setError('')
 try{
   const stored=note.document_options.presentation as FormalSnapshot
   let noteIssuer=issuerMatchesSociety(issuer,note.society_name)?issuer:null
   if(!noteIssuer&&supabase){const result=await supabase.from('billing_entities').select('id,name,legal_name,tax_number,address,email,phone,bank_account_holder,bank_name,bank_account_number,iban,bic_swift,bank_accounts,default_vat_rate,default_currency,logo_path').eq('id',note.billing_entity_id).maybeSingle();if(result.error)throw result.error;if(result.data&&issuerMatchesSociety(result.data as IssuerData,note.society_name))noteIssuer=result.data as IssuerData}
   if(!noteIssuer&&issuerMatchesSociety(stored.issuer,note.society_name))noteIssuer=stored.issuer
   if(!noteIssuer)throw new Error(`Não foi possível confirmar a identidade da sociedade ${note.society_name}.`)
   const currentLogo=await logoData(issuerLogoPath(noteIssuer,note.society_name)),storedLogo=issuerMatchesSociety(stored.issuer,note.society_name)?stored.issuerLogo:null
   const baseClient=stored.clientDocument??clientDocument??{legal_name:null,address:null,honorarium_language:'pt' as const,honorarium_delivery_method:'email' as const,honorarium_recipient_name:null,default_billing_entity_id:null}
   const currentAccounts=bankAccountsFor(noteIssuer)
   const presentation:FormalSnapshot={...stored,societyName:note.society_name,clientName,clientDocument:{...baseClient,honorarium_salutation:clientDocument?.honorarium_salutation??'exma_senhora'},issuer:noteIssuer,issuerLogo:await compactLogo(currentLogo)??storedLogo,bankAccounts:currentAccounts.length?currentAccounts:stored.bankAccounts}
   const previewRows=note.items.map(row=>({...row,professional_name:'',billing_entity_name:note.society_name})),previewExpenses=(note.document_options.expenses as EntryExpense[]|undefined)??[],pdfDocument=createFormalDocumentPdf(presentation,previewRows,previewExpenses,note),bytes=new Uint8Array(pdfDocument.output('arraybuffer')),docxBlob=await createFormalDocumentDocx(presentation,previewRows,previewExpenses,note),docxBytes=new Uint8Array(await docxBlob.arrayBuffer()),baseName=`nota-honorarios-${filePart(clientName)}-${fileDate(new Date(note.issued_at))}`,pdfJs=await import('pdfjs-dist')
   pdfJs.GlobalWorkerOptions.workerSrc=pdfWorkerUrl
   const pdf=await pdfJs.getDocument({data:bytes.slice().buffer}).promise,pages:string[]=[]
   for(let index=1;index<=pdf.numPages;index++){const page=await pdf.getPage(index),viewport=page.getViewport({scale:1.5}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const context=canvas.getContext('2d');if(!context)throw new Error('Não foi possível desenhar a página.');await page.render({canvas,canvasContext:context,viewport}).promise;pages.push(canvas.toDataURL('image/png'))}
   setPreviewPdf({bytes,fileName:`${baseName}.pdf`});setPreviewDocx({bytes:docxBytes,fileName:`${baseName}.docx`});setPreviewPages(pages)
  }catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível abrir a nota.')}finally{setGenerating(false)}
 }
 async function savePreviewPdf(){
  if(!previewPdf)return
  const picker=(window as typeof window&{showSaveFilePicker?:SaveFilePicker}).showSaveFilePicker
  if(!picker){setError('Este browser não permite escolher a pasta. Utilize um browser compatível com “Guardar como…”.');return}
  try{const handle=await picker({suggestedName:previewPdf.fileName,types:[{description:'Documento PDF',accept:{'application/pdf':['.pdf']}}]}),writable=await handle.createWritable();await writable.write(previewPdf.bytes);await writable.close()}
  catch(cause){if(cause instanceof DOMException&&cause.name==='AbortError')return;setError(cause instanceof Error?cause.message:'Não foi possível guardar o PDF.')}
 }
 async function savePreviewDocx(){
  if(!previewDocx)return
  const picker=(window as typeof window&{showSaveFilePicker?:SaveFilePicker}).showSaveFilePicker
  if(!picker){setError('Este browser não permite escolher a pasta. Utilize um browser compatível com “Guardar como…”.');return}
  try{const handle=await picker({suggestedName:previewDocx.fileName,types:[{description:'Documento Word',accept:{'application/vnd.openxmlformats-officedocument.wordprocessingml.document':['.docx']}}]}),writable=await handle.createWritable();await writable.write(previewDocx.bytes);await writable.close()}
  catch(cause){if(cause instanceof DOMException&&cause.name==='AbortError')return;setError(cause instanceof Error?cause.message:'Não foi possível guardar o Word.')}
 }
 async function voidDocument(){if(!voidTarget||!supabase)return;setGenerating(true);try{const result=await supabase.rpc('void_honorarium_document',{p_document_id:voidTarget.document_id,p_expected_revision:voidTarget.revision,p_request_id:crypto.randomUUID()});if(result.error)throw result.error;await refreshDocuments();setVoidTarget(null);newDocument()}catch(cause){setError(cause&&typeof cause==='object'&&'message' in cause?String(cause.message):'Não foi possível anular a nota.')}finally{setGenerating(false)}}
 async function previewDraft(){
  if(!chosen.length||generating||invalidChosen.length)return
  setGenerating(true);setError('')
  try{
   if(!issuerMatchesSociety(issuer,selectedSociety))throw new Error('Confirme a sociedade emissora antes de pré-visualizar.')
   let translated=preparedTranslation
   if(documentLanguage!=='pt'&&!translated){setTranslationBusy(true);translated=await translateDocument(clientId,documentLanguage,translationSource);setTranslation({fingerprint:translationFingerprint,value:translated})}
   const byId=new Map(translated?.items.map(item=>[translationKey(item),item.text])??[])
   const translatedText=(kind:'work'|'expense',id:string,original:string)=>documentLanguage==='pt'?original:byId.get(`${kind}:${id}`)??original
   const draftRows=chosen.map(row=>({...row,activity_description:translatedText('work',row.id,row.activity_description)}))
   const draftExpenses=chosenExpenses.map(row=>({...row,observations:translatedText('expense',row.id,row.observations??'')}))
   const logo=await logoData(issuerLogoPath(issuer,selectedSociety))
   const presentation:FormalSnapshot={version:1,societyName:selectedSociety,clientName,clientDocument,issuer,issuerLogo:await compactLogo(logo),language:documentLanguage,columns:pdfColumns,showTimeTotal,showAmountTotal,bankAccounts:chosenBankAccounts}
   const draft={id:'rascunho',number:'RASCUNHO',issued_at:new Date().toISOString(),subtotal:provisionPreview.subtotal,vat_rate:documentVatRate,vat:provisionPreview.vat,total:provisionPreview.total,deducted:provisionPreview.deducted,remaining:settlement.remaining,balance_after:provisionPreview.balance_after,items:draftRows,document_options:{expenses_included:true,expenses:draftExpenses}} as ProvisionNote
   const pdfDocument=createFormalDocumentPdf(presentation,draftRows,draftExpenses,draft,isCollection),bytes=new Uint8Array(pdfDocument.output('arraybuffer'))
   const docx=await createFormalDocumentDocx(presentation,draftRows,draftExpenses,draft,isCollection),docxBytes=new Uint8Array(await docx.arrayBuffer())
   const pdfJs=await import('pdfjs-dist');pdfJs.GlobalWorkerOptions.workerSrc=pdfWorkerUrl
   const pdf=await pdfJs.getDocument({data:bytes.slice().buffer}).promise,pages:string[]=[]
   for(let index=1;index<=pdf.numPages;index++){const page=await pdf.getPage(index),viewport=page.getViewport({scale:1.5}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const context=canvas.getContext('2d');if(!context)throw new Error('Não foi possível desenhar a página.');await page.render({canvas,canvasContext:context,viewport}).promise;pages.push(canvas.toDataURL('image/png'))}
   const draftFileBase=`rascunho-${isCollection?copy.collectionFile:copy.honorariumFile}`
   setPreviewPdf({bytes,fileName:`${draftFileBase}.pdf`});setPreviewDocx({bytes:docxBytes,fileName:`${draftFileBase}.docx`});setPreviewPages(pages)
  }catch(cause){setError(cause instanceof Error?cause.message:`Não foi possível pré-visualizar ${isCollection?'a cobrança':'a nota'}.`)}finally{setGenerating(false);setTranslationBusy(false)}
 }
 async function savePdf(){
  if(!chosen.length||generating||savingLock.current)return
  if(invalidChosen.length){setError('Há registos seleccionados sem valor/hora ou sem montante válido. Corrija o preço na ficha de cada registo antes de emitir a nota.');return}
  savingLock.current=true
  setGenerating(true);setError('')
  try{
   if(directPayment.trim()&&(!Number.isFinite(Number(directPayment.replace(',','.')))||directPaid<=0||directPaid>1000000000||Math.abs(directPaid*100-Math.round(directPaid*100))>0.00001))throw new Error('Indique o pagamento directo com até duas casas decimais.')
   if(!issuerMatchesSociety(issuer,selectedSociety))throw new Error(`A sociedade emissora ${selectedSociety} ainda não foi confirmada. Tente novamente.`)
   if(issuedProvision){
    if(outputFormat==='pdf'){await saveProvisionNotePdf({id:'',client_id:clientId,client_name:clientName,billing_entity_id:issuer?.id??'',society_name:selectedSociety,currency:issuer?.default_currency||'EUR',received:0,consumed:0,balance:0},issuedProvision);return}
    const options=issuedProvision.document_options??{},presentation=options.presentation as FormalSnapshot|undefined,storedTranslation=options.translation as DocumentTranslation|undefined
    if(!presentation)throw new Error('Esta nota antiga não contém a apresentação necessária para gerar Word.')
    const storedText=(id:string,original:string)=>presentation.language==='pt'?original:storedTranslation?.items.find(item=>item.kind==='work'&&item.id===id)?.text??original
    const storedRows=issuedProvision.items.map(row=>({...row,professional_name:'',billing_entity_name:selectedSociety,activity_description:storedText(row.id,row.activity_description)}))
    const blob=await createFormalDocumentDocx(presentation,storedRows,(options.expenses as EntryExpense[]|undefined)??[],issuedProvision,isCollection)
    downloadDocx(blob,`${isCollection?copy.collectionFile:copy.honorariumFile}-${filePart(clientName)}-${fileDate(new Date(issuedProvision.issued_at))}.docx`);return
   }
   let translated=preparedTranslation
   const priorTranslation=revisionBase?.document_options.translation as DocumentTranslation|undefined
   const priorExpenses=(revisionBase?.document_options.expenses as EntryExpense[]|undefined)??[]
   const unchanged=revisionBase?.items.length===chosen.length&&revisionBase.items.every(item=>chosen.some(row=>row.id===item.id&&row.activity_description===item.activity_description))&&priorExpenses.length===chosenExpenses.length&&priorExpenses.every(item=>chosenExpenses.some(row=>row.id===item.id&&row.observations===item.observations))
   if(documentLanguage!=='pt'&&!translated&&unchanged&&priorTranslation?.language===documentLanguage)translated={language:documentLanguage,items:validateTranslations(translationSource,priorTranslation.items)}
   if(documentLanguage!=='pt'&&!translated){setTranslationBusy(true);translated=await translateDocument(clientId,documentLanguage,translationSource);setTranslation({fingerprint:translationFingerprint,value:translated});setTranslationBusy(false)}
   const textById=new Map(translated?.items.map(item=>[translationKey(item),item.text])??[])
   const translatedText=(kind:'work'|'expense',id:string,original:string)=>documentLanguage==='pt'?original:textById.get(`${kind}:${id}`)??original
   const pdfRows=chosen.map(row=>({...row,activity_description:translatedText('work',row.id,row.activity_description)}))
   const pdfExpenses=chosenExpenses.map(row=>({...row,observations:translatedText('expense',row.id,row.observations??'')}))
   const issuerLogo=await logoData(issuerLogoPath(issuer,selectedSociety))
   const presentation:FormalSnapshot={version:1,societyName:selectedSociety,clientName,clientDocument,issuer,issuerLogo:await compactLogo(issuerLogo),language:documentLanguage,columns:pdfColumns,showTimeTotal,showAmountTotal,bankAccounts:chosenBankAccounts}
    const documentOptions={language:documentLanguage,outputFormat,recipient:clientDocument?.honorarium_recipient_name||clientDocument?.legal_name||clientName,client_name:clientName,society_name:selectedSociety,columns:pdfColumns,showTimeTotal,showAmountTotal,bankAccounts:chosenBankAccounts,translation:translated,expenses:pdfExpenses,expenses_included:true,presentation,...(directPaid>0?{direct_payment:{amount:directPaid,reference:revisionBase?.number??'Pagamento directo confirmado pelo operador'}}:{})}
   if(new TextEncoder().encode(JSON.stringify(documentOptions)).length>55000)throw new Error('O conteúdo traduzido excede o limite desta nota. Divida os registos por duas notas.')
   let provisionNote:ProvisionNote|null=null
   if(!isCollection&&!provisionNote){
     const response=await supabase!.rpc('save_honorarium_document',{p_client_id:clientId,p_billing_entity_id:issuer?.id??chosen[0]?.billing_entity_id,p_work_entry_ids:chosen.map(row=>row.id),p_vat_rate:documentVatRate,p_document_options:documentOptions,p_document_id:revisionBase?.document_id??null,p_expected_revision:revisionBase?.revision??null,p_apply_provision:Boolean(provisionAccount)&&useProvision,p_expected_total:provisionPreview.total,p_expected_deduction:provisionPreview.deducted,p_request_id:provisionRequest.current})
    if(response.error)throw response.error
    provisionNote={...response.data,document_options:documentOptions} as ProvisionNote;setIssuedProvision(provisionNote);await refreshDocuments()
   }
   const savedRows=provisionNote?provisionNote.items.map(row=>({...row,professional_name:'',billing_entity_name:selectedSociety,activity_description:translatedText('work',row.id,row.activity_description)})):pdfRows
    const fileBase=`${isCollection?copy.collectionFile:copy.honorariumFile}-${filePart(clientName)}-${fileDate(provisionNote?new Date(provisionNote.issued_at):new Date())}`
    if(outputFormat==='docx')downloadDocx(await createFormalDocumentDocx(presentation,savedRows,pdfExpenses,provisionNote,isCollection),`${fileBase}.docx`)
    else downloadPdf(createFormalDocumentPdf(presentation,savedRows,pdfExpenses,provisionNote,isCollection),`${fileBase}.pdf`)
   }catch(cause){const detail=cause&&typeof cause==='object'&&'message' in cause?String(cause.message):'';setError(detail?`Não foi possível gerar o documento: ${detail}`:'Não foi possível gerar o documento.')}
  finally{setGenerating(false);setTranslationBusy(false);savingLock.current=false}
 }
 return <div className="app-safe-fixed fixed z-[90] grid place-items-center bg-navigation/65 p-0 sm:p-4" role="dialog" aria-modal="true" aria-labelledby="honorarium-title">
  <section className="card flex h-full max-h-dvh w-full max-w-7xl flex-col overflow-hidden rounded-none sm:h-auto sm:max-h-[calc(100dvh-2rem)] sm:rounded-xl">
   <header className="flex shrink-0 items-start justify-between gap-4 border-b border-border bg-surface px-4 py-3 sm:px-6"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-secondary">Preparação</p><h2 id="honorarium-title" className="mt-1 font-display text-xl font-semibold sm:text-2xl">{documentTitle} · {clientName}</h2><p className="mt-1 text-sm text-text-secondary">Seleccione os movimentos {eligibleLabel} que devem constar do documento.</p></div><button type="button" onClick={onClose} disabled={generating} className="min-h-11 min-w-11 rounded-lg border border-border text-xl" aria-label="Fechar">×</button></header>
   <div className="min-h-0 flex-1 overflow-auto p-4 sm:p-6">
    {preparing&&<p role="status" className="rounded-lg bg-surface-subtle p-4">A carregar movimentos {eligibleLabel}…</p>}
    {error&&<p role="alert" className="rounded-lg bg-danger-soft p-4 text-danger">{error}</p>}{!preparing&&unpricedCount>0&&<p role="alert" aria-label="Registos sem preço" className="mb-3 rounded-lg border border-warning/50 bg-warning-soft p-3 text-sm text-warning-strong">{noHourlyRateCount>0?<><strong>{noHourlyRateCount}</strong> {noHourlyRateCount===1?'registo sem valor/hora e sem montante':'registos sem valor/hora e sem montante'}. Preencha o valor/hora na ficha de cada registo.</>:null}{unpricedCount>noHourlyRateCount?<>{noHourlyRateCount>0?' ':''}<strong>{unpricedCount-noHourlyRateCount}</strong> {unpricedCount-noHourlyRateCount===1?'registo com montante inválido':'registos com montante inválido'}. Corrija o montante na ficha.</>:null} Estes registos não podem ser incluídos na nota enquanto não forem corrigidos.</p>}
     {issuedProvision&&<p role="status" className="my-3 rounded-lg bg-success-soft p-3 text-success">{issuedProvision.number} guardada{issuedProvision.deducted>0?` · Provisão apresentada: ${creditMoney(issuedProvision.deducted,provisionAccount?.currency)}`:''}. Guardar novamente descarrega a mesma versão no formato seleccionado. Pode rever a selecção e guardar outra versão.</p>}
    {isCollection&&!issuedProvision&&rows.some(row=>alreadyNoted.has(row.id))&&<p role="status" className="my-3 rounded-lg border border-border bg-surface-subtle p-3 text-sm">Os registos já incluídos em notas com provisão descontada não entram novamente neste documento. Consulte essas notas e o respectivo valor a pagar no separador Provisões.</p>}
    {!isCollection&&<section aria-label="Histórico de notas de honorários" className="my-3 rounded-xl border border-border bg-surface-subtle p-3">
      <p className="text-sm">As notas podem ser revistas e emitidas novamente. O histórico identifica os registos incluídos em cada versão, sem os marcar como facturados ou pagos.</p>
      <div className="mt-2 flex flex-wrap gap-2"><button type="button" disabled={preparing||generating} className="control px-3" onClick={()=>setHistoryOpen(!historyOpen)}>Histórico de notas · {history.length} versões</button><button type="button" disabled={preparing||generating} className="control px-3" onClick={newDocument}>Nova nota</button>{issuedProvision&&<button type="button" className="control px-3" onClick={()=>{const note=history.find(n=>n.id===issuedProvision.id);if(note)review(note)}}>Rever esta nota</button>}</div>
      {revisionBase&&<p className="mt-2 font-semibold">Revisão de {revisionBase.number} · versão {revisionBase.revision}. Pode acrescentar ou retirar registos.</p>}
      {historyOpen&&<div className="mt-3 space-y-2">{history.length===0?<p>Ainda não existem notas guardadas.</p>:history.map(note=><article key={note.id} className="rounded-lg border border-border bg-surface p-3 text-sm"><strong>{note.number} · v{note.revision}</strong><p>{note.society_name} · {note.fixed_fee_job_id?'trabalho a preço fixo':`${note.items.length} registos`} · {creditMoney(Number(note.total),note.currency)} · {formatDate(note.issued_at)}</p><p className={documentIsVoided(note)?'text-danger':'text-text-secondary'}>{!note.is_current?'Versão anterior':documentIsVoided(note)?'Estornada / anulada':'Versão actual'}</p><p className="mt-1 font-medium">Provisão: {creditMoney(Number(note.deducted),note.currency)} · Pagamento directo: {creditMoney(Number((note.document_options.direct_payment as {amount?:number}|undefined)?.amount??0),note.currency)} · Por pagar: {creditMoney(Number(note.remaining),note.currency)}{Number((note.document_options.direct_payment as {amount?:number}|undefined)?.amount??0)+Number(note.deducted)>Number(note.total)?' · Excedente fora das provisões: '+creditMoney(Number((note.document_options.direct_payment as {amount?:number}).amount)+Number(note.deducted)-Number(note.total),note.currency):''}</p><div className="mt-2 flex flex-wrap gap-2"><button type="button" className="control px-3" title={note.document_options.presentation?'Abrir a versão guardada, sem nova emissão.':'Nota antiga: os elementos de apresentação em falta serão recuperados das fichas actuais.'} disabled={generating} onClick={()=>void previewStoredNote(note)}>Ver PDF v{note.revision}</button>{note.is_current&&<>{note.fixed_fee_job_id?<span className="self-center text-xs text-text-secondary">Rever na ficha do trabalho</span>:<button type="button" className="control px-3" disabled={generating} onClick={()=>review(note)}>Rever e reemitir</button>}{!documentIsVoided(note)&&<button type="button" className="control px-3 text-danger" disabled={generating} onClick={()=>setVoidTarget(note)}>{note.fixed_fee_job_id?'Anular nota':'Anular nota / estornar provisão'}</button>}</>}</div></article>)}</div>}
      {voidTarget&&<div role="alert" className="mt-3 rounded-lg bg-danger-soft p-3"><p>{voidTarget.fixed_fee_job_id?`Anular ${voidTarget.number}? A nota fica no histórico como anulada; a provisão aplicada ao trabalho mantém-se no livro.`:`Anular ${voidTarget.number}? Os registos voltam a ficar sem esta nota e a aplicação de provisão desta nota é devolvida ao saldo. O histórico mantém-se.`}</p><button type="button" className="control mt-2 px-3 text-danger" disabled={generating} onClick={()=>void voidDocument()}>Confirmar anulação</button><button type="button" className="control ml-2 px-3" onClick={()=>setVoidTarget(null)}>Cancelar</button></div>}
    </section>}
    <fieldset disabled={preparing||generating||Boolean(issuedProvision)} className="min-w-0 border-0 p-0">
     {!isCollection&&<section aria-label="Pagamento directo da nota" className="my-3 rounded-xl border border-border bg-surface-subtle p-3 text-sm"><h3 className="font-semibold">Pagamento directo da nota, separado da provisão</h3><p className="mt-1 text-text-secondary">Indique o valor recebido pela nota depois da primeira factura com IVA. Este pagamento não entra no saldo de provisões.</p><label className="mt-2 block max-w-xs font-semibold">Total recebido pela nota (€)<input aria-label="Pagamento directo da nota" inputMode="decimal" value={directPayment} onChange={event=>setDirectPayment(event.target.value)} placeholder="0,00" className="control mt-1 w-full px-2"/></label><p className="mt-2">Provisão com IVA: <strong>{creditMoney(provisionPreview.deducted)}</strong> · Pagamento directo: <strong>{creditMoney(directPaid)}</strong> · Por pagar: <strong>{creditMoney(settlement.remaining)}</strong></p>{settlement.excess>0&&<p className="mt-1 font-semibold text-warning-strong">Excedente a regularizar fora das provisões: {creditMoney(settlement.excess)}. Confirme o reembolso ou outro acerto contabilístico.</p>}</section>}
     {!issuedProvision&&clientDocument&&!clientDocument.honorarium_salutation&&<section role="alert" aria-label="Escolher tratamento formal" className="my-3 rounded-xl border border-warning/50 bg-warning-soft p-4"><h3 className="font-semibold">Escolha o tratamento formal</h3><p className="mt-1 text-sm">A ficha deste cliente não tem uma saudação definida. Seleccione a forma que deve ser usada neste documento.</p><label className="mt-3 block max-w-sm text-sm font-semibold">Saudação<select aria-label="Saudação do documento" value="" onChange={event=>setClientDocument(current=>current?{...current,honorarium_salutation:event.target.value as HonorariumSalutation}:current)} className="control mt-1 block w-full px-3" required><option value="" disabled>Seleccione uma saudação…</option><option value="exmo_senhor">Exmo. Senhor,</option><option value="exma_senhora">Exma. Senhora,</option><option value="exmos_senhores">Exmos. Senhores,</option><option value="exmas_senhoras">Exmas. Senhoras,</option></select></label></section>}
     {!isCollection&&provisionAccount&&<section aria-label="Provisão para honorários" className="my-3 rounded-xl border border-border bg-surface-subtle p-3"><h3 className="font-semibold">Provisão para honorários</h3><label className="mt-2 flex min-h-11 items-center gap-2"><input type="checkbox" checked={useProvision} onChange={event=>setUseProvision(event.target.checked)}/>Descontar a provisão nesta Nota de Honorários</label><p className="text-sm">Saldo disponível antes desta nota: <strong>{creditMoney(provisionAccount.balance,provisionAccount.currency)}</strong></p>{useProvision&&<p className="mt-2 text-sm">Total com IVA: {creditMoney(provisionPreview.total,provisionAccount.currency)} · Provisão a descontar: <strong>{creditMoney(provisionPreview.deducted,provisionAccount.currency)}</strong> · Após provisão, antes do pagamento directo: <strong>{creditMoney(provisionPreview.remaining,provisionAccount.currency)}</strong> · Saldo restante: {creditMoney(provisionPreview.balance_after,provisionAccount.currency)}</p>}<p className="mt-2 text-xs text-text-secondary">A reemissão conserva as aplicações já feitas sem as descontar duas vezes. Uma revisão recalcula a aplicação desta nota; o estorno devolve o valor ao saldo. A nota não altera os estados Facturado ou Pago.</p></section>}
     {!preparing&&<>{societyOptions.length>0&&<div className="mb-3 rounded-lg border border-border bg-surface-subtle p-3"><label className="text-sm font-semibold">Sociedade emissora<select aria-label="Sociedade emissora do documento" value={selectedSociety} onChange={event=>{setSelectedSociety(event.target.value);setSelected([])}} className="control mt-1 block w-full max-w-md px-3">{societyOptions.map(name=><option key={name} value={name}>{name}</option>)}</select></label>{societyOptions.length>1&&<p className="mt-1 text-xs text-text-secondary">O documento inclui apenas movimentos da sociedade seleccionada.</p>}{issuerBankAccounts.length>0&&<fieldset className="mt-3"><legend className="text-sm font-semibold">Dados bancários a apresentar</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{issuerBankAccounts.map((account,index)=><label key={`${account.iban}-${index}`} className="flex min-h-10 items-center gap-2 rounded-lg border border-border bg-surface px-3 text-sm"><input type="checkbox" checked={selectedBankAccounts.includes(index)} onChange={()=>setSelectedBankAccounts(current=>current.includes(index)?current.filter(value=>value!==index):[...current,index].sort((a,b)=>a-b))}/><span><strong>{account.bank_name||`Conta ${index+1}`}</strong>{account.iban&&<span className="block text-xs text-text-secondary">{account.iban}</span>}</span></label>)}</div></fieldset>}{missingIssuerFields.length>0&&<p role="status" className="mt-2 rounded-md border border-warning/40 bg-warning-soft p-2 text-xs text-warning-strong">Complete na ficha da sociedade: {missingIssuerFields.join(', ')}. O PDF pode ser gerado para revisão, mas ficará incompleto.</p>}</div>}{!isCollection&&<label className="mb-3 block text-sm font-semibold">Registos por nota<select aria-label="Filtrar registos por nota" value={noteFilter} onChange={event=>setNoteFilter(event.target.value)} className="control ml-2 px-3"><option value="unpaid">Não pagos</option><option value="all">Todos</option><option value="without">Sem nota activa</option><option value="with">Com nota activa</option><option value="void">Com nota estornada / anulada</option></select></label>}<div className="mb-3 flex flex-wrap items-center justify-between gap-3"><label className="flex min-h-10 items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={allSelected} disabled={selectableRows.length===0} onChange={event=>setSelected(event.target.checked?[...new Set([...selected,...selectableRows.map(row=>row.id)])]:selected.filter(id=>!documentRows.some(row=>row.id===id)))}/>Seleccionar todos os {selectableRows.length} {selectableRows.length===1?'movimento':'movimentos'} com preço</label><p className="text-sm text-text-secondary">{chosen.length} seleccionados · {duration(totalMinutes)}</p></div>
     <div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[38rem] text-sm"><thead className="bg-surface-subtle"><tr><th className="w-12 p-2 text-center">Sel.</th><th className="w-28 p-2 text-center">Mês/Ano</th><th className="p-2 text-left">Descrição</th><th className="w-28 p-2 text-center">Duração</th>{!isCollection&&<th className="p-2 text-left">Nota de honorários</th>}</tr></thead><tbody>{documentRows.map(row=><tr key={row.id} className="odd:bg-surface even:bg-surface-subtle"><td className="border-t border-border p-2 text-center"><input aria-label={`Seleccionar movimento de ${row.work_date}`} type="checkbox" checked={selected.includes(row.id)} disabled={Boolean(priceIssue(row))} title={priceIssue(row)??undefined} onChange={()=>setSelected(current=>current.includes(row.id)?current.filter(id=>id!==row.id):[...current,row.id])}/></td><td className="border-t border-border p-2 text-center tabular-nums">{monthYear(row.work_date)}</td><td className="border-t border-border p-2 text-left">{row.activity_description}{priceIssue(row)&&<span className="ml-2 inline-block rounded bg-warning-soft px-2 py-0.5 text-xs font-semibold text-warning-strong">{priceIssue(row)}</span>}</td><td className="border-t border-border p-2 text-center tabular-nums">{duration(row.duration_minutes)}</td>{!isCollection&&<td className="border-t border-border p-2 text-xs">{notesFor(row.id).length?notesFor(row.id).map(note=><span key={note.id} className="mr-1 inline-block rounded bg-success-soft px-2 py-1 text-success">{note.number} · v{note.revision}</span>):voidedFor(row.id)?<span className="text-danger">Nota estornada / anulada</span>:<span className="text-text-secondary">Sem nota</span>}</td>}</tr>)}</tbody></table>{documentRows.length===0&&<p className="p-8 text-center text-text-secondary">Não existem movimentos neste filtro. Experimente Todos ou outra sociedade.</p>}</div></>}
    <section aria-label="Conteúdo do documento" className="mt-4 rounded-xl border border-border bg-surface-subtle p-3"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-semibold">Conteúdo do documento</h3><p className="mt-1 text-xs text-text-secondary">Confirme o destinatário, o idioma, o formato e as opções específicas. O Word (.docx) fica editável antes do envio. As descrições dos registos e as observações das despesas são traduzidas ao gerar o documento; os originais mantêm-se.</p></div><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-semibold">Destinatário do documento<input aria-label="Destinatário do documento" maxLength={200} value={clientDocument?.honorarium_recipient_name??''} onChange={event=>setClientDocument(current=>current?{...current,honorarium_recipient_name:event.target.value}:current)} placeholder={clientDocument?.legal_name||clientName} className="control mt-1 block min-h-9 min-w-64 px-2"/></label>{!isCollection&&<label className="text-xs font-semibold">IVA (%)<input aria-label="IVA do documento" type="number" min="0" max="100" step="0.01" value={documentVatRate} onChange={event=>setDocumentVatRate(Math.min(100,Math.max(0,Number(event.target.value)||0)))} className="control mt-1 block min-h-9 w-24 px-2"/></label>}<label className="text-xs font-semibold">Formato<select aria-label="Formato do documento" value={outputFormat} onChange={event=>setOutputFormat(event.target.value as 'pdf'|'docx')} className="control mt-1 block min-h-9 px-2"><option value="pdf">PDF</option><option value="docx">Word (.docx)</option></select></label><label className="text-xs font-semibold">Idioma do documento<select aria-label="Idioma do documento" value={documentLanguage} onChange={event=>setDocumentLanguage(event.target.value as DocumentLanguage)} className="control mt-1 block min-h-9 px-2"><option value="pt">Português</option><option value="en">English</option><option value="fr">Français</option></select></label></div></div><DocumentContentLayout columns={pdfColumns} onColumnsChange={setPdfColumns} showTimeTotal={showTimeTotal} onShowTimeTotal={setShowTimeTotal} showAmountTotal={showAmountTotal} onShowAmountTotal={setShowAmountTotal}/>{!isCollection&&<p className="mt-3 rounded-lg border border-border bg-surface p-2 text-xs text-text-secondary">As despesas dos movimentos seleccionados são somadas ao total depois do IVA sobre os honorários. Total de despesas: {creditMoney(expenseTotal)}.</p>}</section>
    </fieldset>
    <article className={`honorarium-print-area mt-6 hidden bg-white text-black ${documentLanguage==='pt'||preparedTranslation?'print:block':'print:hidden'}`}><header><h1>{documentTitle.toLocaleUpperCase(documentLanguage==='pt'?'pt-PT':documentLanguage==='fr'?'fr-FR':'en-GB')}</h1><p className="honorarium-client-name">{copy.client}: {clientName}</p></header><table className="honorarium-work-table"><thead><tr>{pdfColumns.map(column=><th key={column}>{copy.columns[column]}</th>)}</tr></thead><tbody>{chosen.map(row=><tr key={row.id}>{pdfColumns.map(column=><td key={column} className={column==='description'?'text-justify':undefined}>{column==='period'?monthYear(row.work_date):column==='description'?printableText('work',row.id,row.activity_description):duration(row.duration_minutes)}</td>)}</tr>)}</tbody>{(showTimeTotal||showAmountTotal)&&<tfoot><tr><th colSpan={pdfColumns.length}>{[showTimeTotal?`${copy.timeTotal}: ${duration(totalMinutes)}`:'',showAmountTotal?`${copy.amountTotal}: ${totalAmount.toLocaleString(documentLanguage==='pt'?'pt-PT':documentLanguage==='fr'?'fr-FR':'en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})} EUR`:''].filter(Boolean).join(' · ')}</th></tr></tfoot>}</table>{!isCollection&&chosenExpenses.length>0&&<><h2>{expenseLabelsCopy.heading}</h2><table className="honorarium-expense-table"><thead><tr><th>{expenseLabelsCopy.amount}</th><th>{expenseLabelsCopy.notes}</th></tr></thead><tbody>{chosenExpenses.map(expense=><tr key={expense.id}><td>{expense.amount.toLocaleString(documentLanguage==='pt'?'pt-PT':documentLanguage==='fr'?'fr-FR':'en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})} {expense.currency}</td><td className="text-justify">{printableText('expense',expense.id,expense.observations||'—')}</td></tr>)}</tbody></table></>}</article>
   </div>
   <footer className="flex shrink-0 flex-wrap justify-end gap-3 border-t border-border bg-surface px-4 py-3 sm:px-6"><button type="button" onClick={onClose} disabled={generating} className="control min-h-11 px-4 font-semibold">Fechar</button><button type="button" disabled={expensesError||preparing||!issuerReady||!chosen.length||invalidChosen.length>0||generating||!pdfColumns.length} onClick={()=>void previewDraft()} className="control min-h-11 px-4 font-semibold">Pré-visualizar sem guardar</button><button type="button" disabled={expensesError||preparing||!issuerReady||!chosen.length||invalidChosen.length>0||!pdfColumns.length||generating||provisionLoading||Boolean(provisionError)||chosen.length>500||Boolean(!issuedProvision&&clientDocument&&!clientDocument.honorarium_salutation)} onClick={savePdf} className="min-h-11 rounded-lg bg-primary px-4 font-semibold text-surface disabled:opacity-40">{translationBusy?'A traduzir todos os registos…':generating?`A gerar ${outputFormat==='pdf'?'PDF':'Word'}…`:issuedProvision?`Guardar novamente em ${outputFormat==='pdf'?'PDF':'Word'}`:isCollection?`Guardar ${outputFormat==='pdf'?'PDF':'Word'}`:revisionBase?`Guardar revisão e ${outputFormat==='pdf'?'PDF':'Word'}`:`Emitir nota e guardar ${outputFormat==='pdf'?'PDF':'Word'}`}</button></footer>
  </section>
  {previewPages.length>0&&<div className="app-safe-fixed fixed z-[110] flex flex-col bg-navigation/90 p-3" role="dialog" aria-modal="true" aria-label="Pré-visualização da nota de honorários"><div className="mx-auto flex h-full w-full max-w-5xl flex-col overflow-hidden rounded-xl bg-surface"><header className="flex flex-wrap items-center justify-between gap-2 border-b border-border px-4 py-2"><strong>Nota de Honorários · {clientName}{previewPdf?.fileName.startsWith('rascunho-')?' · Rascunho sem gravação':''}</strong><div className="flex flex-wrap gap-2">{previewPdf&&<button type="button" onClick={()=>void savePreviewPdf()} className="min-h-10 rounded-lg bg-primary px-4 py-2 font-semibold text-surface">Guardar PDF como…</button>}{previewDocx&&<button type="button" onClick={()=>void savePreviewDocx()} className="min-h-10 rounded-lg bg-primary px-4 py-2 font-semibold text-surface">Guardar Word como…</button>}<button type="button" className="control px-4" onClick={()=>{setPreviewPages([]);setPreviewPdf(null);setPreviewDocx(null)}}>Fechar pré-visualização</button></div></header><div className="min-h-0 flex-1 overflow-auto bg-surface-subtle p-3">{previewPages.map((page,index)=><img key={index} src={page} alt={`Página ${index+1} da Nota de Honorários`} className="mx-auto mb-3 h-auto w-full max-w-[794px] bg-white shadow-lg"/>)}</div></div></div>}
 </div>
}
