import { useEffect, useMemo, useState } from 'react'
import { jsPDF } from 'jspdf'
import { supabase } from '../../lib/supabase'
import { formalCopy, moneyInWords } from './formalDocumentCopy'

type Entry={id:string;work_date:string;activity_description:string;duration_minutes:number;professional_name:string;billing_entity_name:string|null;effective_amount:number|null;status?:string}
type SearchResult={items:Entry[];total:number;pageSize?:number}
type PdfColumn='period'|'description'|'duration'
const pdfColumnLabels:Record<PdfColumn,string>={period:'Mês/Ano',description:'Descrição do movimento',duration:'Tempo'}
type DocumentLanguage='pt'|'en'|'fr'
type ClientDocumentData={legal_name:string|null;address:string|null;honorarium_language:DocumentLanguage;honorarium_delivery_method:'email'|'post'|'hand';honorarium_recipient_name:string|null;default_billing_entity_id:string|null}
type IssuerData={name:string;legal_name:string|null;tax_number:string|null;address:string|null;phone:string|null;bank_account_holder:string|null;bank_name:string|null;bank_account_number:string|null;iban:string|null;bic_swift:string|null;default_vat_rate:number;default_currency:string}
const documentCopy={
 pt:{honorarium:'Nota de Honorários',collection:'Cobrança',client:'Cliente',columns:pdfColumnLabels,timeTotal:'Tempo total',amountTotal:'Valor total',honorariumFile:'nota-honorarios',collectionFile:'cobranca'},
 en:{honorarium:'Fee Note',collection:'Collection Notice',client:'Client',columns:{period:'Month/Year',description:'Work description',duration:'Time'} as Record<PdfColumn,string>,timeTotal:'Total time',amountTotal:'Total amount',honorariumFile:'fee-note',collectionFile:'collection-notice'},
 fr:{honorarium:"Note d'honoraires",collection:'Relance de paiement',client:'Client',columns:{period:'Mois/Année',description:'Description des prestations',duration:'Temps'} as Record<PdfColumn,string>,timeTotal:'Temps total',amountTotal:'Montant total',honorariumFile:'note-honoraires',collectionFile:'relance-paiement'},
} as const

const monthYear=(date:string)=>{const [year,month]=date.split('-');return `${month}-${year}`}
const duration=(minutes:number)=>`${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,'0')}:00`
const filePart=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase()||'cliente'
const downloadPdf=(doc:jsPDF,fileName:string)=>{const url=URL.createObjectURL(doc.output('blob')),link=document.createElement('a');link.href=url;link.download=fileName;link.style.display='none';document.body.appendChild(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function HonorariumNoteModal({clientId,clientName,onClose,documentKind='honorarium'}:{clientId:string;clientName:string;onClose:()=>void;documentKind?:'honorarium'|'collection'}){
 const [rows,setRows]=useState<Entry[]>([]),[selected,setSelected]=useState<string[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[generating,setGenerating]=useState(false)
 const [pdfColumns,setPdfColumns]=useState<PdfColumn[]>(['period','description','duration']),[showTimeTotal,setShowTimeTotal]=useState(true),[showAmountTotal,setShowAmountTotal]=useState(false)
 const [documentLanguage,setDocumentLanguage]=useState<DocumentLanguage>('pt')
 const [expensesDescription,setExpensesDescription]=useState(''),[expensesInput,setExpensesInput]=useState('')
 const [selectedSociety,setSelectedSociety]=useState('')
 const [clientDocument,setClientDocument]=useState<ClientDocumentData|null>(null),[issuer,setIssuer]=useState<IssuerData|null>(null)
 const isCollection=documentKind==='collection',copy=documentCopy[documentLanguage],documentTitle=isCollection?copy.collection:copy.honorarium,eligibleLabel=isCollection?'facturados e não pagos':'não facturados'
 useEffect(()=>{let active=true;void(async()=>{if(!supabase){setError('Ligação ao Supabase indisponível.');setLoading(false);return}const args={p_search:null,p_year:null,p_professional_id:null,p_billing_entity_id:null,p_invoiced:isCollection?true:false,p_paid:isCollection?false:null,p_archive:null,p_review_only:false,p_missing_price:false,p_client_type:null,p_client_id:clientId,p_missing_society:false,p_sort:'work_date',p_direction:'asc',p_page_size:10000};const response=await supabase.rpc('search_work_entries',{...args,p_page:1});if(!active)return;if(response.error){setError(response.error.message);setLoading(false);return}const first=(response.data as SearchResult),pageSize=Math.max(1,first.pageSize??first.items.length??10000),pages=Math.ceil((first.total??first.items.length)/pageSize);let items=[...(first.items??[])];if(pages>1){const remaining=await Promise.all(Array.from({length:pages-1},(_,index)=>supabase!.rpc('search_work_entries',{...args,p_page:index+2})));if(!active)return;const failure=remaining.find(result=>result.error)?.error;if(failure){setError(failure.message);setLoading(false);return}items=items.concat(remaining.flatMap(result=>((result.data as SearchResult)?.items??[]) as Entry[]))}if(items.length!==(first.total??items.length)){setError(`Foram recebidos ${items.length} de ${first.total} movimentos. Tente novamente.`);setLoading(false);return}setRows(items.filter(row=>row.status!==(isCollection?'uncollectible_invoiced':'uncollectible_uninvoiced')));setLoading(false)})();return()=>{active=false}},[clientId,isCollection])
 useEffect(()=>{let active=true;void(async()=>{if(!supabase)return;const result=await supabase.from('clients').select('legal_name,address,honorarium_language,honorarium_delivery_method,honorarium_recipient_name,default_billing_entity_id').eq('id',clientId).maybeSingle();if(!active||result.error||!result.data)return;const client=result.data as ClientDocumentData;setClientDocument(client);setDocumentLanguage(client.honorarium_language??'pt');if(!client.default_billing_entity_id)return;const entity=await supabase.from('billing_entities').select('name,legal_name,tax_number,address,phone,bank_account_holder,bank_name,bank_account_number,iban,bic_swift,default_vat_rate,default_currency').eq('id',client.default_billing_entity_id).maybeSingle();if(active&&!entity.error&&entity.data)setIssuer(entity.data as IssuerData)})();return()=>{active=false}},[clientId])
 const societyOptions=useMemo(()=>[...new Set(rows.map(row=>row.billing_entity_name).filter((name):name is string=>Boolean(name)))].sort((a,b)=>a.localeCompare(b,'pt-PT')),[rows])
 useEffect(()=>{if(!societyOptions.length){setSelectedSociety('');return}setSelectedSociety(current=>current&&societyOptions.includes(current)?current:issuer?.name&&societyOptions.includes(issuer.name)?issuer.name:societyOptions[0])},[societyOptions,issuer?.name])
 useEffect(()=>{let active=true;if(!supabase||!selectedSociety||issuer?.name===selectedSociety)return;void supabase.from('billing_entities').select('name,legal_name,tax_number,address,phone,bank_account_holder,bank_name,bank_account_number,iban,bic_swift,default_vat_rate,default_currency').eq('name',selectedSociety).maybeSingle().then(result=>{if(active&&!result.error&&result.data)setIssuer(result.data as IssuerData)});return()=>{active=false}},[selectedSociety,issuer?.name])
 const documentRows=useMemo(()=>selectedSociety?rows.filter(row=>row.billing_entity_name===selectedSociety):rows,[rows,selectedSociety])
 const chosen=useMemo(()=>documentRows.filter(row=>selected.includes(row.id)),[documentRows,selected]),allSelected=documentRows.length>0&&documentRows.every(row=>selected.includes(row.id)),totalMinutes=chosen.reduce((sum,row)=>sum+row.duration_minutes,0),totalAmount=chosen.reduce((sum,row)=>sum+(row.effective_amount??0),0)
 const missingIssuerFields=issuer?[['denominação legal',issuer.legal_name],['NIF',issuer.tax_number],['morada',issuer.address],['titular da conta',issuer.bank_account_holder],['banco',issuer.bank_name],['IBAN',issuer.iban],['BIC / SWIFT',issuer.bic_swift]].filter(([,value])=>!value).map(([label])=>label):[]
 const togglePdfColumn=(column:PdfColumn)=>setPdfColumns(current=>current.includes(column)?current.filter(value=>value!==column):[...current,column])
 const movePdfColumn=(index:number,direction:-1|1)=>setPdfColumns(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next})
 function savePdf(){
  if(!chosen.length||generating)return
  setGenerating(true);setError('')
  try{
   const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'}),margin=15,pageWidth=210,contentWidth=pageWidth-margin*2
   const fixedWidths:Record<PdfColumn,number>={period:25,description:0,duration:23}
   const nonDescriptionWidth=pdfColumns.filter(column=>column!=='description').reduce((sum,column)=>sum+fixedWidths[column],0)
   const columnWidths=pdfColumns.map(column=>column==='description'?Math.max(45,contentWidth-nonDescriptionWidth):fixedWidths[column])
   const rowValue=(row:Entry,column:PdfColumn)=>column==='period'?monthYear(row.work_date):column==='description'?row.activity_description:duration(row.duration_minutes)
   let y=18
   const locale=documentLanguage==='pt'?'pt-PT':documentLanguage==='fr'?'fr-FR':'en-GB'
   const currency=issuer?.default_currency||'EUR',vatRate=issuer?.default_vat_rate??23,expenses=Math.max(0,Number(expensesInput.replace(',','.'))||0),vat=totalAmount*vatRate/100,grandTotal=totalAmount+vat+expenses,formatMoney=(value:number)=>`${value.toLocaleString(locale,{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}`
   const formal=formalCopy[documentLanguage]
   const tableHeading=()=>{doc.setFontSize(8);doc.setFillColor(235,241,246);doc.rect(margin,y,contentWidth,8,'F');let x=margin;pdfColumns.forEach((column,index)=>{const align=column==='period'||column==='duration'?'center':'left';doc.text(copy.columns[column],align==='center'?x+columnWidths[index]/2:x+2,y+5.3,{align});x+=columnWidths[index]});y+=8}
   const writeBankDetails=()=>{if(!issuer)return;doc.setFontSize(9);const bankRows=[[formal.account,issuer.bank_account_holder],[formal.bank,issuer.bank_name],[formal.number,issuer.bank_account_number],[formal.iban,issuer.iban],[formal.swift,issuer.bic_swift]].filter((row):row is [string,string]=>Boolean(row[1]));for(const [label,value] of bankRows){doc.setFont('helvetica','bold');doc.text(label,margin+18,y);doc.setFont('helvetica','normal');doc.text(value,margin+62,y);y+=4.7}y+=4}
   const heading=()=>{doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text((issuer?.name||documentTitle).toLocaleUpperCase(locale),pageWidth/2,y,{align:'center'});y+=10;doc.setFontSize(10);const recipient=clientDocument?.honorarium_recipient_name||clientDocument?.legal_name||clientName;doc.text(recipient,margin+contentWidth*.52,y);y+=5;doc.setFont('helvetica','normal');for(const line of String(clientDocument?.address||'').split(/\r?\n/).filter(Boolean)){doc.text(line,margin+contentWidth*.52,y);y+=4.5}y+=5;doc.setFont('helvetica','bold');doc.text(formal.delivery[clientDocument?.honorarium_delivery_method||'email'],margin,y);doc.setFont('helvetica','normal');doc.text(new Intl.DateTimeFormat(locale,{day:'numeric',month:'long',year:'numeric'}).format(new Date()),margin+contentWidth*.52,y);y+=15;doc.setFont('helvetica','bold');doc.text(isCollection?formal.collectionSubject:formal.subject,margin,y);y+=12;doc.text(formal.greeting,margin,y);y+=9;doc.setFont('helvetica','normal');const intro=isCollection?formal.collectionIntro(formatMoney(totalAmount),moneyInWords(totalAmount,documentLanguage)):formal.intro(formatMoney(totalAmount),moneyInWords(totalAmount,documentLanguage),formatMoney(vat),moneyInWords(vat,documentLanguage),expenses?formatMoney(expenses):'',expenses?moneyInWords(expenses,documentLanguage):'',formatMoney(grandTotal),moneyInWords(grandTotal,documentLanguage));const introLines=doc.splitTextToSize(intro,contentWidth) as string[];doc.text(introLines,margin,y);y+=introLines.length*4.5+6;writeBankDetails();doc.setFont('helvetica','bold');doc.text(formal.work,margin,y);y+=5;tableHeading()}
   const nextPage=(height:number)=>{if(y+height<=282)return;doc.addPage();y=18;doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text((issuer?.name||documentTitle).toLocaleUpperCase(locale),pageWidth/2,y,{align:'center'});y+=8;tableHeading()}
   heading();doc.setFont('helvetica','normal');doc.setFontSize(9)
   for(const row of chosen){const descriptionIndex=pdfColumns.indexOf('description'),descriptionWidth=descriptionIndex>=0?columnWidths[descriptionIndex]-4:0,lines=descriptionIndex>=0?doc.splitTextToSize(row.activity_description,descriptionWidth) as string[]:[],height=Math.max(8,lines.length*4.2+3);nextPage(height);doc.rect(margin,y,contentWidth,height);let x=margin;pdfColumns.forEach((column,index)=>{const align=column==='period'||column==='duration'?'center':'left',value=column==='description'?lines:rowValue(row,column);doc.text(value,align==='center'?x+columnWidths[index]/2:x+2,y+5,{align});x+=columnWidths[index]});y+=height}
   if(showTimeTotal||showAmountTotal){nextPage(10);doc.setFont('helvetica','bold');doc.rect(margin,y,contentWidth,9);const totals=[showTimeTotal?`${copy.timeTotal}: ${duration(totalMinutes)}`:'',showAmountTotal?`${copy.amountTotal}: ${formatMoney(totalAmount)}`:''].filter(Boolean).join('   ·   ');doc.text(totals,pageWidth-margin-2,y+5.8,{align:'right'});y+=15}if(!isCollection&&expenses){nextPage(10);doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(`${formal.expenses}${expensesDescription.trim()?` · ${expensesDescription.trim()}`:''}: ${formatMoney(expenses)}`,margin,y);y+=9}if(!isCollection){nextPage(28);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(`${formal.total}: ${formatMoney(totalAmount)} + IVA${expenses?` + ${formal.expenses.toLocaleLowerCase(locale)}`:''} = ${formatMoney(grandTotal)} (${moneyInWords(grandTotal,documentLanguage)}).`,margin,y);y+=12}nextPage(20);doc.setFont('helvetica','normal');for(const line of formal.closing){doc.text(line,margin,y);y+=8}if(issuer){const footer=[`${issuer.legal_name||issuer.name}${issuer.tax_number?` · NIF ${issuer.tax_number}`:''}`,[issuer.address,issuer.phone].filter(Boolean).join(' · ')].filter(Boolean);for(let page=1;page<=doc.getNumberOfPages();page++){doc.setPage(page);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.setFillColor(164,92,63);doc.rect(margin,287,contentWidth,.35,'F');footer.forEach((line,index)=>doc.text(line,pageWidth/2,291+index*3.3,{align:'center'}))}}doc.setProperties({title:`${documentTitle} - ${clientName}`,subject:documentLanguage==='pt'?`Movimentos ${eligibleLabel} seleccionados`:documentLanguage==='fr'?'Prestations sélectionnées':'Selected work entries'});downloadPdf(doc,`${isCollection?copy.collectionFile:copy.honorariumFile}-${filePart(clientName)}.pdf`)
  }catch(cause){setError(cause instanceof Error?`Não foi possível gerar o PDF: ${cause.message}`:'Não foi possível gerar o PDF.')}
  finally{setGenerating(false)}
 }
 return <div className="app-safe-fixed fixed z-[90] grid place-items-center bg-navigation/65 p-0 sm:p-4" role="dialog" aria-modal="true" aria-labelledby="honorarium-title">
  <section className="card flex h-full max-h-dvh w-full max-w-7xl flex-col overflow-hidden rounded-none sm:h-auto sm:max-h-[calc(100dvh-2rem)] sm:rounded-xl">
   <header className="flex shrink-0 items-start justify-between gap-4 border-b border-border bg-surface px-4 py-3 sm:px-6"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-secondary">Preparação</p><h2 id="honorarium-title" className="mt-1 font-display text-xl font-semibold sm:text-2xl">{documentTitle} · {clientName}</h2><p className="mt-1 text-sm text-text-secondary">Seleccione os movimentos {eligibleLabel} que devem constar do documento.</p></div><button type="button" onClick={onClose} className="min-h-11 min-w-11 rounded-lg border border-border text-xl" aria-label="Fechar">×</button></header>
   <div className="min-h-0 flex-1 overflow-auto p-4 sm:p-6">
    {loading&&<p role="status" className="rounded-lg bg-surface-subtle p-4">A carregar movimentos {eligibleLabel}…</p>}
    {error&&<p role="alert" className="rounded-lg bg-danger-soft p-4 text-danger">Não foi possível carregar os movimentos: {error}</p>}
    {!loading&&!error&&<>{societyOptions.length>0&&<div className="mb-3 rounded-lg border border-border bg-surface-subtle p-3"><label className="text-sm font-semibold">Sociedade emissora<select aria-label="Sociedade emissora do documento" value={selectedSociety} onChange={event=>{setSelectedSociety(event.target.value);setSelected([])}} className="control mt-1 block w-full max-w-md px-3">{societyOptions.map(name=><option key={name} value={name}>{name}</option>)}</select></label>{societyOptions.length>1&&<p className="mt-1 text-xs text-text-secondary">O documento inclui apenas movimentos da sociedade seleccionada.</p>}{missingIssuerFields.length>0&&<p role="status" className="mt-2 rounded-md border border-warning/40 bg-warning-soft p-2 text-xs text-warning-strong">Complete na ficha da sociedade: {missingIssuerFields.join(', ')}. O PDF pode ser gerado para revisão, mas ficará incompleto.</p>}</div>}<div className="mb-3 flex flex-wrap items-center justify-between gap-3"><label className="flex min-h-10 items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={allSelected} onChange={event=>setSelected(event.target.checked?documentRows.map(row=>row.id):selected.filter(id=>!documentRows.some(row=>row.id===id)))}/>Seleccionar todos os {documentRows.length} movimentos</label><p className="text-sm text-text-secondary">{chosen.length} seleccionados · {duration(totalMinutes)}</p></div>
     <div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[38rem] text-sm"><thead className="bg-surface-subtle"><tr><th className="w-12 p-2 text-center">Sel.</th><th className="w-28 p-2 text-center">Mês/Ano</th><th className="p-2 text-left">Descrição</th><th className="w-28 p-2 text-center">Duração</th></tr></thead><tbody>{documentRows.map(row=><tr key={row.id} className="odd:bg-surface even:bg-surface-subtle"><td className="border-t border-border p-2 text-center"><input aria-label={`Seleccionar movimento de ${row.work_date}`} type="checkbox" checked={selected.includes(row.id)} onChange={()=>setSelected(current=>current.includes(row.id)?current.filter(id=>id!==row.id):[...current,row.id])}/></td><td className="border-t border-border p-2 text-center tabular-nums">{monthYear(row.work_date)}</td><td className="border-t border-border p-2 text-left">{row.activity_description}</td><td className="border-t border-border p-2 text-center tabular-nums">{duration(row.duration_minutes)}</td></tr>)}</tbody></table>{documentRows.length===0&&<p className="p-8 text-center text-text-secondary">Este cliente não tem movimentos {eligibleLabel}.</p>}</div></>}
    <section aria-label="Conteúdo do PDF" className="mt-4 rounded-xl border border-border bg-surface-subtle p-3"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-semibold">Conteúdo do PDF</h3><p className="mt-1 text-xs text-text-secondary">Seleccione as colunas e use as setas para definir a ordem.</p></div><label className="text-xs font-semibold">Idioma do documento<select aria-label="Idioma do documento" value={documentLanguage} onChange={event=>setDocumentLanguage(event.target.value as DocumentLanguage)} className="control mt-1 block min-h-9 px-2"><option value="pt">Português</option><option value="en">English</option><option value="fr">Français</option></select></label></div><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(Object.keys(pdfColumnLabels) as PdfColumn[]).map(column=>{const index=pdfColumns.indexOf(column),active=index>=0;return <div key={column} className="flex min-h-9 items-center gap-1 rounded-lg border border-border bg-surface px-2"><label className="flex min-w-0 flex-1 items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={active} onChange={()=>togglePdfColumn(column)}/><span className="truncate">{pdfColumnLabels[column]}</span></label>{active&&<><button type="button" disabled={index===0} onClick={()=>movePdfColumn(index,-1)} aria-label={`Mover ${pdfColumnLabels[column]} para a esquerda`} className="h-7 w-7 rounded border border-border disabled:opacity-30">←</button><button type="button" disabled={index===pdfColumns.length-1} onClick={()=>movePdfColumn(index,1)} aria-label={`Mover ${pdfColumnLabels[column]} para a direita`} className="h-7 w-7 rounded border border-border disabled:opacity-30">→</button></>}</div>})}</div><div className="mt-3 flex flex-wrap gap-4 text-sm font-semibold"><label className="flex items-center gap-2"><input type="checkbox" checked={showTimeTotal} onChange={event=>setShowTimeTotal(event.target.checked)}/>Total de tempo</label><label className="flex items-center gap-2"><input type="checkbox" checked={showAmountTotal} onChange={event=>setShowAmountTotal(event.target.checked)}/>Total monetário</label></div>{!isCollection&&<div className="mt-3 grid gap-2 sm:grid-cols-[1fr_11rem]"><label className="text-xs font-semibold">Descrição das despesas<input value={expensesDescription} onChange={event=>setExpensesDescription(event.target.value)} placeholder="Ex.: certidões, deslocações ou portes" className="control mt-1 w-full px-3"/></label><label className="text-xs font-semibold">Despesas ({issuer?.default_currency||'EUR'})<input aria-label="Despesas" type="number" inputMode="decimal" min="0" step="0.01" value={expensesInput} onChange={event=>setExpensesInput(event.target.value)} placeholder="0,00" className="control mt-1 w-full px-3 text-right tabular-nums"/></label></div>}</section>
    <article className="honorarium-print-area mt-6 hidden bg-white text-black print:block"><header><h1>{documentTitle.toLocaleUpperCase(documentLanguage==='pt'?'pt-PT':documentLanguage==='fr'?'fr-FR':'en-GB')}</h1><p className="honorarium-client-name">{copy.client}: {clientName}</p></header><table><thead><tr>{pdfColumns.map(column=><th key={column}>{copy.columns[column]}</th>)}</tr></thead><tbody>{chosen.map(row=><tr key={row.id}>{pdfColumns.map(column=><td key={column}>{column==='period'?monthYear(row.work_date):column==='description'?row.activity_description:duration(row.duration_minutes)}</td>)}</tr>)}</tbody>{(showTimeTotal||showAmountTotal)&&<tfoot><tr><th colSpan={pdfColumns.length}>{[showTimeTotal?`${copy.timeTotal}: ${duration(totalMinutes)}`:'',showAmountTotal?`${copy.amountTotal}: ${totalAmount.toLocaleString(documentLanguage==='pt'?'pt-PT':documentLanguage==='fr'?'fr-FR':'en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})} EUR`:''].filter(Boolean).join(' · ')}</th></tr></tfoot>}</table></article>
   </div>
   <footer className="flex shrink-0 flex-wrap justify-end gap-3 border-t border-border bg-surface px-4 py-3 sm:px-6"><button type="button" onClick={onClose} className="control min-h-11 px-4 font-semibold">Fechar</button><button type="button" disabled={!chosen.length||!pdfColumns.length||generating} onClick={savePdf} className="min-h-11 rounded-lg bg-primary px-4 font-semibold text-surface disabled:opacity-40">{generating?'A gerar PDF…':'Guardar PDF'}</button></footer>
  </section>
 </div>
}
