import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'
import { StandardDataTable, type TableColumn } from '../../components/table/StandardDataTable'
import { ClientCreditPanel } from './ClientCreditPanel'
import { creditMoney, creditDate, type CreditAccount, type CreditDetail } from './credit'
import { loadCreditUsage } from './loadCreditUsage'
import type { CreditUsage } from './creditUsage'
type ProvisionRow=CreditAccount&{usage:CreditUsage}

export function ProvisionsPage(){
 const [rows,setRows]=useState<ProvisionRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[client,setClient]=useState<CreditAccount|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError('');try{if(!supabase)throw new Error('Ligação indisponível.');const result=await supabase.rpc('get_client_credit_accounts');if(result.error)throw result.error;const accounts=(result.data??[]) as CreditAccount[];const loaded:ProvisionRow[]=[];for(let offset=0;offset<accounts.length;offset+=4){loaded.push(...await Promise.all(accounts.slice(offset,offset+4).map(async account=>{const detail=await supabase!.rpc('get_client_credit_detail',{p_account_id:account.id});if(detail.error)throw detail.error;return {...account,usage:await loadCreditUsage(detail.data as CreditDetail)}})))}setRows(loaded)}catch(cause){setError(cause&&typeof cause==='object'&&'message' in cause?String(cause.message):'Não foi possível carregar as provisões.')}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const columns:TableColumn<ProvisionRow>[]=[
  {id:'client',label:'Cliente',value:row=>row.client_name,essential:true,align:'left',width:230,render:row=><strong className={Number(row.balance)>0?'text-success':'text-danger'}>{row.client_name}</strong>},
  {id:'history',label:'Histórico',value:()=>'',width:115,sortable:false,filterable:false,searchable:false,exportable:false,render:row=><button type="button" className="min-h-11 rounded-lg border border-border bg-surface px-3 font-semibold text-primary" aria-label={`Histórico de ${row.client_name} · ${row.society_name} · ${row.currency}`} onClick={event=>{event.stopPropagation();setClient(row)}} onDoubleClick={event=>event.stopPropagation()}>Histórico</button>},
  {id:'treatment',label:'Estado da provisão',width:170,value:row=>Number(row.balance)>0?'Com saldo':'Saldo esgotado',render:row=><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${Number(row.balance)>0?'bg-success-soft text-success':'bg-danger-soft text-danger'}`}>{Number(row.balance)>0?'Com saldo':'Saldo esgotado'}</span>},
  {id:'society',label:'Sociedade',value:row=>row.society_name,align:'left',width:210,render:row=><div><span>{row.society_name}</span><small className="block text-text-secondary">Provisões · {row.currency}</small></div>},
  {id:'received',label:'Provisões recebidas',width:180,kind:'money',value:row=>Number(row.received),render:row=><div><strong className="financial-value">{creditMoney(row.received,row.currency)}</strong><small className="block text-text-secondary">{row.usage.startsOn?`Desde ${creditDate(row.usage.startsOn)}`:"Líquido de estornos"}</small></div>},
  {id:'work',label:'Registos desde depósito',width:210,kind:'money',value:row=>row.usage.total,render:row=><div><strong className="financial-value">{creditMoney(row.usage.total,row.currency)}</strong><small className="block text-text-secondary">{row.usage.rows.length} registos · {Math.floor(row.usage.minutes/60)} h {row.usage.minutes%60} min · com IVA</small></div>},
  {id:'consumed',label:'Provisão utilizada',width:230,kind:'money',value:row=>Number(row.consumed),render:row=>{const percent=Number(row.received)>0?Math.min(100,Math.max(0,Number(row.consumed)/Number(row.received)*100)):0;return <div className={Number(row.balance)>0?'text-success':'text-danger'}><strong className="financial-value">{creditMoney(row.consumed,row.currency)}</strong><div role="progressbar" aria-label={`Provisão consumida de ${row.client_name}`} aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100} className="my-1 h-2 overflow-hidden rounded-full bg-surface"><div className={`h-full rounded-full ${Number(row.balance)>0?'bg-success':'bg-danger'}`} style={{width:`${percent}%`}}/></div><small>{percent.toLocaleString('pt-PT',{maximumFractionDigits:1})}% consumido</small></div>}},
  {id:'balance',label:'Saldo disponível',essential:true,width:180,kind:'money',value:row=>Number(row.balance),render:row=><div className={Number(row.balance)>0?'text-success':'text-danger'}><strong className="financial-value text-base">{creditMoney(row.balance,row.currency)}</strong><small className="block">{Number(row.balance)>0?'Após notas e estornos':'Provisão esgotada'}</small></div>},
 ]
 const displayColumns=['client','balance','consumed','received','history','work','society','treatment'].map(id=>columns.find(column=>column.id===id)!)
 return <section className="space-y-4"><div className="card p-5"><h2 className="sr-only">Provisões</h2><p className="mt-1 text-sm text-text-secondary">Todos os clientes que já tiveram provisões, incluindo as esgotadas. Mantêm-se nas listas de Particulares e Empresas.</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-sm font-semibold"><span className="text-success">● Com saldo disponível</span><span className="text-danger">● Saldo esgotado</span></div><p className="mt-2 text-xs text-text-secondary">Saldo actualizado pelos pagamentos, abates das notas e estornos. O histórico apresenta também a estimativa pelas horas registadas. Consulte o consumo através de Histórico ou com duplo clique na linha.</p><button type="button" className="mt-3 min-h-11 rounded-lg border border-border px-3 text-sm font-semibold" disabled={loading} onClick={()=>void load()}>Actualizar provisões</button></div>
  <StandardDataTable id="client-provisions" label="Clientes com provisões" rows={rows} columns={displayColumns} rowKey={row=>row.id} rowHeight={80} rowClassName={row=>Number(row.balance)>0?'bg-success-soft/40':'bg-danger-soft/40'} loading={loading} error={error} onRetry={()=>void load()} onRowDoubleClick={setClient}/>
  {client&&<div className="app-safe-fixed fixed z-[80] flex bg-navigation/65 p-0 sm:p-4" role="dialog" aria-modal="true" aria-label={`Provisões · ${client.client_name}`}><section className="card mx-auto flex w-full max-w-5xl flex-col overflow-hidden"><header className="flex shrink-0 items-center justify-between gap-3 border-b border-border p-4"><h2 className="min-w-0 break-words font-semibold">{client.client_name} · Provisões</h2><button type="button" aria-label="Fechar provisões" className="min-h-11 min-w-11 rounded-lg border border-border" onClick={()=>{setClient(null);void load()}}>×</button></header><div className="min-h-0 overflow-auto p-4"><ClientCreditPanel key={client.id} clientId={client.client_id} initialAccountId={client.id}/></div></section></div>}
 </section>
}
