import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'
import { AppLink } from '../../components/ui/AppLink'
import { openClientRecord } from '../master-data/openClientRecord'
import { ClientCreditPanel } from './ClientCreditPanel'
import { creditMoney, creditDate, type CreditAccount, type CreditDetail } from './credit'
import { loadCreditUsage } from './loadCreditUsage'
import type { CreditUsage } from './creditUsage'
import type { HonorariumDocument } from './honorariumDocuments'
type ProvisionRow=CreditAccount&{usage:CreditUsage;toSettle:number}

async function remainingWithoutConfirmedPayment(account:CreditAccount,detail:CreditDetail,documents:HonorariumDocument[]){
 if(!supabase)throw new Error('Ligação indisponível.')
 const activeNotes=new Set(detail.movements.filter(m=>m.kind==='consumption'&&!m.reversed).map(m=>m.note_id))
 const notes=documents.filter(doc=>doc.is_current&&!doc.voided&&doc.credit_active&&doc.credit_note_id&&activeNotes.has(doc.credit_note_id)&&doc.billing_entity_id===account.billing_entity_id&&doc.currency===account.currency)
 const ids=[...new Set(notes.flatMap(doc=>doc.items.map(item=>item.id)))],paid=new Map<string,boolean>()
 for(let index=0;index<ids.length;index+=200){const response=await supabase.from('work_entries').select('id,is_paid').in('id',ids.slice(index,index+200));if(response.error)throw response.error;for(const item of response.data)paid.set(item.id,item.is_paid)}
 // Never infer payment from the issue of a note or an invoice. An incomplete
 // read also preserves the alert rather than silently clearing a balance.
 return notes.reduce((sum,doc)=>sum+(doc.items.length>0&&doc.items.every(item=>paid.get(item.id)===true)?0:Number(doc.remaining)),0)
}

export function ProvisionsPage(){
 const [rows,setRows]=useState<ProvisionRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[client,setClient]=useState<CreditAccount|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError('');try{if(!supabase)throw new Error('Ligação indisponível.');const result=await supabase.rpc('get_client_credit_accounts');if(result.error)throw result.error;const accounts=(result.data??[]) as CreditAccount[];const loaded:ProvisionRow[]=[];const documentCache=new Map<string,Promise<HonorariumDocument[]>>();for(let offset=0;offset<accounts.length;offset+=4){loaded.push(...await Promise.all(accounts.slice(offset,offset+4).map(async account=>{const detail=await supabase!.rpc('get_client_credit_detail',{p_account_id:account.id});if(detail.error)throw detail.error;const documents=documentCache.get(account.client_id)??Promise.resolve(supabase!.rpc('get_client_honorarium_documents',{p_client_id:account.client_id})).then(response=>{if(response.error)throw response.error;return (response.data??[]) as HonorariumDocument[]});documentCache.set(account.client_id,documents);return {...account,usage:await loadCreditUsage(detail.data as CreditDetail),toSettle:await remainingWithoutConfirmedPayment(account,detail.data as CreditDetail,await documents)}})))}setRows(loaded)}catch(cause){setError(cause&&typeof cause==='object'&&'message' in cause?String(cause.message):'Não foi possível carregar as provisões.')}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 return <section className="space-y-4"><div className="card p-5"><h2 className="sr-only">Provisões</h2><p className="mt-1 text-sm text-text-secondary">Todos os clientes que já tiveram provisões, incluindo as esgotadas. Mantêm-se nas listas de Particulares e Empresas.</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-sm font-semibold"><span className="text-success">● Com saldo disponível</span><span className="text-danger">● Saldo esgotado</span></div><p className="mt-2 text-xs text-text-secondary">Saldo actualizado pelos pagamentos, abates das notas e estornos. O histórico apresenta também a estimativa pelas horas registadas.</p><button type="button" className="mt-3 min-h-11 rounded-lg border border-border px-3 text-sm font-semibold" disabled={loading} onClick={()=>void load()}>Actualizar provisões</button></div>
  <section aria-label="Clientes com provisões" aria-busy={loading}>{loading&&<p role="status" className="card p-5">A carregar provisões…</p>}{error&&<div role="alert" className="card p-5 text-danger">{error}<button type="button" className="control ml-3 px-3" onClick={()=>void load()}>Tentar novamente</button></div>}{!loading&&!error&&!rows.length&&<p className="card p-5 text-text-secondary">Ainda não existem clientes com provisões.</p>}
   <div role="list" className="grid gap-4 lg:grid-cols-2">{rows.map(row=>{const position=Math.round((Number(row.balance)-row.usage.total-row.toSettle)*100)/100,hasBalance=Number(row.balance)>0,percent=Number(row.received)>0?Math.min(100,Math.max(0,Number(row.consumed)/Number(row.received)*100)):0;return <article role="listitem" key={row.id} className="card flex min-w-0 flex-col overflow-hidden p-5"><header className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><h3 className="break-words font-display text-xl font-semibold">{row.client_name}</h3><p className="text-xs text-text-secondary">{row.society_name} · Provisões em {row.currency}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${position<0?'bg-danger-soft text-danger':position>0?'bg-success-soft text-success':'bg-danger-soft text-danger'}`}>{position<0?'Provisão excedida':position>0?'Com saldo':'Saldo esgotado'}</span></header>
    <dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className={`col-span-2 rounded-lg border-2 p-3 ${position<0?'border-danger bg-danger-soft':'border-success bg-success-soft/40'}`}><dt className="text-xs text-text-secondary">Posição da provisão após trabalho registado</dt><dd className={`financial-value mt-1 text-xl font-semibold ${position<0?'text-danger':'text-success'}`}>{creditMoney(position,row.currency)}</dd><small className="text-text-secondary">Saldo contabilístico menos trabalho ainda sem nota e remanescente das notas vigentes. A liquidação das notas requer confirmação.</small></div><div className="col-span-2 rounded-lg bg-surface-subtle p-3"><dt className="text-xs text-text-secondary">Saldo contabilístico disponível</dt><dd className={`financial-value mt-1 font-semibold ${hasBalance?'text-success':'text-danger'}`}>{creditMoney(row.balance,row.currency)}</dd><small className="text-text-secondary">Após notas e estornos; não inclui trabalho ainda sem nota.</small></div><div className="rounded-lg bg-surface-subtle p-3"><dt className="text-xs text-text-secondary">Provisões recebidas</dt><dd className="financial-value mt-1 font-semibold">{creditMoney(row.received,row.currency)}</dd><small className="text-text-secondary">{row.usage.startsOn?`Desde ${creditDate(row.usage.startsOn)}`:'Líquido de estornos'}</small></div><div className="rounded-lg bg-surface-subtle p-3"><dt className="text-xs text-text-secondary">Provisão utilizada em notas</dt><dd className="financial-value mt-1 font-semibold">{creditMoney(row.consumed,row.currency)}</dd></div></dl>
    <div className="mt-3 rounded-lg border border-border p-3 text-sm"><p className="text-xs text-text-secondary">Consumo contabilizado em notas</p><div role="progressbar" aria-label={`Provisão consumida de ${row.client_name}`} aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100} className="mt-2 h-2 overflow-hidden rounded-full bg-surface-subtle"><div className={`h-full rounded-full ${hasBalance?'bg-success':'bg-danger'}`} style={{width:`${percent}%`}}/></div><p className={`mt-1 font-semibold ${hasBalance?'text-success':'text-danger'}`}>{percent.toLocaleString('pt-PT',{maximumFractionDigits:1})}% consumido</p><p className="mt-2 text-xs text-text-secondary">Trabalho com valor ainda sem nota de provisão: <strong className="financial-value text-text-primary">{creditMoney(row.usage.total,row.currency)}</strong> · {row.usage.rows.length} registos ({row.usage.invoicedUnpaid} facturados e não pagos) · {Math.floor(row.usage.minutes/60)} h {row.usage.minutes%60} min · com IVA</p></div>
    {row.toSettle>0&&<p className="mt-2 text-xs text-danger">Remanescente das notas vigentes indicado a pagar: {creditMoney(row.toSettle,row.currency)}. A nota não confirma factura nem pagamento; confira a liquidação antes de o considerar dívida efectiva.</p>}
    {row.usage.missingPrice>0&&<p className="mt-2 text-xs text-danger">{row.usage.missingPrice} registo(s) sem preço podem aumentar o consumo.</p>}
    <footer className="mt-auto grid gap-2 pt-4 sm:grid-cols-3"><button type="button" className="control min-h-11 px-3 text-sm font-semibold" onClick={()=>setClient(row)}>Histórico</button><button type="button" className="control min-h-11 px-3 text-sm font-semibold" onClick={()=>openClientRecord(row.client_id)}>Ficha do cliente</button><AppLink href={`?view=work&clientId=${encodeURIComponent(row.client_id)}`} className="flex min-h-11 items-center justify-center rounded-lg bg-secondary px-3 text-center text-sm font-semibold text-surface">Registos do cliente</AppLink></footer>
   </article>})}</div>
  </section>
  {client&&<div className="app-safe-fixed fixed z-[80] flex bg-navigation/65 p-0 sm:p-4" role="dialog" aria-modal="true" aria-label={`Provisões · ${client.client_name}`}><section className="card mx-auto flex w-full max-w-5xl flex-col overflow-hidden"><header className="flex shrink-0 items-center justify-between gap-3 border-b border-border p-4"><h2 className="min-w-0 break-words font-semibold">{client.client_name} · Provisões</h2><button type="button" aria-label="Fechar provisões" className="min-h-11 min-w-11 rounded-lg border border-border" onClick={()=>{setClient(null);void load()}}>×</button></header><div className="min-h-0 overflow-auto p-4"><ClientCreditPanel key={client.id} clientId={client.client_id} initialAccountId={client.id}/></div></section></div>}
 </section>
}
